SELECT * FROM (
    WITH VENDAS_PERIODO AS (
        SELECT /*+ MATERIALIZE */
            C.SEQPRODUTO,
            C.NROEMPRESA,
            SUM(C.QTDVDA) AS TOTAL_QTD_VENDIDA,
            COUNT(DISTINCT C.DTAENTRADASAIDA) AS QTD_DIAS_COM_VENDA,
            MIN(C.DTAENTRADASAIDA) AS PRIMEIRA_DATA_VENDA,
            MAX(C.DTAENTRADASAIDA) AS ULTIMA_DATA_VENDA
        FROM MRL_CUSTODIA C
        WHERE C.SEQPRODUTO = 15312
          AND C.NROEMPRESA = 2
          AND C.DTAENTRADASAIDA BETWEEN TO_DATE('01/02/2026', 'DD/MM/YYYY') AND TO_DATE('31/05/2026', 'DD/MM/YYYY')
        GROUP BY C.SEQPRODUTO, C.NROEMPRESA
    )
    SELECT
        A.SEQPRODUTO AS CODIGO_PRODUTO,
        A.DESCCOMPLETA AS DESCRICAO_PRODUTO,
        2 AS CODIGO_LOJA,
        NVL(VP.TOTAL_QTD_VENDIDA, 0) AS TOTAL_VENDIDO,
        NVL(VP.QTD_DIAS_COM_VENDA, 0) AS DIAS_COM_VENDA,
        TO_CHAR(VP.PRIMEIRA_DATA_VENDA, 'DD/MM/YYYY') AS DATA_PRIMEIRA_VENDA,
        TO_CHAR(VP.ULTIMA_DATA_VENDA, 'DD/MM/YYYY') AS DATA_ULTIMA_VENDA
    FROM MAP_PRODUTO A
    LEFT JOIN VENDAS_PERIODO VP ON VP.SEQPRODUTO = A.SEQPRODUTO
    WHERE A.SEQPRODUTO = 15312
)
