SELECT
  TRUNC(N.DTAEMISSAO) AS DTA_EMISSAO,
  N.NROEMPRESA,
  N.CODGERALOPER,
  N.NUMERONF,
  N.SERIENF,
  N.SEQNF,
  N.SEQPESSOA AS SEQPESSOA_FORNECEDOR_NF,
  NF.NOMERAZAO AS FORNECEDOR_NF,
  I.SEQPRODUTO,
  P.DESCCOMPLETA AS DESC_PRODUTO,
  FD.SEQCOMPRADOR,
  NVL(C.COMPRADOR, 'SEM GESTOR') AS COMPRADOR,
  FF.SEQFORNECEDOR AS CODIGO_FORNECEDOR_PRINCIPAL,
  GP.NOMERAZAO AS FORNECEDOR_PRINCIPAL,
  NVL(I.QUANTIDADE, 0) AS QTD_ITEM,
  NVL(I.VLRITEM, 0) AS VLR_ITEM_ENTRADA
FROM MLFV_BASENFE N
LEFT JOIN MFLV_BASEDFITEM I
    ON I.NROEMPRESA = N.NROEMPRESA
  AND I.SEQNF = N.SEQNF
LEFT JOIN MAP_PRODUTO P
    ON P.SEQPRODUTO = I.SEQPRODUTO
LEFT JOIN MAP_FAMFORNEC FF
    ON FF.SEQFAMILIA = P.SEQFAMILIA
   AND FF.PRINCIPAL = 'S'
LEFT JOIN GE_PESSOA GP
    ON GP.SEQPESSOA = FF.SEQFORNECEDOR
LEFT JOIN GE_PESSOA NF
    ON NF.SEQPESSOA = N.SEQPESSOA
LEFT JOIN MAP_FAMDIVISAO FD
    ON FD.SEQFAMILIA = P.SEQFAMILIA
   AND FD.NRODIVISAO = 1
LEFT JOIN MAX_COMPRADOR C
  ON C.SEQCOMPRADOR = FD.SEQCOMPRADOR
WHERE N.CODGERALOPER IN (200, 202)
  AND N.NROEMPRESA IN (1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 14, 15, 17, 18)
  AND N.DTAEMISSAO >= TRUNC(SYSDATE) - 30
  AND N.DTAEMISSAO < TRUNC(SYSDATE) + 1
  AND (
        N.SEQPESSOA = 7086
     OR FF.SEQFORNECEDOR = 7086
     OR UPPER(NF.NOMERAZAO) LIKE '%BUNGE%'
     OR UPPER(GP.NOMERAZAO) LIKE '%BUNGE%'
  )
ORDER BY
  TRUNC(N.DTAEMISSAO),
  N.NROEMPRESA,
  N.NUMERONF,
  I.SEQPRODUTO;


SELECT
  NVL(N.SEQPESSOA, FF.SEQFORNECEDOR) AS CODIGO_FORNECEDOR,
  NVL(NF.NOMERAZAO, GP.NOMERAZAO) AS FORNECEDOR,
  NVL(C.COMPRADOR, 'SEM GESTOR') AS COMPRADOR,
  COUNT(DISTINCT N.SEQNF) AS QTD_NOTAS,
  ROUND(SUM(NVL(I.VLRITEM, 0)), 2) AS VLR_COMPRA_MES
FROM MLFV_BASENFE N
LEFT JOIN MFLV_BASEDFITEM I
    ON I.NROEMPRESA = N.NROEMPRESA
  AND I.SEQNF = N.SEQNF
LEFT JOIN MAP_PRODUTO P
    ON P.SEQPRODUTO = I.SEQPRODUTO
LEFT JOIN MAP_FAMFORNEC FF
    ON FF.SEQFAMILIA = P.SEQFAMILIA
   AND FF.PRINCIPAL = 'S'
LEFT JOIN GE_PESSOA GP
    ON GP.SEQPESSOA = FF.SEQFORNECEDOR
LEFT JOIN GE_PESSOA NF
  ON NF.SEQPESSOA = N.SEQPESSOA
LEFT JOIN MAP_FAMDIVISAO FD
    ON FD.SEQFAMILIA = P.SEQFAMILIA
   AND FD.NRODIVISAO = 1
LEFT JOIN MAX_COMPRADOR C
  ON C.SEQCOMPRADOR = FD.SEQCOMPRADOR
WHERE N.CODGERALOPER IN (200, 202)
  AND N.NROEMPRESA IN (1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 14, 15, 17, 18)
  AND N.DTAEMISSAO >= TRUNC(SYSDATE) - 30
  AND N.DTAEMISSAO < TRUNC(SYSDATE) + 1
GROUP BY
  NVL(N.SEQPESSOA, FF.SEQFORNECEDOR),
  NVL(NF.NOMERAZAO, GP.NOMERAZAO),
  NVL(C.COMPRADOR, 'SEM GESTOR')
ORDER BY
  VLR_COMPRA_MES DESC,
  COMPRADOR;