SELECT
  TRUNC(MLF_NOTAFISCAL.DTAENTRADA) AS DTA_ENTRADA,
  N.NROEMPRESA,
  N.SEQNF,
  N.NUMERONF,
  N.SERIENF,
  N.SEQPESSOA AS SEQPESSOA_FORNECEDOR_NF,
  GE_PESSOA.NOMERAZAO AS FORNECEDOR_NF,
  N.SEQPRODUTO,
  MAP_PRODUTO.DESCCOMPLETA AS DESC_PRODUTO,
  MAX_CODGERALOPER.CODGERALOPER AS CODGERALOPER_ORIGINAL,
  CASE
    WHEN (N.TIPPEDCOMPRAITEM = 'B' OR N.TIPPEDCOMPRAITEM = 'E')
    AND MLF_NOTAFISCAL.TIPPEDIDOCOMPRA = 'C'
    THEN TO_NUMBER(MAX_PARAMETRO.VALOR)
    ELSE MAX_CODGERALOPER.CODGERALOPER
  END AS CODGERALOPER_EFETIVO,
  CASE
    WHEN (
      CASE
        WHEN (N.TIPPEDCOMPRAITEM = 'B' OR N.TIPPEDCOMPRAITEM = 'E')
         AND MLF_NOTAFISCAL.TIPPEDIDOCOMPRA = 'C'
        THEN TO_NUMBER(MAX_PARAMETRO.VALOR)
        ELSE MAX_CODGERALOPER.CODGERALOPER
      END
    ) = 1 THEN NVL(N.VLRITEM, 0)
    ELSE 0
  END AS VLR_CGO_1,
  CASE
    WHEN (
      CASE
        WHEN (N.TIPPEDCOMPRAITEM = 'B' OR N.TIPPEDCOMPRAITEM = 'E')
         AND MLF_NOTAFISCAL.TIPPEDIDOCOMPRA = 'C'
        THEN TO_NUMBER(MAX_PARAMETRO.VALOR)
        ELSE MAX_CODGERALOPER.CODGERALOPER
      END
    ) = 50 THEN NVL(N.VLRITEM, 0)
    ELSE 0
  END AS VLR_CGO_50,
  N.LANCAMENTOST,
  NVL(N.QUANTIDADE, 0) AS QTD_ITEM,
  NVL(N.QTDEMBALAGEM, 0) AS QTDEMBALAGEM,
  N.EMBALAGEM || ' ' || N.QTDEMBALAGEM AS EMB,
  NVL(N.VLRITEM, 0) AS VLR_ITEM_ENTRADA,
  MAX_COMPRADOR.SEQCOMPRADOR,
  NVL(MAX_COMPRADOR.COMPRADOR, 'SEM GESTOR') AS COMPRADOR,
  MAX_FAMFORNEC.SEQFORNECEDOR AS CODIGO_FORNECEDOR_PRINCIPAL,
  GE_PESSOA_1.NOMERAZAO AS FORNECEDOR_PRINCIPAL,
  N.ROWID AS ROWID_NF
FROM MLF_NFITEM N
JOIN MLF_NOTAFISCAL MLF_NOTAFISCAL
  ON MLF_NOTAFISCAL.NUMERONF = N.NUMERONF
 AND MLF_NOTAFISCAL.SERIENF = N.SERIENF
 AND MLF_NOTAFISCAL.NROEMPRESA = N.NROEMPRESA
 AND MLF_NOTAFISCAL.TIPNOTAFISCAL = N.TIPNOTAFISCAL
 AND NVL(MLF_NOTAFISCAL.SEQNF, 0) = NVL(N.SEQNF, NVL(MLF_NOTAFISCAL.SEQNF, 0))
JOIN GE_PESSOA
  ON GE_PESSOA.SEQPESSOA = MLF_NOTAFISCAL.SEQPESSOA
JOIN MAX_CODGERALOPER
  ON MAX_CODGERALOPER.CODGERALOPER = MLF_NOTAFISCAL.CODGERALOPER
JOIN MAP_PRODUTO
  ON MAP_PRODUTO.SEQPRODUTO = N.SEQPRODUTO
LEFT JOIN MAP_FAMFORNEC MAX_FAMFORNEC
  ON MAX_FAMFORNEC.SEQFAMILIA = MAP_PRODUTO.SEQFAMILIA
 AND MAX_FAMFORNEC.PRINCIPAL = 'S'
LEFT JOIN GE_PESSOA GE_PESSOA_1
  ON GE_PESSOA_1.SEQPESSOA = MAX_FAMFORNEC.SEQFORNECEDOR
LEFT JOIN MAP_FAMDIVISAO
  ON MAP_FAMDIVISAO.SEQFAMILIA = MAP_PRODUTO.SEQFAMILIA
 AND MAP_FAMDIVISAO.NRODIVISAO = 1
LEFT JOIN MAX_COMPRADOR
  ON MAX_COMPRADOR.SEQCOMPRADOR = MAP_FAMDIVISAO.SEQCOMPRADOR
LEFT JOIN MAX_PARAMETRO
  ON MAX_PARAMETRO.NROEMPRESA = MLF_NOTAFISCAL.NROEMPRESA
 AND MAX_PARAMETRO.PARAMETRO = 'CGO_ENTR_BONIF_NFCOMPRA'
WHERE MLF_NOTAFISCAL.DTAENTRADA >= TRUNC(SYSDATE) - 30
  AND MLF_NOTAFISCAL.DTAENTRADA < TRUNC(SYSDATE) + 1
  AND MLF_NOTAFISCAL.STATUSNF <> 'C'
  AND MLF_NOTAFISCAL.NUMERONF IS NOT NULL
  AND N.TIPNOTAFISCAL = 'E'
  AND N.TIPITEM = 'R'
  AND N.SEQPRODUTO = 981
  AND (
        MLF_NOTAFISCAL.SEQPESSOA = 7086
     OR MAX_FAMFORNEC.SEQFORNECEDOR = 7086
     OR UPPER(GE_PESSOA.NOMERAZAO) LIKE '%BUNGE%'
     OR UPPER(GE_PESSOA_1.NOMERAZAO) LIKE '%BUNGE%'
  )
ORDER BY
  TRUNC(MLF_NOTAFISCAL.DTAENTRADA) DESC,
  N.NROEMPRESA,
  MLF_NOTAFISCAL.NUMERONF,
  N.SEQPRODUTO;


SELECT
  NVL(MLF_NOTAFISCAL.SEQPESSOA, MAX_FAMFORNEC.SEQFORNECEDOR) AS CODIGO_FORNECEDOR,
  NVL(GE_PESSOA.NOMERAZAO, GE_PESSOA_1.NOMERAZAO) AS FORNECEDOR,
  NVL(MAX_COMPRADOR.COMPRADOR, 'SEM GESTOR') AS COMPRADOR,
  COUNT(DISTINCT MLF_NOTAFISCAL.SEQNF) AS QTD_NOTAS,
  ROUND(SUM(CASE
    WHEN (
      CASE
        WHEN (N.TIPPEDCOMPRAITEM = 'B' OR N.TIPPEDCOMPRAITEM = 'E')
         AND MLF_NOTAFISCAL.TIPPEDIDOCOMPRA = 'C'
        THEN TO_NUMBER(MAX_PARAMETRO.VALOR)
        ELSE MAX_CODGERALOPER.CODGERALOPER
      END
    ) = 1 THEN NVL(N.VLRITEM, 0)
    ELSE 0
  END), 2) AS VLR_CGO_1,
  ROUND(SUM(CASE
    WHEN (
      CASE
        WHEN (N.TIPPEDCOMPRAITEM = 'B' OR N.TIPPEDCOMPRAITEM = 'E')
         AND MLF_NOTAFISCAL.TIPPEDIDOCOMPRA = 'C'
        THEN TO_NUMBER(MAX_PARAMETRO.VALOR)
        ELSE MAX_CODGERALOPER.CODGERALOPER
      END
    ) = 50 THEN NVL(N.VLRITEM, 0)
    ELSE 0
  END), 2) AS VLR_CGO_50
FROM MLF_NFITEM N
JOIN MLF_NOTAFISCAL MLF_NOTAFISCAL
  ON MLF_NOTAFISCAL.NUMERONF = N.NUMERONF
 AND MLF_NOTAFISCAL.SERIENF = N.SERIENF
 AND MLF_NOTAFISCAL.NROEMPRESA = N.NROEMPRESA
 AND MLF_NOTAFISCAL.TIPNOTAFISCAL = N.TIPNOTAFISCAL
 AND NVL(MLF_NOTAFISCAL.SEQNF, 0) = NVL(N.SEQNF, NVL(MLF_NOTAFISCAL.SEQNF, 0))
JOIN GE_PESSOA
  ON GE_PESSOA.SEQPESSOA = MLF_NOTAFISCAL.SEQPESSOA
JOIN MAX_CODGERALOPER
  ON MAX_CODGERALOPER.CODGERALOPER = MLF_NOTAFISCAL.CODGERALOPER
JOIN MAP_PRODUTO
  ON MAP_PRODUTO.SEQPRODUTO = N.SEQPRODUTO
LEFT JOIN MAP_FAMFORNEC MAX_FAMFORNEC
  ON MAX_FAMFORNEC.SEQFAMILIA = MAP_PRODUTO.SEQFAMILIA
 AND MAX_FAMFORNEC.PRINCIPAL = 'S'
LEFT JOIN GE_PESSOA GE_PESSOA_1
  ON GE_PESSOA_1.SEQPESSOA = MAX_FAMFORNEC.SEQFORNECEDOR
LEFT JOIN MAP_FAMDIVISAO
  ON MAP_FAMDIVISAO.SEQFAMILIA = MAP_PRODUTO.SEQFAMILIA
 AND MAP_FAMDIVISAO.NRODIVISAO = 1
LEFT JOIN MAX_COMPRADOR
  ON MAX_COMPRADOR.SEQCOMPRADOR = MAP_FAMDIVISAO.SEQCOMPRADOR
LEFT JOIN MAX_PARAMETRO
  ON MAX_PARAMETRO.NROEMPRESA = MLF_NOTAFISCAL.NROEMPRESA
 AND MAX_PARAMETRO.PARAMETRO = 'CGO_ENTR_BONIF_NFCOMPRA'
WHERE MLF_NOTAFISCAL.DTAENTRADA >= TRUNC(SYSDATE) - 60
  AND MLF_NOTAFISCAL.DTAENTRADA < TRUNC(SYSDATE) + 1
  AND MLF_NOTAFISCAL.STATUSNF <> 'C'
  AND MLF_NOTAFISCAL.NUMERONF IS NOT NULL
  AND N.TIPNOTAFISCAL = 'E'
  AND N.TIPITEM = 'R'
  AND N.SEQPRODUTO = 981
  AND (
        MLF_NOTAFISCAL.SEQPESSOA = 7086
     OR MAX_FAMFORNEC.SEQFORNECEDOR = 7086
     OR UPPER(GE_PESSOA.NOMERAZAO) LIKE '%BUNGE%'
     OR UPPER(GE_PESSOA_1.NOMERAZAO) LIKE '%BUNGE%'
  )
GROUP BY
  NVL(MLF_NOTAFISCAL.SEQPESSOA, MAX_FAMFORNEC.SEQFORNECEDOR),
  NVL(GE_PESSOA.NOMERAZAO, GE_PESSOA_1.NOMERAZAO),
  NVL(MAX_COMPRADOR.COMPRADOR, 'SEM GESTOR')
ORDER BY
  VLR_CGO_1 DESC,
  VLR_CGO_50 DESC,
  COMPRADOR;