SELECT
    BASE.NROCARGA,
    BASE.NROPEDVENDA,
    BASE.QTDE_PRODUTOS_CONFERIDOS,
    TO_CHAR(BASE.DATA_CONFERENCIA, 'DD/MM/YYYY HH24:MI') AS DATA_CONFERENCIA,
    BASE.USUARIO_CONFERENCIA,
    EXP.STATUSCARGA,
    TO_CHAR(EXP.DTAHORGERACAO, 'DD/MM/YYYY HH24:MI') AS DATA_GERACAO_CARGA,
    TO_CHAR(EXP.DTAHORFATURAMENTO, 'DD/MM/YYYY HH24:MI') AS DATA_FATURAMENTO_CARGA,
    TO_CHAR(EXP.DTAHORSAIDA, 'DD/MM/YYYY HH24:MI') AS DATA_SAIDA_CARGA,
    TO_CHAR(EXP.DTAHORSAIDANF, 'DD/MM/YYYY HH24:MI') AS DATA_SAIDA_NF,
    CLI.STATUSSEPARACAO,
    CLI.STATUSFATURAMENTO,
    CASE
        WHEN CAR.NROCARGA IS NOT NULL THEN 'SIM'
        ELSE 'NAO'
    END AS TEM_CARREGAMENTO,
    CAR.STATUSPALETE_EXEMPLO,
    CAR.USUARIO_CARREGAMENTO,
    CASE
        WHEN NF.NROCARGA IS NOT NULL THEN 'SIM'
        ELSE 'NAO'
    END AS TEM_NF,
    TO_CHAR(NF.DTAEMISSAO, 'DD/MM/YYYY HH24:MI') AS DATA_EMISSAO_NF,
    TO_CHAR(NF.DTAHORFATURAMENTO, 'DD/MM/YYYY HH24:MI') AS DATA_FATURAMENTO_NF,
    NF.STATUSCARGA_NF,
    NF.USUFATURAMENTO_NF
FROM (
    SELECT
        X.NROCARGA,
        X.NROPEDVENDA,
        COUNT(DISTINCT X.SEQPRODUTO) AS QTDE_PRODUTOS_CONFERIDOS,
        MAX(X.DTAHORCONFERENCIA) AS DATA_CONFERENCIA,
        MAX(X.USUCONFERENCIA) KEEP (DENSE_RANK LAST ORDER BY X.DTAHORCONFERENCIA) AS USUARIO_CONFERENCIA
    FROM (
        SELECT
            P.NROCARGA,
            P.NROPEDVENDA,
            P.SEQPRODUTO,
            P.DTAHORCONFERENCIA,
            P.USUCONFERENCIA
        FROM MRL_CARGAEXPPROD P
        WHERE P.DTAHORCONFERENCIA IS NOT NULL
          AND P.DTAHORCONFERENCIA >= TRUNC(SYSDATE) - 120

        UNION ALL

        SELECT
            L.NROCARGA,
            L.NROPEDVENDA,
            L.SEQPRODUTO,
            L.DTAHORCONFERENCIA,
            L.USUCONFERENCIA
        FROM MRL_CARGAEXPPRODLOTE L
        WHERE L.DTAHORCONFERENCIA IS NOT NULL
          AND L.DTAHORCONFERENCIA >= TRUNC(SYSDATE) - 120
    ) X
    GROUP BY
        X.NROCARGA,
        X.NROPEDVENDA
) BASE
LEFT JOIN MRL_CARGAEXPED EXP
    ON BASE.NROCARGA = EXP.NROCARGA
LEFT JOIN (
    SELECT
        C.NROCARGA,
        C.NROPEDVENDA,
        MAX(C.STATUSSEPARACAO) KEEP (DENSE_RANK LAST ORDER BY C.DTAHORFATURAMENTO NULLS FIRST) AS STATUSSEPARACAO,
        MAX(C.STATUSFATURAMENTO) KEEP (DENSE_RANK LAST ORDER BY C.DTAHORFATURAMENTO NULLS FIRST) AS STATUSFATURAMENTO
    FROM MRL_CARGAEXPCLI C
    GROUP BY
        C.NROCARGA,
        C.NROPEDVENDA
) CLI
    ON BASE.NROCARGA = CLI.NROCARGA
   AND BASE.NROPEDVENDA = CLI.NROPEDVENDA
LEFT JOIN (
    SELECT
        W.NROCARGA,
        MAX(W.STATUSPALETE) AS STATUSPALETE_EXEMPLO,
        MAX(W.NOMEUSUARIO) AS USUARIO_CARREGAMENTO
    FROM WMSV_CARREGAMENTOS W
    GROUP BY
        W.NROCARGA
) CAR
    ON BASE.NROCARGA = CAR.NROCARGA
LEFT JOIN (
    SELECT
        N.NROCARGA,
        MAX(N.DTAEMISSAO) AS DTAEMISSAO,
        MAX(N.DTAHORFATURAMENTO) AS DTAHORFATURAMENTO,
        MAX(N.STATUSCARGA) AS STATUSCARGA_NF,
        MAX(N.USUFATURAMENTO) AS USUFATURAMENTO_NF
    FROM MRLV_CARGAEXPTOTALNF N
    GROUP BY
        N.NROCARGA
) NF
    ON BASE.NROCARGA = NF.NROCARGA
ORDER BY
    CASE
        WHEN NF.NROCARGA IS NOT NULL THEN 0
        WHEN CAR.NROCARGA IS NOT NULL THEN 1
        WHEN EXP.DTAHORFATURAMENTO IS NOT NULL THEN 2
        WHEN EXP.DTAHORSAIDA IS NOT NULL THEN 3
        ELSE 4
    END,
    BASE.DATA_CONFERENCIA DESC,
    BASE.NROCARGA,
    BASE.NROPEDVENDA;