SELECT * FROM (
    WITH PRODUTOS_FORNEC AS (
        SELECT /*+ MATERIALIZE */
            A.SEQPRODUTO,
            A.DESCCOMPLETA,
            FF.SEQFORNECEDOR AS COD_FORNECEDOR,
            PES.NOMERAZAO AS RAZAO_FORNECEDOR,
            FF.PRINCIPAL AS FORN_PRINCIPAL,
            TO_CHAR(TRUNC(A.DTAHORINCLUSAO), 'DD/MM/YYYY') AS DATA_CADASTRO,
            (TRUNC(SYSDATE) - TRUNC(A.DTAHORINCLUSAO)) AS DIAS_CADASTRO
        FROM MAP_PRODUTO A
        INNER JOIN MAP_FAMFORNEC FF 
            ON FF.SEQFAMILIA = A.SEQFAMILIA
        INNER JOIN GE_PESSOA PES 
            ON PES.SEQPESSOA = FF.SEQFORNECEDOR
        WHERE (
            NVL(TRIM(:LT1), '0') IN ('0', 'TODOS', '')
            OR INSTR(',' || REPLACE(TRIM(:LT1), ' ', '') || ',', ',' || TO_CHAR(FF.SEQFORNECEDOR) || ',') > 0
        )
          AND TRUNC(A.DTAHORINCLUSAO) <= TRUNC(SYSDATE) - 90
    ),
    PRODUTOS_LOJAS_ATIVOS AS (
        SELECT /*+ MATERIALIZE */
            PF.SEQPRODUTO,
            PF.DESCCOMPLETA,
            PF.COD_FORNECEDOR,
            PF.RAZAO_FORNECEDOR,
            PF.FORN_PRINCIPAL,
            PF.DATA_CADASTRO,
            PF.DIAS_CADASTRO,
            PE.NROEMPRESA,
            TO_CHAR(PE.DTAULTVENDA, 'DD/MM/YYYY') AS DATA_ULTIMA_VENDA,
            NVL(TRUNC(SYSDATE) - TRUNC(PE.DTAULTVENDA), PF.DIAS_CADASTRO) AS DIAS_SEM_VENDA,
            (NVL(PE.ESTQLOJA, 0) + NVL(PE.ESTQDEPOSITO, 0) - NVL(PE.QTDRESERVADAVDA, 0) - NVL(PE.QTDRESERVADARECEB, 0)) AS ESTOQUE_LOJA
        FROM MRL_PRODUTOEMPRESA PE
        INNER JOIN PRODUTOS_FORNEC PF 
            ON PF.SEQPRODUTO = PE.SEQPRODUTO
        WHERE PE.NROEMPRESA IN (1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 14, 15, 17, 18)
          AND PE.STATUSCOMPRA = 'A'
    ),
    VENDAS_90D AS (
        SELECT /*+ MATERIALIZE */
            C.SEQPRODUTO,
            C.NROEMPRESA,
            SUM(NVL(C.QTDVDA, 0)) AS TOTAL_QTD_VENDIDA
        FROM MRL_CUSTODIA C
        INNER JOIN PRODUTOS_FORNEC PF 
            ON PF.SEQPRODUTO = C.SEQPRODUTO
        WHERE C.DTAENTRADASAIDA >= TRUNC(SYSDATE) - 90
          AND C.NROEMPRESA IN (1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 14, 15, 17, 18)
        GROUP BY C.SEQPRODUTO, C.NROEMPRESA
    ),
    ESTOQUE_CD15 AS (
        SELECT /*+ MATERIALIZE */
            PE.SEQPRODUTO,
            SUM(NVL(PE.ESTQLOJA, 0) + NVL(PE.ESTQDEPOSITO, 0) - NVL(PE.QTDRESERVADAVDA, 0) - NVL(PE.QTDRESERVADARECEB, 0)) AS ESTOQUE_CD15
        FROM MRL_PRODUTOEMPRESA PE
        INNER JOIN PRODUTOS_FORNEC PF 
            ON PF.SEQPRODUTO = PE.SEQPRODUTO
        WHERE PE.NROEMPRESA = 15
        GROUP BY PE.SEQPRODUTO
    )
    SELECT DISTINCT
        PLA.NROEMPRESA AS COD_EMPRESA,
        NVL(E.FANTASIA, 'LOJA ' || TO_CHAR(PLA.NROEMPRESA)) AS LOJA,
        PLA.SEQPRODUTO,
        PLA.DESCCOMPLETA,
        PLA.COD_FORNECEDOR,
        PLA.RAZAO_FORNECEDOR,
        PLA.FORN_PRINCIPAL,
        PLA.DATA_CADASTRO,
        PLA.DIAS_CADASTRO,
        PLA.DATA_ULTIMA_VENDA,
        PLA.DIAS_SEM_VENDA,
        PLA.ESTOQUE_LOJA,
        NVL(CD15.ESTOQUE_CD15, 0) AS ESTOQUE_CD15
    FROM PRODUTOS_LOJAS_ATIVOS PLA
    INNER JOIN MAX_EMPRESA E 
        ON E.NROEMPRESA = PLA.NROEMPRESA
    LEFT JOIN VENDAS_90D V 
        ON V.SEQPRODUTO = PLA.SEQPRODUTO 
       AND V.NROEMPRESA = PLA.NROEMPRESA
    LEFT JOIN ESTOQUE_CD15 CD15 
        ON CD15.SEQPRODUTO = PLA.SEQPRODUTO
    WHERE NVL(V.TOTAL_QTD_VENDIDA, 0) = 0
    ORDER BY 
        PLA.NROEMPRESA,
        PLA.COD_FORNECEDOR,
        PLA.DESCCOMPLETA
)
