SELECT * FROM (
    WITH PRODUTOS_FORNEC AS (
        SELECT /*+ MATERIALIZE */
            A.SEQPRODUTO,
            A.DESCCOMPLETA,
            FF.SEQFORNECEDOR AS COD_FORNECEDOR,
            PES.NOMERAZAO AS RAZAO_FORNECEDOR,
            FF.PRINCIPAL AS FORN_PRINCIPAL,
            TO_CHAR(TRUNC(A.DTAHORINCLUSAO), 'DD/MM/YYYY') AS DATA_CADASTRO,
            (TRUNC(SYSDATE) - TRUNC(A.DTAHORINCLUSAO)) AS DIAS_CADASTRO
        FROM MAP_PRODUTO A
        INNER JOIN MAP_FAMFORNEC FF 
            ON FF.SEQFAMILIA = A.SEQFAMILIA
        INNER JOIN GE_PESSOA PES 
            ON PES.SEQPESSOA = FF.SEQFORNECEDOR
        WHERE (
            NVL(TRIM(:LT1), '0') IN ('0', 'TODOS', '')
            OR INSTR(',' || REPLACE(TRIM(:LT1), ' ', '') || ',', ',' || TO_CHAR(FF.SEQFORNECEDOR) || ',') > 0
        )
    ),
    VENDAS_90D AS (
        SELECT /*+ MATERIALIZE */
            C.SEQPRODUTO,
            C.NROEMPRESA,
            ROUND(SUM(NVL(C.QTDVDA, 0)), 2) AS TOTAL_QTD_VENDIDA
        FROM MRL_CUSTODIA C
        INNER JOIN PRODUTOS_FORNEC PF 
            ON PF.SEQPRODUTO = C.SEQPRODUTO
        WHERE C.DTAENTRADASAIDA >= TRUNC(SYSDATE) - 90
          AND C.NROEMPRESA IN (1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 14, 15, 17, 18)
        GROUP BY C.SEQPRODUTO, C.NROEMPRESA
        HAVING SUM(NVL(C.QTDVDA, 0)) > 0
    ),
    ESTOQUE_CD15 AS (
        SELECT /*+ MATERIALIZE */
            PE.SEQPRODUTO,
            SUM(NVL(PE.ESTQLOJA, 0) + NVL(PE.ESTQDEPOSITO, 0) - NVL(PE.QTDRESERVADAVDA, 0) - NVL(PE.QTDRESERVADARECEB, 0)) AS ESTOQUE_CD15
        FROM MRL_PRODUTOEMPRESA PE
        INNER JOIN PRODUTOS_FORNEC PF 
            ON PF.SEQPRODUTO = PE.SEQPRODUTO
        WHERE PE.NROEMPRESA = 15
        GROUP BY PE.SEQPRODUTO
    )
    SELECT DISTINCT
        V.NROEMPRESA AS COD_EMPRESA,
        NVL(E.FANTASIA, 'LOJA ' || TO_CHAR(V.NROEMPRESA)) AS LOJA,
        PF.SEQPRODUTO,
        PF.DESCCOMPLETA,
        PF.COD_FORNECEDOR,
        PF.RAZAO_FORNECEDOR,
        PF.FORN_PRINCIPAL,
        PF.DATA_CADASTRO,
        PF.DIAS_CADASTRO,
        TO_CHAR(PE.DTAULTVENDA, 'DD/MM/YYYY') AS DATA_ULTIMA_VENDA,
        NVL(TRUNC(SYSDATE) - TRUNC(PE.DTAULTVENDA), 0) AS DIAS_SEM_VENDA,
        V.TOTAL_QTD_VENDIDA AS QTD_VENDIDA_90D,
        (NVL(PE.ESTQLOJA, 0) + NVL(PE.ESTQDEPOSITO, 0) - NVL(PE.QTDRESERVADAVDA, 0) - NVL(PE.QTDRESERVADARECEB, 0)) AS ESTOQUE_LOJA,
        NVL(CD15.ESTOQUE_CD15, 0) AS ESTOQUE_CD15
    FROM VENDAS_90D V
    INNER JOIN PRODUTOS_FORNEC PF 
        ON PF.SEQPRODUTO = V.SEQPRODUTO
    INNER JOIN MAX_EMPRESA E 
        ON E.NROEMPRESA = V.NROEMPRESA
    LEFT JOIN MRL_PRODUTOEMPRESA PE 
        ON PE.SEQPRODUTO = V.SEQPRODUTO 
       AND PE.NROEMPRESA = V.NROEMPRESA
    LEFT JOIN ESTOQUE_CD15 CD15 
        ON CD15.SEQPRODUTO = V.SEQPRODUTO
    ORDER BY 
        V.NROEMPRESA,
        V.TOTAL_QTD_VENDIDA DESC,
        PF.DESCCOMPLETA
)
