SELECT
  X.CODIGO_FORNECEDOR,
  X.FORNECEDOR,
  X.COMPRADOR,
  X.COD,
  X.DESCRICAO,
  X.STATUS_COMPRA,
  X.QTD_ANTERIOR,
  X.QTD_ATUAL,
  (NVL(X.QTD_ATUAL, 0) - NVL(X.QTD_ANTERIOR, 0)) AS DIFERENCA_QTD
FROM (
  SELECT
    :NR1 AS CODIGO_FORNECEDOR,
    NVL(FORN.NOMERAZAO, 'SEM FORNECEDOR') AS FORNECEDOR,
    NVL(COMP.APELIDO, NVL(COMP.COMPRADOR, 'SEM COMPRADOR')) AS COMPRADOR,
    P.SEQPRODUTO AS COD,
    P.DESCCOMPLETA AS DESCRICAO,
    CASE WHEN PE.STATUSCOMPRA = 'A' THEN 'Ativo' ELSE 'Inativo' END AS STATUS_COMPRA,
    NVL(Q1.QTD_ATUAL, 0) AS QTD_ATUAL,
    NVL(Q2.QTD_ANTERIOR, 0) AS QTD_ANTERIOR
  FROM MAP_PRODUTO P
  LEFT JOIN MAP_FAMDIVISAO FD
    ON FD.SEQFAMILIA = P.SEQFAMILIA
   AND FD.NRODIVISAO = 1
  LEFT JOIN MAX_COMPRADOR COMP
    ON COMP.SEQCOMPRADOR = FD.SEQCOMPRADOR
  LEFT JOIN GE_PESSOA FORN
    ON FORN.SEQPESSOA = :NR1
  LEFT JOIN MRL_PRODUTOEMPRESA PE
    ON PE.SEQPRODUTO = P.SEQPRODUTO
   AND PE.NROEMPRESA = 1
  LEFT JOIN (
    SELECT
      V.SEQPRODUTO,
      SUM(V.QTDVDA) AS QTD_ATUAL
    FROM MRL_PRODVENDADIA V
    WHERE V.DTAVDA BETWEEN :DT3 AND :DT4
    GROUP BY
      V.SEQPRODUTO
  ) Q1
    ON Q1.SEQPRODUTO = P.SEQPRODUTO
  LEFT JOIN (
    SELECT
      V.SEQPRODUTO,
      SUM(V.QTDVDA) AS QTD_ANTERIOR
    FROM MRL_PRODVENDADIA V
    WHERE V.DTAVDA BETWEEN :DT1 AND :DT2
    GROUP BY
      V.SEQPRODUTO
  ) Q2
    ON Q2.SEQPRODUTO = P.SEQPRODUTO
  WHERE NVL(:NR1, 0) > 0
    AND PE.STATUSCOMPRA = 'A'
    AND EXISTS (
      SELECT 1
      FROM MAP_FAMFORNEC F
      WHERE F.SEQFAMILIA = P.SEQFAMILIA
        AND F.SEQFORNECEDOR = :NR1
    )
    AND NOT EXISTS (
      SELECT 1
      FROM MAP_FAMDIVCATEG FDC
      INNER JOIN MAP_CATEGORIA CAT ON CAT.SEQCATEGORIA = FDC.SEQCATEGORIA
      WHERE FDC.SEQFAMILIA = P.SEQFAMILIA
        AND FDC.NRODIVISAO = 1
        AND CAT.NRODIVISAO = 1
        AND CAT.NIVELHIERARQUIA = 1
        AND UPPER(CAT.CATEGORIA) IN ('ALMOXARIFADO', 'A CLASSIFICAR', 'INATIVAR', 'SERVICOS')
    )
    AND (
      NVL(TRIM(#LS1), '0 - TODOS') IN ('0 - TODOS', 'TODOS', '')
      OR (
        INSTR(#LS1, ' - ') > 0
        AND FD.SEQCOMPRADOR = TO_NUMBER(SUBSTR(#LS1, 1, INSTR(#LS1, ' - ') - 1))
      )
    )
) X
ORDER BY
  X.DESCRICAO