SELECT * FROM (

    WITH FORN_RANK AS (
        SELECT /*+ MATERIALIZE */
            F.SEQFAMILIA,
            F.SEQFORNECEDOR AS CODIGO_FORNECEDOR,
            P.NOMERAZAO AS FORNECEDOR,
            ROW_NUMBER() OVER (PARTITION BY F.SEQFAMILIA ORDER BY F.PRINCIPAL DESC, F.SEQFORNECEDOR ASC) AS RN
        FROM MAP_FAMFORNEC F
        JOIN GE_PESSOA P ON P.SEQPESSOA = F.SEQFORNECEDOR
    ),
    FORNECEDORES AS (
        SELECT /*+ MATERIALIZE */
            SEQFAMILIA,
            CODIGO_FORNECEDOR,
            FORNECEDOR
        FROM FORN_RANK
        WHERE RN = 1
    ),
    VENDAS AS (
        SELECT /*+ MATERIALIZE */
            V.SEQPRODUTO,
            SUM(CASE WHEN V.DTAVDA BETWEEN :DT3 AND :DT4 THEN V.QTDVDA ELSE 0 END) AS QTD_ATUAL,
            SUM(CASE WHEN V.DTAVDA BETWEEN :DT1 AND :DT2 THEN V.QTDVDA ELSE 0 END) AS QTD_ANTERIOR
        FROM MRL_PRODVENDADIA V
        WHERE V.DTAVDA BETWEEN TRUNC(LEAST(:DT1, :DT3)) AND TRUNC(GREATEST(:DT2, :DT4))
        GROUP BY V.SEQPRODUTO
    )
    SELECT
      X.CODIGO_FORNECEDOR,
      X.FORNECEDOR,
      X.COMPRADOR,
      X.COD,
      X.DESCRICAO,
      X.STATUS_COMPRA,
      X.QTD_ANTERIOR,
      X.QTD_ATUAL,
      (NVL(X.QTD_ATUAL, 0) - NVL(X.QTD_ANTERIOR, 0)) AS DIFERENCA_QTD
    FROM (
      SELECT
        CASE WHEN TO_NUMBER(NVL(:NR1, '0')) > 0 THEN TO_NUMBER(:NR1) ELSE NVL(FORN.CODIGO_FORNECEDOR, 0) END AS CODIGO_FORNECEDOR,
        CASE WHEN TO_NUMBER(NVL(:NR1, '0')) > 0 THEN NVL(FORN_FILTRO.NOMERAZAO, 'SEM FORNECEDOR') ELSE NVL(FORN.FORNECEDOR, 'SEM FORNECEDOR') END AS FORNECEDOR,
        NVL(COMP.APELIDO, NVL(COMP.COMPRADOR, 'SEM COMPRADOR')) AS COMPRADOR,
        P.SEQPRODUTO AS COD,
        P.DESCCOMPLETA AS DESCRICAO,
        CASE WHEN PE.STATUSCOMPRA = 'A' THEN 'Ativo' ELSE 'Inativo' END AS STATUS_COMPRA,
        NVL(V.QTD_ATUAL, 0) AS QTD_ATUAL,
        NVL(V.QTD_ANTERIOR, 0) AS QTD_ANTERIOR
      FROM MAP_PRODUTO P
      LEFT JOIN MAP_FAMDIVISAO FD ON FD.SEQFAMILIA = P.SEQFAMILIA AND FD.NRODIVISAO = 1
      LEFT JOIN MAX_COMPRADOR COMP ON COMP.SEQCOMPRADOR = FD.SEQCOMPRADOR
      LEFT JOIN GE_PESSOA FORN_FILTRO ON FORN_FILTRO.SEQPESSOA = TO_NUMBER(:NR1) AND TO_NUMBER(NVL(:NR1, '0')) > 0
      LEFT JOIN FORNECEDORES FORN ON FORN.SEQFAMILIA = P.SEQFAMILIA
      LEFT JOIN MRL_PRODUTOEMPRESA PE ON PE.SEQPRODUTO = P.SEQPRODUTO AND PE.NROEMPRESA = 1
      LEFT JOIN VENDAS V ON V.SEQPRODUTO = P.SEQPRODUTO
      WHERE (
          TO_NUMBER(NVL(:NR1, '0')) = 0
          OR FORN.CODIGO_FORNECEDOR = TO_NUMBER(:NR1)
          OR EXISTS (
            SELECT 1
            FROM MAP_FAMFORNEC F2
            WHERE F2.SEQFAMILIA = P.SEQFAMILIA
              AND F2.SEQFORNECEDOR = TO_NUMBER(:NR1)
          )
          OR EXISTS (
            SELECT 1
            FROM MLF_NOTAFISCAL NF
            JOIN MLF_NFITEM I ON I.NUMERONF = NF.NUMERONF AND I.SERIENF = NF.SERIENF AND I.NROEMPRESA = NF.NROEMPRESA AND I.TIPNOTAFISCAL = NF.TIPNOTAFISCAL AND NVL(I.SEQNF,0) = NVL(NF.SEQNF, NVL(I.SEQNF,0))
            WHERE I.SEQPRODUTO = P.SEQPRODUTO
              AND NF.SEQPESSOA = TO_NUMBER(:NR1)
              AND NF.STATUSNF != 'C'
              AND NF.TIPNOTAFISCAL = 'E'
              AND NF.DTAENTRADA >= TRUNC(LEAST(:DT1, :DT3))
              AND NF.DTAENTRADA <= TRUNC(GREATEST(:DT2, :DT4))
          )
          OR EXISTS (
            SELECT 1
            FROM MLFV_BASENFE NFE
            JOIN MFLV_BASEDFITEM IT ON IT.SEQNF = NFE.SEQNF AND IT.NROEMPRESA = NFE.NROEMPRESA AND IT.TIPNOTAFISCAL = NFE.TIPNOTAFISCAL
            WHERE IT.SEQPRODUTO = P.SEQPRODUTO
              AND NFE.SEQPESSOA = TO_NUMBER(:NR1)
              AND NFE.STATUSNF != 'C'
              AND NFE.CODGERALOPER IN (802, 860)
              AND NFE.DTAEMISSAO >= TRUNC(LEAST(:DT1, :DT3))
              AND NFE.DTAEMISSAO <= TRUNC(GREATEST(:DT2, :DT4))
          )
        )
        AND (
          PE.STATUSCOMPRA = 'A'
          OR NVL(V.QTD_ATUAL, 0) <> 0
          OR NVL(V.QTD_ANTERIOR, 0) <> 0
          OR (
            TO_NUMBER(NVL(:NR1, '0')) > 0 AND (
              EXISTS (
                SELECT 1
                FROM MLF_NOTAFISCAL NF
                JOIN MLF_NFITEM I ON I.NUMERONF = NF.NUMERONF AND I.SERIENF = NF.SERIENF AND I.NROEMPRESA = NF.NROEMPRESA AND I.TIPNOTAFISCAL = NF.TIPNOTAFISCAL AND NVL(I.SEQNF,0) = NVL(NF.SEQNF, NVL(I.SEQNF,0))
                WHERE I.SEQPRODUTO = P.SEQPRODUTO
                  AND NF.SEQPESSOA = TO_NUMBER(:NR1)
                  AND NF.STATUSNF != 'C'
                  AND NF.TIPNOTAFISCAL = 'E'
                  AND NF.DTAENTRADA >= TRUNC(LEAST(:DT1, :DT3))
                  AND NF.DTAENTRADA <= TRUNC(GREATEST(:DT2, :DT4))
              )
              OR EXISTS (
                SELECT 1
                FROM MLFV_BASENFE NFE
                JOIN MFLV_BASEDFITEM IT ON IT.SEQNF = NFE.SEQNF AND IT.NROEMPRESA = NFE.NROEMPRESA AND IT.TIPNOTAFISCAL = NFE.TIPNOTAFISCAL
                WHERE IT.SEQPRODUTO = P.SEQPRODUTO
                  AND NFE.SEQPESSOA = TO_NUMBER(:NR1)
                  AND NFE.STATUSNF != 'C'
                  AND NFE.CODGERALOPER IN (802, 860)
                  AND NFE.DTAEMISSAO >= TRUNC(LEAST(:DT1, :DT3))
                  AND NFE.DTAEMISSAO <= TRUNC(GREATEST(:DT2, :DT4))
              )
            )
          )
        )
        AND NOT EXISTS (
          SELECT 1
          FROM MAP_FAMDIVCATEG FDC
          INNER JOIN MAP_CATEGORIA CAT ON CAT.SEQCATEGORIA = FDC.SEQCATEGORIA
          WHERE FDC.SEQFAMILIA = P.SEQFAMILIA
            AND FDC.NRODIVISAO = 1
            AND CAT.NRODIVISAO = 1
            AND CAT.NIVELHIERARQUIA = 1
            AND UPPER(CAT.CATEGORIA) = 'ALMOXARIFADO'
            AND NOT EXISTS (
              SELECT 1
              FROM MAP_FAMDIVCATEG FDC2
              INNER JOIN MAP_CATEGORIA CAT2 ON CAT2.SEQCATEGORIA = FDC2.SEQCATEGORIA
              WHERE FDC2.SEQFAMILIA = P.SEQFAMILIA
                AND FDC2.NRODIVISAO = 1
                AND CAT2.NRODIVISAO = 1
                AND CAT2.NIVELHIERARQUIA = 1
                AND UPPER(CAT2.CATEGORIA) <> 'ALMOXARIFADO'
            )
        )
        AND (
          NVL(TRIM(:LS1), '0 - TODOS') IN ('0 - TODOS', 'TODOS', '')
          OR (
            INSTR(:LS1, ' - ') > 0
            AND FD.SEQCOMPRADOR = TO_NUMBER(SUBSTR(:LS1, 1, INSTR(:LS1, ' - ') - 1))
          )
        )
        AND (
          NVL(TRIM(:LT1), 'T') IN ('T', '0', 'TODOS')
          OR INSTR(UPPER(:LT1), PE.STATUSCOMPRA) > 0
        )
    ) X
    ORDER BY
      X.FORNECEDOR ASC,
      X.DESCRICAO ASC

)