SELECT * FROM (
WITH PRODUTOS_FILTRADOS AS (
    SELECT /*+ MATERIALIZE */ 
           A.SEQPRODUTO, 
           A.SEQFAMILIA, 
           NVL(COMP.COMPRADOR, 'SEM GESTOR') AS COMPRADOR, 
           NVL(FD.SEQCOMPRADOR, 0) AS SEQCOMPRADOR, 
           FP.CODIGO_FORNECEDOR AS FORN_PRINCIPAL_COD, 
           FP.FORNECEDOR_PRINCIPAL AS FORN_PRINCIPAL_NOME 
      FROM MAP_PRODUTO A 
      JOIN MAP_FAMDIVISAO FD ON FD.SEQFAMILIA = A.SEQFAMILIA AND FD.NRODIVISAO = 1 
      LEFT JOIN MAX_COMPRADOR COMP ON COMP.SEQCOMPRADOR = FD.SEQCOMPRADOR 
      JOIN (
          SELECT F.SEQFAMILIA, 
                 MAX(F.SEQFORNECEDOR) AS CODIGO_FORNECEDOR, 
                 MAX(P.NOMERAZAO) AS FORNECEDOR_PRINCIPAL 
            FROM MAP_FAMFORNEC F 
            JOIN GE_PESSOA P ON P.SEQPESSOA = F.SEQFORNECEDOR 
           WHERE F.PRINCIPAL = 'S'
             AND (:NR1 = '0' OR F.SEQFORNECEDOR = TO_NUMBER(:NR1))
           GROUP BY F.SEQFAMILIA
      ) FP ON FP.SEQFAMILIA = A.SEQFAMILIA 
     WHERE ((:LS1 = '0 - TODOS') OR NVL(FD.SEQCOMPRADOR, 0) = TO_NUMBER(SUBSTR(:LS1, 1, INSTR(:LS1, ' - ') - 1)))
       AND NOT EXISTS (
           SELECT 1 
             FROM MAP_FAMDIVCATEG XF 
             JOIN MAP_CATEGORIA YF ON XF.SEQCATEGORIA = YF.SEQCATEGORIA 
            WHERE XF.SEQFAMILIA = A.SEQFAMILIA 
              AND XF.STATUS = 'A' 
              AND YF.NIVELHIERARQUIA = 1 
              AND YF.TIPCATEGORIA = 'M' 
              AND UPPER(YF.CATEGORIA) = 'ALMOXARIFADO' 
              AND NOT EXISTS (
                  SELECT 1 
                    FROM MAP_FAMDIVCATEG XF2 
                    JOIN MAP_CATEGORIA YF2 ON XF2.SEQCATEGORIA = YF2.SEQCATEGORIA 
                   WHERE XF2.SEQFAMILIA = A.SEQFAMILIA 
                     AND XF2.STATUS = 'A' 
                     AND YF2.NIVELHIERARQUIA = 1 
                     AND YF2.TIPCATEGORIA = 'M' 
                     AND UPPER(YF2.CATEGORIA) <> 'ALMOXARIFADO'
              )
       )
)
SELECT TO_CHAR(R.CODIGO_FORNECEDOR) AS COD_F,
       NVL(R.FORNECEDOR, 'SEM DESCRICAO') AS FORNECEDOR,
       DECODE(NVL(UPPER(TRIM(:LT2)),'D'),'C','CONSOLIDADO',MIN(R.COMPRADOR)) AS COMPRADOR,
       COUNT(DISTINCT R.SEQPRODUTO_ATIVO) AS QTD_SKU,
       'R$ ' || TO_CHAR(ROUND(SUM(R.VLR_VENDA),2),'999G999G999G990D00') AS VLR_VENDA,
       'R$ ' || TO_CHAR(ROUND(SUM(R.VLR_COMPRA) - SUM(R.VLR_DEVOLUCAO_COMPRA) - SUM(R.VLR_TROCA_COMPRA),2),'999G999G999G990D00') AS VLR_COMPRA,
       'R$ ' || TO_CHAR(ROUND(SUM(R.VLR_DEVOLUCAO_COMPRA),2),'999G999G999G990D00') AS VLR_DEVOLUCAO_COMPRA,
       'R$ ' || TO_CHAR(ROUND(SUM(R.VLR_TROCA_COMPRA),2),'999G999G999G990D00') AS VLR_TROCA_COMPRA,
       'R$ ' || TO_CHAR(ROUND(SUM(R.VLR_BONIFICADO),2),'999G999G999G990D00') AS VLR_BONIFICADO,
       'R$ ' || TO_CHAR(ROUND(SUM(R.VLR_CUSTO_CD),2),'999G999G999G990D00') AS VLR_CUSTO_CD,
       'R$ ' || TO_CHAR(ROUND(SUM(R.VLR_CUSTO_LOJAS),2),'999G999G999G990D00') AS VLR_CUSTO_LOJAS,
       'R$ ' || TO_CHAR(ROUND(SUM(R.VLR_CUSTO_CD + R.VLR_CUSTO_LOJAS),2),'999G999G999G990D00') AS VLR_CUSTO_EMPRESA,
       TO_CHAR(ROUND(SUM(R.QTD_INCINERACAO_ANO),2),'999G999G999G990D00') AS QTD_INCINERACAO_ANO
FROM (
    SELECT PR.FORN_PRINCIPAL_COD AS CODIGO_FORNECEDOR,
           PR.FORN_PRINCIPAL_NOME AS FORNECEDOR,
           PR.COMPRADOR,
           PR.SEQPRODUTO,
           SUM(NVL(V.VLRTOTALVDA, 0)) AS VLR_VENDA,
           0 AS VLR_COMPRA, 
           0 AS VLR_BONIFICADO, 
           0 AS VLR_DEVOLUCAO_COMPRA, 
           0 AS VLR_TROCA_COMPRA, 
           0 AS VLR_CUSTO_CD, 
           0 AS VLR_CUSTO_LOJAS, 
           0 AS QTD_INCINERACAO_ANO,
           TO_NUMBER(NULL) AS SEQPRODUTO_ATIVO
      FROM MRL_CUSTODIA V
      JOIN PRODUTOS_FILTRADOS PR ON PR.SEQPRODUTO = V.SEQPRODUTO
     WHERE V.DTAENTRADASAIDA >= TRUNC(:DT1) 
       AND V.DTAENTRADASAIDA < TRUNC(:DT2) + 1 
       AND V.NROEMPRESA IN (1,2,3,4,5,6,7,8,11,12,13,14,15,16,17,18,50)
     GROUP BY PR.FORN_PRINCIPAL_COD, PR.FORN_PRINCIPAL_NOME, PR.COMPRADOR, PR.SEQPRODUTO

    UNION ALL

    SELECT PR.FORN_PRINCIPAL_COD AS CODIGO_FORNECEDOR,
           PR.FORN_PRINCIPAL_NOME AS FORNECEDOR,
           PR.COMPRADOR,
           PR.SEQPRODUTO,
           0 AS VLR_VENDA, 
           SUM(CASE WHEN (CASE WHEN N.TIPPEDCOMPRAITEM = 'B' AND NF.TIPPEDIDOCOMPRA = 'C' AND REGEXP_LIKE(MP.VALOR, '^[0-9]+$') THEN TO_NUMBER(MP.VALOR) ELSE NF.CODGERALOPER END) IN (1,28,32,200,290) THEN NVL(N.VLRITEM,0) ELSE 0 END) AS VLR_COMPRA,
           SUM(CASE WHEN (CASE WHEN N.TIPPEDCOMPRAITEM = 'B' AND NF.TIPPEDIDOCOMPRA = 'C' AND REGEXP_LIKE(MP.VALOR, '^[0-9]+$') THEN TO_NUMBER(MP.VALOR) ELSE NF.CODGERALOPER END) IN (100,101,103) OR N.CFOPORIGEM IN (5910, 6910) OR N.CFOP IN (5910, 6910, 1910, 2910) THEN NVL(N.VLRTOTALITEM,0) ELSE 0 END) AS VLR_BONIFICADO,
           SUM(CASE WHEN (CASE WHEN N.TIPPEDCOMPRAITEM = 'B' AND NF.TIPPEDIDOCOMPRA = 'C' AND REGEXP_LIKE(MP.VALOR, '^[0-9]+$') THEN TO_NUMBER(MP.VALOR) ELSE NF.CODGERALOPER END) IN (802) THEN NVL(N.VLRITEM,0) ELSE 0 END) AS VLR_DEVOLUCAO_COMPRA,
           SUM(CASE WHEN (CASE WHEN N.TIPPEDCOMPRAITEM = 'B' AND NF.TIPPEDIDOCOMPRA = 'C' AND REGEXP_LIKE(MP.VALOR, '^[0-9]+$') THEN TO_NUMBER(MP.VALOR) ELSE NF.CODGERALOPER END) IN (860) THEN NVL(N.VLRITEM,0) ELSE 0 END) AS VLR_TROCA_COMPRA,
           0 AS VLR_CUSTO_CD, 0 AS VLR_CUSTO_LOJAS, 0 AS QTD_INCINERACAO_ANO,
           TO_NUMBER(NULL) AS SEQPRODUTO_ATIVO
      FROM MLF_NFITEM N
      JOIN MLF_NOTAFISCAL NF ON NF.NUMERONF = N.NUMERONF AND NF.SERIENF = N.SERIENF AND NF.NROEMPRESA = N.NROEMPRESA AND NF.TIPNOTAFISCAL = N.TIPNOTAFISCAL AND NF.SEQPESSOA = N.SEQPESSOA
      JOIN PRODUTOS_FILTRADOS PR ON PR.SEQPRODUTO = N.SEQPRODUTO
      LEFT JOIN MAX_PARAMETRO MP ON MP.NROEMPRESA = NF.NROEMPRESA AND MP.PARAMETRO = 'CGO_ENTR_BONIF_NFCOMPRA'
     WHERE NF.TIPNOTAFISCAL = 'E' 
       AND NF.NROEMPRESA IN (1,2,3,4,5,6,7,8,11,12,13,14,15,16,17,18,21,50) 
       AND NF.DTAENTRADA >= TRUNC(:DT1) 
       AND NF.DTAENTRADA < TRUNC(:DT2) + 1 
       AND NF.STATUSNF <> 'C' 
       AND N.TIPNOTAFISCAL = 'E' 
       AND N.TIPITEM = 'R'
     GROUP BY PR.FORN_PRINCIPAL_COD, PR.FORN_PRINCIPAL_NOME, PR.COMPRADOR, PR.SEQPRODUTO

    UNION ALL

    SELECT PR.FORN_PRINCIPAL_COD AS CODIGO_FORNECEDOR,
           PR.FORN_PRINCIPAL_NOME AS FORNECEDOR,
           PR.COMPRADOR,
           PR.SEQPRODUTO,
           0 AS VLR_VENDA, 
           0 AS VLR_COMPRA, 
           0 AS VLR_BONIFICADO, 
           SUM(CASE WHEN N.CODGERALOPER = 802 THEN NVL(I.VLRITEM, 0) + NVL(I.VLRIPI, 0) + NVL(I.VLRICMSST, 0) ELSE 0 END) AS VLR_DEVOLUCAO_COMPRA,
           SUM(CASE WHEN N.CODGERALOPER = 860 THEN NVL(I.VLRITEM, 0) + NVL(I.VLRIPI, 0) + NVL(I.VLRICMSST, 0) ELSE 0 END) AS VLR_TROCA_COMPRA,
           0 AS VLR_CUSTO_CD, 
           0 AS VLR_CUSTO_LOJAS, 
           SUM(CASE WHEN N.CODGERALOPER IN (821, 831) AND NVL(N.MODELO,'0') <> '65' THEN NVL(I.VLRITEM,0) ELSE 0 END) AS QTD_INCINERACAO_ANO,
           TO_NUMBER(NULL) AS SEQPRODUTO_ATIVO
      FROM MLFV_BASENFE N
      JOIN MFLV_BASEDFITEM I ON I.SEQNF = N.SEQNF AND I.NROEMPRESA = N.NROEMPRESA AND I.TIPNOTAFISCAL = N.TIPNOTAFISCAL
      JOIN PRODUTOS_FILTRADOS PR ON PR.SEQPRODUTO = I.SEQPRODUTO
     WHERE N.TIPNOTAFISCAL = 'S'
       AND N.CODGERALOPER IN (802, 860, 821, 831) 
       AND N.DTAEMISSAO >= TRUNC(:DT1) 
       AND N.DTAEMISSAO < TRUNC(:DT2) + 1 
       AND N.STATUSNF != 'C' 
       AND N.NROEMPRESA IN (1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 13, 14, 15, 16, 17, 18, 21, 50)
     GROUP BY PR.FORN_PRINCIPAL_COD, PR.FORN_PRINCIPAL_NOME, PR.COMPRADOR, PR.SEQPRODUTO

    UNION ALL

    SELECT PR.FORN_PRINCIPAL_COD AS CODIGO_FORNECEDOR,
           PR.FORN_PRINCIPAL_NOME AS FORNECEDOR,
           PR.COMPRADOR,
           PR.SEQPRODUTO,
           0 AS VLR_VENDA, 0 AS VLR_COMPRA, 0 AS VLR_BONIFICADO, 0 AS VLR_DEVOLUCAO_COMPRA, 0 AS VLR_TROCA_COMPRA,
           SUM(CASE WHEN PE.NROEMPRESA IN (15,16,50) THEN (NVL(PE.ESTQLOJA,0)+NVL(PE.ESTQDEPOSITO,0)) * (NVL(PE.CMULTVLRNF,0)+NVL(PE.CMULTIPI,0)+NVL(PE.CMULTICMSST,0)+NVL(PE.CMULTDESPNF,0)+NVL(PE.CMULTDESPFORANF,0)) ELSE 0 END) AS VLR_CUSTO_CD,
           SUM(CASE WHEN PE.NROEMPRESA IN (1,2,3,4,5,6,7,8,11,12,13,14,17,18) THEN (NVL(PE.ESTQLOJA,0)+NVL(PE.ESTQDEPOSITO,0)) * (NVL(PE.CMULTVLRNF,0)+NVL(PE.CMULTIPI,0)+NVL(PE.CMULTICMSST,0)+NVL(PE.CMULTDESPNF,0)+NVL(PE.CMULTDESPFORANF,0)) ELSE 0 END) AS VLR_CUSTO_LOJAS,
           0 AS QTD_INCINERACAO_ANO,
           MAX(CASE WHEN PE.STATUSCOMPRA = 'A' THEN PR.SEQPRODUTO ELSE NULL END) AS SEQPRODUTO_ATIVO
      FROM MRL_PRODUTOEMPRESA PE
      JOIN PRODUTOS_FILTRADOS PR ON PR.SEQPRODUTO = PE.SEQPRODUTO
     WHERE PE.NROEMPRESA IN (1,2,3,4,5,6,7,8,11,12,13,14,15,16,17,18,50)
     GROUP BY PR.FORN_PRINCIPAL_COD, PR.FORN_PRINCIPAL_NOME, PR.COMPRADOR, PR.SEQPRODUTO
) R
WHERE (:NR1 = '0' OR R.CODIGO_FORNECEDOR = TO_NUMBER(:NR1))
  AND NVL(UPPER(TRIM(:LT2)),'D') IN ('D','C')
GROUP BY R.CODIGO_FORNECEDOR,
         R.FORNECEDOR,
         CASE WHEN NVL(UPPER(TRIM(:LT2)),'D') = 'C' THEN '1' ELSE R.COMPRADOR END
HAVING SUM(R.VLR_VENDA) > 0 OR SUM(R.VLR_COMPRA) > 0 OR SUM(R.VLR_BONIFICADO) > 0 OR SUM(R.VLR_DEVOLUCAO_COMPRA) > 0 OR SUM(R.VLR_TROCA_COMPRA) > 0 OR SUM(R.QTD_INCINERACAO_ANO) > 0
ORDER BY SUM(R.VLR_COMPRA - R.VLR_DEVOLUCAO_COMPRA - R.VLR_TROCA_COMPRA) DESC, 2 ASC
)
