SELECT TO_CHAR(R.CODIGO_FORNECEDOR) AS COD_F,
       NVL(R.FORNECEDOR, 'SEM DESCRICAO') AS FORNECEDOR,
       DECODE(NVL(UPPER(TRIM(:LT2)),'D'),'C','CONSOLIDADO',MIN(R.COMPRADOR)) AS COMPRADOR,
       COUNT(DISTINCT R.SEQPRODUTO) AS QTD_SKU,
       'R$ ' || TO_CHAR(ROUND(SUM(R.VLR_VENDA),2),'999G999G999G990D00') AS VLR_VENDA,
       'R$ ' || TO_CHAR(ROUND(SUM(R.VLR_COMPRA) - SUM(R.VLR_DEVOLUCAO_COMPRA) - SUM(R.VLR_TROCA_COMPRA),2),'999G999G999G990D00') AS VLR_COMPRA,
       'R$ ' || TO_CHAR(ROUND(SUM(R.VLR_DEVOLUCAO_COMPRA),2),'999G999G999G990D00') AS VLR_DEVOLUCAO_COMPRA,
       'R$ ' || TO_CHAR(ROUND(SUM(R.VLR_TROCA_COMPRA),2),'999G999G999G990D00') AS VLR_TROCA_COMPRA,
       'R$ ' || TO_CHAR(ROUND(SUM(R.VLR_BONIFICADO),2),'999G999G999G990D00') AS VLR_BONIFICADO,
       'R$ ' || TO_CHAR(ROUND(SUM(R.VLR_CUSTO_CD),2),'999G999G999G990D00') AS VLR_CUSTO_CD,
       'R$ ' || TO_CHAR(ROUND(SUM(R.VLR_CUSTO_LOJAS),2),'999G999G999G990D00') AS VLR_CUSTO_LOJAS,
       'R$ ' || TO_CHAR(ROUND(SUM(R.VLR_CUSTO_CD + R.VLR_CUSTO_LOJAS),2),'999G999G999G990D00') AS VLR_CUSTO_EMPRESA,
       TO_CHAR(ROUND(SUM(R.QTD_INCINERACAO_ANO),2),'999G999G999G990D00') AS QTD_INCINERACAO_ANO
FROM (
    SELECT PR.FORN_PRINCIPAL_COD AS CODIGO_FORNECEDOR,
           PR.FORN_PRINCIPAL_NOME AS FORNECEDOR,
           PR.COMPRADOR,
           PR.SEQPRODUTO,
           SUM(NVL(V2.VLRITEM, 0) + NVL(V2.VLRICMSST, 0) + NVL(V2.VLRIPI, 0)) AS VLR_VENDA,
           0 AS VLR_COMPRA, 0 AS VLR_BONIFICADO, 0 AS VLR_DEVOLUCAO_COMPRA, 0 AS VLR_TROCA_COMPRA, 0 AS VLR_CUSTO_CD, 0 AS VLR_CUSTO_LOJAS, 0 AS QTD_INCINERACAO_ANO
      FROM MLFV_BASENFE V1
      JOIN MFLV_BASEDFITEM V2 ON V2.NROEMPRESA = V1.NROEMPRESA AND V2.SEQNF = V1.SEQNF AND V2.TIPNOTAFISCAL = V1.TIPNOTAFISCAL AND V2.SERIEDF = V1.SERIENF AND V2.NUMERODF = V1.NUMERONF AND V2.SEQPESSOA = V1.SEQPESSOA
      JOIN (
          SELECT A.SEQPRODUTO, A.SEQFAMILIA, NVL(COMP.COMPRADOR, 'SEM GESTOR') AS COMPRADOR, NVL(FD.SEQCOMPRADOR, 0) AS SEQCOMPRADOR, FP.CODIGO_FORNECEDOR AS FORN_PRINCIPAL_COD, FP.FORNECEDOR_PRINCIPAL AS FORN_PRINCIPAL_NOME FROM MAP_PRODUTO A LEFT JOIN MAP_FAMDIVISAO FD ON FD.SEQFAMILIA = A.SEQFAMILIA AND FD.NRODIVISAO = 1 LEFT JOIN MAX_COMPRADOR COMP ON COMP.SEQCOMPRADOR = FD.SEQCOMPRADOR LEFT JOIN (SELECT F.SEQFAMILIA, MAX(F.SEQFORNECEDOR) CODIGO_FORNECEDOR, MAX(P.NOMERAZAO) FORNECEDOR_PRINCIPAL FROM MAP_FAMFORNEC F JOIN GE_PESSOA P ON P.SEQPESSOA = F.SEQFORNECEDOR WHERE F.PRINCIPAL = 'S' GROUP BY F.SEQFAMILIA) FP ON FP.SEQFAMILIA = A.SEQFAMILIA WHERE NOT EXISTS (SELECT 1 FROM MAP_FAMDIVCATEG XF JOIN MAP_CATEGORIA YF ON XF.SEQCATEGORIA = YF.SEQCATEGORIA WHERE XF.SEQFAMILIA = A.SEQFAMILIA AND XF.STATUS = 'A' AND YF.NIVELHIERARQUIA = 1 AND YF.TIPCATEGORIA = 'M' AND UPPER(YF.CATEGORIA) = 'ALMOXARIFADO' AND NOT EXISTS (SELECT 1 FROM MAP_FAMDIVCATEG XF2 JOIN MAP_CATEGORIA YF2 ON XF2.SEQCATEGORIA = YF2.SEQCATEGORIA WHERE XF2.SEQFAMILIA = A.SEQFAMILIA AND XF2.STATUS = 'A' AND YF2.NIVELHIERARQUIA = 1 AND YF2.TIPCATEGORIA = 'M' AND UPPER(YF2.CATEGORIA) <> 'ALMOXARIFADO'))
      ) PR ON PR.SEQPRODUTO = V2.SEQPRODUTO
     WHERE V1.TIPNOTAFISCAL = 'S' AND V1.CODGERALOPER IN (800, 810, 848) AND NVL(V1.STATUSNF, 'A') != 'C' AND V1.DTAEMISSAO >= TRUNC(:DT1) AND V1.DTAEMISSAO < TRUNC(:DT2) + 1 AND V1.NROEMPRESA IN (1,2,3,4,5,6,7,8,11,12,13,14,15,16,17,18,50) AND ((:LS1 = '0 - TODOS') OR PR.SEQCOMPRADOR = TO_NUMBER(SUBSTR(:LS1, 1, INSTR(:LS1, ' - ') - 1)))
     GROUP BY PR.FORN_PRINCIPAL_COD, PR.FORN_PRINCIPAL_NOME, PR.COMPRADOR, PR.SEQPRODUTO

    UNION ALL

    SELECT NF.SEQPESSOA AS CODIGO_FORNECEDOR,
           PESS.FANTASIA AS FORNECEDOR,
           PR.COMPRADOR,
           PR.SEQPRODUTO,
           0 AS VLR_VENDA, 
           SUM(CASE WHEN (CASE WHEN N.TIPPEDCOMPRAITEM = 'B' AND NF.TIPPEDIDOCOMPRA = 'C' AND REGEXP_LIKE(MP.VALOR, '^[0-9]+$') THEN TO_NUMBER(MP.VALOR) ELSE NF.CODGERALOPER END) IN (1,28,32,200,290) THEN NVL(N.VLRITEM,0) ELSE 0 END) AS VLR_COMPRA,
           SUM(CASE WHEN (CASE WHEN N.TIPPEDCOMPRAITEM = 'B' AND NF.TIPPEDIDOCOMPRA = 'C' AND REGEXP_LIKE(MP.VALOR, '^[0-9]+$') THEN TO_NUMBER(MP.VALOR) ELSE NF.CODGERALOPER END) IN (100,101,103) OR N.CFOPORIGEM IN (5910, 6910) OR N.CFOP IN (5910, 6910, 1910, 2910) THEN NVL(N.VLRITEM,0) ELSE 0 END) AS VLR_BONIFICADO,
           SUM(CASE WHEN (CASE WHEN N.TIPPEDCOMPRAITEM = 'B' AND NF.TIPPEDIDOCOMPRA = 'C' AND REGEXP_LIKE(MP.VALOR, '^[0-9]+$') THEN TO_NUMBER(MP.VALOR) ELSE NF.CODGERALOPER END) IN (802) THEN NVL(N.VLRITEM,0) ELSE 0 END) AS VLR_DEVOLUCAO_COMPRA,
           SUM(CASE WHEN (CASE WHEN N.TIPPEDCOMPRAITEM = 'B' AND NF.TIPPEDIDOCOMPRA = 'C' AND REGEXP_LIKE(MP.VALOR, '^[0-9]+$') THEN TO_NUMBER(MP.VALOR) ELSE NF.CODGERALOPER END) IN (860) THEN NVL(N.VLRITEM,0) ELSE 0 END) AS VLR_TROCA_COMPRA,
           0 AS VLR_CUSTO_CD, 0 AS VLR_CUSTO_LOJAS, 0 AS QTD_INCINERACAO_ANO
      FROM MLF_NFITEM N
      JOIN MLF_NOTAFISCAL NF ON NF.NUMERONF = N.NUMERONF AND NF.SERIENF = N.SERIENF AND NF.NROEMPRESA = N.NROEMPRESA AND NF.TIPNOTAFISCAL = N.TIPNOTAFISCAL AND NVL(NF.SEQNF,0) = NVL(N.SEQNF,NVL(NF.SEQNF,0))
      JOIN GE_PESSOA PESS ON PESS.SEQPESSOA = NF.SEQPESSOA
      JOIN (
          SELECT A.SEQPRODUTO, A.SEQFAMILIA, NVL(COMP.COMPRADOR, 'SEM GESTOR') AS COMPRADOR, NVL(FD.SEQCOMPRADOR, 0) AS SEQCOMPRADOR, FP.CODIGO_FORNECEDOR AS FORN_PRINCIPAL_COD, FP.FORNECEDOR_PRINCIPAL AS FORN_PRINCIPAL_NOME FROM MAP_PRODUTO A LEFT JOIN MAP_FAMDIVISAO FD ON FD.SEQFAMILIA = A.SEQFAMILIA AND FD.NRODIVISAO = 1 LEFT JOIN MAX_COMPRADOR COMP ON COMP.SEQCOMPRADOR = FD.SEQCOMPRADOR LEFT JOIN (SELECT F.SEQFAMILIA, MAX(F.SEQFORNECEDOR) CODIGO_FORNECEDOR, MAX(P.NOMERAZAO) FORNECEDOR_PRINCIPAL FROM MAP_FAMFORNEC F JOIN GE_PESSOA P ON P.SEQPESSOA = F.SEQFORNECEDOR WHERE F.PRINCIPAL = 'S' GROUP BY F.SEQFAMILIA) FP ON FP.SEQFAMILIA = A.SEQFAMILIA WHERE NOT EXISTS (SELECT 1 FROM MAP_FAMDIVCATEG XF JOIN MAP_CATEGORIA YF ON XF.SEQCATEGORIA = YF.SEQCATEGORIA WHERE XF.SEQFAMILIA = A.SEQFAMILIA AND XF.STATUS = 'A' AND YF.NIVELHIERARQUIA = 1 AND YF.TIPCATEGORIA = 'M' AND UPPER(YF.CATEGORIA) = 'ALMOXARIFADO' AND NOT EXISTS (SELECT 1 FROM MAP_FAMDIVCATEG XF2 JOIN MAP_CATEGORIA YF2 ON XF2.SEQCATEGORIA = YF2.SEQCATEGORIA WHERE XF2.SEQFAMILIA = A.SEQFAMILIA AND XF2.STATUS = 'A' AND YF2.NIVELHIERARQUIA = 1 AND YF2.TIPCATEGORIA = 'M' AND UPPER(YF2.CATEGORIA) <> 'ALMOXARIFADO'))
      ) PR ON PR.SEQPRODUTO = N.SEQPRODUTO
      LEFT JOIN MAX_PARAMETRO MP ON MP.NROEMPRESA = NF.NROEMPRESA AND MP.PARAMETRO = 'CGO_ENTR_BONIF_NFCOMPRA'
     WHERE NF.TIPNOTAFISCAL = 'E' AND NF.NROEMPRESA IN (1,2,3,4,5,6,7,8,11,12,13,14,15,16,17,18,21,50) AND NF.DTAENTRADA >= TRUNC(:DT1) AND NF.DTAENTRADA < TRUNC(:DT2) + 1 AND NF.STATUSNF <> 'C' AND NF.NUMERONF IS NOT NULL AND N.TIPNOTAFISCAL = 'E' AND N.TIPITEM = 'R' AND ((:LS1 = '0 - TODOS') OR PR.SEQCOMPRADOR = TO_NUMBER(SUBSTR(:LS1, 1, INSTR(:LS1, ' - ') - 1)))
     GROUP BY NF.SEQPESSOA, PESS.FANTASIA, PR.COMPRADOR, PR.SEQPRODUTO

    UNION ALL

    SELECT N.SEQPESSOA AS CODIGO_FORNECEDOR,
           PESS.FANTASIA AS FORNECEDOR,
           PR.COMPRADOR,
           PR.SEQPRODUTO,
           0 AS VLR_VENDA, 0 AS VLR_COMPRA, 0 AS VLR_BONIFICADO, 
           SUM(CASE WHEN N.CODGERALOPER = 802 THEN NVL(I.VLRITEM, 0) + NVL(I.VLRIPI, 0) + NVL(I.VLRICMSST, 0) ELSE 0 END) AS VLR_DEVOLUCAO_COMPRA,
           SUM(CASE WHEN N.CODGERALOPER = 860 THEN NVL(I.VLRITEM, 0) + NVL(I.VLRIPI, 0) + NVL(I.VLRICMSST, 0) ELSE 0 END) AS VLR_TROCA_COMPRA,
           0 AS VLR_CUSTO_CD, 0 AS VLR_CUSTO_LOJAS, 0 AS QTD_INCINERACAO_ANO
      FROM MLFV_BASENFE N
      JOIN MFLV_BASEDFITEM I ON I.SEQNF = N.SEQNF AND I.NROEMPRESA = N.NROEMPRESA AND I.TIPNOTAFISCAL = N.TIPNOTAFISCAL
      JOIN GE_PESSOA PESS ON PESS.SEQPESSOA = N.SEQPESSOA
      JOIN (
          SELECT A.SEQPRODUTO, A.SEQFAMILIA, NVL(COMP.COMPRADOR, 'SEM GESTOR') AS COMPRADOR, NVL(FD.SEQCOMPRADOR, 0) AS SEQCOMPRADOR, FP.CODIGO_FORNECEDOR AS FORN_PRINCIPAL_COD, FP.FORNECEDOR_PRINCIPAL AS FORN_PRINCIPAL_NOME FROM MAP_PRODUTO A LEFT JOIN MAP_FAMDIVISAO FD ON FD.SEQFAMILIA = A.SEQFAMILIA AND FD.NRODIVISAO = 1 LEFT JOIN MAX_COMPRADOR COMP ON COMP.SEQCOMPRADOR = FD.SEQCOMPRADOR LEFT JOIN (SELECT F.SEQFAMILIA, MAX(F.SEQFORNECEDOR) CODIGO_FORNECEDOR, MAX(P.NOMERAZAO) FORNECEDOR_PRINCIPAL FROM MAP_FAMFORNEC F JOIN GE_PESSOA P ON P.SEQPESSOA = F.SEQFORNECEDOR WHERE F.PRINCIPAL = 'S' GROUP BY F.SEQFAMILIA) FP ON FP.SEQFAMILIA = A.SEQFAMILIA WHERE NOT EXISTS (SELECT 1 FROM MAP_FAMDIVCATEG XF JOIN MAP_CATEGORIA YF ON XF.SEQCATEGORIA = YF.SEQCATEGORIA WHERE XF.SEQFAMILIA = A.SEQFAMILIA AND XF.STATUS = 'A' AND YF.NIVELHIERARQUIA = 1 AND YF.TIPCATEGORIA = 'M' AND UPPER(YF.CATEGORIA) = 'ALMOXARIFADO' AND NOT EXISTS (SELECT 1 FROM MAP_FAMDIVCATEG XF2 JOIN MAP_CATEGORIA YF2 ON XF2.SEQCATEGORIA = YF2.SEQCATEGORIA WHERE XF2.SEQFAMILIA = A.SEQFAMILIA AND XF2.STATUS = 'A' AND YF2.NIVELHIERARQUIA = 1 AND YF2.TIPCATEGORIA = 'M' AND UPPER(YF2.CATEGORIA) <> 'ALMOXARIFADO'))
      ) PR ON PR.SEQPRODUTO = I.SEQPRODUTO
     WHERE N.CODGERALOPER IN (802, 860) AND N.DTAEMISSAO >= TRUNC(:DT1) AND N.DTAEMISSAO < TRUNC(:DT2) + 1 AND N.STATUSNF != 'C' AND N.NROEMPRESA IN (1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 14, 15, 16, 17, 18, 21, 50) AND ((:LS1 = '0 - TODOS') OR PR.SEQCOMPRADOR = TO_NUMBER(SUBSTR(:LS1, 1, INSTR(:LS1, ' - ') - 1)))
     GROUP BY N.SEQPESSOA, PESS.FANTASIA, PR.COMPRADOR, PR.SEQPRODUTO

    UNION ALL

    SELECT PR.FORN_PRINCIPAL_COD AS CODIGO_FORNECEDOR,
           PR.FORN_PRINCIPAL_NOME AS FORNECEDOR,
           PR.COMPRADOR,
           PR.SEQPRODUTO,
           0 AS VLR_VENDA, 0 AS VLR_COMPRA, 0 AS VLR_BONIFICADO, 0 AS VLR_DEVOLUCAO_COMPRA, 0 AS VLR_TROCA_COMPRA,
           SUM(CASE WHEN PE.NROEMPRESA IN (15,16,50) THEN (NVL(PE.ESTQLOJA,0)+NVL(PE.ESTQDEPOSITO,0)) * (NVL(PE.CMULTVLRNF,0)+NVL(PE.CMULTIPI,0)+NVL(PE.CMULTICMSST,0)+NVL(PE.CMULTDESPNF,0)+NVL(PE.CMULTDESPFORANF,0)) ELSE 0 END) AS VLR_CUSTO_CD,
           SUM(CASE WHEN PE.NROEMPRESA IN (1,2,3,4,5,6,7,8,11,12,13,14,17,18) THEN (NVL(PE.ESTQLOJA,0)+NVL(PE.ESTQDEPOSITO,0)) * (NVL(PE.CMULTVLRNF,0)+NVL(PE.CMULTIPI,0)+NVL(PE.CMULTICMSST,0)+NVL(PE.CMULTDESPNF,0)+NVL(PE.CMULTDESPFORANF,0)) ELSE 0 END) AS VLR_CUSTO_LOJAS,
           0 AS QTD_INCINERACAO_ANO
      FROM MRL_PRODUTOEMPRESA PE
      JOIN (
          SELECT A.SEQPRODUTO, A.SEQFAMILIA, NVL(COMP.COMPRADOR, 'SEM GESTOR') AS COMPRADOR, NVL(FD.SEQCOMPRADOR, 0) AS SEQCOMPRADOR, FP.CODIGO_FORNECEDOR AS FORN_PRINCIPAL_COD, FP.FORNECEDOR_PRINCIPAL AS FORN_PRINCIPAL_NOME FROM MAP_PRODUTO A LEFT JOIN MAP_FAMDIVISAO FD ON FD.SEQFAMILIA = A.SEQFAMILIA AND FD.NRODIVISAO = 1 LEFT JOIN MAX_COMPRADOR COMP ON COMP.SEQCOMPRADOR = FD.SEQCOMPRADOR LEFT JOIN (SELECT F.SEQFAMILIA, MAX(F.SEQFORNECEDOR) CODIGO_FORNECEDOR, MAX(P.NOMERAZAO) FORNECEDOR_PRINCIPAL FROM MAP_FAMFORNEC F JOIN GE_PESSOA P ON P.SEQPESSOA = F.SEQFORNECEDOR WHERE F.PRINCIPAL = 'S' GROUP BY F.SEQFAMILIA) FP ON FP.SEQFAMILIA = A.SEQFAMILIA WHERE NOT EXISTS (SELECT 1 FROM MAP_FAMDIVCATEG XF JOIN MAP_CATEGORIA YF ON XF.SEQCATEGORIA = YF.SEQCATEGORIA WHERE XF.SEQFAMILIA = A.SEQFAMILIA AND XF.STATUS = 'A' AND YF.NIVELHIERARQUIA = 1 AND YF.TIPCATEGORIA = 'M' AND UPPER(YF.CATEGORIA) = 'ALMOXARIFADO' AND NOT EXISTS (SELECT 1 FROM MAP_FAMDIVCATEG XF2 JOIN MAP_CATEGORIA YF2 ON XF2.SEQCATEGORIA = YF2.SEQCATEGORIA WHERE XF2.SEQFAMILIA = A.SEQFAMILIA AND XF2.STATUS = 'A' AND YF2.NIVELHIERARQUIA = 1 AND YF2.TIPCATEGORIA = 'M' AND UPPER(YF2.CATEGORIA) <> 'ALMOXARIFADO'))
      ) PR ON PR.SEQPRODUTO = PE.SEQPRODUTO
     WHERE PE.NROEMPRESA IN (1,2,3,4,5,6,7,8,11,12,13,14,15,16,17,18,50) AND ((:LS1 = '0 - TODOS') OR PR.SEQCOMPRADOR = TO_NUMBER(SUBSTR(:LS1, 1, INSTR(:LS1, ' - ') - 1)))
     GROUP BY PR.FORN_PRINCIPAL_COD, PR.FORN_PRINCIPAL_NOME, PR.COMPRADOR, PR.SEQPRODUTO

    UNION ALL

    SELECT PR.FORN_PRINCIPAL_COD AS CODIGO_FORNECEDOR,
           PR.FORN_PRINCIPAL_NOME AS FORNECEDOR,
           PR.COMPRADOR,
           PR.SEQPRODUTO,
           0 AS VLR_VENDA, 0 AS VLR_COMPRA, 0 AS VLR_BONIFICADO, 0 AS VLR_DEVOLUCAO_COMPRA, 0 AS VLR_TROCA_COMPRA, 0 AS VLR_CUSTO_CD, 0 AS VLR_CUSTO_LOJAS,
           SUM(NVL(I.VLRITEM,0)) AS QTD_INCINERACAO_ANO
      FROM MLFV_BASENFE N
      JOIN MFLV_BASEDFITEM I ON I.NROEMPRESA = N.NROEMPRESA AND I.SEQNF = N.SEQNF AND I.TIPNOTAFISCAL = N.TIPNOTAFISCAL AND I.SERIEDF = N.SERIENF AND I.NUMERODF = N.NUMERONF AND I.SEQPESSOA = N.SEQPESSOA
      JOIN (
          SELECT A.SEQPRODUTO, A.SEQFAMILIA, NVL(COMP.COMPRADOR, 'SEM GESTOR') AS COMPRADOR, NVL(FD.SEQCOMPRADOR, 0) AS SEQCOMPRADOR, FP.CODIGO_FORNECEDOR AS FORN_PRINCIPAL_COD, FP.FORNECEDOR_PRINCIPAL AS FORN_PRINCIPAL_NOME FROM MAP_PRODUTO A LEFT JOIN MAP_FAMDIVISAO FD ON FD.SEQFAMILIA = A.SEQFAMILIA AND FD.NRODIVISAO = 1 LEFT JOIN MAX_COMPRADOR COMP ON COMP.SEQCOMPRADOR = FD.SEQCOMPRADOR LEFT JOIN (SELECT F.SEQFAMILIA, MAX(F.SEQFORNECEDOR) CODIGO_FORNECEDOR, MAX(P.NOMERAZAO) FORNECEDOR_PRINCIPAL FROM MAP_FAMFORNEC F JOIN GE_PESSOA P ON P.SEQPESSOA = F.SEQFORNECEDOR WHERE F.PRINCIPAL = 'S' GROUP BY F.SEQFAMILIA) FP ON FP.SEQFAMILIA = A.SEQFAMILIA WHERE NOT EXISTS (SELECT 1 FROM MAP_FAMDIVCATEG XF JOIN MAP_CATEGORIA YF ON XF.SEQCATEGORIA = YF.SEQCATEGORIA WHERE XF.SEQFAMILIA = A.SEQFAMILIA AND XF.STATUS = 'A' AND YF.NIVELHIERARQUIA = 1 AND YF.TIPCATEGORIA = 'M' AND UPPER(YF.CATEGORIA) = 'ALMOXARIFADO' AND NOT EXISTS (SELECT 1 FROM MAP_FAMDIVCATEG XF2 JOIN MAP_CATEGORIA YF2 ON XF2.SEQCATEGORIA = YF2.SEQCATEGORIA WHERE XF2.SEQFAMILIA = A.SEQFAMILIA AND XF2.STATUS = 'A' AND YF2.NIVELHIERARQUIA = 1 AND YF2.TIPCATEGORIA = 'M' AND UPPER(YF2.CATEGORIA) <> 'ALMOXARIFADO'))
      ) PR ON PR.SEQPRODUTO = I.SEQPRODUTO
     WHERE N.CODGERALOPER IN (821, 831) AND N.TIPNOTAFISCAL = 'S' AND NVL(N.MODELO,'0') <> '65' AND N.NROEMPRESA IN (1,2,3,4,5,6,7,8,9,11,12,13,14,15,16,17,18,50) AND N.DTAEMISSAO >= TO_DATE('01/02/2026', 'DD/MM/YYYY') AND N.DTAEMISSAO < TRUNC(:DT2) + 1 AND ((:LS1 = '0 - TODOS') OR PR.SEQCOMPRADOR = TO_NUMBER(SUBSTR(:LS1, 1, INSTR(:LS1, ' - ') - 1)))
     GROUP BY PR.FORN_PRINCIPAL_COD, PR.FORN_PRINCIPAL_NOME, PR.COMPRADOR, PR.SEQPRODUTO
) R
WHERE (:NR1 = '0' OR R.CODIGO_FORNECEDOR = TO_NUMBER(:NR1))
  AND NVL(UPPER(TRIM(:LT2)),'D') IN ('D','C')
GROUP BY R.CODIGO_FORNECEDOR,
         R.FORNECEDOR,
         CASE WHEN NVL(UPPER(TRIM(:LT2)),'D') = 'C' THEN '1' ELSE R.COMPRADOR END
HAVING SUM(R.VLR_VENDA) > 0 OR SUM(R.VLR_COMPRA) > 0 OR SUM(R.VLR_BONIFICADO) > 0 OR SUM(R.VLR_DEVOLUCAO_COMPRA) > 0 OR SUM(R.VLR_TROCA_COMPRA) > 0 OR SUM(R.QTD_INCINERACAO_ANO) > 0
ORDER BY SUM(R.VLR_COMPRA - R.VLR_DEVOLUCAO_COMPRA - R.VLR_TROCA_COMPRA) DESC, 2 ASC
