SELECT * FROM (
SELECT TO_CHAR(B.CODIGO_FORNECEDOR) AS COD_F,
       NVL(B.FORNECEDOR_PRINCIPAL,'SEM DESCRICAO') AS FORNECEDOR,
       DECODE(NVL(UPPER(TRIM(:LT2)),'D'),'C','CONSOLIDADO',MIN(B.COMPRADOR)) AS COMPRADOR,
       COUNT(DISTINCT B.SEQPRODUTO) AS QTD_SKU,
       'R$ ' || TO_CHAR(ROUND(SUM(B.VLR_VENDA),2),'999G999G999G990D00') AS VLR_VENDA
  FROM (
         SELECT FP.CODIGO_FORNECEDOR,
                FP.FORNECEDOR_PRINCIPAL,
                NVL(COMP.COMPRADOR,'SEM GESTOR') AS COMPRADOR,
                A.SEQPRODUTO,
                NVL(VF.VLR_VENDA,0) AS VLR_VENDA
           FROM MAP_PRODUTO A
           LEFT JOIN MAP_FAMDIVISAO FD ON A.SEQFAMILIA = FD.SEQFAMILIA AND FD.NRODIVISAO = 1
           LEFT JOIN MAX_COMPRADOR COMP ON COMP.SEQCOMPRADOR = FD.SEQCOMPRADOR
           LEFT JOIN (SELECT F.SEQFAMILIA, MAX(F.SEQFORNECEDOR) CODIGO_FORNECEDOR, MAX(P.NOMERAZAO) FORNECEDOR_PRINCIPAL
                        FROM MAP_FAMFORNEC F JOIN GE_PESSOA P ON P.SEQPESSOA = F.SEQFORNECEDOR
                       WHERE F.PRINCIPAL = 'S'
                       GROUP BY F.SEQFAMILIA) FP ON FP.SEQFAMILIA = A.SEQFAMILIA
           INNER JOIN (
                  SELECT V2.SEQPRODUTO,
                         SUM(NVL(V2.VLRITEM, 0) + NVL(V2.VLRICMSST, 0) + NVL(V2.VLRIPI, 0)) VLR_VENDA
                    FROM MLFV_BASENFE V1
                    JOIN MFLV_BASEDFITEM V2 ON V2.NROEMPRESA = V1.NROEMPRESA
                                           AND V2.SEQNF = V1.SEQNF
                                           AND V2.TIPNOTAFISCAL = V1.TIPNOTAFISCAL
                                           AND V2.SERIEDF = V1.SERIENF
                                           AND V2.NUMERODF = V1.NUMERONF
                                           AND V2.SEQPESSOA = V1.SEQPESSOA
                    INNER JOIN MAP_PRODUTO PX ON PX.SEQPRODUTO = V2.SEQPRODUTO
                    LEFT JOIN MAP_FAMDIVISAO FDX ON FDX.SEQFAMILIA = PX.SEQFAMILIA AND FDX.NRODIVISAO = 1
                    LEFT JOIN MAP_FAMFORNEC FPX ON FPX.SEQFAMILIA = PX.SEQFAMILIA AND FPX.PRINCIPAL = 'S'
                   WHERE V1.TIPNOTAFISCAL = 'S'
                     AND V1.CODGERALOPER IN (800, 810, 834, 848)
                     AND NVL(V1.STATUSNF, 'A') != 'C'
                     AND V1.DTAEMISSAO >= TRUNC(:DT1)
                     AND V1.DTAEMISSAO < TRUNC(:DT2) + 1
                     AND V1.NROEMPRESA IN (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,20,21,22,23,50,900,901,902)
                     AND ((:LS1 = '0 - TODOS') OR NVL(FDX.SEQCOMPRADOR, 0) = TO_NUMBER(SUBSTR(:LS1, 1, INSTR(:LS1, ' - ') - 1)))
                     AND (:NR1 = '0' OR FPX.SEQFORNECEDOR = TO_NUMBER(:NR1))
                     GROUP BY V2.SEQPRODUTO
           ) VF ON VF.SEQPRODUTO = A.SEQPRODUTO
          WHERE ((:LS1 = '0 - TODOS') OR NVL(FD.SEQCOMPRADOR, 0) = TO_NUMBER(SUBSTR(:LS1, 1, INSTR(:LS1, ' - ') - 1)))
            AND (:NR1 = '0' OR FP.CODIGO_FORNECEDOR = TO_NUMBER(:NR1))
            AND EXISTS (
                  SELECT 1
                    FROM MAP_FAMDIVCATEG XF
                    JOIN MAP_CATEGORIA YF ON XF.SEQCATEGORIA = YF.SEQCATEGORIA
                   WHERE XF.SEQFAMILIA = A.SEQFAMILIA
                     AND YF.NIVELHIERARQUIA = 1
                     AND UPPER(YF.CATEGORIA) NOT IN ('ALMOXARIFADO')
              )
       ) B
 WHERE NVL(UPPER(TRIM(:LT2)),'D') IN ('D','C')
 GROUP BY B.CODIGO_FORNECEDOR,
          B.FORNECEDOR_PRINCIPAL,
          CASE WHEN NVL(UPPER(TRIM(:LT2)),'D') = 'C' THEN '1' ELSE B.COMPRADOR END
 HAVING SUM(B.VLR_VENDA) > 0
 ORDER BY SUM(B.VLR_VENDA) DESC, 2 ASC
)
