SELECT TO_CHAR(B.CODIGO_FORNECEDOR) AS CODIGO_FORNECEDOR,
       NVL(B.FORNECEDOR_PRINCIPAL,'SEM DESCRICAO') AS FORNECEDOR,
      DECODE(NVL(UPPER(TRIM(:LT2)),'D'),'C','CONSOLIDADO',MIN(B.COMPRADOR)) AS COMPRADOR,
       COUNT(DISTINCT B.SEQPRODUTO) AS QTD_SKU,
       'R$ ' || TO_CHAR(ROUND(SUM(B.VLR_VENDA),2),'999G999G999G990D00') AS VLR_VENDA_TOTAL,
       'R$ ' || TO_CHAR(ROUND(SUM(B.VLR_COMPRA),2),'999G999G999G990D00') AS VLR_COMPRA_TOTAL,
       'R$ ' || TO_CHAR(ROUND(SUM(B.VLR_BONIFICADO),2),'999G999G999G990D00') AS VLR_ENTRADA_BONIFICADA,
       'R$ ' || TO_CHAR(ROUND(SUM(B.VLR_CUSTO_BRUTO_CD),2),'999G999G999G990D00') AS VLR_CUSTO_BRUTO_CD,
       'R$ ' || TO_CHAR(ROUND(SUM(B.VLR_CUSTO_BRUTO_LOJAS),2),'999G999G999G990D00') AS VLR_CUSTO_BRUTO_LOJAS,
       'R$ ' || TO_CHAR(ROUND(SUM(B.VLR_CUSTO_BRUTO_CD + B.VLR_CUSTO_BRUTO_LOJAS),2),'999G999G999G990D00') AS VLR_CUSTO_BRUTO_TOTAL_EMPRESA
  FROM (
        SELECT FP.CODIGO_FORNECEDOR,
               FP.FORNECEDOR_PRINCIPAL,
               NVL(COMP.COMPRADOR,'SEM GESTOR') AS COMPRADOR,
               A.SEQPRODUTO,
               NVL(VF.QTD_VENDIDA_TOTAL,0) * NVL(PV.PRECO_VENDA,0) AS VLR_VENDA,
               NVL(E.VLR_COMPRADO_TOTAL,0) AS VLR_COMPRA,
               NVL(E.VLR_BONIFICADO_TOTAL,0) AS VLR_BONIFICADO,
               NVL(CS.VLR_CUSTO_BRUTO_ESTOQUE_CD,0) AS VLR_CUSTO_BRUTO_CD,
               NVL(CS.VLR_CUSTO_BRUTO_ESTOQUE_LOJAS,0) AS VLR_CUSTO_BRUTO_LOJAS
          FROM MAP_PRODUTO A
          LEFT JOIN MAP_FAMDIVISAO FD ON A.SEQFAMILIA = FD.SEQFAMILIA AND FD.NRODIVISAO = 1
          LEFT JOIN MAX_COMPRADOR COMP ON COMP.SEQCOMPRADOR = FD.SEQCOMPRADOR
          LEFT JOIN (SELECT F.SEQFAMILIA, MAX(F.SEQFORNECEDOR) CODIGO_FORNECEDOR, MAX(P.NOMERAZAO) FORNECEDOR_PRINCIPAL
                       FROM MAP_FAMFORNEC F JOIN GE_PESSOA P ON P.SEQPESSOA = F.SEQFORNECEDOR
                      WHERE F.PRINCIPAL = 'S'
                      GROUP BY F.SEQFAMILIA) FP ON FP.SEQFAMILIA = A.SEQFAMILIA
          LEFT JOIN (SELECT SEG.SEQPRODUTO, MAX(ROUND(NVL(NULLIF(SEG.PRECOVALIDPROMOC,0),SEG.PRECOVALIDNORMAL),2)) PRECO_VENDA
                       FROM MRL_PRODEMPSEG SEG
                      WHERE SEG.NROEMPRESA = 3 AND SEG.QTDEMBALAGEM = 1
                      GROUP BY SEG.SEQPRODUTO) PV ON PV.SEQPRODUTO = A.SEQPRODUTO
          JOIN (SELECT SEQPRODUTO, SUM(QTDVDA) QTD_VENDIDA_TOTAL
                  FROM MRL_PRODVENDADIA
                 WHERE DTAVDA BETWEEN :DT1 AND :DT2
                   AND NROEMPRESA IN (1,2,3,4,5,6,7,8,11,12,13,14,17,18)
                 GROUP BY SEQPRODUTO) VF ON VF.SEQPRODUTO = A.SEQPRODUTO
          LEFT JOIN (
                    SELECT X.SEQPRODUTO,
                           SUM(CASE WHEN X.CGO_EFETIVA IN (1,28) THEN X.VLRITEM ELSE 0 END) VLR_COMPRADO_TOTAL,
                           SUM(CASE WHEN X.CGO_EFETIVA IN (100,101) THEN X.VLRITEM ELSE 0 END) VLR_BONIFICADO_TOTAL
                      FROM (
                            SELECT N.SEQPRODUTO,
                                   NVL(N.VLRITEM,0) VLRITEM,
                                   CASE WHEN N.TIPPEDCOMPRAITEM IN ('B','E') AND NF.TIPPEDIDOCOMPRA = 'C' THEN TO_NUMBER(MP.VALOR)
                                        ELSE CGO.CODGERALOPER END CGO_EFETIVA
                              FROM MLF_NFITEM N
                              JOIN MLF_NOTAFISCAL NF ON NF.NUMERONF = N.NUMERONF AND NF.SERIENF = N.SERIENF
                                                   AND NF.NROEMPRESA = N.NROEMPRESA AND NF.TIPNOTAFISCAL = N.TIPNOTAFISCAL
                                                   AND NVL(NF.SEQNF,0) = NVL(N.SEQNF,NVL(NF.SEQNF,0))
                              JOIN MAX_CODGERALOPER CGO ON CGO.CODGERALOPER = NF.CODGERALOPER
                              LEFT JOIN MAX_PARAMETRO MP ON MP.NROEMPRESA = NF.NROEMPRESA AND MP.PARAMETRO = 'CGO_ENTR_BONIF_NFCOMPRA'
                             WHERE NF.TIPNOTAFISCAL = 'E'
                               AND NF.NROEMPRESA IN (1,2,3,4,5,6,7,8,11,12,13,14,15,16,17,18,50)
                               AND NF.DTAENTRADA >= TRUNC(:DT1)
                               AND NF.DTAENTRADA < TRUNC(:DT2) + 1
                               AND NF.STATUSNF <> 'C'
                               AND NF.NUMERONF IS NOT NULL
                               AND N.TIPNOTAFISCAL = 'E'
                               AND N.TIPITEM = 'R'
                           ) X
                     GROUP BY X.SEQPRODUTO
                   ) E ON E.SEQPRODUTO = A.SEQPRODUTO
          LEFT JOIN (
                    SELECT X.SEQPRODUTO,
                           SUM(CASE WHEN X.NROEMPRESA IN (15,16,50) THEN X.VLR_CUSTO ELSE 0 END) VLR_CUSTO_BRUTO_ESTOQUE_CD,
                           SUM(CASE WHEN X.NROEMPRESA IN (1,2,3,4,5,6,7,8,11,12,13,14,17,18) THEN X.VLR_CUSTO ELSE 0 END) VLR_CUSTO_BRUTO_ESTOQUE_LOJAS
                      FROM (
                            SELECT PE.SEQPRODUTO,
                                   PE.NROEMPRESA,
                              (NVL(PE.ESTQLOJA,0)+NVL(PE.ESTQDEPOSITO,0))
                                   *
                                   (NVL(PE.CMULTVLRNF,0)+NVL(PE.CMULTIPI,0)+NVL(PE.CMULTICMSST,0)+NVL(PE.CMULTDESPNF,0)+NVL(PE.CMULTDESPFORANF,0)) VLR_CUSTO
                              FROM MRL_PRODUTOEMPRESA PE
                             WHERE PE.NROEMPRESA IN (1,2,3,4,5,6,7,8,11,12,13,14,15,16,17,18,50)
                               AND PE.STATUSCOMPRA = 'A'
                           ) X
                     GROUP BY X.SEQPRODUTO
                   ) CS ON CS.SEQPRODUTO = A.SEQPRODUTO
         WHERE (#LS1 = '0 - TODOS' OR #LS1 LIKE TO_CHAR(NVL(FD.SEQCOMPRADOR,0)) || ' - %')
           AND NOT EXISTS (
                 SELECT 1
                   FROM MAP_FAMDIVCATEG XF
                   JOIN MAP_CATEGORIA YF ON XF.SEQCATEGORIA = YF.SEQCATEGORIA
                  WHERE XF.SEQFAMILIA = A.SEQFAMILIA
                    AND YF.NIVELHIERARQUIA = 1
                    AND (UPPER(YF.CATEGORIA) IN ('A CLASSIFICAR','ALMOXARIFADO','INATIVAR') OR UPPER(YF.CATEGORIA) LIKE 'SERVIC%')
               )
       ) B
 WHERE NVL(UPPER(TRIM(:LT2)),'D') IN ('D','C')
 GROUP BY B.CODIGO_FORNECEDOR,
          B.FORNECEDOR_PRINCIPAL,
          CASE WHEN NVL(UPPER(TRIM(:LT2)),'D') = 'C' THEN '1' ELSE B.COMPRADOR END
HAVING SUM(B.VLR_VENDA) > 0 OR SUM(B.VLR_COMPRA) > 0 OR SUM(B.VLR_BONIFICADO) > 0
 ORDER BY 5 DESC, 2 ASC