SELECT V2.SEQPRODUTO AS CODIGO_PRODUTO,
       MAX(PX.DESCCOMPLETA) AS PRODUTO,
       V1.CODGERALOPER AS CGO,
       SUM(V2.QUANTIDADE) AS QUANTIDADE,
       SUM(NVL(V2.VLRITEM, 0) + NVL(V2.VLRICMSST, 0) + NVL(V2.VLRIPI, 0)) AS VALOR_BRUTO,
       SUM(V2.VLRITEM) AS VALOR_LIQUIDO
  FROM MLFV_BASENFE V1
  JOIN MFLV_BASEDFITEM V2 ON V2.NROEMPRESA = V1.NROEMPRESA
                         AND V2.SEQNF = V1.SEQNF
                         AND V2.TIPNOTAFISCAL = V1.TIPNOTAFISCAL
                         AND V2.SERIEDF = V1.SERIENF
                         AND V2.NUMERODF = V1.NUMERONF
                         AND V2.SEQPESSOA = V1.SEQPESSOA
  INNER JOIN MAP_PRODUTO PX ON PX.SEQPRODUTO = V2.SEQPRODUTO
  LEFT JOIN MAP_FAMDIVISAO FDX ON FDX.SEQFAMILIA = PX.SEQFAMILIA AND FDX.NRODIVISAO = 1
  LEFT JOIN MAP_FAMFORNEC FPX ON FPX.SEQFAMILIA = PX.SEQFAMILIA AND FPX.PRINCIPAL = 'S'
 WHERE V1.TIPNOTAFISCAL = 'S'
   AND V1.CODGERALOPER IN (800, 810, 834, 848)
   AND NVL(V1.STATUSNF, 'A') != 'C'
   AND V1.DTAEMISSAO >= TO_DATE('01/05/2026', 'DD/MM/YYYY')
   AND V1.DTAEMISSAO < TO_DATE('01/06/2026', 'DD/MM/YYYY')
   AND V1.NROEMPRESA IN (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 20, 21, 22, 23, 50, 900, 901, 902)
   AND (:LS1 = '0 - TODOS' OR NVL(FDX.SEQCOMPRADOR, 0) = TO_NUMBER(SUBSTR(:LS1, 1, INSTR(:LS1, ' - ') - 1)))
   AND (:NR1 = '0' OR FPX.SEQFORNECEDOR = TO_NUMBER(:NR1))
   AND EXISTS (
         SELECT 1
           FROM MAP_FAMDIVCATEG XF
           JOIN MAP_CATEGORIA YF ON XF.SEQCATEGORIA = YF.SEQCATEGORIA
          WHERE XF.SEQFAMILIA = PX.SEQFAMILIA
            AND YF.NIVELHIERARQUIA = 1
            AND UPPER(YF.CATEGORIA) NOT IN ('ALMOXARIFADO')
     )
 GROUP BY V2.SEQPRODUTO, V1.CODGERALOPER
 ORDER BY CODIGO_PRODUTO, V1.CODGERALOPER
