SELECT 
    B.COD_FORN AS COD_F,
    B.FORNECEDOR,
    'R$ ' || TO_CHAR(ROUND(SUM(B.VLR_DEVOLUCAO), 2), 'FM999G999G999G990D00') AS VLR_DEVOLUCAO_COMPRA
FROM (
    SELECT 
        FP.CODIGO_FORNECEDOR AS COD_FORN,
        FP.FORNECEDOR_PRINCIPAL AS FORNECEDOR,
        SUM(NVL(I.VLRITEM, 0) + NVL(I.VLRIPI, 0) + NVL(I.VLRICMSST, 0)) AS VLR_DEVOLUCAO
    FROM MLF_NOTAFISCAL NF
    JOIN MLF_NFITEM I ON I.NROEMPRESA = NF.NROEMPRESA 
                     AND NVL(I.SEQNF, 0) = NVL(NF.SEQNF, NVL(I.SEQNF, 0))
                     AND I.NUMERONF = NF.NUMERONF 
                     AND I.SERIENF = NF.SERIENF
    JOIN MAP_PRODUTO P ON P.SEQPRODUTO = I.SEQPRODUTO
    LEFT JOIN (
        SELECT F.SEQFAMILIA, MAX(F.SEQFORNECEDOR) CODIGO_FORNECEDOR, MAX(P.NOMERAZAO) FORNECEDOR_PRINCIPAL
        FROM MAP_FAMFORNEC F 
        JOIN GE_PESSOA P ON P.SEQPESSOA = F.SEQFORNECEDOR
        WHERE F.PRINCIPAL = 'S'
        GROUP BY F.SEQFAMILIA
    ) FP ON FP.SEQFAMILIA = P.SEQFAMILIA
    LEFT JOIN MAX_PARAMETRO MP ON MP.NROEMPRESA = NF.NROEMPRESA AND MP.PARAMETRO = 'CGO_ENTR_BONIF_NFCOMPRA'
    WHERE NF.STATUSNF != 'C'
      AND NF.DTAENTRADA BETWEEN :DT1 AND :DT2
      AND NF.NROEMPRESA IN (1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 14, 15, 17, 18)
      AND (:NR1 = 0 OR FP.CODIGO_FORNECEDOR = :NR1)
      AND (
          CASE 
            WHEN I.TIPPEDCOMPRAITEM IN ('B','E') AND NF.TIPPEDIDOCOMPRA = 'C' AND REGEXP_LIKE(MP.VALOR, '^[0-9]+$') 
            THEN TO_NUMBER(MP.VALOR)
            ELSE NF.CODGERALOPER 
          END
      ) IN (802, 860)
    GROUP BY 
        FP.CODIGO_FORNECEDOR,
        FP.FORNECEDOR_PRINCIPAL
) B
GROUP BY 
    B.COD_FORN,
    B.FORNECEDOR
ORDER BY SUM(B.VLR_DEVOLUCAO) DESC, B.FORNECEDOR ASC
