SELECT * FROM (
    WITH CTE_CATEGORIAS AS (
        SELECT /*+ MATERIALIZE */
            X.SEQFAMILIA,
            MAX(CASE WHEN Y.NIVELHIERARQUIA = 1 THEN Y.CATEGORIA END) AS DEPARTAMENTO,
            MAX(CASE WHEN Y.NIVELHIERARQUIA = 2 THEN Y.CATEGORIA END) AS SECAO,
            MAX(CASE WHEN Y.NIVELHIERARQUIA = 3 THEN Y.CATEGORIA END) AS GRUPO,
            MAX(CASE WHEN Y.NIVELHIERARQUIA = 4 THEN Y.CATEGORIA END) AS SUBGRUPO_NIVEL4,
            MAX(CASE WHEN Y.NIVELHIERARQUIA = 5 THEN Y.CATEGORIA END) AS NIVEL5
        FROM MAP_FAMDIVCATEG X
        INNER JOIN MAP_CATEGORIA Y
            ON Y.SEQCATEGORIA = X.SEQCATEGORIA
           AND Y.NRODIVISAO = X.NRODIVISAO
        WHERE Y.TIPCATEGORIA = 'M'
          AND Y.STATUSCATEGOR = 'A'
          AND X.STATUS = 'A'
          AND X.NRODIVISAO = 1
        GROUP BY X.SEQFAMILIA
    ),
    CTE_VENDAS AS (
        SELECT /*+ MATERIALIZE */
            V.SEQPRODUTO,
            V.NROEMPRESA,
            SUM(NVL(V.QTDVDA, 0) - NVL(V.QTDDEVOL, 0)) AS QUANTIDADE,
            SUM(NVL(V.VLRTOTALVDA, 0) - NVL(V.VLRTOTALDEVOL, 0) + NVL(V.VLRDESCFORANFVDA, 0) - NVL(V.VLRDESCFORANFDEVOL, 0)) AS VALOR_TOTAL_BRUTO,
            SUM(NVL(V.VLRDESCFORANFVDA, 0) - NVL(V.VLRDESCFORANFDEVOL, 0)) AS VALOR_DESCONTO,
            SUM(NVL(V.VLRTOTALVDA, 0) - NVL(V.VLRTOTALDEVOL, 0)) AS VALOR_TOTAL_LIQ,
            SUM(NVL(V.VLRCUSLIQUIDOVDA, 0) - NVL(V.VLRCUSLIQUIDODEVOL, 0)) AS CUSTO_LIQUIDO,
            SUM(
                (NVL(V.VLRICMSVDA, 0) - NVL(V.VLRICMSDEVOL, 0))
                + (NVL(V.VLRPISVDA, 0) - NVL(V.VLRPISDEVOL, 0))
                + (NVL(V.VLRCOFINSVDA, 0) - NVL(V.VLRCOFINSDEVOL, 0))
                + (NVL(V.VLRFCPICMSVDA, 0) - NVL(V.VLRFCPICMSVDADEVOL, 0))
            ) AS IMPOSTOS,
            SUM(
                (NVL(V.VLRTOTALVDA, 0) - NVL(V.VLRTOTALDEVOL, 0))
                - (NVL(V.VLRCUSLIQUIDOVDA, 0) - NVL(V.VLRCUSLIQUIDODEVOL, 0))
                - (
                    (NVL(V.VLRICMSVDA, 0) - NVL(V.VLRICMSDEVOL, 0))
                    + (NVL(V.VLRPISVDA, 0) - NVL(V.VLRPISDEVOL, 0))
                    + (NVL(V.VLRCOFINSVDA, 0) - NVL(V.VLRCOFINSDEVOL, 0))
                    + (NVL(V.VLRFCPICMSVDA, 0) - NVL(V.VLRFCPICMSVDADEVOL, 0))
                )
            ) AS LUCRATIVIDADE_TOTAL
        FROM MRL_CUSTODIA V
        WHERE V.NROEMPRESA = 3
          AND V.DTAENTRADASAIDA >= ADD_MONTHS(TRUNC(SYSDATE) - 1, -6)
          AND V.DTAENTRADASAIDA <= TRUNC(SYSDATE) - 1
        GROUP BY V.SEQPRODUTO, V.NROEMPRESA
        HAVING SUM(NVL(V.QTDVDA, 0) - NVL(V.QTDDEVOL, 0)) > 0
            OR SUM(NVL(V.VLRTOTALVDA, 0) - NVL(V.VLRTOTALDEVOL, 0)) > 0
    ),
    CTE_DADOS_PRODUTO AS (
        SELECT /*+ MATERIALIZE */
            CAT.DEPARTAMENTO,
            CAT.SECAO,
            CAT.GRUPO,
            CAT.SUBGRUPO_NIVEL4 AS CATEGORIA_NIVEL4,
            A.SEQPRODUTO AS CODIGO_PRODUTO,
            A.DESCCOMPLETA AS DESCRICAO_PRODUTO,
            NVL(V.QUANTIDADE, 0) AS QUANTIDADE,
            NVL(V.VALOR_TOTAL_BRUTO, 0) AS VALOR_TOTAL_BRUTO,
            NVL(V.VALOR_DESCONTO, 0) AS VALOR_DESCONTO,
            NVL(V.VALOR_TOTAL_LIQ, 0) AS VALOR_TOTAL_LIQ,
            NVL(V.CUSTO_LIQUIDO, 0) AS CUSTO_LIQUIDO,
            NVL(V.IMPOSTOS, 0) AS IMPOSTOS,
            NVL(V.LUCRATIVIDADE_TOTAL, 0) AS LUCRATIVIDADE_TOTAL
        FROM MAP_PRODUTO A
        INNER JOIN CTE_CATEGORIAS CAT
            ON CAT.SEQFAMILIA = A.SEQFAMILIA
        INNER JOIN CTE_VENDAS V
            ON V.SEQPRODUTO = A.SEQPRODUTO
        WHERE (
            UPPER(TRANSLATE(NVL(CAT.SUBGRUPO_NIVEL4, ' '), 'ÁÉÍÓÚÀÈÌÒÙÃÕÂÊÎÔÛÇ', 'AEIOUAEIOUAOAEIOUC')) LIKE '%CAFE%AFIN%'
            OR UPPER(TRANSLATE(NVL(CAT.SUBGRUPO_NIVEL4, ' '), 'ÁÉÍÓÚÀÈÌÒÙÃÕÂÊÎÔÛÇ', 'AEIOUAEIOUAOAEIOUC')) LIKE '%CAFE%'
            OR UPPER(TRANSLATE(NVL(CAT.GRUPO, ' '), 'ÁÉÍÓÚÀÈÌÒÙÃÕÂÊÎÔÛÇ', 'AEIOUAEIOUAOAEIOUC')) LIKE '%CAFE%AFIN%'
        )
    )
    SELECT
        1 AS ORDEM_BLOCO,
        3 AS LOJA,
        D.DEPARTAMENTO,
        D.SECAO,
        D.GRUPO,
        D.CATEGORIA_NIVEL4,
        D.CODIGO_PRODUTO,
        D.DESCRICAO_PRODUTO,
        ROUND(D.QUANTIDADE, 3) AS QUANTIDADE,
        ROUND(D.VALOR_TOTAL_BRUTO, 2) AS VALOR_TOTAL_BRUTO,
        ROUND(D.VALOR_DESCONTO, 2) AS VALOR_DESCONTO,
        ROUND(D.VALOR_TOTAL_LIQ, 2) AS VALOR_TOTAL_LIQ,
        ROUND(D.CUSTO_LIQUIDO, 2) AS CUSTO_LIQUIDO,
        ROUND(D.IMPOSTOS, 2) AS IMPOSTOS,
        ROUND(D.LUCRATIVIDADE_TOTAL, 2) AS LUCRATIVIDADE_TOTAL,
        ROUND(
            CASE 
                WHEN D.VALOR_TOTAL_LIQ > 0 
                THEN (D.LUCRATIVIDADE_TOTAL / D.VALOR_TOTAL_LIQ) * 100
                ELSE 0 
            END
        , 2) AS MARGEM_LUCRO_PERC,
        ROUND(
            CASE 
                WHEN D.VALOR_TOTAL_LIQ > 0 
                THEN ((D.VALOR_TOTAL_LIQ - D.CUSTO_LIQUIDO) / D.VALOR_TOTAL_LIQ) * 100
                ELSE 0 
            END
        , 2) AS MARGEM_BRUTA_COMERCIAL_PERC
    FROM CTE_DADOS_PRODUTO D

    UNION ALL

    SELECT
        2 AS ORDEM_BLOCO,
        3 AS LOJA,
        'TOTAL GERAL ->' AS DEPARTAMENTO,
        NULL AS SECAO,
        NULL AS GRUPO,
        'TODOS (CAFES E AFINS)' AS CATEGORIA_NIVEL4,
        TO_NUMBER(NULL) AS CODIGO_PRODUTO,
        'TOTAL CONSOLIDADO DA CATEGORIA' AS DESCRICAO_PRODUTO,
        ROUND(SUM(D.QUANTIDADE), 3) AS QUANTIDADE,
        ROUND(SUM(D.VALOR_TOTAL_BRUTO), 2) AS VALOR_TOTAL_BRUTO,
        ROUND(SUM(D.VALOR_DESCONTO), 2) AS VALOR_DESCONTO,
        ROUND(SUM(D.VALOR_TOTAL_LIQ), 2) AS VALOR_TOTAL_LIQ,
        ROUND(SUM(D.CUSTO_LIQUIDO), 2) AS CUSTO_LIQUIDO,
        ROUND(SUM(D.IMPOSTOS), 2) AS IMPOSTOS,
        ROUND(SUM(D.LUCRATIVIDADE_TOTAL), 2) AS LUCRATIVIDADE_TOTAL,
        ROUND(
            CASE 
                WHEN SUM(D.VALOR_TOTAL_LIQ) > 0 
                THEN (SUM(D.LUCRATIVIDADE_TOTAL) / SUM(D.VALOR_TOTAL_LIQ)) * 100
                ELSE 0 
            END
        , 2) AS MARGEM_LUCRO_PERC,
        ROUND(
            CASE 
                WHEN SUM(D.VALOR_TOTAL_LIQ) > 0 
                THEN ((SUM(D.VALOR_TOTAL_LIQ) - SUM(D.CUSTO_LIQUIDO)) / SUM(D.VALOR_TOTAL_LIQ)) * 100
                ELSE 0 
            END
        , 2) AS MARGEM_BRUTA_COMERCIAL_PERC
    FROM CTE_DADOS_PRODUTO D

    ORDER BY ORDEM_BLOCO ASC, VALOR_TOTAL_LIQ DESC, CODIGO_PRODUTO ASC
)
