SELECT
    MAX(NVL(COMP.COMPRADOR, 'SEM GESTOR')) AS COMPRADOR,
    MAX(NVL(FP.CODIGO_FORNECEDOR, 0)) AS CODIGO_FORNECEDOR_PRINCIPAL,
    MAX(NVL(FP.FORNECEDOR_PRINCIPAL, 'SEM FORNECEDOR')) AS FORNECEDOR_PRINCIPAL,
    SUB.SUBGRUPO,
    A.SEQPRODUTO AS CODIGO_PRODUTO,
    A.DESCCOMPLETA AS DESCRICAO_PRODUTO,
    MAX(FD.PADRAOEMBCOMPRA) AS EMBALAGEM,
    ROUND(
        SUM(SUM(NVL(VND.QTD_VENDIDA, 0) * NVL(PV.PRECO_VENDA, 0))) OVER (ORDER BY SUM(NVL(VND.QTD_VENDIDA, 0) * NVL(PV.PRECO_VENDA, 0)) DESC) /
        NULLIF(SUM(SUM(NVL(VND.QTD_VENDIDA, 0) * NVL(PV.PRECO_VENDA, 0))) OVER (), 0) * 100,
        1
    ) AS PERC_ACM,
    MAX(NVL(C3.PRECO_CUSTO, 0)) AS PRECO_CUSTO,
    MAX(NVL(PV.PRECO_VENDA, 0)) AS PRECO_VENDA,
    ROUND(
        DECODE(
            MAX(NVL(PV.PRECO_VENDA, 0)),
            0,
            0,
            ((MAX(NVL(PV.PRECO_VENDA, 0)) - MAX(NVL(C3.PRECO_CUSTO, 0))) / MAX(NVL(PV.PRECO_VENDA, 0))) * 100
        ),
        2
    ) AS MARGEM_ATUAL,
    ROUND(
        MAX(
            NVL(
                NULLIF(MOBJ.MARGEM_OBJETIVA, 0),
                FC5MARGEMPRECOCADDESPOPER(
                    A.SEQPRODUTO,
                    3,
                    EMP3.NROSEGMENTOPRINC,
                    NVL(FSEG.PADRAOEMBVENDA, 1),
                    'M'
                )
            )
        ),
        2
    ) AS MARGEM_OBJETIVA,
    SUM(NVL(VND.QTD_VENDIDA, 0)) AS QTD_VENDIDA,
    SUM(NVL(Y.ESTQMINIMOLOJA, 0)) AS ESTOQUE_MINIMO,
    SUM(NVL(Y.ESTQMAXIMOLOJA, 0)) AS ESTOQUE_MAXIMO,
    SUM(NVL(Y.ESTQLOJA, 0)) AS ESTOQUE_LOJA,
    MAX(NVL(CD.ESTOQUE_CD, 0)) AS ESTOQUE_DEPOSITO,
    MAX(NVL(CD.QTD_PENDENTE_EXPEDIR_CD, 0)) AS PENDENTE_EXPEDIR_CD
FROM MAP_PRODUTO A
INNER JOIN MRL_PRODUTOEMPRESA Y ON A.SEQPRODUTO = Y.SEQPRODUTO
LEFT JOIN MAP_FAMDIVISAO FD ON A.SEQFAMILIA = FD.SEQFAMILIA AND FD.NRODIVISAO = 1
LEFT JOIN MAX_COMPRADOR COMP ON COMP.SEQCOMPRADOR = FD.SEQCOMPRADOR
LEFT JOIN (
    SELECT F.SEQFAMILIA,
        MAX(F.SEQFORNECEDOR) AS CODIGO_FORNECEDOR,
           MAX(P.NOMERAZAO) AS FORNECEDOR_PRINCIPAL
    FROM MAP_FAMFORNEC F
    INNER JOIN GE_PESSOA P ON P.SEQPESSOA = F.SEQFORNECEDOR
    WHERE F.PRINCIPAL = 'S'
    GROUP BY F.SEQFAMILIA
) FP ON FP.SEQFAMILIA = A.SEQFAMILIA
LEFT JOIN (
    SELECT X.SEQFAMILIA, MAX(Y2.CATEGORIA) AS SUBGRUPO
    FROM MAP_FAMDIVCATEG X
    INNER JOIN MAP_CATEGORIA Y2 ON X.SEQCATEGORIA = Y2.SEQCATEGORIA
    WHERE Y2.NIVELHIERARQUIA = 4 AND X.NRODIVISAO = 1 AND X.STATUS = 'A'
    GROUP BY X.SEQFAMILIA
) SUB ON SUB.SEQFAMILIA = A.SEQFAMILIA
LEFT JOIN (
    SELECT SEG.SEQPRODUTO,
           MAX(ROUND(NVL(NULLIF(SEG.PRECOVALIDPROMOC, 0), SEG.PRECOVALIDNORMAL), 2)) AS PRECO_VENDA
    FROM MRL_PRODEMPSEG SEG
    WHERE SEG.NROEMPRESA = 3
      AND SEG.QTDEMBALAGEM = 1
    GROUP BY SEG.SEQPRODUTO
) PV ON PV.SEQPRODUTO = A.SEQPRODUTO
LEFT JOIN MAX_EMPRESA EMP3 ON EMP3.NROEMPRESA = 3
LEFT JOIN MAD_FAMSEGMENTO FSEG ON FSEG.SEQFAMILIA = A.SEQFAMILIA AND FSEG.NROSEGMENTO = EMP3.NROSEGMENTOPRINC
LEFT JOIN (
    SELECT Y1.SEQPRODUTO,
           ROUND(NVL(Y1.CMULTCUSLIQUIDOEMP, 0), 2) AS PRECO_CUSTO
    FROM MRL_PRODUTOEMPRESA Y1
    WHERE Y1.NROEMPRESA = 3
) C3 ON C3.SEQPRODUTO = A.SEQPRODUTO
LEFT JOIN (
    SELECT X.SEQPRODUTO,
           X.MARGEM_OBJETIVA
    FROM (
                SELECT E.SEQDETALHE2 AS SEQPRODUTO,
                             NVL(E.MARGEMCADASTRO, 0) AS MARGEM_OBJETIVA,
                             1 AS ORDEM_FONTE,
               ROW_NUMBER() OVER (
                   PARTITION BY E.SEQDETALHE2
                   ORDER BY E.SEQCONSULTA DESC
               ) AS RN
                FROM MBI_TABCDISTRIB E
                WHERE E.SEQDETALHE2 IS NOT NULL
                    AND NVL(E.MARGEMCADASTRO, 0) > 0

                UNION ALL

                SELECT E.SEQDETALHE2 AS SEQPRODUTO,
                             NVL(E.MARGEMCADASTRO, 0) AS MARGEM_OBJETIVA,
                             2 AS ORDEM_FONTE,
                             ROW_NUMBER() OVER (
                                     PARTITION BY E.SEQDETALHE2
                                     ORDER BY E.SEQCONSULTA DESC
                             ) AS RN
        FROM MBI_TABCESTOQUE E
        WHERE E.SEQDETALHE2 IS NOT NULL
          AND NVL(E.MARGEMCADASTRO, 0) > 0
    ) X
        WHERE X.RN = 1
            AND NOT EXISTS (
                    SELECT 1
                    FROM (
                            SELECT D.SEQDETALHE2 AS SEQPRODUTO,
                                         1 AS ORDEM_FONTE,
                                         ROW_NUMBER() OVER (
                                                 PARTITION BY D.SEQDETALHE2
                                                 ORDER BY D.SEQCONSULTA DESC
                                         ) AS RN
                            FROM MBI_TABCDISTRIB D
                            WHERE D.SEQDETALHE2 IS NOT NULL
                                AND NVL(D.MARGEMCADASTRO, 0) > 0

                            UNION ALL

                            SELECT E2.SEQDETALHE2 AS SEQPRODUTO,
                                         2 AS ORDEM_FONTE,
                                         ROW_NUMBER() OVER (
                                                 PARTITION BY E2.SEQDETALHE2
                                                 ORDER BY E2.SEQCONSULTA DESC
                                         ) AS RN
                            FROM MBI_TABCESTOQUE E2
                            WHERE E2.SEQDETALHE2 IS NOT NULL
                                AND NVL(E2.MARGEMCADASTRO, 0) > 0
                    ) Y
                    WHERE Y.SEQPRODUTO = X.SEQPRODUTO
                        AND Y.RN = 1
                        AND Y.ORDEM_FONTE < X.ORDEM_FONTE
            )
) MOBJ ON MOBJ.SEQPRODUTO = A.SEQPRODUTO
LEFT JOIN (
    SELECT SEQPRODUTO, NROEMPRESA, SUM(QTDVDA) AS QTD_VENDIDA
    FROM MRL_PRODVENDADIA
    WHERE DTAVDA BETWEEN TRUNC(SYSDATE) - 40 AND TRUNC(SYSDATE)
    GROUP BY SEQPRODUTO, NROEMPRESA
) VND ON VND.SEQPRODUTO = A.SEQPRODUTO AND VND.NROEMPRESA = Y.NROEMPRESA
LEFT JOIN (
    SELECT SEQPRODUTO, 
           SUM(NVL(ESTQLOJA, 0) + NVL(ESTQDEPOSITO, 0) - (NVL(QTDRESERVADAVDA, 0) + NVL(QTDRESERVADARECEB, 0) + NVL(QTDRESERVADAFIXA, 0))) AS ESTOQUE_CD,
           SUM(NVL(QTDPENDPEDEXPED, 0)) AS QTD_PENDENTE_EXPEDIR_CD
    FROM MRL_PRODUTOEMPRESA
    WHERE NROEMPRESA IN (15, 16, 50)
    GROUP BY SEQPRODUTO
) CD ON CD.SEQPRODUTO = A.SEQPRODUTO
WHERE Y.NROEMPRESA IN (1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 14, 17, 18)
  AND NOT EXISTS (
      SELECT 1 
      FROM MAP_FAMDIVCATEG XF
      INNER JOIN MAP_CATEGORIA YF ON XF.SEQCATEGORIA = YF.SEQCATEGORIA
      WHERE XF.SEQFAMILIA = A.SEQFAMILIA 
        AND YF.NIVELHIERARQUIA = 1
        AND (
            UPPER(YF.CATEGORIA) IN ('A CLASSIFICAR', 'ALMOXARIFADO', 'INATIVAR')
            OR UPPER(YF.CATEGORIA) LIKE 'SERVIC%'
        )
  )
GROUP BY
    SUB.SUBGRUPO,
    A.SEQPRODUTO,
    A.DESCCOMPLETA
HAVING SUM(NVL(VND.QTD_VENDIDA, 0)) > 0
ORDER BY SUB.SUBGRUPO, QTD_VENDIDA DESC
