SELECT * FROM (
WITH FILTRADOS_BASE AS (
  SELECT A.SEQPRODUTO, A.SEQFAMILIA
  FROM MAP_PRODUTO A
  INNER JOIN MRL_PRODUTOEMPRESA Y ON A.SEQPRODUTO = Y.SEQPRODUTO
  LEFT JOIN MAP_FAMDIVISAO FD ON A.SEQFAMILIA = FD.SEQFAMILIA AND FD.NRODIVISAO = 1
  WHERE Y.NROEMPRESA IN (1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 14, 17, 18)
    AND (:NR1 = '0' OR Y.NROEMPRESA = TO_NUMBER(:NR1))
    AND (:NR2 = '0' OR A.SEQPRODUTO = TO_NUMBER(:NR2))
    AND Y.STATUSCOMPRA = 'A'
    AND ((:LS3 = '0 - TODOS') OR NVL(FD.SEQCOMPRADOR, 0) = TO_NUMBER(SUBSTR(:LS3, 1, INSTR(:LS3, ' - ') - 1)))
    AND (:LT2 = '0' OR EXISTS (SELECT 1 FROM MAP_FAMFORNEC F WHERE F.SEQFAMILIA = A.SEQFAMILIA AND F.SEQFORNECEDOR = TO_NUMBER(:LT2)))
  
  UNION
  
  SELECT A.SEQPRODUTO, A.SEQFAMILIA
  FROM MRL_CUSTODIA V
  INNER JOIN MAP_PRODUTO A ON A.SEQPRODUTO = V.SEQPRODUTO
  LEFT JOIN MAP_FAMDIVISAO FD ON A.SEQFAMILIA = FD.SEQFAMILIA AND FD.NRODIVISAO = 1
  WHERE V.DTAENTRADASAIDA BETWEEN :DT1 AND :DT2
    AND V.NROEMPRESA IN (1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 14, 17, 18)
    AND (:NR1 = '0' OR V.NROEMPRESA = TO_NUMBER(:NR1))
    AND (:NR2 = '0' OR A.SEQPRODUTO = TO_NUMBER(:NR2))
    AND ((:LS3 = '0 - TODOS') OR NVL(FD.SEQCOMPRADOR, 0) = TO_NUMBER(SUBSTR(:LS3, 1, INSTR(:LS3, ' - ') - 1)))
    AND (:LT2 = '0' OR EXISTS (SELECT 1 FROM MAP_FAMFORNEC F WHERE F.SEQFAMILIA = A.SEQFAMILIA AND F.SEQFORNECEDOR = TO_NUMBER(:LT2)))

  UNION
  
  SELECT A.SEQPRODUTO, A.SEQFAMILIA
  FROM MLF_NOTAFISCAL NF
  JOIN MLF_NFITEM I ON I.NUMERONF = NF.NUMERONF AND I.SERIENF = NF.SERIENF AND I.NROEMPRESA = NF.NROEMPRESA AND I.TIPNOTAFISCAL = NF.TIPNOTAFISCAL AND NVL(I.SEQNF,0) = NVL(NF.SEQNF, NVL(I.SEQNF,0))
  JOIN MAP_PRODUTO A ON A.SEQPRODUTO = I.SEQPRODUTO
  LEFT JOIN MAP_FAMDIVISAO FD ON A.SEQFAMILIA = FD.SEQFAMILIA AND FD.NRODIVISAO = 1
  WHERE NF.STATUSNF != 'C'
    AND NF.TIPNOTAFISCAL = 'E'
    AND NF.DTAENTRADA BETWEEN :DT1 AND :DT2
    AND (:NR2 = '0' OR A.SEQPRODUTO = TO_NUMBER(:NR2))
    AND ((:LS3 = '0 - TODOS') OR NVL(FD.SEQCOMPRADOR, 0) = TO_NUMBER(SUBSTR(:LS3, 1, INSTR(:LS3, ' - ') - 1)))
    AND (:LT2 = '0' OR NF.SEQPESSOA = TO_NUMBER(:LT2) OR EXISTS (SELECT 1 FROM MAP_FAMFORNEC F WHERE F.SEQFAMILIA = A.SEQFAMILIA AND F.SEQFORNECEDOR = TO_NUMBER(:LT2)))

  UNION
  
  SELECT A.SEQPRODUTO, A.SEQFAMILIA
  FROM MLFV_BASENFE NFE
  JOIN MFLV_BASEDFITEM IT ON IT.SEQNF = NFE.SEQNF AND IT.NROEMPRESA = NFE.NROEMPRESA AND IT.TIPNOTAFISCAL = NFE.TIPNOTAFISCAL
  JOIN MAP_PRODUTO A ON A.SEQPRODUTO = IT.SEQPRODUTO
  LEFT JOIN MAP_FAMDIVISAO FD ON A.SEQFAMILIA = FD.SEQFAMILIA AND FD.NRODIVISAO = 1
  WHERE NFE.STATUSNF != 'C'
    AND NFE.CODGERALOPER IN (802, 860)
    AND NFE.DTAEMISSAO BETWEEN :DT1 AND :DT2
    AND (:NR2 = '0' OR A.SEQPRODUTO = TO_NUMBER(:NR2))
    AND ((:LS3 = '0 - TODOS') OR NVL(FD.SEQCOMPRADOR, 0) = TO_NUMBER(SUBSTR(:LS3, 1, INSTR(:LS3, ' - ') - 1)))
    AND (:LT2 = '0' OR NFE.SEQPESSOA = TO_NUMBER(:LT2) OR EXISTS (SELECT 1 FROM MAP_FAMFORNEC F WHERE F.SEQFAMILIA = A.SEQFAMILIA AND F.SEQFORNECEDOR = TO_NUMBER(:LT2)))
),
FILTRADOS AS (
  SELECT /*+ MATERIALIZE */ DISTINCT F.SEQPRODUTO, F.SEQFAMILIA
  FROM FILTRADOS_BASE F
  INNER JOIN MRL_PRODUTOEMPRESA Y ON Y.SEQPRODUTO = F.SEQPRODUTO
  WHERE Y.NROEMPRESA IN (1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 14, 17, 18)
    AND (:NR1 = '0' OR Y.NROEMPRESA = TO_NUMBER(:NR1))
    AND Y.STATUSCOMPRA = 'A'
),
LINHAS_ITENS AS (
  SELECT /*+ MATERIALIZE */
    1 AS ORDEM,
    MAX(NVL(VF.QTD_VENDIDA_TOTAL, 0)) AS QTD_VDA_NUM,
  TO_NUMBER(:NR1) AS LOJA,
  (TRUNC(TO_DATE(:DT2, 'DD/MM/YYYY')) - TRUNC(TO_DATE(:DT1, 'DD/MM/YYYY')) + 1) AS DIAS,
  CASE WHEN :LT2 != '0' THEN NVL(TO_CHAR(FORN_FILTRO.SEQPESSOA), '0') || ' - ' || NVL(FORN_FILTRO.NOMERAZAO, 'SEM DESCRICAO') ELSE NVL(TO_CHAR(FP.CODIGO_FORNECEDOR), '0') || ' - ' || NVL(FP.FORNECEDOR_PRINCIPAL, 'SEM DESCRICAO') END AS TITULO_FORNECEDOR,
  SUB.SUBGRUPO AS SUBGRUPO,
  TO_CHAR(A.SEQPRODUTO) AS COD_PROD,
  SUBSTR(A.DESCCOMPLETA, 1, 55) AS PRODUTO,
  '  ' || TO_CHAR(MAX(FD.PADRAOEMBCOMPRA)) AS EMB,
  '  ' || TO_CHAR(MAX(NVL(CD_CST.PRECO_CUSTO_CD, 0)), 'FM99990D00', 'NLS_NUMERIC_CHARACTERS='',.''') AS CST_CD,
  '  ' || TO_CHAR(ROUND(MAX(FC5MARGEMPRECO(A.SEQPRODUTO, 3, (SELECT MAX(NROSEGMENTOPRINC) FROM MAX_EMPRESA WHERE NROEMPRESA = 3), 1, NVL(CD_CST.PRECO_CUSTO_CD, 0), NVL(PV.PRECO_VENDA, 0), NULL, NULL)), 2), 'FM9990D00', 'NLS_NUMERIC_CHARACTERS='',.''') AS MG_CD,
  '  ' || TO_CHAR(MAX(NVL(LJ_CST.PRECO_CUSTO_LJ, 0)), 'FM99990D00', 'NLS_NUMERIC_CHARACTERS='',.''') AS CST_LJ,
  '  ' || TO_CHAR(MAX(NVL(LJ_CST.MARGEM_LIQUIDA_LJ, 0)), 'FM9990D00', 'NLS_NUMERIC_CHARACTERS='',.''') AS MG_LJ,
  '  ' || TO_CHAR(MAX(NVL(PV.PRECO_VENDA, 0)), 'FM99990D00', 'NLS_NUMERIC_CHARACTERS='',.''') AS PRC_VDA,
  '  ' || TO_CHAR(ROUND(MAX(NVL(NULLIF(MOBJ.MARGEM_OBJETIVA, 0), FC5MARGEMPRECOCADDESPOPER(A.SEQPRODUTO, 3, EMP3.NROSEGMENTOPRINC, NVL(FSEG.PADRAOEMBVENDA, 1), 'M'))), 2), 'FM9990D00', 'NLS_NUMERIC_CHARACTERS='',.''') AS MARG_OBJ,
  '  ' || TO_CHAR(SUM(NVL(Y.ESTQMINIMOLOJA, 0))) AS EST_MIN,
  '  ' || TO_CHAR(SUM(NVL(Y.ESTQMAXIMOLOJA, 0))) AS EST_MAX,
  '  ' || TO_CHAR(MAX(NVL(VF.QTD_VENDIDA_TOTAL, 0))) AS QTD_VDA,
  '  ' || TO_CHAR(SUM(NVL(Y.ESTQLOJA, 0))) AS EST_LOJA,
  '  ' || TO_CHAR(MAX(NVL(CD.ESTOQUE_CD, 0))) AS EST_CD,
  '  ' || TO_CHAR(MAX(CD.QTD_PENDENTE_EXPEDIR_CD)) AS PEND_CD,
  '  ' || TO_CHAR(
    (
      SELECT NVL(SUM(CASE WHEN X.QTDSOLICITADA > X.QTDRECCANC THEN X.QTDSOLICITADA - X.QTDRECCANC ELSE 0 END), 0)
        FROM MAXV_MSUPEDIDOSUPRIMREC X
       WHERE X.SEQPRODUTO = A.SEQPRODUTO
          AND X.TIPPEDIDOSUPRIM = 'C'
          AND X.NROEMPRESA IN (1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 14, 15, 16, 17, 18, 50)
          AND (:NR1 = '0' OR X.NROEMPRESA = TO_NUMBER(:NR1))
    )
  ) AS PEND_FOR,
  '  ' || TO_CHAR(MAX(NVL(CD.QTD_ULTIMA_COMPRA_CD, 0))) AS QTD_ULT_COMP,
  '  ' || TO_CHAR(MAX(CD.DATA_ULTIMA_COMPRA_CD), 'DD/MM/YYYY') AS DT_ULT_COMP,
  '___________' AS "Comprar"
FROM FILTRADOS F
INNER JOIN MAP_PRODUTO A ON A.SEQPRODUTO = F.SEQPRODUTO
INNER JOIN MRL_PRODUTOEMPRESA Y ON Y.SEQPRODUTO = F.SEQPRODUTO AND Y.NROEMPRESA IN (1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 14, 17, 18) AND (:NR1 = '0' OR Y.NROEMPRESA = TO_NUMBER(:NR1))
LEFT JOIN MAP_FAMDIVISAO FD ON A.SEQFAMILIA = FD.SEQFAMILIA AND FD.NRODIVISAO = 1
LEFT JOIN MAX_COMPRADOR COMP ON COMP.SEQCOMPRADOR = FD.SEQCOMPRADOR
LEFT JOIN (
  SELECT YCD.SEQPRODUTO,
         MAX(ROUND(NVL(YCD.CMULTVLRNF, 0), 2)) AS PRECO_CUSTO_CD
    FROM MRL_PRODUTOEMPRESA YCD
    INNER JOIN FILTRADOS F ON F.SEQPRODUTO = YCD.SEQPRODUTO
   WHERE YCD.NROEMPRESA = TO_NUMBER(:LT1)
   GROUP BY YCD.SEQPRODUTO
) CD_CST ON CD_CST.SEQPRODUTO = A.SEQPRODUTO
LEFT JOIN (
  SELECT YLJ.SEQPRODUTO,
         ROUND(AVG(NVL(YLJ.CMULTVLRNF, 0)), 2) AS PRECO_CUSTO_LJ,
         ROUND(AVG(NVL(
           FC5MARGEMPRECO(
             YLJ.SEQPRODUTO,
             YLJ.NROEMPRESA,
             (SELECT MAX(NROSEGMENTOPRINC) FROM MAX_EMPRESA WHERE NROEMPRESA = YLJ.NROEMPRESA),
             1,
             NULL,
             (SELECT MAX(ROUND(NVL(NULLIF(SEG.PRECOVALIDPROMOC, 0), SEG.PRECOVALIDNORMAL), 2))
                FROM MRL_PRODEMPSEG SEG
               WHERE SEG.SEQPRODUTO = YLJ.SEQPRODUTO
                 AND SEG.NROEMPRESA = YLJ.NROEMPRESA
                 AND SEG.NROSEGMENTO = (SELECT MAX(NROSEGMENTOPRINC) FROM MAX_EMPRESA WHERE NROEMPRESA = YLJ.NROEMPRESA)
                 AND SEG.QTDEMBALAGEM = 1),
             NULL,
             NULL
           ), 0
         )), 2) AS MARGEM_LIQUIDA_LJ
    FROM MRL_PRODUTOEMPRESA YLJ
    INNER JOIN FILTRADOS F ON F.SEQPRODUTO = YLJ.SEQPRODUTO
   WHERE YLJ.NROEMPRESA IN (1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 14, 17, 18)
     AND (:NR1 = '0' OR YLJ.NROEMPRESA = TO_NUMBER(:NR1))
   GROUP BY YLJ.SEQPRODUTO
) LJ_CST ON LJ_CST.SEQPRODUTO = A.SEQPRODUTO
LEFT JOIN (
  SELECT F.SEQFAMILIA,
       MAX(F.SEQFORNECEDOR) AS CODIGO_FORNECEDOR,
       MAX(P.NOMERAZAO) AS FORNECEDOR_PRINCIPAL
  FROM MAP_FAMFORNEC F
  INNER JOIN GE_PESSOA P ON P.SEQPESSOA = F.SEQFORNECEDOR
  INNER JOIN (SELECT DISTINCT SEQFAMILIA FROM FILTRADOS) FIL ON FIL.SEQFAMILIA = F.SEQFAMILIA
  WHERE F.PRINCIPAL = 'S'
  GROUP BY F.SEQFAMILIA
) FP ON FP.SEQFAMILIA = A.SEQFAMILIA
LEFT JOIN (
  SELECT TO_NUMBER(:LT2) AS SEQPESSOA, MAX(NOMERAZAO) AS NOMERAZAO FROM GE_PESSOA WHERE SEQPESSOA = TO_NUMBER(:LT2)
) FORN_FILTRO ON :LT2 != '0'
LEFT JOIN (
  SELECT X.SEQFAMILIA,
       MAX(Y2.CATEGORIA) AS SUBGRUPO
  FROM MAP_FAMDIVCATEG X
  INNER JOIN MAP_CATEGORIA Y2 ON X.SEQCATEGORIA = Y2.SEQCATEGORIA
  INNER JOIN (SELECT DISTINCT SEQFAMILIA FROM FILTRADOS) FIL ON FIL.SEQFAMILIA = X.SEQFAMILIA
  WHERE Y2.NIVELHIERARQUIA = 5
    AND X.NRODIVISAO = 1
    AND X.STATUS = 'A'
  GROUP BY X.SEQFAMILIA
) SUB ON SUB.SEQFAMILIA = A.SEQFAMILIA
LEFT JOIN (
  SELECT SEG.SEQPRODUTO,
       MAX(ROUND(NVL(NULLIF(SEG.PRECOVALIDPROMOC, 0), SEG.PRECOVALIDNORMAL), 2)) AS PRECO_VENDA
  FROM MRL_PRODEMPSEG SEG
  INNER JOIN FILTRADOS F ON F.SEQPRODUTO = SEG.SEQPRODUTO
  WHERE SEG.NROEMPRESA = 3
    AND SEG.NROSEGMENTO = (SELECT MAX(NROSEGMENTOPRINC) FROM MAX_EMPRESA WHERE NROEMPRESA = 3)
    AND SEG.QTDEMBALAGEM = 1
  GROUP BY SEG.SEQPRODUTO
) PV ON PV.SEQPRODUTO = A.SEQPRODUTO
LEFT JOIN MAX_EMPRESA EMP3 ON EMP3.NROEMPRESA = 3
LEFT JOIN MAD_FAMSEGMENTO FSEG ON FSEG.SEQFAMILIA = A.SEQFAMILIA AND FSEG.NROSEGMENTO = EMP3.NROSEGMENTOPRINC
LEFT JOIN (
  SELECT X.SEQPRODUTO,
       X.MARGEM_OBJETIVA
    FROM (
      SELECT E.SEQDETALHE2 AS SEQPRODUTO,
             NVL(E.MARGEMCADASTRO, 0) AS MARGEM_OBJETIVA,
             1 AS ORDEM_FONTE,
             ROW_NUMBER() OVER (
               PARTITION BY E.SEQDETALHE2
               ORDER BY E.SEQCONSULTA DESC
             ) AS RN
        FROM MBI_TABCDISTRIB E
        INNER JOIN FILTRADOS F ON F.SEQPRODUTO = E.SEQDETALHE2
        WHERE E.SEQDETALHE2 IS NOT NULL
          AND NVL(E.MARGEMCADASTRO, 0) > 0
      UNION ALL
      SELECT E.SEQDETALHE2 AS SEQPRODUTO,
             NVL(E.MARGEMCADASTRO, 0) AS MARGEM_OBJETIVA,
             2 AS ORDEM_FONTE,
             ROW_NUMBER() OVER (
               PARTITION BY E.SEQDETALHE2
               ORDER BY E.SEQCONSULTA DESC
             ) AS RN
        FROM MBI_TABCESTOQUE E
        INNER JOIN FILTRADOS F ON F.SEQPRODUTO = E.SEQDETALHE2
        WHERE E.SEQDETALHE2 IS NOT NULL
          AND NVL(E.MARGEMCADASTRO, 0) > 0
    ) X
   WHERE X.RN = 1
     AND NOT EXISTS (
       SELECT 1
         FROM (
           SELECT D.SEQDETALHE2 AS SEQPRODUTO,
                  1 AS ORDEM_FONTE,
                  ROW_NUMBER() OVER (
                    PARTITION BY D.SEQDETALHE2
                    ORDER BY D.SEQCONSULTA DESC
                  ) AS RN
             FROM MBI_TABCDISTRIB D
             INNER JOIN FILTRADOS F ON F.SEQPRODUTO = D.SEQDETALHE2
            WHERE D.SEQDETALHE2 IS NOT NULL
              AND NVL(D.MARGEMCADASTRO, 0) > 0
           UNION ALL
           SELECT E2.SEQDETALHE2 AS SEQPRODUTO,
                  2 AS ORDEM_FONTE,
                  ROW_NUMBER() OVER (
                    PARTITION BY E2.SEQDETALHE2
                    ORDER BY E2.SEQCONSULTA DESC
                  ) AS RN
             FROM MBI_TABCESTOQUE E2
             INNER JOIN FILTRADOS F ON F.SEQPRODUTO = E2.SEQDETALHE2
            WHERE E2.SEQDETALHE2 IS NOT NULL
              AND NVL(E2.MARGEMCADASTRO, 0) > 0
         ) Y
        WHERE Y.SEQPRODUTO = X.SEQPRODUTO
          AND Y.RN = 1
          AND Y.ORDEM_FONTE < X.ORDEM_FONTE
     )
) MOBJ ON MOBJ.SEQPRODUTO = A.SEQPRODUTO
LEFT JOIN (
  SELECT M.SEQPRODUTO,
       SUM(M.QTDVDA) AS QTD_VENDIDA_TOTAL
  FROM MRL_CUSTODIA M
  INNER JOIN FILTRADOS F ON F.SEQPRODUTO = M.SEQPRODUTO
  WHERE M.DTAENTRADASAIDA BETWEEN :DT1 AND :DT2
    AND M.NROEMPRESA IN (1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 14, 17, 18)
    AND (:NR1 = '0' OR M.NROEMPRESA = TO_NUMBER(:NR1))
  GROUP BY M.SEQPRODUTO
) VF ON VF.SEQPRODUTO = A.SEQPRODUTO
LEFT JOIN (
  SELECT PE.SEQPRODUTO,
       SUM(PE.ESTQLOJA + PE.ESTQDEPOSITO - (PE.QTDRESERVADAVDA + PE.QTDRESERVADARECEB + PE.QTDRESERVADAFIXA)) AS ESTOQUE_CD,
       MAX(NVL(EXP.QTD_PEND_CD, 0)) AS QTD_PENDENTE_EXPEDIR_CD,
       MAX(PE.DTAULTCOMPRA) AS DATA_ULTIMA_COMPRA_CD,
       MAX(PE.QTDULTCOMPRA) AS QTD_ULTIMA_COMPRA_CD
  FROM MRL_PRODUTOEMPRESA PE
  INNER JOIN FILTRADOS F ON F.SEQPRODUTO = PE.SEQPRODUTO
  LEFT JOIN (
    SELECT X.SEQPRODUTO,
           SUM(X.QTDSOLICITADA - X.QTDEXPCANC) AS QTD_PEND_CD
    FROM MAXV_MSUPEDIDOSUPRIMEXP X
    INNER JOIN FILTRADOS F2 ON F2.SEQPRODUTO = X.SEQPRODUTO
    WHERE X.NROEMPRESA IN (15, 16, 50)
    GROUP BY X.SEQPRODUTO
  ) EXP ON EXP.SEQPRODUTO = PE.SEQPRODUTO
  WHERE PE.NROEMPRESA IN (15, 16, 50)
  GROUP BY PE.SEQPRODUTO
) CD ON CD.SEQPRODUTO = A.SEQPRODUTO
GROUP BY
  FORN_FILTRO.SEQPESSOA,
  FORN_FILTRO.NOMERAZAO,
  FP.CODIGO_FORNECEDOR,
  FP.FORNECEDOR_PRINCIPAL,
  SUB.SUBGRUPO,
  A.SEQPRODUTO,
  A.DESCCOMPLETA
),
LINHA_CABECALHO AS (
  SELECT /*+ MATERIALIZE */
    0 AS ORDEM,
    999999999 AS QTD_VDA_NUM,
    0 AS LOJA,
    0 AS DIAS,
    ' ' AS TITULO_FORNECEDOR,
    'LOJA: ' || NVL(TO_CHAR(MAX(LOJA)), '0') AS SUBGRUPO,
    'DIAS: ' || NVL(TO_CHAR(MAX(DIAS)), '0') AS COD_PROD,
    '> FORN: ' || NVL(MAX(TITULO_FORNECEDOR), 'VÁRIOS / TODOS') || ' >' AS PRODUTO,
    ' ' AS EMB,
    ' ' AS CST_CD,
    ' ' AS MG_CD,
    ' ' AS CST_LJ,
    ' ' AS MG_LJ,
    ' ' AS PRC_VDA,
    ' ' AS MARG_OBJ,
    ' ' AS EST_MIN,
    ' ' AS EST_MAX,
    ' ' AS QTD_VDA,
    ' ' AS EST_LOJA,
    ' ' AS EST_CD,
    ' ' AS PEND_CD,
    ' ' AS PEND_FOR,
    ' ' AS QTD_ULT_COMP,
    ' ' AS DT_ULT_COMP,
    '___________' AS "Comprar"
  FROM LINHAS_ITENS
)
SELECT
  SUBGRUPO,
  COD_PROD,
  PRODUTO,
  EMB,
  CST_CD,
  MG_CD,
  CST_LJ,
  MG_LJ,
  PRC_VDA,
  MARG_OBJ,
  EST_MIN,
  EST_MAX,
  QTD_VDA,
  EST_LOJA,
  EST_CD,
  PEND_CD,
  PEND_FOR,
  QTD_ULT_COMP,
  DT_ULT_COMP,
  "Comprar"
FROM (
  SELECT * FROM LINHA_CABECALHO
  UNION ALL
  SELECT * FROM LINHAS_ITENS
)
ORDER BY
  ORDEM ASC,
  SUBGRUPO ASC,
  QTD_VDA_NUM DESC,
  PRODUTO ASC,
  COD_PROD ASC
)
