SELECT
  NVL(TO_CHAR(FP.CODIGO_FORNECEDOR), '0') || ' - ' || NVL(FP.FORNECEDOR_PRINCIPAL, 'SEM DESCRICAO') AS TITULO_FORNECEDOR,
  SUB.SUBGRUPO AS SUBGRUPO,
  A.SEQPRODUTO AS COD_PROD,
  SUBSTR(A.DESCCOMPLETA, 1, 55) AS PRODUTO,
  MAX(FD.PADRAOEMBCOMPRA) AS EMB,
  TO_CHAR(MAX(NVL(CD_CST.PRECO_CUSTO_CD, 0)), 'FM99990D00', 'NLS_NUMERIC_CHARACTERS='',.''') AS CST_CD,
  TO_CHAR(MAX(NVL(LJ_CST.PRECO_CUSTO_LJ, 0)), 'FM99990D00', 'NLS_NUMERIC_CHARACTERS='',.''') AS CST_LJ,
  TO_CHAR(MAX(NVL(PV.PRECO_VENDA, 0)), 'FM99990D00', 'NLS_NUMERIC_CHARACTERS='',.''') AS PRC_VDA,
  ROUND(
    DECODE(
      MAX(NVL(PV.PRECO_VENDA, 0)),
      0,
      0,
      ((MAX(NVL(PV.PRECO_VENDA, 0)) - MAX(NVL(C3.PRECO_CUSTO, 0))) / MAX(NVL(PV.PRECO_VENDA, 0))) * 100
    ),
    2
  ) AS MARG_ATU,
  ROUND(
    MAX(
      NVL(
        NULLIF(MOBJ.MARGEM_OBJETIVA, 0),
        FC5MARGEMPRECOCADDESPOPER(
          A.SEQPRODUTO,
          3,
          EMP3.NROSEGMENTOPRINC,
          NVL(FSEG.PADRAOEMBVENDA, 1),
          'M'
        )
      )
    ),
    2
  ) AS MARG_OBJ,
  SUM(NVL(Y.ESTQMINIMOLOJA, 0)) AS EST_MIN,
  SUM(NVL(Y.ESTQMAXIMOLOJA, 0)) AS EST_MAX,
  MAX(NVL(VF.QTD_VENDIDA_TOTAL, 0)) AS QTD_VDA,
  SUM(NVL(Y.ESTQLOJA, 0)) AS EST_LOJA,
  MAX(NVL(CD.ESTOQUE_CD, 0)) AS EST_CD,
  MAX(NVL(CD.QTD_PENDENTE_EXPEDIR_CD, 0)) AS PEND_CD,
  MAX(NVL(CD.QTD_ULTIMA_COMPRA_CD, 0)) AS QTD_ULT_COMP,
  TO_CHAR(MAX(CD.DATA_ULTIMA_COMPRA_CD), 'DD/MM/YYYY') AS DT_ULT_COMP,
  '___________' AS "Comprar"
FROM MAP_PRODUTO A
INNER JOIN MRL_PRODUTOEMPRESA Y ON A.SEQPRODUTO = Y.SEQPRODUTO
LEFT JOIN MAP_FAMDIVISAO FD ON A.SEQFAMILIA = FD.SEQFAMILIA AND FD.NRODIVISAO = 1
LEFT JOIN MAX_COMPRADOR COMP ON COMP.SEQCOMPRADOR = FD.SEQCOMPRADOR
LEFT JOIN (
  SELECT Y1.SEQPRODUTO,
         ROUND(NVL(Y1.CMULTVLRNF, 0), 2) AS PRECO_CUSTO
    FROM MRL_PRODUTOEMPRESA Y1
   WHERE Y1.NROEMPRESA = 15
) C3 ON C3.SEQPRODUTO = A.SEQPRODUTO
LEFT JOIN (
  SELECT YCD.SEQPRODUTO,
         MAX(ROUND(NVL(YCD.CMULTVLRNF, 0), 2)) AS PRECO_CUSTO_CD
    FROM MRL_PRODUTOEMPRESA YCD
   WHERE YCD.NROEMPRESA IN (15, 16)
   GROUP BY YCD.SEQPRODUTO
) CD_CST ON CD_CST.SEQPRODUTO = A.SEQPRODUTO
LEFT JOIN (
  SELECT YLJ.SEQPRODUTO,
         MAX(ROUND(NVL(YLJ.CMULTVLRNF, 0), 2)) AS PRECO_CUSTO_LJ
    FROM MRL_PRODUTOEMPRESA YLJ
   WHERE YLJ.NROEMPRESA IN (3, 11)
   GROUP BY YLJ.SEQPRODUTO
) LJ_CST ON LJ_CST.SEQPRODUTO = A.SEQPRODUTO
LEFT JOIN (
  SELECT F.SEQFAMILIA,
       MAX(F.SEQFORNECEDOR) AS CODIGO_FORNECEDOR,
       MAX(P.NOMERAZAO) AS FORNECEDOR_PRINCIPAL
  FROM MAP_FAMFORNEC F
  INNER JOIN GE_PESSOA P ON P.SEQPESSOA = F.SEQFORNECEDOR
  WHERE F.PRINCIPAL = 'S'
  GROUP BY F.SEQFAMILIA
) FP ON FP.SEQFAMILIA = A.SEQFAMILIA
LEFT JOIN (
  SELECT X.SEQFAMILIA,
       MAX(Y2.CATEGORIA) AS SUBGRUPO
  FROM MAP_FAMDIVCATEG X
  INNER JOIN MAP_CATEGORIA Y2 ON X.SEQCATEGORIA = Y2.SEQCATEGORIA
  WHERE Y2.NIVELHIERARQUIA = 4
    AND X.NRODIVISAO = 1
    AND X.STATUS = 'A'
  GROUP BY X.SEQFAMILIA
) SUB ON SUB.SEQFAMILIA = A.SEQFAMILIA
LEFT JOIN (
  SELECT SEG.SEQPRODUTO,
       MAX(ROUND(NVL(NULLIF(SEG.PRECOVALIDPROMOC, 0), SEG.PRECOVALIDNORMAL), 2)) AS PRECO_VENDA
  FROM MRL_PRODEMPSEG SEG
  WHERE SEG.NROEMPRESA = 3
    AND SEG.QTDEMBALAGEM = 1
  GROUP BY SEG.SEQPRODUTO
) PV ON PV.SEQPRODUTO = A.SEQPRODUTO
LEFT JOIN MAX_EMPRESA EMP3 ON EMP3.NROEMPRESA = 3
LEFT JOIN MAD_FAMSEGMENTO FSEG ON FSEG.SEQFAMILIA = A.SEQFAMILIA AND FSEG.NROSEGMENTO = EMP3.NROSEGMENTOPRINC
LEFT JOIN (
  SELECT X.SEQPRODUTO,
         X.MARGEM_OBJETIVA
    FROM (
      SELECT E.SEQDETALHE2 AS SEQPRODUTO,
             NVL(E.MARGEMCADASTRO, 0) AS MARGEM_OBJETIVA,
             1 AS ORDEM_FONTE,
             ROW_NUMBER() OVER (
               PARTITION BY E.SEQDETALHE2
               ORDER BY E.SEQCONSULTA DESC
             ) AS RN
        FROM MBI_TABCDISTRIB E
        WHERE E.SEQDETALHE2 IS NOT NULL
          AND NVL(E.MARGEMCADASTRO, 0) > 0
      UNION ALL
      SELECT E.SEQDETALHE2 AS SEQPRODUTO,
             NVL(E.MARGEMCADASTRO, 0) AS MARGEM_OBJETIVA,
             2 AS ORDEM_FONTE,
             ROW_NUMBER() OVER (
               PARTITION BY E.SEQDETALHE2
               ORDER BY E.SEQCONSULTA DESC
             ) AS RN
        FROM MBI_TABCESTOQUE E
        WHERE E.SEQDETALHE2 IS NOT NULL
          AND NVL(E.MARGEMCADASTRO, 0) > 0
    ) X
   WHERE X.RN = 1
     AND NOT EXISTS (
       SELECT 1
         FROM (
           SELECT D.SEQDETALHE2 AS SEQPRODUTO,
                  1 AS ORDEM_FONTE,
                  ROW_NUMBER() OVER (
                    PARTITION BY D.SEQDETALHE2
                    ORDER BY D.SEQCONSULTA DESC
                  ) AS RN
             FROM MBI_TABCDISTRIB D
            WHERE D.SEQDETALHE2 IS NOT NULL
              AND NVL(D.MARGEMCADASTRO, 0) > 0
           UNION ALL
           SELECT E2.SEQDETALHE2 AS SEQPRODUTO,
                  2 AS ORDEM_FONTE,
                  ROW_NUMBER() OVER (
                    PARTITION BY E2.SEQDETALHE2
                    ORDER BY E2.SEQCONSULTA DESC
                  ) AS RN
             FROM MBI_TABCESTOQUE E2
            WHERE E2.SEQDETALHE2 IS NOT NULL
              AND NVL(E2.MARGEMCADASTRO, 0) > 0
         ) Y
        WHERE Y.SEQPRODUTO = X.SEQPRODUTO
          AND Y.RN = 1
          AND Y.ORDEM_FONTE < X.ORDEM_FONTE
     )
) MOBJ ON MOBJ.SEQPRODUTO = A.SEQPRODUTO
INNER JOIN (
  SELECT SEQPRODUTO,
       SUM(QTDVDA) AS QTD_VENDIDA_TOTAL
  FROM MRL_PRODVENDADIA
  WHERE DTAVDA BETWEEN :DT1 AND :DT2
    AND NROEMPRESA IN (1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 14, 17, 18)
    AND (:NR1 = '0' OR NROEMPRESA = TO_NUMBER(:NR1))
  GROUP BY SEQPRODUTO
) VF ON VF.SEQPRODUTO = A.SEQPRODUTO
LEFT JOIN (
  SELECT SEQPRODUTO,
       SUM(NVL(ESTQLOJA, 0) + NVL(ESTQDEPOSITO, 0) - (NVL(QTDRESERVADAVDA, 0) + NVL(QTDRESERVADARECEB, 0) + NVL(QTDRESERVADAFIXA, 0))) AS ESTOQUE_CD,
       SUM(NVL(QTDPENDPEDEXPED, 0)) AS QTD_PENDENTE_EXPEDIR_CD,
       MAX(DTAULTCOMPRA) AS DATA_ULTIMA_COMPRA_CD,
       MAX(NVL(QTDULTCOMPRA, 0)) AS QTD_ULTIMA_COMPRA_CD
  FROM MRL_PRODUTOEMPRESA
  WHERE NROEMPRESA IN (15, 16, 50)
  GROUP BY SEQPRODUTO
) CD ON CD.SEQPRODUTO = A.SEQPRODUTO
WHERE Y.NROEMPRESA IN (1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 14, 17, 18)
  AND (:NR1 = '0' OR Y.NROEMPRESA = TO_NUMBER(:NR1))
  AND (:NR2 = '0' OR A.SEQPRODUTO = TO_NUMBER(:NR2))
  AND Y.STATUSCOMPRA = 'A'
  AND (:LT2 = '0' OR FP.CODIGO_FORNECEDOR = TO_NUMBER(:LT2))
  AND ((:LS3 = '0 - TODOS') OR NVL(FD.SEQCOMPRADOR, 0) = TO_NUMBER(SUBSTR(:LS3, 1, INSTR(:LS3, ' - ') - 1)))
GROUP BY
  NVL(TO_CHAR(FP.CODIGO_FORNECEDOR), '0') || ' - ' || NVL(FP.FORNECEDOR_PRINCIPAL, 'SEM DESCRICAO'),
  SUB.SUBGRUPO,
  A.SEQPRODUTO,
  A.DESCCOMPLETA
ORDER BY
  SUB.SUBGRUPO ASC,
  QTD_VDA DESC
