SELECT
    SUB.SUBGRUPO,
    A.SEQPRODUTO AS CODIGO_PRODUTO,
    A.DESCCOMPLETA AS DESCRICAO_PRODUTO,
    MAX(NVL((SELECT MAX(ROUND(NVL(NULLIF(SEG.PRECOVALIDPROMOC, 0), SEG.PRECOVALIDNORMAL), 2))
             FROM MRL_PRODEMPSEG SEG 
             WHERE SEG.SEQPRODUTO = A.SEQPRODUTO 
               AND SEG.NROEMPRESA = 1 
               AND SEG.QTDEMBALAGEM = 1), 0)) AS PRECO_VENDA,
    MAX(FD.PADRAOEMBCOMPRA) AS EMBALAGEM,
    SUM(NVL(VND.QTD_VENDIDA, 0)) AS QTD_VENDIDA,
    SUM(NVL(Y.ESTQLOJA, 0)) AS ESTOQUE_LOJA,
    MAX(NVL(CD.ESTOQUE_CD, 0)) AS ESTOQUE_DEPOSITO,
    SUM(NVL(Y.ESTQMINIMOLOJA, 0)) AS ESTOQUE_MINIMO,
    SUM(NVL(Y.ESTQMAXIMOLOJA, 0)) AS ESTOQUE_MAXIMO
FROM MAP_PRODUTO A
INNER JOIN MRL_PRODUTOEMPRESA Y ON A.SEQPRODUTO = Y.SEQPRODUTO
LEFT JOIN MAP_FAMDIVISAO FD ON A.SEQFAMILIA = FD.SEQFAMILIA AND FD.NRODIVISAO = 1
LEFT JOIN (
    SELECT X.SEQFAMILIA, MAX(Y2.CATEGORIA) AS SUBGRUPO
    FROM MAP_FAMDIVCATEG X
    INNER JOIN MAP_CATEGORIA Y2 ON X.SEQCATEGORIA = Y2.SEQCATEGORIA
    WHERE Y2.NIVELHIERARQUIA = 4 AND X.NRODIVISAO = 1 AND X.STATUS = 'A'
    GROUP BY X.SEQFAMILIA
) SUB ON SUB.SEQFAMILIA = A.SEQFAMILIA
LEFT JOIN (
    SELECT SEQPRODUTO, NROEMPRESA, SUM(QTDVDA) AS QTD_VENDIDA
    FROM MRL_PRODVENDADIA
    WHERE DTAVDA BETWEEN TO_DATE('05/04/2026', 'DD/MM/YYYY') AND TO_DATE('06/04/2026', 'DD/MM/YYYY')
    GROUP BY SEQPRODUTO, NROEMPRESA
) VND ON VND.SEQPRODUTO = A.SEQPRODUTO AND VND.NROEMPRESA = Y.NROEMPRESA
LEFT JOIN (
    SELECT SEQPRODUTO, 
           SUM(NVL(ESTQLOJA, 0) + NVL(ESTQDEPOSITO, 0) - (NVL(QTDRESERVADAVDA, 0) + NVL(QTDRESERVADARECEB, 0) + NVL(QTDRESERVADAFIXA, 0))) AS ESTOQUE_CD
    FROM MRL_PRODUTOEMPRESA
    WHERE NROEMPRESA IN (15, 16, 50)
    GROUP BY SEQPRODUTO
) CD ON CD.SEQPRODUTO = A.SEQPRODUTO
WHERE Y.NROEMPRESA IN (1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 14, 17, 18)
  AND NOT EXISTS (
      SELECT 1 
      FROM MAP_FAMDIVCATEG XF
      INNER JOIN MAP_CATEGORIA YF ON XF.SEQCATEGORIA = YF.SEQCATEGORIA
      WHERE XF.SEQFAMILIA = A.SEQFAMILIA 
        AND YF.NIVELHIERARQUIA = 1
        AND (
            UPPER(YF.CATEGORIA) IN ('A CLASSIFICAR', 'ALMOXARIFADO', 'INATIVAR')
            OR UPPER(YF.CATEGORIA) LIKE 'SERVIC%'
        )
  )
GROUP BY
    SUB.SUBGRUPO,
    A.SEQPRODUTO,
    A.DESCCOMPLETA
ORDER BY SUB.SUBGRUPO, A.DESCCOMPLETA
