SELECT
  TO_CHAR(FP.CODIGO_FORNECEDOR) AS CODIGO_FORNECEDOR,
  NVL(FP.FORNECEDOR_PRINCIPAL, 'SEM DESCRICAO') AS FORNECEDOR,
  NVL(COMP.COMPRADOR, 'SEM GESTOR') AS COMPRADOR,
  COUNT(DISTINCT A.SEQPRODUTO) AS QTD_SKU,
  'R$ ' || TO_CHAR(ROUND(SUM(NVL(VF.QTD_VENDIDA_TOTAL, 0) * NVL(PV.PRECO_VENDA, 0)), 2), '999G999G999G990D00') AS VLR_VENDA_TOTAL,
  'R$ ' || TO_CHAR(ROUND(SUM(NVL(COMPRA.VLR_COMPRADO_TOTAL, 0)), 2), '999G999G999G990D00') AS VLR_COMPRA_TOTAL
FROM MAP_PRODUTO A
LEFT JOIN MAP_FAMDIVISAO FD ON A.SEQFAMILIA = FD.SEQFAMILIA AND FD.NRODIVISAO = 1
LEFT JOIN MAX_COMPRADOR COMP ON COMP.SEQCOMPRADOR = FD.SEQCOMPRADOR
LEFT JOIN (
  SELECT F.SEQFAMILIA,
         MAX(F.SEQFORNECEDOR) AS CODIGO_FORNECEDOR,
         MAX(P.NOMERAZAO) AS FORNECEDOR_PRINCIPAL
  FROM MAP_FAMFORNEC F
  INNER JOIN GE_PESSOA P ON P.SEQPESSOA = F.SEQFORNECEDOR
  WHERE F.PRINCIPAL = 'S'
  GROUP BY F.SEQFAMILIA
) FP ON FP.SEQFAMILIA = A.SEQFAMILIA
LEFT JOIN (
  SELECT SEG.SEQPRODUTO,
         MAX(ROUND(NVL(NULLIF(SEG.PRECOVALIDPROMOC, 0), SEG.PRECOVALIDNORMAL), 2)) AS PRECO_VENDA
  FROM MRL_PRODEMPSEG SEG
  WHERE SEG.NROEMPRESA = 3
    AND SEG.QTDEMBALAGEM = 1
  GROUP BY SEG.SEQPRODUTO
) PV ON PV.SEQPRODUTO = A.SEQPRODUTO
INNER JOIN (
  SELECT SEQPRODUTO,
         SUM(QTDVDA) AS QTD_VENDIDA_TOTAL
  FROM MRL_PRODVENDADIA
  WHERE DTAVDA BETWEEN :DT1 AND :DT2
    AND NROEMPRESA IN (1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 14, 17, 18)
  GROUP BY SEQPRODUTO
) VF ON VF.SEQPRODUTO = A.SEQPRODUTO
LEFT JOIN (
  SELECT I.SEQPRODUTO,
         SUM(NVL(I.VLRITEM, 0)) AS VLR_COMPRADO_TOTAL
  FROM MLFV_BASENFE N
  INNER JOIN MFLV_BASEDFITEM I
      ON I.NROEMPRESA = N.NROEMPRESA
     AND I.SEQNF = N.SEQNF
     AND I.TIPNOTAFISCAL = N.TIPNOTAFISCAL
     AND I.SERIEDF = N.SERIENF
     AND I.NUMERODF = N.NUMERONF
     AND I.SEQPESSOA = N.SEQPESSOA
  WHERE N.TIPNOTAFISCAL = 'E'
    AND N.CODGERALOPER IN (200, 202)
    AND N.NROEMPRESA IN (1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 14, 17, 18)
    AND N.DTAEMISSAO >= TRUNC(:DT1)
    AND N.DTAEMISSAO < TRUNC(:DT2) + 1
  GROUP BY I.SEQPRODUTO
) COMPRA ON COMPRA.SEQPRODUTO = A.SEQPRODUTO
WHERE
  NVL(UPPER(TRIM(:LT2)), 'D') = 'D'
  AND (
    #LS1 = '0 - TODOS'
    OR #LS1 LIKE TO_CHAR(NVL(FD.SEQCOMPRADOR, 0)) || ' - %'
  )
  AND NOT EXISTS (
    SELECT 1
    FROM MAP_FAMDIVCATEG XF
    INNER JOIN MAP_CATEGORIA YF ON XF.SEQCATEGORIA = YF.SEQCATEGORIA
    WHERE XF.SEQFAMILIA = A.SEQFAMILIA
      AND YF.NIVELHIERARQUIA = 1
      AND (
        UPPER(YF.CATEGORIA) IN ('A CLASSIFICAR', 'ALMOXARIFADO', 'INATIVAR')
        OR UPPER(YF.CATEGORIA) LIKE 'SERVIC%'
      )
  )
GROUP BY
  FP.CODIGO_FORNECEDOR,
  FP.FORNECEDOR_PRINCIPAL,
  FD.SEQCOMPRADOR,
  COMP.COMPRADOR

UNION ALL

SELECT
  TO_CHAR(FP.CODIGO_FORNECEDOR) AS CODIGO_FORNECEDOR,
  NVL(FP.FORNECEDOR_PRINCIPAL, 'SEM DESCRICAO') AS FORNECEDOR,
  'CONSOLIDADO' AS COMPRADOR,
  COUNT(DISTINCT A.SEQPRODUTO) AS QTD_SKU,
  'R$ ' || TO_CHAR(ROUND(SUM(NVL(VF.QTD_VENDIDA_TOTAL, 0) * NVL(PV.PRECO_VENDA, 0)), 2), '999G999G999G990D00') AS VLR_VENDA_TOTAL,
  'R$ ' || TO_CHAR(ROUND(SUM(NVL(COMPRA.VLR_COMPRADO_TOTAL, 0)), 2), '999G999G999G990D00') AS VLR_COMPRA_TOTAL
FROM MAP_PRODUTO A
LEFT JOIN MAP_FAMDIVISAO FD ON A.SEQFAMILIA = FD.SEQFAMILIA AND FD.NRODIVISAO = 1
LEFT JOIN MAX_COMPRADOR COMP ON COMP.SEQCOMPRADOR = FD.SEQCOMPRADOR
LEFT JOIN (
  SELECT F.SEQFAMILIA,
         MAX(F.SEQFORNECEDOR) AS CODIGO_FORNECEDOR,
         MAX(P.NOMERAZAO) AS FORNECEDOR_PRINCIPAL
  FROM MAP_FAMFORNEC F
  INNER JOIN GE_PESSOA P ON P.SEQPESSOA = F.SEQFORNECEDOR
  WHERE F.PRINCIPAL = 'S'
  GROUP BY F.SEQFAMILIA
) FP ON FP.SEQFAMILIA = A.SEQFAMILIA
LEFT JOIN (
  SELECT SEG.SEQPRODUTO,
         MAX(ROUND(NVL(NULLIF(SEG.PRECOVALIDPROMOC, 0), SEG.PRECOVALIDNORMAL), 2)) AS PRECO_VENDA
  FROM MRL_PRODEMPSEG SEG
  WHERE SEG.NROEMPRESA = 3
    AND SEG.QTDEMBALAGEM = 1
  GROUP BY SEG.SEQPRODUTO
) PV ON PV.SEQPRODUTO = A.SEQPRODUTO
INNER JOIN (
  SELECT SEQPRODUTO,
         SUM(QTDVDA) AS QTD_VENDIDA_TOTAL
  FROM MRL_PRODVENDADIA
  WHERE DTAVDA BETWEEN :DT1 AND :DT2
    AND NROEMPRESA IN (1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 14, 17, 18)
  GROUP BY SEQPRODUTO
) VF ON VF.SEQPRODUTO = A.SEQPRODUTO
LEFT JOIN (
  SELECT I.SEQPRODUTO,
         SUM(NVL(I.VLRITEM, 0)) AS VLR_COMPRADO_TOTAL
  FROM MLFV_BASENFE N
  INNER JOIN MFLV_BASEDFITEM I
      ON I.NROEMPRESA = N.NROEMPRESA
     AND I.SEQNF = N.SEQNF
     AND I.TIPNOTAFISCAL = N.TIPNOTAFISCAL
     AND I.SERIEDF = N.SERIENF
     AND I.NUMERODF = N.NUMERONF
     AND I.SEQPESSOA = N.SEQPESSOA
  WHERE N.TIPNOTAFISCAL = 'E'
    AND N.CODGERALOPER IN (200, 202)
    AND N.NROEMPRESA IN (1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 14, 17, 18)
    AND N.DTAEMISSAO >= TRUNC(:DT1)
    AND N.DTAEMISSAO < TRUNC(:DT2) + 1
  GROUP BY I.SEQPRODUTO
) COMPRA ON COMPRA.SEQPRODUTO = A.SEQPRODUTO
WHERE
  NVL(UPPER(TRIM(:LT2)), 'D') = 'C'
  AND (
    #LS1 = '0 - TODOS'
    OR #LS1 LIKE TO_CHAR(NVL(FD.SEQCOMPRADOR, 0)) || ' - %'
  )
  AND NOT EXISTS (
    SELECT 1
    FROM MAP_FAMDIVCATEG XF
    INNER JOIN MAP_CATEGORIA YF ON XF.SEQCATEGORIA = YF.SEQCATEGORIA
    WHERE XF.SEQFAMILIA = A.SEQFAMILIA
      AND YF.NIVELHIERARQUIA = 1
      AND (
        UPPER(YF.CATEGORIA) IN ('A CLASSIFICAR', 'ALMOXARIFADO', 'INATIVAR')
        OR UPPER(YF.CATEGORIA) LIKE 'SERVIC%'
      )
  )
GROUP BY
  FP.CODIGO_FORNECEDOR,
  FP.FORNECEDOR_PRINCIPAL
ORDER BY
  5 DESC,
  2 ASC
