SELECT
    SUB.SUBGRUPO,
    A.SEQPRODUTO AS CODIGO_PRODUTO,
    A.DESCCOMPLETA AS DESCRICAO_PRODUTO,
    MAX(FD.PADRAOEMBCOMPRA) AS EMBALAGEM,
    MAX(NVL(VF.QTD_VENDIDA_TOTAL, 0)) AS QTD_VENDIDA,
    SUM(NVL(Y.ESTQLOJA, 0)) AS ESTOQUE_LOJA,
    MAX(NVL(CD.ESTOQUE_CD, 0)) AS ESTOQUE_CD,
    MAX(NVL(CD.QTD_PENDENTE_EXPEDIR_CD, 0)) AS PENDENTE_EXPEDIR_CD,
    TO_CHAR(MAX(CD.DATA_ULTIMA_COMPRA_CD), 'DD/MM/YYYY') AS DATA_ULTIMA_COMPRA_CD,
    MAX(NVL(CD.QTD_ULTIMA_COMPRA_CD, 0)) AS QTD_ULTIMA_COMPRA_CD
FROM MAP_PRODUTO A
INNER JOIN MRL_PRODUTOEMPRESA Y ON A.SEQPRODUTO = Y.SEQPRODUTO
LEFT JOIN MAP_FAMDIVISAO FD ON A.SEQFAMILIA = FD.SEQFAMILIA AND FD.NRODIVISAO = 1
LEFT JOIN MAX_COMPRADOR COMP ON COMP.SEQCOMPRADOR = FD.SEQCOMPRADOR
LEFT JOIN (
    SELECT F.SEQFAMILIA,
           MAX(F.SEQFORNECEDOR) AS CODIGO_FORNECEDOR,
           MAX(P.NOMERAZAO) AS FORNECEDOR_PRINCIPAL
    FROM MAP_FAMFORNEC F
    INNER JOIN GE_PESSOA P ON P.SEQPESSOA = F.SEQFORNECEDOR
    WHERE F.PRINCIPAL = 'S'
    GROUP BY F.SEQFAMILIA
) FP ON FP.SEQFAMILIA = A.SEQFAMILIA
LEFT JOIN (
    SELECT X.SEQFAMILIA,
           MAX(Y2.CATEGORIA) AS SUBGRUPO
    FROM MAP_FAMDIVCATEG X
    INNER JOIN MAP_CATEGORIA Y2 ON X.SEQCATEGORIA = Y2.SEQCATEGORIA
    WHERE Y2.NIVELHIERARQUIA = 4
      AND X.NRODIVISAO = 1
      AND X.STATUS = 'A'
    GROUP BY X.SEQFAMILIA
) SUB ON SUB.SEQFAMILIA = A.SEQFAMILIA
INNER JOIN (
    SELECT SEQPRODUTO,
           SUM(QTDVDA) AS QTD_VENDIDA_TOTAL
    FROM MRL_PRODVENDADIA
    WHERE DTAVDA BETWEEN :DT1 AND :DT2
      AND NROEMPRESA IN (1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 14, 17, 18)
    GROUP BY SEQPRODUTO
    HAVING SUM(QTDVDA) > :NR1
) VF ON VF.SEQPRODUTO = A.SEQPRODUTO
LEFT JOIN (
    SELECT SEQPRODUTO,
           SUM(NVL(ESTQLOJA, 0) + NVL(ESTQDEPOSITO, 0) - (NVL(QTDRESERVADAVDA, 0) + NVL(QTDRESERVADARECEB, 0) + NVL(QTDRESERVADAFIXA, 0))) AS ESTOQUE_CD,
           SUM(NVL(QTDPENDPEDEXPED, 0)) AS QTD_PENDENTE_EXPEDIR_CD,
           MAX(DTAULTCOMPRA) AS DATA_ULTIMA_COMPRA_CD,
           MAX(NVL(QTDULTCOMPRA, 0)) AS QTD_ULTIMA_COMPRA_CD
    FROM MRL_PRODUTOEMPRESA
    WHERE NROEMPRESA IN (15, 16, 50)
    GROUP BY SEQPRODUTO
) CD ON CD.SEQPRODUTO = A.SEQPRODUTO
WHERE Y.NROEMPRESA IN (1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 14, 17, 18)
    AND (:LT2 = '0' OR FP.CODIGO_FORNECEDOR = TO_NUMBER(:LT2))
    AND (
        UPPER(NVL(TRIM(:LT3), 'TODOS')) = 'TODOS'
        OR UPPER(NVL(COMP.APELIDO, COMP.COMPRADOR)) = UPPER(TRIM(:LT3))
        OR UPPER(NVL(COMP.COMPRADOR, 'SEM GESTOR')) = UPPER(TRIM(:LT3))
    )
  AND NOT EXISTS (
      SELECT 1
      FROM MAP_FAMDIVCATEG XF
      INNER JOIN MAP_CATEGORIA YF ON XF.SEQCATEGORIA = YF.SEQCATEGORIA
      WHERE XF.SEQFAMILIA = A.SEQFAMILIA
        AND YF.NIVELHIERARQUIA = 1
        AND (
            UPPER(YF.CATEGORIA) IN ('A CLASSIFICAR', 'ALMOXARIFADO', 'INATIVAR')
            OR UPPER(YF.CATEGORIA) LIKE 'SERVIC%'
        )
  )
GROUP BY
    SUB.SUBGRUPO,
    A.SEQPRODUTO,
    A.DESCCOMPLETA
ORDER BY
    SUB.SUBGRUPO,
    QTD_VENDIDA DESC,
    DESCRICAO_PRODUTO