SELECT
    A.NROEMPRESA AS EMPRESA_DESTINO,
    B.SEQPRODUTO AS CODIGO_PRODUTO,
    C.DESCCOMPLETA AS DESCRICAO_PRODUTO,
    B.QTDSOLICITADA AS QUANTIDADE_PEDIDA,
    (NVL(D.ESTQLOJA, 0) + NVL(D.ESTQDEPOSITO, 0)) AS ESTOQUE_CD,
    A.USUINCLUSAO AS USUARIO_DIGITACAO,
    TO_CHAR(A.DTAHORINCLUSAO, 'DD/MM/YYYY') AS DATA_DIGITACAO,
    TO_CHAR(A.DTAHORINCLUSAO, 'HH24:MI:SS') AS HORA_DIGITACAO
FROM MSU_PEDIDOSUPRIM A
INNER JOIN MSU_PSITEMRECEBER B ON A.NROPEDIDOSUPRIM = B.NROPEDIDOSUPRIM 
                              AND A.NROEMPRESA = B.NROEMPRESA 
                              AND A.CENTRALLOJA = B.CENTRALLOJA
INNER JOIN MAP_PRODUTO C ON B.SEQPRODUTO = C.SEQPRODUTO
LEFT JOIN MRL_PRODUTOEMPRESA D ON B.SEQPRODUTO = D.SEQPRODUTO AND D.NROEMPRESA = :NR2
WHERE A.DTAHORINCLUSAO >= :DT1
  AND A.DTAHORINCLUSAO <  :DT2 + 1
  AND A.NROEMPRESA IN (1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 14, 15, 17, 18)
  AND (:LT1 = '0' OR TO_CHAR(A.NROEMPRESA) IN (
      SELECT TRIM(REGEXP_SUBSTR(:LT1, '[^,]+', 1, LEVEL))
      FROM DUAL
      CONNECT BY REGEXP_SUBSTR(:LT1, '[^,]+', 1, LEVEL) IS NOT NULL
  ))
  AND (:NR1 = 0 OR B.SEQPRODUTO = :NR1)
  AND (:NR2 = 0 OR A.SEQFORNECEDOR = :NR2)
  AND (:LT2 = '0' OR UPPER(A.USUINCLUSAO) NOT IN (
      SELECT UPPER(TRIM(REGEXP_SUBSTR(:LT2, '[^,]+', 1, LEVEL)))
      FROM DUAL
      CONNECT BY REGEXP_SUBSTR(:LT2, '[^,]+', 1, LEVEL) IS NOT NULL
  ))
ORDER BY A.DTAHORINCLUSAO DESC
