SELECT
    A.SEQPRODUTO AS CODIGO_PRODUTO,
    A.DESCCOMPLETA AS DESCRICAO,
    DEP.CATEGORIA AS DEPARTAMENTO,
    NVL(FPUL.EMBALAGEM || ' ' || FPUL.QTDEMBALAGEM, 'N/C') AS PULMAO_EMB,
    NVL(PUL.PALETELASTRO, 0) AS PULMAO_LASTRO,
    NVL(PUL.PALETEALTURA, 0) AS PULMAO_ALTURA,
    NVL(FSEL.EMBALAGEM || ' ' || FSEL.QTDEMBALAGEM, 'N/C') AS SELECAO_EMB,
    NVL(SEL.PALETELASTRO, 0) AS SELECAO_LASTRO,
    NVL(SEL.PALETEALTURA, 0) AS SELECAO_ALTURA
FROM MAP_PRODUTO A
INNER JOIN MRL_PRODUTOEMPRESA C ON A.SEQPRODUTO = C.SEQPRODUTO
LEFT JOIN (
    SELECT X.SEQFAMILIA, Y.CATEGORIA 
    FROM MAP_FAMDIVCATEG X 
    INNER JOIN MAP_CATEGORIA Y ON X.SEQCATEGORIA = Y.SEQCATEGORIA 
    WHERE Y.NIVELHIERARQUIA = 1 AND X.NRODIVISAO = 1 AND Y.NRODIVISAO = 1 AND X.STATUS = 'A' AND Y.STATUSCATEGOR = 'A'
) DEP ON DEP.SEQFAMILIA = A.SEQFAMILIA
LEFT JOIN (
    SELECT MP.SEQPRODUTO, MP.NROEMPRESA, MAX(MP.QTDEMBALAGEM) AS QTDEMBALAGEM, MAX(MP.PALETELASTRO) AS PALETELASTRO, MAX(MP.PALETEALTURA) AS PALETEALTURA
    FROM MAD_PRODESPENDERECO MP
    INNER JOIN MAD_ESPECIEENDERECO ME ON MP.CODESPECENDERECO = ME.CODESPECENDERECO AND MP.NROEMPRESA = ME.NROEMPRESA
    WHERE UPPER(ME.DESCRICAO) LIKE '%PULM%'
    GROUP BY MP.SEQPRODUTO, MP.NROEMPRESA
) PUL ON PUL.SEQPRODUTO = A.SEQPRODUTO AND PUL.NROEMPRESA = C.NROEMPRESA
LEFT JOIN MAP_FAMEMBALAGEM FPUL ON FPUL.SEQFAMILIA = A.SEQFAMILIA AND FPUL.QTDEMBALAGEM = PUL.QTDEMBALAGEM
LEFT JOIN (
    SELECT MP.SEQPRODUTO, MP.NROEMPRESA, MAX(MP.QTDEMBALAGEM) AS QTDEMBALAGEM, MAX(MP.PALETELASTRO) AS PALETELASTRO, MAX(MP.PALETEALTURA) AS PALETEALTURA
    FROM MAD_PRODESPENDERECO MP
    INNER JOIN MAD_ESPECIEENDERECO ME ON MP.CODESPECENDERECO = ME.CODESPECENDERECO AND MP.NROEMPRESA = ME.NROEMPRESA
    WHERE UPPER(ME.DESCRICAO) LIKE '%INVERSA%'
    GROUP BY MP.SEQPRODUTO, MP.NROEMPRESA
) SEL ON SEL.SEQPRODUTO = A.SEQPRODUTO AND SEL.NROEMPRESA = C.NROEMPRESA
LEFT JOIN MAP_FAMEMBALAGEM FSEL ON FSEL.SEQFAMILIA = A.SEQFAMILIA AND FSEL.QTDEMBALAGEM = SEL.QTDEMBALAGEM
WHERE C.NROEMPRESA = 15
  AND C.STATUSCOMPRA = 'A'
  AND UPPER(DEP.CATEGORIA) NOT IN ('INATIVAR', 'A CLASSIFICAR', 'ALMOXARIFADO', 'NAO ALIMENTO', 'SERVICOS')
ORDER BY A.DESCCOMPLETA
