SELECT * FROM (
    WITH CTE_EMPRESAS AS (
        SELECT /*+ MATERIALIZE */
            E.NROEMPRESA
        FROM MAX_EMPRESA E
        WHERE E.NROEMPRESA IN (#LT1)
    ),
    CTE_DEPARTAMENTO AS (
        SELECT /*+ MATERIALIZE */
            X.SEQFAMILIA,
            MAX(Y.CATEGORIA) AS DEPARTAMENTO
        FROM MAP_FAMDIVCATEG X
        INNER JOIN MAP_CATEGORIA Y
            ON Y.SEQCATEGORIA = X.SEQCATEGORIA
           AND Y.NRODIVISAO = X.NRODIVISAO
           AND Y.STATUSCATEGOR = 'A'
        WHERE Y.TIPCATEGORIA = 'M'
          AND Y.NIVELHIERARQUIA = 1
          AND X.NRODIVISAO = 1
          AND X.STATUS = 'A'
        GROUP BY X.SEQFAMILIA
    ),
    CTE_WMS_ENDERECO AS (
        SELECT /*+ MATERIALIZE */
            X.NROEMPRESA,
            X.SEQPRODUTO,
            SUM(CASE WHEN X.ESPECIEENDERECO = 'A' THEN NVL(X.QTDATUAL, 0) ELSE 0 END) AS QTD_APANHA,
            SUM(CASE WHEN X.ESPECIEENDERECO = 'P' THEN NVL(X.QTDATUAL, 0) ELSE 0 END) AS QTD_PULMAO,
            SUM(CASE WHEN NVL(X.ESPECIEENDERECO, 'X') NOT IN ('A', 'P') THEN NVL(X.QTDATUAL, 0) ELSE 0 END) AS QTD_OUTROS_END,
            SUM(CASE WHEN X.ESPECIEENDERECO IN ('A', 'P') THEN NVL(X.QTDATUAL, 0) ELSE 0 END) AS QTD_WMS_REAL,
            SUM(NVL(X.QTDATUAL, 0)) AS QTD_TOTAL_WMS
        FROM MLO_ENDERECO X
        WHERE X.NROEMPRESA IN (#LT1)
          AND X.SEQPRODUTO > 0
        GROUP BY X.NROEMPRESA, X.SEQPRODUTO
    ),
    CTE_RECEBIMENTO_PENDENTE AS (
        SELECT /*+ MATERIALIZE */
            RP.NROEMPRESA,
            RP.SEQPRODUTO,
            SUM(NVL(RP.QTDTOTALDOCUMENTO, RP.QTDDOCUMENTO)) AS QTD_RECEB_PENDENTE
        FROM MLO_CARGARECEB C
        INNER JOIN MLO_CARGARECPROD RP 
            ON RP.NROCARGA = C.NROCARGA 
           AND RP.NROEMPRESA = C.NROEMPRESA
        WHERE C.NROEMPRESA IN (#LT1)
          AND (
              (C.STATUSCARGA = 'L' AND C.STATUSARMAZENAGEM != 'A')
              OR
              (C.STATUSCARGA != 'L' AND C.STATUSARMAZENAGEM IN ('R', 'A'))
          )
        GROUP BY RP.NROEMPRESA, RP.SEQPRODUTO
    ),
    CTE_SEPARACAO_PENDENTE AS (
        SELECT /*+ MATERIALIZE */
            EP.NROEMPRESA,
            EP.SEQPRODUTO,
            SUM(NVL(EP.QTDEMBSOLICITADA, 0) * NVL(EP.QTDEMBALAGEM, 1)) AS QTD_SEPARACAO_PENDENTE
        FROM MLO_CARGAEXPED E
        INNER JOIN MLO_CARGAEXPPROD EP
            ON EP.NROCARGA = E.NROCARGA
           AND EP.NROEMPRESA = E.NROEMPRESA
        WHERE E.NROEMPRESA IN (#LT1)
          AND E.STATUSCARGA = 'L'
        GROUP BY EP.NROEMPRESA, EP.SEQPRODUTO
    ),
    CTE_ESTOQUE_ERP AS (
        SELECT /*+ MATERIALIZE */
            PE.NROEMPRESA,
            PE.SEQPRODUTO,
            NVL(PE.ESTQDEPOSITO, 0) AS ESTQ_DEPOSITO_ERP,
            NVL(PE.ESTQTROCA, 0) AS ESTQ_TROCA_ERP,
            NVL(PE.ESTQOUTRO, 0) AS ESTQ_OUTRO_ERP,
            (NVL(PE.ESTQDEPOSITO, 0) + NVL(PE.ESTQTROCA, 0) + NVL(PE.ESTQOUTRO, 0)) AS ESTQ_TOTAL_ERP,
            (NVL(PE.QTDRESERVADAVDA, 0) + NVL(PE.QTDRESERVADARECEB, 0) + NVL(PE.QTDRESERVADAFIXA, 0) + NVL(PE.QTDRESERVADAFISC, 0)) AS QTD_RESERVADA_ERP
        FROM MRL_PRODUTOEMPRESA PE
        WHERE PE.NROEMPRESA IN (#LT1)
    ),
    CTE_BASE_PRODUTOS AS (
        SELECT /*+ MATERIALIZE */
            DISTINCT
            COALESCE(E.NROEMPRESA, W.NROEMPRESA, R.NROEMPRESA, S.NROEMPRESA) AS NROEMPRESA,
            COALESCE(E.SEQPRODUTO, W.SEQPRODUTO, R.SEQPRODUTO, S.SEQPRODUTO) AS SEQPRODUTO
        FROM CTE_ESTOQUE_ERP E
        FULL OUTER JOIN CTE_WMS_ENDERECO W 
            ON W.NROEMPRESA = E.NROEMPRESA 
           AND W.SEQPRODUTO = E.SEQPRODUTO
        FULL OUTER JOIN CTE_RECEBIMENTO_PENDENTE R 
            ON R.NROEMPRESA = COALESCE(E.NROEMPRESA, W.NROEMPRESA) 
           AND R.SEQPRODUTO = COALESCE(E.SEQPRODUTO, W.SEQPRODUTO)
        FULL OUTER JOIN CTE_SEPARACAO_PENDENTE S 
            ON S.NROEMPRESA = COALESCE(E.NROEMPRESA, W.NROEMPRESA, R.NROEMPRESA) 
           AND S.SEQPRODUTO = COALESCE(E.SEQPRODUTO, W.SEQPRODUTO, R.SEQPRODUTO)
    ),
    CTE_CONSOLIDADO AS (
        SELECT /*+ MATERIALIZE */
            NVL(DEP.DEPARTAMENTO, 'SEM DEPARTAMENTO') AS DEPARTAMENTO,
            B.NROEMPRESA,
            B.SEQPRODUTO,
            PR.DESCCOMPLETA AS DESCRICAO_PRODUTO,
            NVL(E.ESTQ_DEPOSITO_ERP, 0) AS ESTQ_DEPOSITO_ERP,
            NVL(E.ESTQ_TROCA_ERP, 0) AS ESTQ_TROCA_ERP,
            NVL(E.ESTQ_TOTAL_ERP, 0) AS ESTQ_TOTAL_ERP,
            NVL(W.QTD_APANHA, 0) AS QTD_WMS_APANHA,
            NVL(W.QTD_PULMAO, 0) AS QTD_WMS_PULMAO,
            NVL(W.QTD_OUTROS_END, 0) AS QTD_WMS_OUTROS,
            NVL(W.QTD_WMS_REAL, 0) AS QTD_WMS_REAL,
            NVL(W.QTD_TOTAL_WMS, 0) AS QTD_TOTAL_WMS,
            NVL(R.QTD_RECEB_PENDENTE, 0) AS QTD_RECEB_PENDENTE,
            NVL(S.QTD_SEPARACAO_PENDENTE, 0) AS QTD_SEPARACAO_PENDENTE,
            (NVL(E.ESTQ_DEPOSITO_ERP, 0) - NVL(W.QTD_WMS_REAL, 0)) AS DIVERGENCIA_BRUTA,
            (NVL(E.ESTQ_DEPOSITO_ERP, 0) - (NVL(W.QTD_WMS_REAL, 0) + NVL(R.QTD_RECEB_PENDENTE, 0))) AS DIVERGENCIA_AJUSTADA
        FROM CTE_BASE_PRODUTOS B
        INNER JOIN CTE_EMPRESAS EMP ON EMP.NROEMPRESA = B.NROEMPRESA
        INNER JOIN MAP_PRODUTO PR ON PR.SEQPRODUTO = B.SEQPRODUTO
        LEFT JOIN CTE_DEPARTAMENTO DEP ON DEP.SEQFAMILIA = PR.SEQFAMILIA
        LEFT JOIN CTE_ESTOQUE_ERP E 
            ON E.NROEMPRESA = B.NROEMPRESA 
           AND E.SEQPRODUTO = B.SEQPRODUTO
        LEFT JOIN CTE_WMS_ENDERECO W 
            ON W.NROEMPRESA = B.NROEMPRESA 
           AND W.SEQPRODUTO = B.SEQPRODUTO
        LEFT JOIN CTE_RECEBIMENTO_PENDENTE R 
            ON R.NROEMPRESA = B.NROEMPRESA 
           AND R.SEQPRODUTO = B.SEQPRODUTO
        LEFT JOIN CTE_SEPARACAO_PENDENTE S 
            ON S.NROEMPRESA = B.NROEMPRESA 
           AND S.SEQPRODUTO = B.SEQPRODUTO
        WHERE (NVL(:NR1, 0) = 0 OR B.SEQPRODUTO = :NR1)
          AND (
              NVL(TRIM(:LS1), 'TODOS') IN ('TODOS', '')
              OR (INSTR(TRIM(:LS1), 'ALINHADO') > 0 AND (NVL(E.ESTQ_DEPOSITO_ERP, 0) - NVL(W.QTD_WMS_REAL, 0)) = 0)
              OR (INSTR(TRIM(:LS1), 'DIVERGENCIA') > 0 AND (NVL(E.ESTQ_DEPOSITO_ERP, 0) - NVL(W.QTD_WMS_REAL, 0)) != 0)
              OR (INSTR(TRIM(:LS1), 'SOBRA ERP') > 0 AND (NVL(E.ESTQ_DEPOSITO_ERP, 0) - NVL(W.QTD_WMS_REAL, 0)) > 0)
              OR (INSTR(TRIM(:LS1), 'SOBRA WMS') > 0 AND (NVL(E.ESTQ_DEPOSITO_ERP, 0) - NVL(W.QTD_WMS_REAL, 0)) < 0)
              OR (INSTR(TRIM(:LS1), 'RECEBIMENTO') > 0 AND NVL(R.QTD_RECEB_PENDENTE, 0) > 0)
          )
          AND (
              NVL(TRIM(:LT2), '0') IN ('0', 'NENHUM', '')
              OR NOT REGEXP_LIKE(
                  REPLACE(TRANSLATE(UPPER(NVL(DEP.DEPARTAMENTO, 'X')), 'ÁÉÍÓÚÀÈÌÒÙÃÕÂÊÎÔÛÇ', 'AEIOUAEIOUAOAEIOUC'), ' ', ''),
                  REPLACE(REPLACE(TRANSLATE(UPPER(TRIM(:LT2)), 'ÁÉÍÓÚÀÈÌÒÙÃÕÂÊÎÔÛÇ', 'AEIOUAEIOUAOAEIOUC'), ' ', ''), ',', '|'),
                  'i'
              )
          )
    )
    SELECT
        C.DEPARTAMENTO AS DEPTO,
        C.NROEMPRESA AS CD,
        C.SEQPRODUTO AS CODIGO,
        C.DESCRICAO_PRODUTO AS DESCRICAO,
        C.ESTQ_DEPOSITO_ERP AS ERP_DISP,
        C.ESTQ_TROCA_ERP AS ERP_TROCA,
        C.ESTQ_TOTAL_ERP AS ERP_TOTAL,
        C.QTD_WMS_APANHA AS WMS_APANHA,
        C.QTD_WMS_PULMAO AS WMS_PULMAO,
        C.QTD_WMS_OUTROS AS WMS_OUTROS,
        C.QTD_WMS_REAL AS WMS_REAL,
        C.QTD_TOTAL_WMS AS WMS_TOTAL,
        C.QTD_RECEB_PENDENTE AS REC_PEND,
        C.QTD_SEPARACAO_PENDENTE AS SEP_PEND,
        C.DIVERGENCIA_BRUTA AS DIF_BRUTA,
        C.DIVERGENCIA_AJUSTADA AS DIF_AJUST,
        CASE
            WHEN C.DIVERGENCIA_BRUTA = 0 THEN '01 - ALINHADO'
            WHEN C.QTD_RECEB_PENDENTE > 0 AND C.DIVERGENCIA_AJUSTADA = 0 THEN '02 - EM RECEBIMENTO'
            WHEN C.DIVERGENCIA_BRUTA > 0 THEN '03 - SOBRA ERP (FALTA WMS)'
            ELSE '04 - FALTA ERP (SOBRA WMS)'
        END AS STATUS
    FROM CTE_CONSOLIDADO C
    ORDER BY
        C.DEPARTAMENTO ASC,
        ABS(C.DIVERGENCIA_BRUTA) DESC,
        C.NROEMPRESA ASC,
        C.DESCRICAO_PRODUTO ASC
)
