SELECT * FROM (
    WITH CTE_CATEGORIAS AS (
        SELECT /*+ MATERIALIZE */
            X.SEQFAMILIA,
            MAX(CASE WHEN Y.NIVELHIERARQUIA = 1 THEN Y.SEQCATEGORIA END) AS SEQDEPARTAMENTO,
            MAX(CASE WHEN Y.NIVELHIERARQUIA = 1 THEN Y.CATEGORIA END) AS DEPARTAMENTO
        FROM MAP_FAMDIVCATEG X
        INNER JOIN MAP_CATEGORIA Y
            ON Y.SEQCATEGORIA = X.SEQCATEGORIA
           AND Y.NRODIVISAO = X.NRODIVISAO
           AND Y.STATUSCATEGOR = 'A'
        WHERE Y.TIPCATEGORIA = 'M'
          AND Y.NIVELHIERARQUIA = 1
          AND X.NRODIVISAO = 1
          AND X.STATUS = 'A'
        GROUP BY X.SEQFAMILIA
        HAVING MAX(CASE WHEN Y.NIVELHIERARQUIA = 1 THEN Y.CATEGORIA END) IS NOT NULL
           AND UPPER(MAX(CASE WHEN Y.NIVELHIERARQUIA = 1 THEN Y.CATEGORIA END)) NOT IN ('ALMOXARIFADO', 'A CLASSIFICAR', 'INATIVAR', 'SERVICOS')
    ),
    CTE_PRODUTOS AS (
        SELECT /*+ MATERIALIZE */
            P.SEQPRODUTO
        FROM MAP_PRODUTO P
        INNER JOIN CTE_CATEGORIAS CAT
            ON CAT.SEQFAMILIA = P.SEQFAMILIA
        INNER JOIN MAP_FAMDIVISAO FD
            ON FD.SEQFAMILIA = P.SEQFAMILIA
           AND FD.NRODIVISAO = 1
        WHERE FD.FINALIDADEFAMILIA = 'R'
    ),
    CTE_ESTOQUE AS (
        SELECT /*+ MATERIALIZE */
            PE.NROEMPRESA,
            ROUND(SUM(
                GREATEST(0, (NVL(PE.ESTQLOJA, 0) + NVL(PE.ESTQDEPOSITO, 0) - NVL(PE.QTDRESERVADAVDA, 0) - NVL(PE.QTDRESERVADARECEB, 0) - NVL(PE.QTDRESERVADAFIXA, 0)))
                * (
                    NVL(PE.CMULTVLRNF, 0)
                    + NVL(PE.CMULTIPI, 0)
                    - NVL(PE.CMULTCREDICMS, 0)
                    + NVL(PE.CMULTICMSST, 0)
                    + NVL(PE.CMULTDESPNF, 0)
                    + NVL(PE.CMULTDESPFORANF, 0)
                    - NVL(PE.CMULTDCTOFORANF, 0)
                    - NVL(PE.CMULTCREDPIS, 0)
                    - NVL(PE.CMULTCREDCOFINS, 0)
                    - NVL(PE.CMULTVLRVERBA, 0)
                )
            ), 2) AS VLR_ESTOQUE
        FROM MRL_PRODUTOEMPRESA PE
        INNER JOIN CTE_PRODUTOS PR
            ON PR.SEQPRODUTO = PE.SEQPRODUTO
        WHERE PE.NROEMPRESA IN (1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 14, 15, 17, 18)
        GROUP BY PE.NROEMPRESA
    ),
    CTE_VENDAS AS (
        SELECT /*+ MATERIALIZE */
            N.NROEMPRESA,
            ROUND(SUM(NVL(I.VLRITEM, 0) + NVL(I.VLRIPI, 0) + NVL(I.VLRICMSST, 0)), 2) AS VLR_VENDA
        FROM MLFV_BASENFE N
        INNER JOIN MFLV_BASEDFITEM I
            ON I.NROEMPRESA = N.NROEMPRESA
           AND I.SEQNF = N.SEQNF
           AND I.TIPNOTAFISCAL = N.TIPNOTAFISCAL
           AND I.SERIEDF = N.SERIENF
           AND I.NUMERODF = N.NUMERONF
           AND I.SEQPESSOA = N.SEQPESSOA
        INNER JOIN CTE_PRODUTOS PR
            ON PR.SEQPRODUTO = I.SEQPRODUTO
        WHERE N.TIPNOTAFISCAL = 'S'
          AND N.CODGERALOPER IN (800, 810, 848)
          AND NVL(N.STATUSNF, 'A') != 'C'
          AND N.DTAEMISSAO >= TRUNC(SYSDATE) - 30
          AND N.DTAEMISSAO < TRUNC(SYSDATE)
          AND N.NROEMPRESA IN (1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 14, 15, 17, 18)
        GROUP BY N.NROEMPRESA
    ),
    CTE_LOJAS AS (
        SELECT /*+ MATERIALIZE */
            ME.NROEMPRESA,
            NVL(ME.FANTASIA, 'LOJA ' || ME.NROEMPRESA) AS FANTASIA
        FROM MAX_EMPRESA ME
        WHERE ME.NROEMPRESA IN (1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 14, 15, 17, 18)
    ),
    CTE_BASE AS (
        SELECT /*+ MATERIALIZE */
            L.NROEMPRESA,
            L.FANTASIA,
            NVL(E.VLR_ESTOQUE, 0) AS VLR_ESTOQUE,
            NVL(V.VLR_VENDA, 0) AS VLR_VENDA,
            30 AS DIAS_PERIODO
        FROM CTE_LOJAS L
        LEFT JOIN CTE_ESTOQUE E ON E.NROEMPRESA = L.NROEMPRESA
        LEFT JOIN CTE_VENDAS V ON V.NROEMPRESA = L.NROEMPRESA
    ),
    CTE_TOTAL AS (
        SELECT /*+ MATERIALIZE */
            SUM(VLR_ESTOQUE) AS TOT_ESTOQUE,
            SUM(VLR_VENDA) AS TOT_VENDA
        FROM CTE_BASE
    )
    SELECT
        1 AS ORDEM,
        TO_CHAR(B.NROEMPRESA) AS COD_EMPRESA,
        B.FANTASIA AS LOJA,
        'R$ ' || TO_CHAR(B.VLR_ESTOQUE, 'FM999G999G990D00', 'NLS_NUMERIC_CHARACTERS='',.''') AS VALOR_ESTOQUE,
        'R$ ' || TO_CHAR(B.VLR_VENDA, 'FM999G999G990D00', 'NLS_NUMERIC_CHARACTERS='',.''') AS VALOR_VENDA,
        TO_CHAR(ROUND(B.VLR_ESTOQUE / NULLIF(B.VLR_VENDA, 0), 2), 'FM990D00', 'NLS_NUMERIC_CHARACTERS='',.''') || ' x' AS INDICE_ESTQ_VDA,
        TO_CHAR(ROUND(B.VLR_ESTOQUE / NULLIF(B.VLR_VENDA / B.DIAS_PERIODO, 0), 1), 'FM9990D0', 'NLS_NUMERIC_CHARACTERS='',.''') || ' dias' AS DIAS_COBERTURA,
        TO_CHAR(ROUND(B.VLR_VENDA / NULLIF(B.VLR_ESTOQUE, 0), 2), 'FM990D00', 'NLS_NUMERIC_CHARACTERS='',.''') || ' giros' AS GIRO_ESTOQUE,
        TO_CHAR(ROUND((B.VLR_ESTOQUE / NULLIF(T.TOT_ESTOQUE, 0)) * 100, 2), 'FM990D00', 'NLS_NUMERIC_CHARACTERS='',.''') || ' %' AS SHARE_ESTOQUE,
        TO_CHAR(ROUND((B.VLR_VENDA / NULLIF(T.TOT_VENDA, 0)) * 100, 2), 'FM990D00', 'NLS_NUMERIC_CHARACTERS='',.''') || ' %' AS SHARE_VENDA,
        TO_CHAR(ROUND((B.VLR_VENDA / NULLIF(T.TOT_VENDA, 0)) / NULLIF(B.VLR_ESTOQUE / NULLIF(T.TOT_ESTOQUE, 0), 0), 2), 'FM990D00', 'NLS_NUMERIC_CHARACTERS='',.''') AS EFICIENCIA_ALOCACAO
    FROM CTE_BASE B
    CROSS JOIN CTE_TOTAL T

    UNION ALL

    SELECT
        2 AS ORDEM,
        'TOTAL' AS COD_EMPRESA,
        'TOTAL EMPRESA' AS LOJA,
        'R$ ' || TO_CHAR(T.TOT_ESTOQUE, 'FM999G999G990D00', 'NLS_NUMERIC_CHARACTERS='',.''') AS VALOR_ESTOQUE,
        'R$ ' || TO_CHAR(T.TOT_VENDA, 'FM999G999G990D00', 'NLS_NUMERIC_CHARACTERS='',.''') AS VALOR_VENDA,
        TO_CHAR(ROUND(T.TOT_ESTOQUE / NULLIF(T.TOT_VENDA, 0), 2), 'FM990D00', 'NLS_NUMERIC_CHARACTERS='',.''') || ' x' AS INDICE_ESTQ_VDA,
        TO_CHAR(ROUND(T.TOT_ESTOQUE / NULLIF(T.TOT_VENDA / 30, 0), 1), 'FM9990D0', 'NLS_NUMERIC_CHARACTERS='',.''') || ' dias' AS DIAS_COBERTURA,
        TO_CHAR(ROUND(T.TOT_VENDA / NULLIF(T.TOT_ESTOQUE, 0), 2), 'FM990D00', 'NLS_NUMERIC_CHARACTERS='',.''') || ' giros' AS GIRO_ESTOQUE,
        '100,00 %' AS SHARE_ESTOQUE,
        '100,00 %' AS SHARE_VENDA,
        '1,00' AS EFICIENCIA_ALOCACAO
    FROM CTE_TOTAL T
)
ORDER BY ORDEM ASC, TO_NUMBER(REGEXP_SUBSTR(COD_EMPRESA, '^[0-9]+')) ASC
