SELECT * FROM (
    WITH FORNECEDORES_FAMILIA AS (
        SELECT /*+ MATERIALIZE */
            F.SEQFAMILIA,
            MAX(CASE WHEN F.PRINCIPAL = 'S' THEN F.SEQFORNECEDOR ELSE NULL END) AS COD_FORN_PRINC,
            MAX(F.SEQFORNECEDOR) AS COD_FORN_QUALQUER,
            MAX(CASE WHEN F.PRINCIPAL = 'S' THEN G.NOMERAZAO ELSE NULL END) AS FORN_PRINC,
            MAX(G.NOMERAZAO) AS FORN_QUALQUER,
            MAX(CASE WHEN F.PRINCIPAL = 'S' THEN R.DESCRICAO ELSE NULL END) AS REDE_PRINC,
            MAX(R.DESCRICAO) AS REDE_QUALQUER
        FROM MAP_FAMFORNEC F
        INNER JOIN GE_PESSOA G
            ON G.SEQPESSOA = F.SEQFORNECEDOR
        LEFT JOIN GE_REDEPESSOA RP
            ON RP.SEQPESSOA = F.SEQFORNECEDOR
        LEFT JOIN GE_REDE R
            ON R.SEQREDE = RP.SEQREDE
        GROUP BY F.SEQFAMILIA
    ),
    DEPARTAMENTOS_FAMILIA AS (
        SELECT /*+ MATERIALIZE */
            FDC.SEQFAMILIA,
            MAX(
                CASE 
                    WHEN C1.NIVELHIERARQUIA = 1 THEN C1.CATEGORIA
                    WHEN C2.NIVELHIERARQUIA = 1 THEN C2.CATEGORIA
                    WHEN C3.NIVELHIERARQUIA = 1 THEN C3.CATEGORIA
                    WHEN C4.NIVELHIERARQUIA = 1 THEN C4.CATEGORIA
                    WHEN C5.NIVELHIERARQUIA = 1 THEN C5.CATEGORIA
                END
            ) AS DEPARTAMENTO
        FROM MAP_FAMDIVCATEG FDC
        INNER JOIN MAP_CATEGORIA C1 
            ON C1.SEQCATEGORIA = FDC.SEQCATEGORIA 
           AND C1.NRODIVISAO = FDC.NRODIVISAO
           AND C1.TIPCATEGORIA = 'M'
        LEFT JOIN MAP_CATEGORIA C2 
            ON C2.SEQCATEGORIA = C1.SEQCATEGORIAPAI 
           AND C2.NRODIVISAO = C1.NRODIVISAO
        LEFT JOIN MAP_CATEGORIA C3 
            ON C3.SEQCATEGORIA = C2.SEQCATEGORIAPAI 
           AND C3.NRODIVISAO = C2.NRODIVISAO
        LEFT JOIN MAP_CATEGORIA C4 
            ON C4.SEQCATEGORIA = C3.SEQCATEGORIAPAI 
           AND C4.NRODIVISAO = C3.NRODIVISAO
        LEFT JOIN MAP_CATEGORIA C5 
            ON C5.SEQCATEGORIA = C4.SEQCATEGORIAPAI 
           AND C5.NRODIVISAO = C4.NRODIVISAO
        WHERE FDC.NRODIVISAO = 1
          AND FDC.STATUS = 'A'
          AND UPPER(NVL(C1.CATEGORIA, 'X')) NOT IN ('A CLASSIFICAR', 'ALMOXARIFADO', 'INATIVAR', 'SERVICOS')
        GROUP BY FDC.SEQFAMILIA
    ),
    PRODUTOS_ALVO AS (
        SELECT /*+ MATERIALIZE */
            P.SEQPRODUTO,
            P.DESCCOMPLETA AS DESCRICAO_PRODUTO,
            P.SEQFAMILIA,
            COALESCE(FF.COD_FORN_PRINC, FF.COD_FORN_QUALQUER, 0) AS CODIGO_FORNECEDOR,
            COALESCE(FF.FORN_PRINC, FF.FORN_QUALQUER, 'SEM FORNECEDOR') AS FORNECEDOR,
            COALESCE(FF.REDE_PRINC, FF.REDE_QUALQUER, 'SEM REDE') AS REDE,
            NVL(DF.DEPARTAMENTO, 'SEM DEPARTAMENTO') AS DEPARTAMENTO,
            NVL(COMP.COMPRADOR, 'SEM COMPRADOR') AS COMPRADOR
        FROM MAP_PRODUTO P
        INNER JOIN FORNECEDORES_FAMILIA FF
            ON FF.SEQFAMILIA = P.SEQFAMILIA
        LEFT JOIN DEPARTAMENTOS_FAMILIA DF
            ON DF.SEQFAMILIA = P.SEQFAMILIA
        LEFT JOIN MAP_FAMDIVISAO FD
            ON FD.SEQFAMILIA = P.SEQFAMILIA
           AND FD.NRODIVISAO = 1
        LEFT JOIN MAX_COMPRADOR COMP
            ON COMP.SEQCOMPRADOR = FD.SEQCOMPRADOR
        WHERE (
            NVL(TRIM(:LT4), '0') = '0' 
            OR TO_CHAR(NVL(FF.COD_FORN_PRINC, 0)) = TRIM(:LT4)
            OR TO_CHAR(NVL(FF.COD_FORN_QUALQUER, 0)) = TRIM(:LT4)
            OR INSTR(',' || REPLACE(TRIM(:LT4), ' ', '') || ',', ',' || TO_CHAR(NVL(FF.COD_FORN_PRINC, 0)) || ',') > 0
            OR INSTR(',' || REPLACE(TRIM(:LT4), ' ', '') || ',', ',' || TO_CHAR(NVL(FF.COD_FORN_QUALQUER, 0)) || ',') > 0
        )
        AND (
            :LS1 = ' TODAS AS REDES'
            OR NVL(TRIM(:LS1), 'TODOS') IN ('TODOS', '0 - TODOS', '0', '', ' TODAS AS REDES', 'TODAS AS REDES')
            OR UPPER(TRIM(NVL(FF.REDE_PRINC, ''))) = UPPER(TRIM(:LS1))
            OR UPPER(TRIM(NVL(FF.REDE_QUALQUER, ''))) = UPPER(TRIM(:LS1))
        )
    ),
    CTE_COMPRAS AS (
        SELECT /*+ MATERIALIZE */
            NI.SEQPRODUTO,
            SUM(NVL(NI.QUANTIDADE, 0)) AS QTD_COMPRA,
            SUM(NVL(NI.VLRITEM, 0)) AS VLR_COMPRA,
            RTRIM(
                NVL(MAX(CASE WHEN NF.CODGERALOPER = 1 THEN '1, ' END), '') ||
                NVL(MAX(CASE WHEN NF.CODGERALOPER = 28 THEN '28, ' END), '') ||
                NVL(MAX(CASE WHEN NF.CODGERALOPER = 34 THEN '34, ' END), '') ||
                NVL(MAX(CASE WHEN NF.CODGERALOPER NOT IN (1, 28, 34) THEN TO_CHAR(NF.CODGERALOPER) || ', ' END), ''),
                ', '
            ) AS CGO_COMPRA
        FROM PRODUTOS_ALVO PA
        INNER JOIN MLF_NFITEM NI
            ON NI.SEQPRODUTO = PA.SEQPRODUTO
        INNER JOIN MLF_NOTAFISCAL NF
            ON NF.NROEMPRESA = NI.NROEMPRESA
           AND NF.SEQNF = NI.SEQNF
           AND NF.TIPNOTAFISCAL = NI.TIPNOTAFISCAL
        INNER JOIN MAX_CODGERALOPER CGO
            ON CGO.CODGERALOPER = NF.CODGERALOPER
        WHERE NF.TIPNOTAFISCAL = 'E'
          AND NVL(NF.STATUSNF, 'A') != 'C'
          AND (
              NVL(TRIM(:LT2), '0') IN ('0', 'TODOS', 'TODAS', '')
              OR INSTR(',' || REPLACE(TRIM(:LT2), ' ', '') || ',', ',' || TO_CHAR(NF.CODGERALOPER) || ',') > 0
          )
          AND CGO.CODGERALOPER NOT IN (50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 900)
          AND NF.DTAENTRADA >= TRUNC(:DT1)
          AND NF.DTAENTRADA < TRUNC(:DT2) + 1
          AND (
              NVL(TRIM(:LT3), '0') IN ('0', 'TODOS', 'TODAS', '')
              OR INSTR(',' || REPLACE(TRIM(:LT3), ' ', '') || ',', ',' || TO_CHAR(NF.NROEMPRESA) || ',') > 0
          )
        GROUP BY
            NI.SEQPRODUTO
    ),
    CTE_DEVOLUCOES_TROCAS AS (
        SELECT /*+ MATERIALIZE */
            I.SEQPRODUTO,
            SUM(NVL(I.QUANTIDADE, 0)) AS QTD_DEV,
            SUM(NVL(I.VLRITEM, 0)) AS VLR_DEV,
            RTRIM(
                NVL(MAX(CASE WHEN N.CODGERALOPER = 802 THEN '802, ' END), '') ||
                NVL(MAX(CASE WHEN N.CODGERALOPER = 860 THEN '860, ' END), '') ||
                NVL(MAX(CASE WHEN N.CODGERALOPER NOT IN (802, 860) THEN TO_CHAR(N.CODGERALOPER) || ', ' END), ''),
                ', '
            ) AS CGO_DEV
        FROM PRODUTOS_ALVO PA
        INNER JOIN MFLV_BASEDFITEM I
            ON I.SEQPRODUTO = PA.SEQPRODUTO
        INNER JOIN MLFV_BASENFE N
            ON N.NROEMPRESA = I.NROEMPRESA
           AND N.SEQNF = I.SEQNF
           AND N.TIPNOTAFISCAL = I.TIPNOTAFISCAL
        WHERE N.TIPNOTAFISCAL = 'S'
          AND NVL(N.STATUSNF, 'A') != 'C'
          AND NVL(N.MODELO, '0') <> '65'
          AND N.CODGERALOPER IN (#LT1)
          AND N.CODGERALOPER IN (802, 860)
          AND N.DTAEMISSAO >= TRUNC(:DT1)
          AND N.DTAEMISSAO < TRUNC(:DT2) + 1
          AND (
              NVL(TRIM(:LT3), '0') IN ('0', 'TODOS', 'TODAS', '')
              OR INSTR(',' || REPLACE(TRIM(:LT3), ' ', '') || ',', ',' || TO_CHAR(N.NROEMPRESA) || ',') > 0
          )
        GROUP BY
            I.SEQPRODUTO
    ),
    CTE_INCINERACOES_PERDAS AS (
        SELECT /*+ MATERIALIZE */
            I.SEQPRODUTO,
            SUM(NVL(I.QUANTIDADE, 0)) AS QTD_INCIN,
            SUM(NVL(I.VLRITEM, 0)) AS VLR_INCIN,
            RTRIM(
                NVL(MAX(CASE WHEN N.CODGERALOPER = 821 THEN '821, ' END), '') ||
                NVL(MAX(CASE WHEN N.CODGERALOPER = 831 THEN '831, ' END), '') ||
                NVL(MAX(CASE WHEN N.CODGERALOPER NOT IN (821, 831) THEN TO_CHAR(N.CODGERALOPER) || ', ' END), ''),
                ', '
            ) AS CGO_INCIN
        FROM PRODUTOS_ALVO PA
        INNER JOIN MFLV_BASEDFITEM I
            ON I.SEQPRODUTO = PA.SEQPRODUTO
        INNER JOIN MLFV_BASENFE N
            ON N.NROEMPRESA = I.NROEMPRESA
           AND N.SEQNF = I.SEQNF
           AND N.TIPNOTAFISCAL = I.TIPNOTAFISCAL
        WHERE N.TIPNOTAFISCAL = 'S'
          AND NVL(N.STATUSNF, 'A') != 'C'
          AND NVL(N.MODELO, '0') <> '65'
          AND N.CODGERALOPER IN (#LT1)
          AND N.CODGERALOPER IN (821, 831)
          AND N.DTAEMISSAO >= TRUNC(:DT1)
          AND N.DTAEMISSAO < TRUNC(:DT2) + 1
          AND (
              NVL(TRIM(:LT3), '0') IN ('0', 'TODOS', 'TODAS', '')
              OR INSTR(',' || REPLACE(TRIM(:LT3), ' ', '') || ',', ',' || TO_CHAR(N.NROEMPRESA) || ',') > 0
          )
        GROUP BY
            I.SEQPRODUTO
    ),
    DADOS_BASE AS (
        SELECT /*+ MATERIALIZE */
            PA.DEPARTAMENTO,
            PA.COMPRADOR,
            PA.REDE,
            PA.CODIGO_FORNECEDOR,
            PA.FORNECEDOR,
            PA.SEQPRODUTO AS CODIGO_PRODUTO,
            PA.DESCRICAO_PRODUTO,
            NVL(C.CGO_COMPRA, '--') AS CGO_COMPRA,
            CASE
                WHEN D.CGO_DEV IS NOT NULL AND INC.CGO_INCIN IS NOT NULL THEN D.CGO_DEV || ', ' || INC.CGO_INCIN
                WHEN D.CGO_DEV IS NOT NULL THEN D.CGO_DEV
                WHEN INC.CGO_INCIN IS NOT NULL THEN INC.CGO_INCIN
                ELSE '--'
            END AS CGO_SAIDA,
            NVL(C.QTD_COMPRA, 0) AS QTD_COMPRA_NUM,
            NVL(C.VLR_COMPRA, 0) AS VLR_COMPRA_NUM,
            NVL(D.QTD_DEV, 0) AS QTD_DEV_NUM,
            NVL(D.VLR_DEV, 0) AS VLR_DEV_NUM,
            NVL(INC.QTD_INCIN, 0) AS QTD_INCIN_NUM,
            NVL(INC.VLR_INCIN, 0) AS VLR_INCIN_NUM,
            (NVL(D.VLR_DEV, 0) + NVL(INC.VLR_INCIN, 0)) AS VLR_TOTAL_PERDAS_DEV_NUM,
            (NVL(C.VLR_COMPRA, 0) - NVL(D.VLR_DEV, 0) - NVL(INC.VLR_INCIN, 0)) AS SALDO_LIQUIDO_NUM
        FROM PRODUTOS_ALVO PA
        LEFT JOIN CTE_COMPRAS C
            ON C.SEQPRODUTO = PA.SEQPRODUTO
        LEFT JOIN CTE_DEVOLUCOES_TROCAS D
            ON D.SEQPRODUTO = PA.SEQPRODUTO
        LEFT JOIN CTE_INCINERACOES_PERDAS INC
            ON INC.SEQPRODUTO = PA.SEQPRODUTO
        WHERE (
            NVL(C.VLR_COMPRA, 0) > 0 
            OR NVL(D.VLR_DEV, 0) > 0 
            OR NVL(INC.VLR_INCIN, 0) > 0
        )
    ),
    SUBTOTAIS_COMPRADOR AS (
        SELECT /*+ MATERIALIZE */
            D.COMPRADOR,
            SUM(D.QTD_COMPRA_NUM) AS TOTAL_QTD_COMPRA,
            SUM(D.VLR_COMPRA_NUM) AS TOTAL_VLR_COMPRA,
            SUM(D.QTD_DEV_NUM) AS TOTAL_QTD_DEV,
            SUM(D.VLR_DEV_NUM) AS TOTAL_VLR_DEV,
            SUM(D.QTD_INCIN_NUM) AS TOTAL_QTD_INCIN,
            SUM(D.VLR_INCIN_NUM) AS TOTAL_VLR_INCIN,
            SUM(D.VLR_TOTAL_PERDAS_DEV_NUM) AS TOTAL_VLR_PERDAS_DEV,
            SUM(D.SALDO_LIQUIDO_NUM) AS TOTAL_SALDO_LIQUIDO
        FROM DADOS_BASE D
        GROUP BY D.COMPRADOR
    ),
    UNIAO_RELATORIO AS (
        SELECT
            1 AS ORDEM_BLOCO,
            DEPARTAMENTO,
            COMPRADOR,
            REDE,
            CODIGO_FORNECEDOR,
            FORNECEDOR,
            CODIGO_PRODUTO,
            DESCRICAO_PRODUTO,
            CGO_COMPRA,
            CGO_SAIDA,
            '    ' || TO_CHAR(ROUND(QTD_COMPRA_NUM, 2), 'FM999G999G990D00') AS QUANTIDADE_COMPRADA,
            'R$     ' || TO_CHAR(ROUND(VLR_COMPRA_NUM, 2), 'FM999G999G999G990D00') AS VALOR_COMPRAS,
            '    ' || TO_CHAR(ROUND(QTD_DEV_NUM, 2), 'FM999G999G990D00') AS QTD_DEVOLVIDA_RESSARCIDA,
            'R$     ' || TO_CHAR(ROUND(VLR_DEV_NUM, 2), 'FM999G999G999G990D00') AS VLR_DEVOLUCAO_RESSARCIDA,
            '    ' || TO_CHAR(ROUND(QTD_INCIN_NUM, 2), 'FM999G999G990D00') AS QTD_INCINERACAO_PERDA,
            'R$     ' || TO_CHAR(ROUND(VLR_INCIN_NUM, 2), 'FM999G999G999G990D00') AS VLR_INCINERACAO_PERDA,
            'R$     ' || TO_CHAR(ROUND(VLR_TOTAL_PERDAS_DEV_NUM, 2), 'FM999G999G999G990D00') AS VLR_TOTAL_PERDAS_DEV,
            'R$     ' || TO_CHAR(ROUND(SALDO_LIQUIDO_NUM, 2), 'FM999G999G999G990D00') AS SALDO_LIQUIDO_ESTOQUE,
            CASE
                WHEN VLR_COMPRA_NUM > 0 THEN TO_CHAR(ROUND((VLR_INCIN_NUM / VLR_COMPRA_NUM) * 100, 2), 'FM990D00') || '%'
                WHEN VLR_INCIN_NUM > 0 THEN '100,00%'
                ELSE '0,00%'
            END AS PERC_INCINERACAO_SOBRE_COMPRA,
            CASE
                WHEN VLR_COMPRA_NUM > 0 THEN TO_CHAR(ROUND((VLR_TOTAL_PERDAS_DEV_NUM / VLR_COMPRA_NUM) * 100, 2), 'FM990D00') || '%'
                WHEN VLR_TOTAL_PERDAS_DEV_NUM > 0 THEN '100,00%'
                ELSE '0,00%'
            END AS PERC_TOTAL_PERDA_SOBRE_COMPRA
        FROM DADOS_BASE
        
        UNION ALL
        
        SELECT
            2 AS ORDEM_BLOCO,
            '--' AS DEPARTAMENTO,
            SC.COMPRADOR AS COMPRADOR,
            '--' AS REDE,
            0 AS CODIGO_FORNECEDOR,
            'SUBTOTAL -> ' || SC.COMPRADOR AS FORNECEDOR,
            0 AS CODIGO_PRODUTO,
            'SUBTOTAL DO COMPRADOR' AS DESCRICAO_PRODUTO,
            '--' AS CGO_COMPRA,
            '--' AS CGO_SAIDA,
            '    ' || TO_CHAR(ROUND(SC.TOTAL_QTD_COMPRA, 2), 'FM999G999G990D00') AS QUANTIDADE_COMPRADA,
            'R$     ' || TO_CHAR(ROUND(SC.TOTAL_VLR_COMPRA, 2), 'FM999G999G999G990D00') AS VALOR_COMPRAS,
            '    ' || TO_CHAR(ROUND(SC.TOTAL_QTD_DEV, 2), 'FM999G999G990D00') AS QTD_DEVOLVIDA_RESSARCIDA,
            'R$     ' || TO_CHAR(ROUND(SC.TOTAL_VLR_DEV, 2), 'FM999G999G999G990D00') AS VLR_DEVOLUCAO_RESSARCIDA,
            '    ' || TO_CHAR(ROUND(SC.TOTAL_QTD_INCIN, 2), 'FM999G999G990D00') AS QTD_INCINERACAO_PERDA,
            'R$     ' || TO_CHAR(ROUND(SC.TOTAL_VLR_INCIN, 2), 'FM999G999G999G990D00') AS VLR_INCINERACAO_PERDA,
            'R$     ' || TO_CHAR(ROUND(SC.TOTAL_VLR_PERDAS_DEV, 2), 'FM999G999G999G990D00') AS VLR_TOTAL_PERDAS_DEV,
            'R$     ' || TO_CHAR(ROUND(SC.TOTAL_SALDO_LIQUIDO, 2), 'FM999G999G999G990D00') AS SALDO_LIQUIDO_ESTOQUE,
            CASE
                WHEN SC.TOTAL_VLR_COMPRA > 0 THEN TO_CHAR(ROUND((SC.TOTAL_VLR_INCIN / SC.TOTAL_VLR_COMPRA) * 100, 2), 'FM990D00') || '%'
                WHEN SC.TOTAL_VLR_INCIN > 0 THEN '100,00%'
                ELSE '0,00%'
            END AS PERC_INCINERACAO_SOBRE_COMPRA,
            CASE
                WHEN SC.TOTAL_VLR_COMPRA > 0 THEN TO_CHAR(ROUND((SC.TOTAL_VLR_PERDAS_DEV / SC.TOTAL_VLR_COMPRA) * 100, 2), 'FM990D00') || '%'
                WHEN SC.TOTAL_VLR_PERDAS_DEV > 0 THEN '100,00%'
                ELSE '0,00%'
            END AS PERC_TOTAL_PERDA_SOBRE_COMPRA
        FROM SUBTOTAIS_COMPRADOR SC
        
        UNION ALL
        
        SELECT
            3 AS ORDEM_BLOCO,
            '--' AS DEPARTAMENTO,
            '--' AS COMPRADOR,
            '--' AS REDE,
            0 AS CODIGO_FORNECEDOR,
            'TOTAL GERAL ->' AS FORNECEDOR,
            0 AS CODIGO_PRODUTO,
            'TOTAL GERAL CONSOLIDADO' AS DESCRICAO_PRODUTO,
            '--' AS CGO_COMPRA,
            '--' AS CGO_SAIDA,
            '    ' || TO_CHAR(ROUND(NVL(SUM(D.QTD_COMPRA_NUM), 0), 2), 'FM999G999G990D00') AS QUANTIDADE_COMPRADA,
            'R$     ' || TO_CHAR(ROUND(NVL(SUM(D.VLR_COMPRA_NUM), 0), 2), 'FM999G999G999G990D00') AS VALOR_COMPRAS,
            '    ' || TO_CHAR(ROUND(NVL(SUM(D.QTD_DEV_NUM), 0), 2), 'FM999G999G990D00') AS QTD_DEVOLVIDA_RESSARCIDA,
            'R$     ' || TO_CHAR(ROUND(NVL(SUM(D.VLR_DEV_NUM), 0), 2), 'FM999G999G999G990D00') AS VLR_DEVOLUCAO_RESSARCIDA,
            '    ' || TO_CHAR(ROUND(NVL(SUM(D.QTD_INCIN_NUM), 0), 2), 'FM999G999G990D00') AS QTD_INCINERACAO_PERDA,
            'R$     ' || TO_CHAR(ROUND(NVL(SUM(D.VLR_INCIN_NUM), 0), 2), 'FM999G999G999G990D00') AS VLR_INCINERACAO_PERDA,
            'R$     ' || TO_CHAR(ROUND(NVL(SUM(D.VLR_TOTAL_PERDAS_DEV_NUM), 0), 2), 'FM999G999G999G990D00') AS VLR_TOTAL_PERDAS_DEV,
            'R$     ' || TO_CHAR(ROUND(NVL(SUM(D.SALDO_LIQUIDO_NUM), 0), 2), 'FM999G999G999G990D00') AS SALDO_LIQUIDO_ESTOQUE,
            CASE
                WHEN SUM(D.VLR_COMPRA_NUM) > 0 THEN TO_CHAR(ROUND((SUM(D.VLR_INCIN_NUM) / SUM(D.VLR_COMPRA_NUM)) * 100, 2), 'FM990D00') || '%'
                WHEN SUM(D.VLR_INCIN_NUM) > 0 THEN '100,00%'
                ELSE '0,00%'
            END AS PERC_INCINERACAO_SOBRE_COMPRA,
            CASE
                WHEN SUM(D.VLR_COMPRA_NUM) > 0 THEN TO_CHAR(ROUND((SUM(D.VLR_TOTAL_PERDAS_DEV_NUM) / SUM(D.VLR_COMPRA_NUM)) * 100, 2), 'FM990D00') || '%'
                WHEN SUM(D.VLR_TOTAL_PERDAS_DEV_NUM) > 0 THEN '100,00%'
                ELSE '0,00%'
            END AS PERC_TOTAL_PERDA_SOBRE_COMPRA
        FROM DADOS_BASE D
    )
    SELECT
        DEPARTAMENTO,
        COMPRADOR,
        REDE,
        CODIGO_FORNECEDOR,
        FORNECEDOR,
        CODIGO_PRODUTO,
        DESCRICAO_PRODUTO,
        CGO_COMPRA,
        CGO_SAIDA,
        QUANTIDADE_COMPRADA,
        VALOR_COMPRAS,
        QTD_DEVOLVIDA_RESSARCIDA,
        VLR_DEVOLUCAO_RESSARCIDA,
        QTD_INCINERACAO_PERDA,
        VLR_INCINERACAO_PERDA,
        VLR_TOTAL_PERDAS_DEV,
        SALDO_LIQUIDO_ESTOQUE,
        PERC_INCINERACAO_SOBRE_COMPRA,
        PERC_TOTAL_PERDA_SOBRE_COMPRA
    FROM UNIAO_RELATORIO
    ORDER BY
        ORDEM_BLOCO ASC,
        CASE WHEN ORDEM_BLOCO = 2 THEN COMPRADOR ELSE NULL END ASC,
        COMPRADOR ASC,
        VLR_INCINERACAO_PERDA DESC,
        VALOR_COMPRAS DESC,
        CODIGO_PRODUTO ASC
)