SELECT
    NVL(COMP.COMPRADOR, 'SEM COMPRADOR') AS COMPRADOR,
    DEP.CATEGORIA AS DEPARTAMENTO,
    P.SEQPRODUTO AS CODIGO_PRODUTO,
    P.DESCCOMPLETA AS DESCRICAO,
    (NVL(E15.ESTQLOJA, 0) + NVL(E15.ESTQDEPOSITO, 0) - NVL(E15.QTDRESERVADAVDA, 0) - NVL(E15.QTDRESERVADARECEB, 0) - NVL(E15.QTDRESERVADAFIXA, 0)) AS ESTOQUE_CD15,
    (NVL(E16.ESTQLOJA, 0) + NVL(E16.ESTQDEPOSITO, 0) - NVL(E16.QTDRESERVADAVDA, 0) - NVL(E16.QTDRESERVADARECEB, 0) - NVL(E16.QTDRESERVADAFIXA, 0)) AS ESTOQUE_CD16,
    E15.STATUSCOMPRA AS STATUS_CD15,
    E16.STATUSCOMPRA AS STATUS_CD16
FROM MAP_PRODUTO P
INNER JOIN MRL_PRODUTOEMPRESA E15
    ON P.SEQPRODUTO = E15.SEQPRODUTO
   AND E15.NROEMPRESA = 15
   AND E15.STATUSCOMPRA = 'A'
INNER JOIN MRL_PRODUTOEMPRESA E16
    ON P.SEQPRODUTO = E16.SEQPRODUTO
   AND E16.NROEMPRESA = 16
   AND E16.STATUSCOMPRA = 'A'
LEFT JOIN MAP_FAMDIVISAO FD
    ON FD.SEQFAMILIA = P.SEQFAMILIA
   AND FD.NRODIVISAO = 1
LEFT JOIN MAX_COMPRADOR COMP
    ON COMP.SEQCOMPRADOR = FD.SEQCOMPRADOR
INNER JOIN (
    SELECT
        X.SEQFAMILIA,
        MAX(CASE WHEN Y.NIVELHIERARQUIA = 1 THEN Y.CATEGORIA END) AS CATEGORIA
    FROM MAP_FAMDIVCATEG X
    INNER JOIN MAP_CATEGORIA Y
        ON X.SEQCATEGORIA = Y.SEQCATEGORIA
       AND Y.NRODIVISAO = 1
       AND Y.STATUSCATEGOR = 'A'
    WHERE X.NRODIVISAO = 1
      AND X.STATUS = 'A'
    GROUP BY X.SEQFAMILIA
    HAVING MAX(CASE WHEN Y.NIVELHIERARQUIA = 1 THEN Y.CATEGORIA END) IS NOT NULL
       AND UPPER(MAX(CASE WHEN Y.NIVELHIERARQUIA = 1 THEN Y.CATEGORIA END)) NOT IN ('ALMOXARIFADO', 'A CLASSIFICAR', 'INATIVAR', 'SERVICOS')
       AND SUM(CASE 
           WHEN UPPER(Y.CATEGORIA) LIKE '%FRUTAS%VERDURAS%'
             OR UPPER(Y.CATEGORIA) LIKE '%PAD%BAKLIZI%'
             OR UPPER(Y.CATEGORIA) LIKE '%PAD%INDUSTRIAL%'
           THEN 1 ELSE 0 END) = 0
) DEP ON DEP.SEQFAMILIA = P.SEQFAMILIA
WHERE (
    :LS1 IN ('0 - TODOS', 'TODOS', 'TODOS OS DEPARTAMENTOS')
    OR DEP.CATEGORIA = :LS1
    OR (
        INSTR(:LS1, ' - ') > 0
        AND DEP.CATEGORIA = SUBSTR(:LS1, INSTR(:LS1, ' - ') + 3)
    )
)
ORDER BY
    DEP.CATEGORIA,
    P.DESCCOMPLETA
