SELECT * FROM (
    WITH DADOS_FISCAL AS (
        SELECT /*+ MATERIALIZE */
            NF.NROEMPRESA,
            NF.SEQPESSOA,
            NF.NUMERONF,
            NF.SERIENF,
            MAX(NF.DTAENTRADA) AS DTAENTRADA,
            MAX(NF.DTAEMISSAO) AS DTAEMISSAO,
            MAX(NF.CODGERALOPER) AS CODGERALOPER,
            SUM(NVL(NI.VLRITEM, 0)) AS VLR_PRODUTOS_NF,
            COALESCE(
                NULLIF(MAX(NF.VLRTOTFORNEC), 0),
                SUM(
                    NVL(NI.VLRITEM, 0)
                    + NVL(NI.VLRICMSST, 0)
                    + NVL(NI.VLRIPI, 0)
                    + NVL(NI.VLRDESPTRIBUTITEM, 0)
                    + NVL(NI.VLRDESPNTRIBUTITEM, 0)
                    + NVL(NI.VLRFCPST, 0)
                    - NVL(NI.VLRDESCITEM, 0)
                )
            ) AS VLR_TOTAL_NF
        FROM MLF_NOTAFISCAL NF
        INNER JOIN MLF_NFITEM NI
            ON NI.NROEMPRESA = NF.NROEMPRESA
           AND NI.SEQNF = NF.SEQNF
           AND NI.TIPNOTAFISCAL = NF.TIPNOTAFISCAL
        INNER JOIN MAX_CODGERALOPER CGO
            ON CGO.CODGERALOPER = NF.CODGERALOPER
        WHERE NF.TIPNOTAFISCAL = 'E'
          AND NVL(NF.STATUSNF, 'A') != 'C'
          AND (
              CGO.TIPUSO IN ('R', 'C') 
              OR CGO.CODGERALOPER IN (#LT1)
          )
          AND CGO.CODGERALOPER NOT IN (50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 900)
          AND NF.DTAENTRADA >= TRUNC(:DT1)
          AND NF.DTAENTRADA < TRUNC(:DT2) + 1
          AND (
              NVL(TRIM(:LT3), '0') IN ('0', 'TODOS', 'TODAS', '')
              OR INSTR(',' || REPLACE(TRIM(:LT3), ' ', '') || ',', ',' || TO_CHAR(NF.NROEMPRESA) || ',') > 0
          )
          AND (
              NVL(:NR1, 0) = 0 
              OR NF.NUMERONF = :NR1
          )
        GROUP BY
            NF.NROEMPRESA,
            NF.SEQPESSOA,
            NF.NUMERONF,
            NF.SERIENF
    ),
    DADOS_FINANCEIRO AS (
        SELECT /*+ MATERIALIZE */
            T.NROEMPRESA,
            T.SEQPESSOA,
            T.NRODOCUMENTO,
            SUM(NVL(T.VLRNOMINAL, 0)) AS VLR_NOMINAL_FIN,
            SUM(NVL(T.VLRPAGO, 0)) AS VLR_PAGO_FIN,
            SUM(NVL(T.VLRNOMINAL, 0) - NVL(T.VLRPAGO, 0)) AS SALDO_ABERTO_FIN,
            COUNT(DISTINCT T.SEQTITULO) AS QTD_PARCELAS,
            MAX(T.DTAVENCIMENTO) AS DTAVENCIMENTO,
            MAX(T.DTAQUITACAO) AS DTAQUITACAO,
            CASE
                WHEN MIN(T.ABERTOQUITADO) = 'A' AND MAX(T.ABERTOQUITADO) = 'A' THEN 'EM ABERTO'
                WHEN MIN(T.ABERTOQUITADO) = 'Q' AND MAX(T.ABERTOQUITADO) = 'Q' THEN 'QUITADO'
                ELSE 'PAGO PARCIAL'
            END AS SITUACAO_FINANCEIRA
        FROM FI_TITULO T
        INNER JOIN DADOS_FISCAL F
            ON F.NROEMPRESA = T.NROEMPRESA
           AND F.SEQPESSOA = T.SEQPESSOA
           AND F.NUMERONF = T.NRODOCUMENTO
        WHERE T.OBRIGDIREITO = 'O'
        GROUP BY
            T.NROEMPRESA,
            T.SEQPESSOA,
            T.NRODOCUMENTO
    ),
    CONFRONTO_BASE AS (
        SELECT /*+ MATERIALIZE */
            F.NROEMPRESA,
            E.NOMEREDUZIDO AS EMPRESA,
            F.SEQPESSOA,
            P.NOMERAZAO AS FORNECEDOR,
            NVL(R.DESCRICAO, 'SEM REDE') AS REDE,
            F.NUMERONF AS NUMERO_NF,
            NVL(F.SERIENF, '--') AS SERIE_NF,
            NVL(F.CODGERALOPER, 0) AS CGO,
            F.DTAENTRADA,
            F.DTAEMISSAO,
            FIN.DTAVENCIMENTO,
            FIN.DTAQUITACAO,
            NVL(FIN.SITUACAO_FINANCEIRA, 'SEM TITULO') AS SITUACAO_FINANCEIRA,
            NVL(FIN.QTD_PARCELAS, 0) AS QTD_PARCELAS,
            NVL(F.VLR_PRODUTOS_NF, 0) AS VLR_PRODUTOS_NF_NUM,
            NVL(F.VLR_TOTAL_NF, 0) AS VLR_TOTAL_NF_NUM,
            NVL(FIN.VLR_NOMINAL_FIN, 0) AS VLR_NOMINAL_FIN_NUM,
            NVL(FIN.VLR_PAGO_FIN, 0) AS VLR_PAGO_FIN_NUM,
            NVL(FIN.SALDO_ABERTO_FIN, 0) AS SALDO_ABERTO_FIN_NUM,
            NVL(F.VLR_TOTAL_NF, 0) - NVL(FIN.VLR_NOMINAL_FIN, 0) AS DIFERENCA_TOTAL_FIN_NUM,
            CASE
                WHEN FIN.NRODOCUMENTO IS NULL THEN 'APENAS NO FISCAL (SEM TITULO)'
                WHEN ABS(NVL(F.VLR_TOTAL_NF, 0) - NVL(FIN.VLR_NOMINAL_FIN, 0)) <= 0.05 THEN 'CONCILIADO 100%'
                WHEN NVL(F.VLR_TOTAL_NF, 0) > NVL(FIN.VLR_NOMINAL_FIN, 0) THEN 'DIVERGENCIA (NF MAIOR QUE TITULO)'
                ELSE 'DIVERGENCIA (TITULO MAIOR QUE NF)'
            END AS STATUS_CONCILIACAO
        FROM DADOS_FISCAL F
        LEFT JOIN DADOS_FINANCEIRO FIN
            ON FIN.NROEMPRESA = F.NROEMPRESA
           AND FIN.SEQPESSOA = F.SEQPESSOA
           AND FIN.NRODOCUMENTO = F.NUMERONF
        LEFT JOIN MAX_EMPRESA E
            ON E.NROEMPRESA = F.NROEMPRESA
        LEFT JOIN GE_PESSOA P
            ON P.SEQPESSOA = F.SEQPESSOA
        LEFT JOIN GE_REDEPESSOA RP
            ON RP.SEQPESSOA = F.SEQPESSOA
        LEFT JOIN GE_REDE R
            ON R.SEQREDE = RP.SEQREDE
        WHERE (
            NVL(TRIM(:LT2), '0') = '0' 
            OR TO_CHAR(F.SEQPESSOA) = TRIM(:LT2)
        )
        AND (
            :LS1 = ' TODAS AS REDES'
            OR NVL(TRIM(:LS1), 'TODOS') IN ('TODOS', '0 - TODOS', '0', '', ' TODAS AS REDES', 'TODAS AS REDES')
            OR UPPER(TRIM(NVL(R.DESCRICAO, ''))) = UPPER(TRIM(:LS1))
        )
    ),
    SUBTOTAIS_REDE AS (
        SELECT /*+ MATERIALIZE */
            CB.REDE,
            SUM(CB.VLR_PRODUTOS_NF_NUM) AS TOTAL_PRODUTOS,
            SUM(CB.VLR_TOTAL_NF_NUM) AS TOTAL_FISCAL_NF,
            SUM(CB.VLR_NOMINAL_FIN_NUM) AS TOTAL_FINANCEIRO,
            SUM(CB.VLR_PAGO_FIN_NUM) AS TOTAL_PAGO,
            SUM(CB.SALDO_ABERTO_FIN_NUM) AS TOTAL_SALDO_ABERTO,
            SUM(CB.DIFERENCA_TOTAL_FIN_NUM) AS TOTAL_DIFERENCA
        FROM CONFRONTO_BASE CB
        GROUP BY CB.REDE
    ),
    UNIAO_RELATORIO AS (
        SELECT
            1 AS ORDEM_BLOCO,
            NROEMPRESA AS CODIGO_EMPRESA,
            EMPRESA,
            TO_CHAR(DTAENTRADA, 'DD/MM/YYYY') AS DATA_ENTRADA,
            NUMERO_NF,
            SERIE_NF,
            CGO,
            REDE,
            SEQPESSOA AS CODIGO_FORNECEDOR,
            FORNECEDOR,
            SITUACAO_FINANCEIRA,
            TO_CHAR(DTAVENCIMENTO, 'DD/MM/YYYY') AS DATA_VENCIMENTO,
            TO_CHAR(DTAQUITACAO, 'DD/MM/YYYY') AS DATA_PAGAMENTO,
            'R$     ' || TO_CHAR(ROUND(VLR_PRODUTOS_NF_NUM, 2), 'FM999G999G999G990D00') AS VALOR_PRODUTOS_NF,
            'R$     ' || TO_CHAR(ROUND(VLR_TOTAL_NF_NUM, 2), 'FM999G999G999G990D00') AS VALOR_TOTAL_NF,
            'R$     ' || TO_CHAR(ROUND(VLR_NOMINAL_FIN_NUM, 2), 'FM999G999G999G990D00') AS VALOR_FINANCEIRO_TITULOS,
            'R$     ' || TO_CHAR(ROUND(VLR_PAGO_FIN_NUM, 2), 'FM999G999G999G990D00') AS VALOR_PAGO,
            'R$     ' || TO_CHAR(ROUND(SALDO_ABERTO_FIN_NUM, 2), 'FM999G999G999G990D00') AS SALDO_ABERTO,
            'R$     ' || TO_CHAR(ROUND(DIFERENCA_TOTAL_FIN_NUM, 2), 'FM999G999G999G990D00') AS DIFERENCA_TOTAL_NF_FIN,
            STATUS_CONCILIACAO
        FROM CONFRONTO_BASE
        
        UNION ALL
        
        SELECT
            2 AS ORDEM_BLOCO,
            998 AS CODIGO_EMPRESA,
            'SUBTOTAL REDE' AS EMPRESA,
            '--/--/----' AS DATA_ENTRADA,
            0 AS NUMERO_NF,
            '--' AS SERIE_NF,
            0 AS CGO,
            SR.REDE AS REDE,
            0 AS CODIGO_FORNECEDOR,
            'SUBTOTAL -> ' || SR.REDE AS FORNECEDOR,
            '--' AS SITUACAO_FINANCEIRA,
            '--/--/----' AS DATA_VENCIMENTO,
            '--/--/----' AS DATA_PAGAMENTO,
            'R$     ' || TO_CHAR(ROUND(SR.TOTAL_PRODUTOS, 2), 'FM999G999G999G990D00') AS VALOR_PRODUTOS_NF,
            'R$     ' || TO_CHAR(ROUND(SR.TOTAL_FISCAL_NF, 2), 'FM999G999G999G990D00') AS VALOR_TOTAL_NF,
            'R$     ' || TO_CHAR(ROUND(SR.TOTAL_FINANCEIRO, 2), 'FM999G999G999G990D00') AS VALOR_FINANCEIRO_TITULOS,
            'R$     ' || TO_CHAR(ROUND(SR.TOTAL_PAGO, 2), 'FM999G999G999G990D00') AS VALOR_PAGO,
            'R$     ' || TO_CHAR(ROUND(SR.TOTAL_SALDO_ABERTO, 2), 'FM999G999G999G990D00') AS SALDO_ABERTO,
            'R$     ' || TO_CHAR(ROUND(SR.TOTAL_DIFERENCA, 2), 'FM999G999G999G990D00') AS DIFERENCA_TOTAL_NF_FIN,
            CASE
                WHEN ABS(SR.TOTAL_DIFERENCA) <= 0.05 THEN 'SUBTOTAL CONCILIADO'
                ELSE 'SUBTOTAL COM DIVERGENCIA'
            END AS STATUS_CONCILIACAO
        FROM SUBTOTAIS_REDE SR
        
        UNION ALL
        
        SELECT
            3 AS ORDEM_BLOCO,
            999 AS CODIGO_EMPRESA,
            'TOTAL GERAL' AS EMPRESA,
            '--/--/----' AS DATA_ENTRADA,
            0 AS NUMERO_NF,
            '--' AS SERIE_NF,
            0 AS CGO,
            '--' AS REDE,
            0 AS CODIGO_FORNECEDOR,
            'TOTAL GERAL CONSOLIDADO' AS FORNECEDOR,
            '--' AS SITUACAO_FINANCEIRA,
            '--/--/----' AS DATA_VENCIMENTO,
            '--/--/----' AS DATA_PAGAMENTO,
            'R$     ' || TO_CHAR(ROUND(NVL(SUM(CB.VLR_PRODUTOS_NF_NUM), 0), 2), 'FM999G999G999G990D00') AS VALOR_PRODUTOS_NF,
            'R$     ' || TO_CHAR(ROUND(NVL(SUM(CB.VLR_TOTAL_NF_NUM), 0), 2), 'FM999G999G999G990D00') AS VALOR_TOTAL_NF,
            'R$     ' || TO_CHAR(ROUND(NVL(SUM(CB.VLR_NOMINAL_FIN_NUM), 0), 2), 'FM999G999G999G990D00') AS VALOR_FINANCEIRO_TITULOS,
            'R$     ' || TO_CHAR(ROUND(NVL(SUM(CB.VLR_PAGO_FIN_NUM), 0), 2), 'FM999G999G999G990D00') AS VALOR_PAGO,
            'R$     ' || TO_CHAR(ROUND(NVL(SUM(CB.SALDO_ABERTO_FIN_NUM), 0), 2), 'FM999G999G999G990D00') AS SALDO_ABERTO,
            'R$     ' || TO_CHAR(ROUND(NVL(SUM(CB.DIFERENCA_TOTAL_FIN_NUM), 0), 2), 'FM999G999G999G990D00') AS DIFERENCA_TOTAL_NF_FIN,
            CASE
                WHEN ABS(NVL(SUM(CB.DIFERENCA_TOTAL_FIN_NUM), 0)) <= 0.05 THEN 'TOTAL GERAL CONCILIADO'
                ELSE 'TOTAL GERAL COM DIVERGENCIA'
            END AS STATUS_CONCILIACAO
        FROM CONFRONTO_BASE CB
    )
    SELECT
        CODIGO_EMPRESA,
        EMPRESA,
        DATA_ENTRADA,
        NUMERO_NF,
        SERIE_NF,
        CGO,
        REDE,
        CODIGO_FORNECEDOR,
        FORNECEDOR,
        SITUACAO_FINANCEIRA,
        DATA_VENCIMENTO,
        DATA_PAGAMENTO,
        VALOR_PRODUTOS_NF,
        VALOR_TOTAL_NF,
        VALOR_FINANCEIRO_TITULOS,
        VALOR_PAGO,
        SALDO_ABERTO,
        DIFERENCA_TOTAL_NF_FIN,
        STATUS_CONCILIACAO
    FROM UNIAO_RELATORIO
    ORDER BY
        ORDEM_BLOCO ASC,
        CASE WHEN ORDEM_BLOCO = 2 THEN REDE ELSE NULL END ASC,
        DATA_ENTRADA ASC,
        NUMERO_NF ASC,
        CODIGO_EMPRESA ASC
)
