SELECT * FROM (
    WITH CTE_DEVOLUCOES AS (
        SELECT /*+ MATERIALIZE */
            I.SEQPRODUTO,
            SUM(NVL(I.QUANTIDADE, 0)) AS QTD_DEV,
            SUM(NVL(I.VLRITEM, 0)) AS VLR_DEV
        FROM MLFV_BASENFE N
        INNER JOIN MFLV_BASEDFITEM I
            ON I.NROEMPRESA = N.NROEMPRESA
           AND I.SEQNF = N.SEQNF
           AND I.TIPNOTAFISCAL = N.TIPNOTAFISCAL
        WHERE N.CODGERALOPER IN (#LT1)
          AND N.TIPNOTAFISCAL = 'S'
          AND NVL(N.STATUSNF, 'A') != 'C'
          AND NVL(N.MODELO, '0') <> '65'
          AND N.DTAEMISSAO >= TRUNC(:DT1)
          AND N.DTAEMISSAO < TRUNC(:DT2) + 1
          AND (
              NVL(TRIM(:LT3), '0') IN ('0', 'TODOS', 'TODAS', '')
              OR INSTR(',' || REPLACE(TRIM(:LT3), ' ', '') || ',', ',' || TO_CHAR(N.NROEMPRESA) || ',') > 0
          )
        GROUP BY
            I.SEQPRODUTO
    ),
    CTE_COMPRAS AS (
        SELECT /*+ MATERIALIZE */
            NI.SEQPRODUTO,
            SUM(NI.QUANTIDADE) AS QTD_COMPRA,
            SUM(NVL(NI.VLRITEM, 0)) AS VLR_COMPRA
        FROM MLF_NOTAFISCAL NF
        INNER JOIN MLF_NFITEM NI
            ON NI.NROEMPRESA = NF.NROEMPRESA
           AND NI.SEQNF = NF.SEQNF
           AND NI.TIPNOTAFISCAL = NF.TIPNOTAFISCAL
        INNER JOIN MAX_CODGERALOPER CGO
            ON CGO.CODGERALOPER = NF.CODGERALOPER
        WHERE NF.TIPNOTAFISCAL = 'E'
          AND (
              CGO.TIPUSO IN ('R', 'C') 
              OR CGO.CODGERALOPER IN (1, 2, 3, 4, 6, 7, 8, 28, 100, 101, 290)
          )
          AND CGO.CODGERALOPER NOT IN (50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 900)
          AND NF.DTAENTRADA >= TRUNC(:DT1)
          AND NF.DTAENTRADA < TRUNC(:DT2) + 1
          AND NVL(NF.STATUSNF, 'A') != 'C'
          AND (
              NVL(TRIM(:LT4), '0') IN ('0', 'TODOS', 'TODAS', '')
              OR INSTR(',' || REPLACE(TRIM(:LT4), ' ', '') || ',', ',' || TO_CHAR(NF.NROEMPRESA) || ',') > 0
          )
        GROUP BY
            NI.SEQPRODUTO
    ),
    PRODUTOS_UNIFICADOS AS (
        SELECT /*+ MATERIALIZE */
            NVL(D.SEQPRODUTO, C.SEQPRODUTO) AS SEQPRODUTO,
            NVL(C.QTD_COMPRA, 0) AS QTD_COMPRA_NUM,
            NVL(C.VLR_COMPRA, 0) AS VLR_COMPRA_NUM,
            NVL(D.QTD_DEV, 0) AS QTD_DEV_NUM,
            NVL(D.VLR_DEV, 0) AS VLR_DEV_NUM
        FROM CTE_DEVOLUCOES D
        FULL OUTER JOIN CTE_COMPRAS C
            ON C.SEQPRODUTO = D.SEQPRODUTO
    ),
    FAMILIAS_ENVOLVIDAS AS (
        SELECT /*+ MATERIALIZE */ DISTINCT
            P.SEQFAMILIA
        FROM PRODUTOS_UNIFICADOS PU
        INNER JOIN MAP_PRODUTO P
            ON P.SEQPRODUTO = PU.SEQPRODUTO
    ),
    CTE_DEPARTAMENTOS AS (
        SELECT /*+ MATERIALIZE */
            FDC.SEQFAMILIA,
            MAX(
                CASE 
                    WHEN C1.NIVELHIERARQUIA = 1 THEN C1.CATEGORIA
                    WHEN C2.NIVELHIERARQUIA = 1 THEN C2.CATEGORIA
                    WHEN C3.NIVELHIERARQUIA = 1 THEN C3.CATEGORIA
                    WHEN C4.NIVELHIERARQUIA = 1 THEN C4.CATEGORIA
                    WHEN C5.NIVELHIERARQUIA = 1 THEN C5.CATEGORIA
                END
            ) AS DEPARTAMENTO
        FROM FAMILIAS_ENVOLVIDAS FE
        INNER JOIN MAP_FAMDIVCATEG FDC
            ON FDC.SEQFAMILIA = FE.SEQFAMILIA
        INNER JOIN MAP_CATEGORIA C1 
            ON C1.SEQCATEGORIA = FDC.SEQCATEGORIA 
           AND C1.NRODIVISAO = FDC.NRODIVISAO
           AND C1.TIPCATEGORIA = 'M'
        LEFT JOIN MAP_CATEGORIA C2 
            ON C2.SEQCATEGORIA = C1.SEQCATEGORIAPAI 
           AND C2.NRODIVISAO = C1.NRODIVISAO
        LEFT JOIN MAP_CATEGORIA C3 
            ON C3.SEQCATEGORIA = C2.SEQCATEGORIAPAI 
           AND C3.NRODIVISAO = C2.NRODIVISAO
        LEFT JOIN MAP_CATEGORIA C4 
            ON C4.SEQCATEGORIA = C3.SEQCATEGORIAPAI 
           AND C4.NRODIVISAO = C3.NRODIVISAO
        LEFT JOIN MAP_CATEGORIA C5 
            ON C5.SEQCATEGORIA = C4.SEQCATEGORIAPAI 
           AND C5.NRODIVISAO = C4.NRODIVISAO
        WHERE FDC.NRODIVISAO = 1
          AND FDC.STATUS = 'A'
          AND UPPER(NVL(C1.CATEGORIA, 'X')) NOT IN ('A CLASSIFICAR', 'ALMOXARIFADO', 'INATIVAR', 'SERVICOS')
        GROUP BY FDC.SEQFAMILIA
    ),
    CTE_FORNEC_FAM AS (
        SELECT /*+ MATERIALIZE */
            F.SEQFAMILIA,
            MAX(CASE WHEN F.PRINCIPAL = 'S' THEN F.SEQFORNECEDOR ELSE NULL END) AS COD_FORN_PRINC,
            MAX(F.SEQFORNECEDOR) AS COD_FORN_QUALQUER,
            MAX(CASE WHEN F.PRINCIPAL = 'S' THEN G.NOMERAZAO ELSE NULL END) AS FORN_PRINC,
            MAX(G.NOMERAZAO) AS FORN_QUALQUER,
            MAX(CASE WHEN F.PRINCIPAL = 'S' THEN R.DESCRICAO ELSE NULL END) AS REDE_PRINC,
            MAX(R.DESCRICAO) AS REDE_QUALQUER
        FROM FAMILIAS_ENVOLVIDAS FE
        INNER JOIN MAP_FAMFORNEC F
            ON F.SEQFAMILIA = FE.SEQFAMILIA
        INNER JOIN GE_PESSOA G
            ON G.SEQPESSOA = F.SEQFORNECEDOR
        LEFT JOIN GE_REDEPESSOA RP
            ON RP.SEQPESSOA = F.SEQFORNECEDOR
        LEFT JOIN GE_REDE R
            ON R.SEQREDE = RP.SEQREDE
        GROUP BY F.SEQFAMILIA
    ),
    DADOS_BASE AS (
        SELECT /*+ MATERIALIZE */
            NVL(DEP.DEPARTAMENTO, 'SEM DEPARTAMENTO') AS DEPARTAMENTO,
            NVL(COMP.COMPRADOR, 'SEM COMPRADOR') AS COMPRADOR,
            COALESCE(FORN.REDE_PRINC, FORN.REDE_QUALQUER, 'SEM REDE') AS REDE,
            COALESCE(FORN.COD_FORN_PRINC, FORN.COD_FORN_QUALQUER, 0) AS CODIGO_FORNECEDOR,
            COALESCE(FORN.FORN_PRINC, FORN.FORN_QUALQUER, 'SEM FORNECEDOR') AS FORNECEDOR,
            PU.SEQPRODUTO AS CODIGO_PRODUTO,
            P.DESCCOMPLETA AS DESCRICAO_PRODUTO,
            PU.QTD_COMPRA_NUM,
            PU.VLR_COMPRA_NUM,
            PU.QTD_DEV_NUM,
            PU.VLR_DEV_NUM
        FROM PRODUTOS_UNIFICADOS PU
        INNER JOIN MAP_PRODUTO P
            ON P.SEQPRODUTO = PU.SEQPRODUTO
        LEFT JOIN CTE_DEPARTAMENTOS DEP
            ON DEP.SEQFAMILIA = P.SEQFAMILIA
        LEFT JOIN CTE_FORNEC_FAM FORN
            ON FORN.SEQFAMILIA = P.SEQFAMILIA
        LEFT JOIN MAP_FAMDIVISAO FD
            ON FD.SEQFAMILIA = P.SEQFAMILIA
           AND FD.NRODIVISAO = 1
        LEFT JOIN MAX_COMPRADOR COMP
            ON COMP.SEQCOMPRADOR = FD.SEQCOMPRADOR
        WHERE (
            NVL(TRIM(:LT2), '0') = '0' 
            OR TO_CHAR(NVL(FORN.COD_FORN_PRINC, 0)) = TRIM(:LT2)
            OR TO_CHAR(NVL(FORN.COD_FORN_QUALQUER, 0)) = TRIM(:LT2)
        )
        AND (
            :LS1 = ' TODAS AS REDES'
            OR NVL(TRIM(:LS1), 'TODOS') IN ('TODOS', '0 - TODOS', '0', '', ' TODAS AS REDES', 'TODAS AS REDES')
            OR UPPER(TRIM(NVL(FORN.REDE_PRINC, ''))) = UPPER(TRIM(:LS1))
            OR UPPER(TRIM(NVL(FORN.REDE_QUALQUER, ''))) = UPPER(TRIM(:LS1))
        )
        AND (PU.VLR_COMPRA_NUM > 0 OR PU.VLR_DEV_NUM > 0)
    ),
    SUBTOTAIS_COMPRADOR AS (
        SELECT /*+ MATERIALIZE */
            D.COMPRADOR,
            SUM(D.QTD_COMPRA_NUM) AS TOTAL_QTD_COMPRA,
            SUM(D.VLR_COMPRA_NUM) AS TOTAL_VLR_COMPRA,
            SUM(D.QTD_DEV_NUM) AS TOTAL_QTD_DEV,
            SUM(D.VLR_DEV_NUM) AS TOTAL_VLR_DEV
        FROM DADOS_BASE D
        GROUP BY D.COMPRADOR
    ),
    UNIAO_RELATORIO AS (
        SELECT
            1 AS ORDEM_BLOCO,
            DEPARTAMENTO,
            COMPRADOR,
            REDE,
            CODIGO_FORNECEDOR,
            FORNECEDOR,
            CODIGO_PRODUTO,
            DESCRICAO_PRODUTO,
            '    ' || TO_CHAR(ROUND(QTD_COMPRA_NUM, 2), 'FM999G999G990D00') AS QUANTIDADE_COMPRADA,
            'R$     ' || TO_CHAR(ROUND(VLR_COMPRA_NUM, 2), 'FM999G999G999G990D00') AS VALOR_COMPRAS,
            '    ' || TO_CHAR(ROUND(QTD_DEV_NUM, 2), 'FM999G999G990D00') AS QUANTIDADE_DEVOLVIDA,
            'R$     ' || TO_CHAR(ROUND(VLR_DEV_NUM, 2), 'FM999G999G999G990D00') AS VALOR_DEVOLUCOES,
            CASE
                WHEN VLR_COMPRA_NUM > 0 THEN TO_CHAR(ROUND((VLR_DEV_NUM / VLR_COMPRA_NUM) * 100, 2), 'FM990D00') || '%'
                WHEN VLR_DEV_NUM > 0 THEN '100,00%'
                ELSE '0,00%'
            END AS PERC_DEVOLUCAO_SOBRE_COMPRA
        FROM DADOS_BASE
        
        UNION ALL
        
        SELECT
            2 AS ORDEM_BLOCO,
            '--' AS DEPARTAMENTO,
            SC.COMPRADOR AS COMPRADOR,
            '--' AS REDE,
            0 AS CODIGO_FORNECEDOR,
            'SUBTOTAL -> ' || SC.COMPRADOR AS FORNECEDOR,
            0 AS CODIGO_PRODUTO,
            'SUBTOTAL DO COMPRADOR' AS DESCRICAO_PRODUTO,
            '    ' || TO_CHAR(ROUND(SC.TOTAL_QTD_COMPRA, 2), 'FM999G999G990D00') AS QUANTIDADE_COMPRADA,
            'R$     ' || TO_CHAR(ROUND(SC.TOTAL_VLR_COMPRA, 2), 'FM999G999G999G990D00') AS VALOR_COMPRAS,
            '    ' || TO_CHAR(ROUND(SC.TOTAL_QTD_DEV, 2), 'FM999G999G990D00') AS QUANTIDADE_DEVOLVIDA,
            'R$     ' || TO_CHAR(ROUND(SC.TOTAL_VLR_DEV, 2), 'FM999G999G999G990D00') AS VALOR_DEVOLUCOES,
            CASE
                WHEN SC.TOTAL_VLR_COMPRA > 0 THEN TO_CHAR(ROUND((SC.TOTAL_VLR_DEV / SC.TOTAL_VLR_COMPRA) * 100, 2), 'FM990D00') || '%'
                WHEN SC.TOTAL_VLR_DEV > 0 THEN '100,00%'
                ELSE '0,00%'
            END AS PERC_DEVOLUCAO_SOBRE_COMPRA
        FROM SUBTOTAIS_COMPRADOR SC
        
        UNION ALL
        
        SELECT
            3 AS ORDEM_BLOCO,
            '--' AS DEPARTAMENTO,
            '--' AS COMPRADOR,
            '--' AS REDE,
            0 AS CODIGO_FORNECEDOR,
            'TOTAL GERAL ->' AS FORNECEDOR,
            0 AS CODIGO_PRODUTO,
            'TOTAL GERAL CONSOLIDADO' AS DESCRICAO_PRODUTO,
            '    ' || TO_CHAR(ROUND(NVL(SUM(D.QTD_COMPRA_NUM), 0), 2), 'FM999G999G990D00') AS QUANTIDADE_COMPRADA,
            'R$     ' || TO_CHAR(ROUND(NVL(SUM(D.VLR_COMPRA_NUM), 0), 2), 'FM999G999G999G990D00') AS VALOR_COMPRAS,
            '    ' || TO_CHAR(ROUND(NVL(SUM(D.QTD_DEV_NUM), 0), 2), 'FM999G999G990D00') AS QUANTIDADE_DEVOLVIDA,
            'R$     ' || TO_CHAR(ROUND(NVL(SUM(D.VLR_DEV_NUM), 0), 2), 'FM999G999G999G990D00') AS VALOR_DEVOLUCOES,
            CASE
                WHEN SUM(D.VLR_COMPRA_NUM) > 0 THEN TO_CHAR(ROUND((SUM(D.VLR_DEV_NUM) / SUM(D.VLR_COMPRA_NUM)) * 100, 2), 'FM990D00') || '%'
                WHEN SUM(D.VLR_DEV_NUM) > 0 THEN '100,00%'
                ELSE '0,00%'
            END AS PERC_DEVOLUCAO_SOBRE_COMPRA
        FROM DADOS_BASE D
    )
    SELECT
        DEPARTAMENTO,
        COMPRADOR,
        REDE,
        CODIGO_FORNECEDOR,
        FORNECEDOR,
        CODIGO_PRODUTO,
        DESCRICAO_PRODUTO,
        QUANTIDADE_COMPRADA,
        VALOR_COMPRAS,
        QUANTIDADE_DEVOLVIDA,
        VALOR_DEVOLUCOES,
        PERC_DEVOLUCAO_SOBRE_COMPRA
    FROM UNIAO_RELATORIO
    ORDER BY
        ORDEM_BLOCO ASC,
        CASE WHEN ORDEM_BLOCO = 2 THEN COMPRADOR ELSE NULL END ASC,
        COMPRADOR ASC,
        VALOR_DEVOLUCOES DESC,
        CODIGO_PRODUTO ASC
)
