SELECT * FROM (

    WITH CATEGORIAS AS (
        SELECT /*+ MATERIALIZE */
            X.SEQFAMILIA,
            MAX(CASE WHEN Y.NIVELHIERARQUIA = 1 THEN Y.CATEGORIA END) AS DEPARTAMENTO,
            MAX(CASE WHEN Y.NIVELHIERARQUIA = 2 THEN Y.CATEGORIA END) AS GRUPO,
            MAX(CASE WHEN Y.NIVELHIERARQUIA = 3 THEN Y.CATEGORIA END) AS SUBGRUPO,
            MAX(CASE WHEN Y.NIVELHIERARQUIA = 4 THEN Y.CATEGORIA END) AS NIVEL_4,
            MAX(CASE WHEN Y.NIVELHIERARQUIA = 5 THEN Y.CATEGORIA END) AS NIVEL_5
        FROM MAP_FAMDIVCATEG X
        JOIN MAP_CATEGORIA Y ON Y.SEQCATEGORIA = X.SEQCATEGORIA AND Y.NRODIVISAO = X.NRODIVISAO
        WHERE Y.TIPCATEGORIA = 'M'
          AND Y.NIVELHIERARQUIA IN (1, 2, 3, 4, 5)
          AND X.STATUS = 'A'
          AND X.NRODIVISAO = 1
        GROUP BY X.SEQFAMILIA
    )
    SELECT DISTINCT
        CAT.DEPARTAMENTO AS DEPARTAMENTO,
        CAT.GRUPO AS GRUPO,
        CAT.SUBGRUPO AS SUBGRUPO,
        CAT.NIVEL_4 AS NIVEL_4,
        CAT.NIVEL_5 AS NIVEL_5,
        B.CODACESSO AS EAN_DUN,
        A.SEQPRODUTO AS SEQPRODUTO,
        A.DESCCOMPLETA AS DESCRICAO_PRODUTO,
        ROUND(
            NVL(
                FC5MARGEMPRECOCADDESPOPER(
                    A.SEQPRODUTO,
                    ME.NROEMPRESA,
                    ME.NROSEGMENTOPRINC,
                    NVL(FS.PADRAOEMBVENDA, 1),
                    'M'
                ),
                0
            ),
            2
        ) AS MARGEM_OBJETIVA
    FROM MAP_PRODUTO A
    INNER JOIN MAP_PRODCODIGO B ON B.SEQPRODUTO = A.SEQPRODUTO
    INNER JOIN CATEGORIAS CAT ON CAT.SEQFAMILIA = A.SEQFAMILIA
    INNER JOIN MRL_PRODUTOEMPRESA PE ON PE.SEQPRODUTO = A.SEQPRODUTO
    INNER JOIN MAX_EMPRESA ME ON ME.NROEMPRESA = PE.NROEMPRESA
    LEFT JOIN MAD_FAMSEGMENTO FS ON FS.SEQFAMILIA = A.SEQFAMILIA AND FS.NROSEGMENTO = ME.NROSEGMENTOPRINC
    WHERE B.TIPCODIGO IN ('E', 'D')
      AND PE.STATUSCOMPRA = 'A'
      AND PE.NROEMPRESA IN (1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 14, 15, 17, 18)
      AND CAT.DEPARTAMENTO IS NOT NULL
      AND UPPER(CAT.DEPARTAMENTO) NOT IN ('A CLASSIFICAR', 'ALMOXARIFADO', 'INATIVAR', 'SERVICOS')
      AND (
          UPPER(CAT.DEPARTAMENTO) LIKE '%BEBIDA%'
       OR UPPER(CAT.DEPARTAMENTO) LIKE '%MERCEARIA%'
       OR UPPER(CAT.DEPARTAMENTO) LIKE '%PERFUMARIA%'
       OR UPPER(CAT.DEPARTAMENTO) LIKE '%LIMPEZA%'
       OR UPPER(CAT.DEPARTAMENTO) LIKE '%PET%'
      )
      AND (NVL(:NR1, 0) = 0 OR A.SEQPRODUTO = :NR1)
    ORDER BY
        CAT.DEPARTAMENTO,
        CAT.GRUPO,
        CAT.SUBGRUPO,
        CAT.NIVEL_4,
        CAT.NIVEL_5,
        A.DESCCOMPLETA,
        A.SEQPRODUTO,
        B.CODACESSO

)