SELECT * FROM (
    WITH PRODUTOS_FORNECEDOR AS (
        SELECT /*+ MATERIALIZE */
            P.SEQPRODUTO,
            P.DESCCOMPLETA,
            P.SEQFAMILIA
        FROM MAP_PRODUTO P
        INNER JOIN MAP_FAMFORNEC FF 
            ON FF.SEQFAMILIA = P.SEQFAMILIA
        WHERE (NVL(:NR1, 0) = 0 OR FF.SEQFORNECEDOR = :NR1)
    ),
    STATUS_EMPRESA_15 AS (
        SELECT /*+ MATERIALIZE */
            PE.SEQPRODUTO,
            PE.STATUSCOMPRA,
            PE.FORMAABASTECIMENTO
        FROM MRL_PRODUTOEMPRESA PE
        INNER JOIN PRODUTOS_FORNECEDOR PF 
            ON PF.SEQPRODUTO = PE.SEQPRODUTO
        WHERE PE.NROEMPRESA = 15
          AND PE.STATUSCOMPRA = 'A'
    )
    SELECT DISTINCT
        PF.SEQPRODUTO,
        PF.DESCCOMPLETA,
        PF.SEQFAMILIA,
        NVL(COMP.APELIDO, COMP.COMPRADOR) AS APELIDO_COMPRADOR,
        NVL(SE.FORMAABASTECIMENTO, FD.FORMAABASTECIMENTO) AS FORMA_ABASTECIMENTO,
        SE.STATUSCOMPRA AS STATUS_EMPRESA_15
    FROM PRODUTOS_FORNECEDOR PF
    INNER JOIN STATUS_EMPRESA_15 SE 
        ON SE.SEQPRODUTO = PF.SEQPRODUTO
    LEFT JOIN MAP_FAMDIVISAO FD 
        ON FD.SEQFAMILIA = PF.SEQFAMILIA 
       AND FD.NRODIVISAO = 1
    LEFT JOIN MAX_COMPRADOR COMP 
        ON COMP.SEQCOMPRADOR = FD.SEQCOMPRADOR
    ORDER BY
        PF.DESCCOMPLETA ASC
)
