SELECT
  C.CATEGORIA AS DEPARTAMENTO,
    A.SEQPRODUTO AS CODIGO_PRODUTO,
    A.DESCCOMPLETA AS DESCRICAO_PRODUTO,
    Y.NROEMPRESA AS EMPRESA,
    CASE WHEN Y.STATUSCOMPRA = 'A' THEN 'ATIVO' ELSE 'INATIVO' END AS STATUS,
    (NVL(Y.ESTQLOJA, 0) + NVL(Y.ESTQDEPOSITO, 0) - NVL(Y.QTDRESERVADAVDA, 0) - NVL(Y.QTDRESERVADARECEB, 0)) AS ESTOQUE,
    NVL(Y.QTDPENDPEDCOMPRA, 0) AS PEDIDOS_PENDENTES,
    TO_CHAR(TRUNC(A.DTAHORINCLUSAO), 'DD/MM/YYYY') AS DATA_CADASTRO_PRODUTO,
    NVL(V.QTD_VENDIDA, 0) AS QTD_VENDIDA_PERIODO
FROM MAP_PRODUTO A
INNER JOIN MRL_PRODUTOEMPRESA Y ON Y.SEQPRODUTO = A.SEQPRODUTO
INNER JOIN MAX_EMPRESA E ON E.NROEMPRESA = Y.NROEMPRESA
INNER JOIN MAP_FAMDIVCATEG FDC ON FDC.SEQFAMILIA = A.SEQFAMILIA AND FDC.NRODIVISAO = 1 AND FDC.STATUS = 'A'
INNER JOIN MAP_CATEGORIA C ON C.SEQCATEGORIA = FDC.SEQCATEGORIA AND C.NRODIVISAO = 1 AND C.NIVELHIERARQUIA = 1 AND C.STATUSCATEGOR = 'A'
LEFT JOIN (
    SELECT
        CUST.SEQPRODUTO,
        CUST.NROEMPRESA,
        ROUND(NVL(SUM(CUST.QTDVDA), 0), 2) AS QTD_VENDIDA
    FROM MRL_CUSTODIA CUST
    WHERE CUST.DTAENTRADASAIDA >= TRUNC(SYSDATE) - 90
      AND CUST.DTAENTRADASAIDA < TRUNC(SYSDATE)
    GROUP BY CUST.SEQPRODUTO, CUST.NROEMPRESA
) V ON V.SEQPRODUTO = Y.SEQPRODUTO AND V.NROEMPRESA = Y.NROEMPRESA
WHERE Y.NROEMPRESA IN (1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 14, 15, 17, 18)
  AND Y.STATUSCOMPRA = 'A'
  AND UPPER(C.CATEGORIA) NOT IN ('A CLASSIFICAR', 'ALMOXARIFADO', 'INATIVAR')
  AND (NVL(TRIM(:LT1), 'TODOS') = 'TODOS' OR UPPER(C.CATEGORIA) = UPPER(TRIM(:LT1)))
  AND NVL(V.QTD_VENDIDA, 0) < NVL(:NR1, 2)
  AND (NVL(Y.ESTQLOJA, 0) + NVL(Y.ESTQDEPOSITO, 0) - NVL(Y.QTDRESERVADAVDA, 0) - NVL(Y.QTDRESERVADARECEB, 0)) < NVL(:NR2, 2)
  AND NVL(Y.QTDPENDPEDCOMPRA, 0) < NVL(:NR3, 2)
  AND (NVL(:NR4, 0) = 0 OR TRUNC(A.DTAHORINCLUSAO) <= TRUNC(SYSDATE) - NVL(:NR4, 0))
ORDER BY Y.NROEMPRESA, A.DESCCOMPLETA