SELECT * FROM (
    SELECT
        C.CATEGORIA AS DEPARTAMENTO,
        NVL(COMP.APELIDO, COMP.COMPRADOR) AS APELIDO_COMPRADOR,
        A.SEQPRODUTO,
        A.DESCCOMPLETA,
        D.FORMAABASTECIMENTO AS FORMA_ABASTECIMENTO,
        B.NROEMPRESA AS EMPRESA_CD,
        NVL(B.ESTQLOJA, 0) + NVL(B.ESTQDEPOSITO, 0) - NVL(B.QTDRESERVADAVDA, 0) - NVL(B.QTDRESERVADARECEB, 0) AS ESTOQUE_ATUAL,
        TO_CHAR(TRUNC(B.DTAULTMOVSAIDA), 'DD/MM/YYYY') AS DATA_ULT_SAIDA,
        TRUNC(SYSDATE) - TRUNC(NVL(B.DTAULTMOVSAIDA, A.DTAHORINCLUSAO)) AS DIAS_SEM_SAIDA,
        TO_CHAR(TRUNC(NVL(B.DTAULTMOVENTRADA, B.DTAULTCOMPRA)), 'DD/MM/YYYY') AS DATA_ULT_ENTRADA,
        TRUNC(SYSDATE) - TRUNC(NVL(NVL(B.DTAULTMOVENTRADA, B.DTAULTCOMPRA), A.DTAHORINCLUSAO)) AS DIAS_SEM_ENTRADA,
        TO_CHAR(TRUNC(A.DTAHORINCLUSAO), 'DD/MM/YYYY') AS DATA_CADASTRO
    FROM MAP_PRODUTO A
    INNER JOIN MRL_PRODUTOEMPRESA B ON A.SEQPRODUTO = B.SEQPRODUTO
    INNER JOIN MAP_FAMDIVCATEG F ON A.SEQFAMILIA = F.SEQFAMILIA AND F.NRODIVISAO = 1 AND F.STATUS = 'A'
    INNER JOIN MAP_CATEGORIA C ON F.SEQCATEGORIA = C.SEQCATEGORIA AND C.NIVELHIERARQUIA = 1 AND C.TIPCATEGORIA = 'M'
    INNER JOIN MAP_FAMDIVISAO D ON A.SEQFAMILIA = D.SEQFAMILIA AND D.NRODIVISAO = 1
    LEFT JOIN MAX_COMPRADOR COMP ON D.SEQCOMPRADOR = COMP.SEQCOMPRADOR
    WHERE B.STATUSCOMPRA = 'A'
      AND (A.SEQPRODUTO = NVL(TO_NUMBER(:NR1), 0) OR NVL(TO_NUMBER(:NR1), 0) = 0)
      AND (',' || :LT1 || ',' LIKE '%,' || B.NROEMPRESA || ',%')
      AND INSTR(',' || UPPER(REPLACE(NVL(:LT3, 'M,C,I,L'), ' ', '')) || ',', ',' || UPPER(TRIM(D.FORMAABASTECIMENTO)) || ',') > 0
      AND (TRUNC(SYSDATE) - TRUNC(A.DTAHORINCLUSAO)) >= NVL(TO_NUMBER(:NR4), 0)
      AND D.FINALIDADEFAMILIA = 'R'
      AND UPPER(C.CATEGORIA) NOT LIKE '%ALMOX%'
      AND UPPER(C.CATEGORIA) NOT LIKE '%SERVI%'
      AND UPPER(C.CATEGORIA) NOT LIKE '%ALIMENTO%'
      AND (TRUNC(SYSDATE) - TRUNC(NVL(B.DTAULTMOVSAIDA, A.DTAHORINCLUSAO))) >= NVL(TO_NUMBER(:NR2), 0)
      AND (TRUNC(SYSDATE) - TRUNC(NVL(NVL(B.DTAULTMOVENTRADA, B.DTAULTCOMPRA), A.DTAHORINCLUSAO))) >= NVL(TO_NUMBER(:NR3), 0)
      AND NOT EXISTS (
          SELECT 1
          FROM MAP_FAMDIVCATEG FDC2
          JOIN MAP_CATEGORIA C2 ON C2.SEQCATEGORIA = FDC2.SEQCATEGORIA AND C2.NRODIVISAO = 1 AND C2.STATUSCATEGOR = 'A'
          WHERE FDC2.SEQFAMILIA = A.SEQFAMILIA
            AND FDC2.NRODIVISAO = 1
            AND FDC2.STATUS = 'A'
            AND (
                (C2.NIVELHIERARQUIA = 2 AND REPLACE(UPPER(C2.CATEGORIA), '_', ' ') IN ('FRUTAS E VERDURAS', 'PADARIA BAKLIZI', 'PADARIA INDUSTRIAL'))
                OR EXISTS (
                    SELECT 1 
                    FROM MAP_CATEGORIA PAI
                    WHERE PAI.SEQCATEGORIA = C2.SEQCATEGORIAPAI
                      AND PAI.NRODIVISAO = 1
                      AND PAI.NIVELHIERARQUIA = 2
                      AND PAI.STATUSCATEGOR = 'A'
                      AND REPLACE(UPPER(PAI.CATEGORIA), '_', ' ') IN ('FRUTAS E VERDURAS', 'PADARIA BAKLIZI', 'PADARIA INDUSTRIAL')
                )
            )
      )
)
WHERE 
    TRIM(:LT2) IS NULL 
    OR ( :LT2 LIKE '>%'  AND :LT2 NOT LIKE '>=%' AND ESTOQUE_ATUAL >  TO_NUMBER(REGEXP_REPLACE(:LT2, '[^0-9-]', '')) )
    OR ( :LT2 LIKE '<%'  AND :LT2 NOT LIKE '<=%' AND ESTOQUE_ATUAL <  TO_NUMBER(REGEXP_REPLACE(:LT2, '[^0-9-]', '')) )
    OR ( :LT2 LIKE '=%'  AND ESTOQUE_ATUAL =  TO_NUMBER(REGEXP_REPLACE(:LT2, '[^0-9-]', '')) )
    OR ( :LT2 LIKE '>=%' AND ESTOQUE_ATUAL >= TO_NUMBER(REGEXP_REPLACE(:LT2, '[^0-9-]', '')) )
    OR ( :LT2 LIKE '<=%' AND ESTOQUE_ATUAL <= TO_NUMBER(REGEXP_REPLACE(:LT2, '[^0-9-]', '')) )
    OR ( :LT2 NOT LIKE '<%' AND :LT2 NOT LIKE '>%' AND :LT2 NOT LIKE '=%' AND ESTOQUE_ATUAL = TO_NUMBER(REGEXP_REPLACE(:LT2, '[^0-9-]', '')) )
ORDER BY DEPARTAMENTO ASC, EMPRESA_CD ASC, DESCCOMPLETA ASC
