SELECT * FROM (
WITH DADOS_NF AS (
    SELECT /*+ MATERIALIZE */
        N.NROEMPRESA,
        N.NUMERONF,
        N.SEQNF,
        N.TIPNOTAFISCAL,
        N.SEQPESSOA,
        F.NOMERAZAO AS FORNECEDOR,
        NVL(MAX(R.DESCRICAO), 'SEM REDE') AS REDE,
        N.DTAEMISSAO,
        MAX(COALESCE(NULLIF(TRIM(I.OBSERVACAO), ''), NULLIF(TRIM(N.OBSERVACAOLF), ''))) AS OBSERVACAO,
        SUM(NVL(I.VLRITEM, 0)) AS VALOR_TOTAL_SEM_IMPOSTOS_NUM,
        SUM(NVL(I.VLRITEM, 0) + NVL(I.VLRIPI, 0) + NVL(I.VLRICMSST, 0)) AS VALOR_TOTAL_COM_IMPOSTOS_NUM
    FROM MLFV_BASENFE N
    JOIN MFLV_BASEDFITEM I
        ON I.SEQNF = N.SEQNF
       AND I.NROEMPRESA = N.NROEMPRESA
       AND I.TIPNOTAFISCAL = N.TIPNOTAFISCAL
    LEFT JOIN GE_PESSOA F
        ON F.SEQPESSOA = N.SEQPESSOA
    LEFT JOIN GE_REDEPESSOA RP
        ON RP.SEQPESSOA = N.SEQPESSOA
    LEFT JOIN GE_REDE R
        ON R.SEQREDE = RP.SEQREDE
    WHERE (:NR1 = 0 OR N.SEQPESSOA = :NR1)
      AND N.CODGERALOPER IN (802, 860)
      AND N.DTAEMISSAO BETWEEN :DT1 AND :DT2
      AND N.STATUSNF != 'C'
      AND N.NROEMPRESA IN (1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 14, 15, 16, 17, 18, 50)
      AND (
          :LS1 = ' TODAS AS REDES'
          OR NVL(TRIM(:LS1), 'TODOS') IN ('TODOS', '0 - TODOS', '0', '', ' TODAS AS REDES', 'TODAS AS REDES')
          OR UPPER(TRIM(R.DESCRICAO)) = UPPER(TRIM(:LS1))
      )
    GROUP BY
        N.NROEMPRESA,
        N.NUMERONF,
        N.SEQNF,
        N.TIPNOTAFISCAL,
        N.SEQPESSOA,
        F.NOMERAZAO,
        N.DTAEMISSAO
), PRODUTOS_NF AS (
    SELECT /*+ MATERIALIZE */
        I.SEQNF,
        I.NROEMPRESA,
        I.TIPNOTAFISCAL,
        LISTAGG(TO_CHAR(I.SEQPRODUTO), ' / ') WITHIN GROUP (ORDER BY I.SEQPRODUTO) AS CODIGOS_PRODUTOS,
        LISTAGG(P.DESCCOMPLETA, ' / ') WITHIN GROUP (ORDER BY I.SEQPRODUTO) AS DESCRICOES_PRODUTOS
    FROM MFLV_BASEDFITEM I
    JOIN DADOS_NF D
        ON D.SEQNF = I.SEQNF
       AND D.NROEMPRESA = I.NROEMPRESA
       AND D.TIPNOTAFISCAL = I.TIPNOTAFISCAL
    JOIN MAP_PRODUTO P
        ON P.SEQPRODUTO = I.SEQPRODUTO
    GROUP BY
        I.SEQNF,
        I.NROEMPRESA,
        I.TIPNOTAFISCAL
)
SELECT
    D.NROEMPRESA AS LOJA,
    D.NUMERONF AS NF,
    D.REDE,
    D.SEQPESSOA AS CODIGO_FORNECEDOR,
    D.FORNECEDOR,
    TO_CHAR(D.DTAEMISSAO, 'DD/MM/YYYY') AS DATA_EMISSAO,
    'R$ ' || TO_CHAR(ROUND(D.VALOR_TOTAL_SEM_IMPOSTOS_NUM, 2), 'FM999G999D00') AS VALOR_TOTAL_SEM_IMPOSTOS,
    'R$ ' || TO_CHAR(ROUND(D.VALOR_TOTAL_COM_IMPOSTOS_NUM, 2), 'FM999G999D00') AS VALOR_TOTAL_COM_IMPOSTOS,
    D.OBSERVACAO,
    P.CODIGOS_PRODUTOS,
    P.DESCRICOES_PRODUTOS
FROM DADOS_NF D
LEFT JOIN PRODUTOS_NF P
    ON P.SEQNF = D.SEQNF
   AND P.NROEMPRESA = D.NROEMPRESA
   AND P.TIPNOTAFISCAL = D.TIPNOTAFISCAL
ORDER BY
    D.DTAEMISSAO,
    D.NUMERONF
)