SELECT
    DEP.DEPARTAMENTO,
    P.SEQPRODUTO AS CODIGO_PRODUTO,
    P.DESCCOMPLETA AS DESCRICAO_PRODUTO,
    PE.STATUSCOMPRA AS STATUS_COMPRA,
    NVL(TC.CODIGO_TRANSICAO, TO_CHAR(P.SEQPRODUTOBASEANTIGO)) AS CODIGO_TRANSICAO
FROM MAP_PRODUTO P
INNER JOIN MRL_PRODUTOEMPRESA PE
    ON PE.SEQPRODUTO = P.SEQPRODUTO
INNER JOIN MAX_EMPRESA E
    ON E.NROEMPRESA = PE.NROEMPRESA
INNER JOIN MAP_FAMDIVISAO FD
    ON FD.SEQFAMILIA = P.SEQFAMILIA
   AND FD.NRODIVISAO = E.NRODIVISAO
INNER JOIN (
    SELECT
        X.SEQFAMILIA,
        X.NRODIVISAO,
        MAX(Y.CATEGORIA) AS DEPARTAMENTO
    FROM MAP_FAMDIVCATEG X
    INNER JOIN MAP_CATEGORIA Y
        ON Y.SEQCATEGORIA = X.SEQCATEGORIA
       AND Y.NRODIVISAO = X.NRODIVISAO
    WHERE X.STATUS = 'A'
      AND Y.STATUSCATEGOR = 'A'
      AND Y.TIPCATEGORIA = 'M'
      AND Y.NIVELHIERARQUIA = 1
      AND UPPER(Y.CATEGORIA) NOT IN ('A CLASSIFICAR', 'ALMOXARIFADO', 'INATIVAR', 'SERVICOS')
    GROUP BY
        X.SEQFAMILIA,
        X.NRODIVISAO
) DEP
    ON DEP.SEQFAMILIA = P.SEQFAMILIA
   AND DEP.NRODIVISAO = E.NRODIVISAO
LEFT JOIN (
    SELECT
        C.SEQPRODUTO,
        MAX(C.CODACESSO) KEEP (
            DENSE_RANK FIRST ORDER BY
                CASE
                    WHEN NVL(C.TIPCODIGO, 'X') = 'I' AND NVL(C.QTDEMBALAGEM, 0) = 1 THEN 0
                    WHEN NVL(C.TIPCODIGO, 'X') = 'I' THEN 1
                    WHEN C.DTAINIUTILCODTRANS IS NOT NULL OR C.DTAFINALUTILCODTRANS IS NOT NULL THEN 2
                    ELSE 3
                END,
                CASE
                    WHEN NVL(C.QTDEMBALAGEM, 0) = 1 THEN 0
                    ELSE 1
                END,
                NVL(C.DTAFINALUTILCODTRANS, DATE '2999-12-31') DESC,
                NVL(C.DTAINIUTILCODTRANS, DATE '1900-01-01') DESC,
                C.CODACESSO DESC
        ) AS CODIGO_TRANSICAO
    FROM MAP_PRODCODIGO C
    WHERE C.CODACESSO IS NOT NULL
      AND (
                        NVL(C.TIPCODIGO, 'X') = 'I'
            OR C.DTAINIUTILCODTRANS IS NOT NULL
            OR C.DTAFINALUTILCODTRANS IS NOT NULL
      )
    GROUP BY
        C.SEQPRODUTO
) TC
    ON TC.SEQPRODUTO = P.SEQPRODUTO
WHERE PE.NROEMPRESA IN (#LT1)
  AND PE.NROEMPRESA IN (1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 14, 15, 17, 18)
  AND PE.STATUSCOMPRA = 'A'
  AND FD.FINALIDADEFAMILIA = 'R'
ORDER BY
    DEP.DEPARTAMENTO,
    P.DESCCOMPLETA,
    P.SEQPRODUTO