SELECT 
    R.NROEMPRESA AS LOJA_DESTINO,
    R.SEQPRODUTO AS CODIGO_PRODUTO,
    M.DESCCOMPLETA AS DESCRICAO_PRODUTO,
    PS.SEQFORNECEDOR AS CODIGO_ORIGEM,
    (SELECT NOMERAZAO FROM GE_PESSOA WHERE SEQPESSOA = PS.SEQFORNECEDOR) AS NOME_ORIGEM,
    SUM(NVL(R.QTDTOTTRANSITO, 0)) AS QTD_EM_TRANSITO
FROM MSU_PSITEMRECEBER R
JOIN MSU_PEDIDOSUPRIM PS 
  ON PS.NROPEDIDOSUPRIM = R.NROPEDIDOSUPRIM 
 AND PS.NROEMPRESA = R.NROEMPRESA
LEFT JOIN MAP_PRODUTO M ON M.SEQPRODUTO = R.SEQPRODUTO
WHERE R.NROEMPRESA IN (1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 14, 17, 18)
  AND NVL(R.QTDTOTTRANSITO, 0) > 0
  AND ('#LT1' = '0' OR PS.SEQFORNECEDOR IN (#LT1))
GROUP BY R.NROEMPRESA, R.SEQPRODUTO, M.DESCCOMPLETA, PS.SEQFORNECEDOR
ORDER BY QTD_EM_TRANSITO DESC;
