SELECT
  M.PROMOCAO,
  TO_CHAR(M.DTAINICIO, 'DD/MM/YYYY') AS DTAINICIO,
  TO_CHAR(M.DTAFIM, 'DD/MM/YYYY') AS DTAFIM,
  M.NROEMPRESA AS LOJA,
  M.SEQPROMOCAO AS NOME,
  M.SEQPRODUTO AS COD,
  M.DESCCOMPLETA AS DESCRICAO,
  M.PRECONORMAL AS PRECO,
  TO_CHAR(M.MGMNORMAL, 'FM999G999D99') AS MGNORMAL,
  M.PRECOPROMOCIONAL AS PROMO,
  TO_CHAR(M.MGMPROMOC, 'FM999G999D99') AS MGPROMOC
FROM
  MRLV_BASEPRODPROMOC M
  JOIN MAD_SEGMENTO S ON M.NROSEGMENTO = S.NROSEGMENTO
WHERE
  M.CENTRALLOJA = 'C'
  AND M.NROEMPRESA IN (#LT2)
  AND M.PRINCIPAL = 'S'
  AND M.PROMOCAO = :LT1
  AND M.DTAINICIO <= :DT2
  AND M.DTAFIM >= :DT1
ORDER BY
  M.SEQPROMOCAO, M.DESCCOMPLETA, M.NROEMPRESA