SELECT * FROM (
    WITH EAN_PRODUTO AS (
        SELECT /*+ MATERIALIZE */
            SEQPRODUTO,
            CODACESSO AS EAN
        FROM (
            SELECT
                C.SEQPRODUTO,
                C.CODACESSO,
                ROW_NUMBER() OVER (PARTITION BY C.SEQPRODUTO ORDER BY DECODE(C.TIPCODIGO, 'E', 1, 'D', 2, 3) ASC, C.CODACESSO ASC) AS RN
            FROM MAP_PRODCODIGO C
            WHERE C.TIPCODIGO IN ('E', 'D')
        )
        WHERE RN = 1
    )
    SELECT
        A.SEQPRODUTO AS CODIGO_PRODUTO,
        E.EAN AS EAN,
        A.DESCCOMPLETA AS DESCRICAO_PRODUTO,
        ME.NROEMPRESA AS CODIGO_EMPRESA,
        NVL(FS.PADRAOEMBVENDA, 1) AS EMBALAGEM_VENDA,
        TO_CHAR(FD.SEQCOMPRADOR) || ' - ' || NVL(C.APELIDO, C.COMPRADOR) AS COMPRADOR,
        ROUND(NVL(S.PRECOVALIDNORMAL, 0), 2) AS PRECO_NORMAL,
        ROUND(NVL(S.PRECOVALIDPROMOC, 0), 2) AS PRECO_PROMOCIONAL,
        ROUND(NVL(NULLIF(S.PRECOVALIDPROMOC, 0), S.PRECOVALIDNORMAL), 2) AS PRECO_PRATICADO_DIA
    FROM MAP_PRODUTO A
    JOIN MRL_PRODUTOEMPRESA PE ON PE.SEQPRODUTO = A.SEQPRODUTO
    JOIN MAX_EMPRESA ME ON ME.NROEMPRESA = PE.NROEMPRESA
    LEFT JOIN EAN_PRODUTO E ON E.SEQPRODUTO = A.SEQPRODUTO
    LEFT JOIN MAP_FAMDIVISAO FD ON FD.SEQFAMILIA = A.SEQFAMILIA
                               AND FD.NRODIVISAO = ME.NRODIVISAO
    LEFT JOIN MAX_COMPRADOR C ON C.SEQCOMPRADOR = FD.SEQCOMPRADOR
    LEFT JOIN MAD_FAMSEGMENTO FS ON FS.SEQFAMILIA = A.SEQFAMILIA
                                AND FS.NROSEGMENTO = ME.NROSEGMENTOPRINC
    LEFT JOIN MRL_PRODEMPSEG S ON S.SEQPRODUTO = A.SEQPRODUTO
                              AND S.NROEMPRESA = ME.NROEMPRESA
                              AND S.NROSEGMENTO = ME.NROSEGMENTOPRINC
                              AND S.QTDEMBALAGEM = NVL(FS.PADRAOEMBVENDA, 1)
    WHERE PE.NROEMPRESA IN (1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 14, 15, 17, 18)
      AND PE.STATUSCOMPRA = 'A'
      AND ((:LS1 = '0 - TODOS') OR NVL(FD.SEQCOMPRADOR, 0) = TO_NUMBER(SUBSTR(:LS1, 1, INSTR(:LS1, ' - ') - 1)))
      AND (NVL(:NR1, 0) = 0 OR PE.NROEMPRESA = :NR1)
      AND (NVL(:NR2, 0) = 0 OR A.SEQPRODUTO = :NR2)
    ORDER BY PE.NROEMPRESA, A.SEQPRODUTO
)
