SELECT 
    MLF_NOTAFISCAL.SEQPESSOA AS CODIGO_FORNECEDOR,
    GE_PESSOA.NOMERAZAO AS DESCRICAO_FORNECEDOR,
    SUBSTR(FC5MASKCNPJCPF(GE_PESSOA.NROCGCCPF, GE_PESSOA.DIGCGCCPF, GE_PESSOA.FISICAJURIDICA), 1, 20) AS CNPJ,
    SUM(NVL(MLF_NFITEM.VLRTOTALITEM, 0)) AS VALOR_TOTAL_FATURADO
FROM MLF_NOTAFISCAL
INNER JOIN MLF_NFITEM ON MLF_NFITEM.NUMERONF = MLF_NOTAFISCAL.NUMERONF 
                     AND MLF_NFITEM.SERIENF = MLF_NOTAFISCAL.SERIENF 
                     AND MLF_NFITEM.NROEMPRESA = MLF_NOTAFISCAL.NROEMPRESA 
                     AND MLF_NFITEM.TIPNOTAFISCAL = MLF_NOTAFISCAL.TIPNOTAFISCAL
                     AND NVL(MLF_NFITEM.SEQNF, 0) = NVL(MLF_NOTAFISCAL.SEQNF, 0)
INNER JOIN GE_PESSOA ON GE_PESSOA.SEQPESSOA = MLF_NOTAFISCAL.SEQPESSOA
WHERE MLF_NOTAFISCAL.CODGERALOPER IN (1, 28, 32, 200, 290)
  AND MLF_NOTAFISCAL.DTAENTRADA BETWEEN :DT1 AND :DT2
  AND MLF_NOTAFISCAL.STATUSNF <> 'C'
GROUP BY 
    MLF_NOTAFISCAL.SEQPESSOA,
    GE_PESSOA.NOMERAZAO,
    GE_PESSOA.NROCGCCPF,
    GE_PESSOA.DIGCGCCPF,
    GE_PESSOA.FISICAJURIDICA
ORDER BY VALOR_TOTAL_FATURADO DESC, DESCRICAO_FORNECEDOR
