SELECT 
    N.NROEMPRESA AS LOJA,
    N.NUMERONF AS NF,
    TO_CHAR(N.DTAEMISSAO, 'DD/MM/YYYY') AS DATA_EMISSAO,
    I.SEQPRODUTO AS COD_PROD,
    P.DESCCOMPLETA AS PRODUTO,
    SUM(I.QUANTIDADE) AS QTD,
    'R$ ' || TO_CHAR(ROUND(SUM(NVL(I.VLRITEM, 0) + NVL(I.VLRIPI, 0) + NVL(I.VLRICMSST, 0)), 2), 'FM999G999D00') AS VALOR_TOTAL_COM_IMPOSTOS
FROM MLFV_BASENFE N
JOIN MFLV_BASEDFITEM I 
    ON I.SEQNF = N.SEQNF 
   AND I.NROEMPRESA = N.NROEMPRESA 
   AND I.TIPNOTAFISCAL = N.TIPNOTAFISCAL
JOIN MAP_PRODUTO P 
    ON P.SEQPRODUTO = I.SEQPRODUTO
WHERE (:NR1 = 0 OR N.SEQPESSOA = :NR1)
  AND N.CODGERALOPER IN (802, 860)
  AND N.DTAEMISSAO BETWEEN :DT1 AND :DT2
  AND N.STATUSNF != 'C'
  AND N.NROEMPRESA IN (1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 14, 15,16, 17, 18,50)
GROUP BY 
    N.NROEMPRESA, 
    N.NUMERONF, 
    N.DTAEMISSAO, 
    I.SEQPRODUTO, 
    P.DESCCOMPLETA
ORDER BY 
    N.DTAEMISSAO, 
    N.NUMERONF