SELECT * FROM (
    WITH CTE_BASE AS (
        SELECT DISTINCT /*+ MATERIALIZE */
            A.NROEMPRESA,
            A.NROACORDO,
            AC.SEQPROCESSO,
            B.SEQPESSOA AS SEQFORNECEDOR,
            B.NOMERAZAO,
            A.DESCACORDO,
            A.DTAEMISSAO,
            C.APELIDO,
            A.STATUS,
            A.TIPOACORDO,
            A.SEQPRODUTO,
            A.QTDUTILIZADAVERBA,
            A.DTAFINALVERBA,
            SUBSTR(A.NUMERONF, 1, 250) AS NUMERONF,
            A.NROPEDIDOSUPRIM,
            NVL(A.VLRFINVENCIDO, fValorTitAcordo(A.NROACORDO, A.NROEMPRESA, A.SEQFORNECEDOR, 'V')) AS VLRFINVENCIDO,
            NVL(A.VLRFINAVENCER, fValorTitAcordo(A.NROACORDO, A.NROEMPRESA, A.SEQFORNECEDOR, 'A')) AS VLRFINAVENCER,
            A.VLRACORDO,
            A.VLRSALDOACORDO,
            A.VLRUTILPROD
        FROM MSUV_ACORDOPROMOC A
        INNER JOIN GE_PESSOA B ON B.SEQPESSOA = A.SEQFORNECEDOR
        INNER JOIN MAX_COMPRADOR C ON C.SEQCOMPRADOR = A.SEQCOMPRADOR
        LEFT JOIN MSU_ACORDOPROMOC AC ON AC.NROACORDO = A.NROACORDO AND AC.NROEMPRESA = A.NROEMPRESA
        WHERE A.NROEMPRESA IN (#LT1)
          AND TRUNC(A.DTAEMISSAO) BETWEEN :DT1 AND :DT2
          AND (NVL(:NR1, 0) = 0 OR A.NROACORDO = :NR1)
          AND (
              NVL(TRIM(:LS1), '0 - TODOS') IN ('0 - TODOS', 'TODOS', '', '0')
              OR (INSTR(:LS1, ' - ') > 0 AND C.SEQCOMPRADOR = TO_NUMBER(SUBSTR(:LS1, 1, INSTR(:LS1, ' - ') - 1)))
          )
          AND (
              NVL(TRIM(:LS2), '0 - TODOS') IN ('0 - TODOS', 'TODOS', '', '0')
              OR (INSTR(:LS2, ' - ') > 0 AND B.SEQPESSOA = TO_NUMBER(SUBSTR(:LS2, 1, INSTR(:LS2, ' - ') - 1)))
          )
          AND (
              NVL(TRIM(:LS3), '0 - TODOS') IN ('0 - TODOS', 'TODOS', '', '0')
              OR (INSTR(:LS3, ' - ') > 0 AND A.STATUS = TO_NUMBER(SUBSTR(:LS3, 1, INSTR(:LS3, ' - ') - 1)))
          )
    ),
    CTE_TOTAL_ACORDO AS (
        SELECT /*+ MATERIALIZE */
            NVL(SUM(VLRACORDO), 0) AS TOTAL_GERAL_VLR_ACORDO
        FROM (
            SELECT DISTINCT NROACORDO, NROEMPRESA, VLRACORDO
            FROM CTE_BASE
        )
    ),
    CTE_TOTAL_SALDO AS (
        SELECT /*+ MATERIALIZE */
            NVL(SUM(VLRSALDOACORDO), 0) AS TOTAL_GERAL_SALDO_ACORDO
        FROM (
            SELECT MAX(VLRSALDOACORDO) AS VLRSALDOACORDO
            FROM CTE_BASE
            GROUP BY NROEMPRESA, NROACORDO, SEQPRODUTO
        )
    ),
    CTE_TOTAIS AS (
        SELECT /*+ MATERIALIZE */
            (SELECT TOTAL_GERAL_VLR_ACORDO FROM CTE_TOTAL_ACORDO) AS TOTAL_VLRACORDO,
            (SELECT TOTAL_GERAL_SALDO_ACORDO FROM CTE_TOTAL_SALDO) AS TOTAL_VLRSALDO,
            (SELECT NVL(SUM(VLRFINVENCIDO), 0) FROM (SELECT DISTINCT NROACORDO, NROEMPRESA, VLRFINVENCIDO FROM CTE_BASE)) AS TOTAL_VLRFINVENCIDO,
            (SELECT NVL(SUM(VLRFINAVENCER), 0) FROM (SELECT DISTINCT NROACORDO, NROEMPRESA, VLRFINAVENCER FROM CTE_BASE)) AS TOTAL_VLRFINAVENCER,
            (SELECT NVL(SUM(VLRUTILPROD), 0) FROM CTE_BASE) AS TOTAL_VLRUTILPROD
        FROM DUAL
    )
    SELECT 
        CODIGO_EMPRESA,
        NUMERO_ACORDO,
        NUMERO_PROCESSO,
        CODIGO_FORNECEDOR,
        FORNECEDOR,
        DESCRICAO_ACORDO,
        DATA_EMISSAO,
        COMPRADOR,
        STATUS_ACORDO,
        TIPO_ACORDO,
        CODIGO_PRODUTO,
        QTD_UTILIZADA_VERBA,
        DATA_FINAL_VERBA,
        NUMERO_NF,
        NUMERO_PEDIDO_SUPRIMENTO,
        VLR_FIN_VENCIDO,
        VLR_FIN_A_VENCER,
        VALOR_ACORDO,
        VALOR_SALDO_ACORDO,
        VALOR_UTILIZADO_PRODUTO
    FROM (
        SELECT
            1 AS ORDEM_LINHA,
            X.NROACORDO AS ORDEM_ACORDO,
            TO_CHAR(X.NROEMPRESA) AS CODIGO_EMPRESA,
            TO_CHAR(X.NROACORDO) AS NUMERO_ACORDO,
            TO_CHAR(X.SEQPROCESSO) AS NUMERO_PROCESSO,
            TO_CHAR(X.SEQFORNECEDOR) AS CODIGO_FORNECEDOR,
            X.NOMERAZAO AS FORNECEDOR,
            X.DESCACORDO AS DESCRICAO_ACORDO,
            TO_CHAR(X.DTAEMISSAO, 'DD/MM/YYYY') AS DATA_EMISSAO,
            X.APELIDO AS COMPRADOR,
            CASE
                WHEN X.STATUS = 1 THEN 'EM ANDAMENTO'
                WHEN X.STATUS = 2 THEN 'CANCELADO'
                WHEN X.STATUS = 3 THEN 'CONCLUIDO'
                WHEN X.STATUS = 4 THEN 'INTERROMPIDA'
            END AS STATUS_ACORDO,
            CASE
                WHEN X.TIPOACORDO = 1 THEN 'VERBA EXTRA'
                WHEN X.TIPOACORDO = 2 THEN 'SELL-OUT'
                WHEN X.TIPOACORDO = 3 THEN 'SELL-IN'
            END AS TIPO_ACORDO,
            TO_CHAR(X.SEQPRODUTO) AS CODIGO_PRODUTO,
            TO_CHAR(X.QTDUTILIZADAVERBA) AS QTD_UTILIZADA_VERBA,
            TO_CHAR(X.DTAFINALVERBA, 'DD/MM/YYYY') AS DATA_FINAL_VERBA,
            X.NUMERONF AS NUMERO_NF,
            TO_CHAR(X.NROPEDIDOSUPRIM) AS NUMERO_PEDIDO_SUPRIMENTO,
            'R$ ' || TO_CHAR(NVL(X.VLRFINVENCIDO, 0), 'FM999G999G990D00', 'NLS_NUMERIC_CHARACTERS='',.''') AS VLR_FIN_VENCIDO,
            'R$ ' || TO_CHAR(NVL(X.VLRFINAVENCER, 0), 'FM999G999G990D00', 'NLS_NUMERIC_CHARACTERS='',.''') AS VLR_FIN_A_VENCER,
            'R$ ' || TO_CHAR(NVL(X.VLRACORDO, 0), 'FM999G999G990D00', 'NLS_NUMERIC_CHARACTERS='',.''') AS VALOR_ACORDO,
            'R$ ' || TO_CHAR(NVL(X.VLRSALDOACORDO, 0), 'FM999G999G990D00', 'NLS_NUMERIC_CHARACTERS='',.''') AS VALOR_SALDO_ACORDO,
            'R$ ' || TO_CHAR(NVL(X.VLRUTILPROD, 0), 'FM999G999G990D00', 'NLS_NUMERIC_CHARACTERS='',.''') AS VALOR_UTILIZADO_PRODUTO
        FROM CTE_BASE X
        UNION ALL
        SELECT
            2 AS ORDEM_LINHA,
            9999999999 AS ORDEM_ACORDO,
            NULL AS CODIGO_EMPRESA,
            NULL AS NUMERO_ACORDO,
            NULL AS NUMERO_PROCESSO,
            NULL AS CODIGO_FORNECEDOR,
            'TOTAL GERAL ->' AS FORNECEDOR,
            NULL AS DESCRICAO_ACORDO,
            NULL AS DATA_EMISSAO,
            NULL AS COMPRADOR,
            NULL AS STATUS_ACORDO,
            NULL AS TIPO_ACORDO,
            NULL AS CODIGO_PRODUTO,
            NULL AS QTD_UTILIZADA_VERBA,
            NULL AS DATA_FINAL_VERBA,
            NULL AS NUMERO_NF,
            NULL AS NUMERO_PEDIDO_SUPRIMENTO,
            'R$ ' || TO_CHAR(NVL(T.TOTAL_VLRFINVENCIDO, 0), 'FM999G999G990D00', 'NLS_NUMERIC_CHARACTERS='',.''') AS VLR_FIN_VENCIDO,
            'R$ ' || TO_CHAR(NVL(T.TOTAL_VLRFINAVENCER, 0), 'FM999G999G990D00', 'NLS_NUMERIC_CHARACTERS='',.''') AS VLR_FIN_A_VENCER,
            'R$ ' || TO_CHAR(NVL(T.TOTAL_VLRACORDO, 0), 'FM999G999G990D00', 'NLS_NUMERIC_CHARACTERS='',.''') AS VALOR_ACORDO,
            'R$ ' || TO_CHAR(NVL(T.TOTAL_VLRSALDO, 0), 'FM999G999G990D00', 'NLS_NUMERIC_CHARACTERS='',.''') AS VALOR_SALDO_ACORDO,
            'R$ ' || TO_CHAR(NVL(T.TOTAL_VLRUTILPROD, 0), 'FM999G999G990D00', 'NLS_NUMERIC_CHARACTERS='',.''') AS VALOR_UTILIZADO_PRODUTO
        FROM CTE_TOTAIS T
    )
    ORDER BY ORDEM_LINHA, ORDEM_ACORDO
)
