SELECT * FROM (
    WITH CTE_COMPRADOR_SUGERIDO AS (
        SELECT /*+ MATERIALIZE */
            SEQFORNECEDOR,
            SEQCOMPRADOR
        FROM (
            SELECT
                B.SEQFORNECEDOR,
                B.SEQCOMPRADOR,
                ROW_NUMBER() OVER (PARTITION BY B.SEQFORNECEDOR ORDER BY COUNT(1) DESC) AS RN
            FROM MACV_PSITEMRECEBER B
            WHERE B.TIPPEDIDOSUPRIM = 'C'
              AND NVL(B.STATUSITEM, 'A') != 'C'
              AND NVL(B.SEQCOMPRADOR, 0) NOT IN (0, 1)
            GROUP BY B.SEQFORNECEDOR, B.SEQCOMPRADOR
        )
        WHERE RN = 1
    ),
    CTE_COMPRADOR_TITULO AS (
        SELECT /*+ MATERIALIZE */
            TC.SEQTITULO,
            MIN(TC.SEQCOMPRADOR) AS SEQCOMPRADOR
        FROM FI_TITCOMPRADOR TC
        WHERE NVL(TC.SEQCOMPRADOR, 0) NOT IN (0, 1)
        GROUP BY TC.SEQTITULO
    ),
    CTE_CHAVE_XML AS (
        SELECT 
            NROEMPRESA,
            SEQPESSOA,
            NUMERONF,
            SERIENF,
            MAX(NFECHAVEACESSO) AS CHAVE_XML
        FROM (
            SELECT NROEMPRESA, SEQPESSOA, TO_CHAR(NUMERODF) AS NUMERONF, SERIEDF AS SERIENF, NFECHAVEACESSO
            FROM MFL_DOCTOFISCAL
            WHERE NFECHAVEACESSO IS NOT NULL
            UNION ALL
            SELECT NROEMPRESA, SEQPESSOA, TO_CHAR(NUMERONF) AS NUMERONF, SERIENF, NFECHAVEACESSO
            FROM MLF_NOTAFISCAL
            WHERE NFECHAVEACESSO IS NOT NULL
        )
        GROUP BY NROEMPRESA, SEQPESSOA, NUMERONF, SERIENF
    ),
    CTE_TITULOS AS (
        SELECT /*+ MATERIALIZE */
            T.SEQTITULO,
            T.NROEMPRESA,
            T.NROTITULO,
            T.SERIETITULO,
            T.NROPARCELA,
            T.CODESPECIE,
            T.SEQPESSOA,
            T.DTAINCLUSAO,
            T.DTAEMISSAO,
            T.DTAVENCIMENTO,
            T.DTAQUITACAO,
            T.VLRNOMINAL,
            T.VLRPAGO,
            T.ABERTOQUITADO,
            T.SITUACAO,
            T.OBSERVACAO
        FROM FI_TITULO T
        WHERE T.SITUACAO != 'C'
          AND T.OBRIGDIREITO = 'D'
          AND (
              T.CODESPECIE IN ('DEVREC', 'ACRCIM', 'ACRCOM', 'ACRINT', 'ACRLOG', 'ACRMKT', 'ACRPRE', 'ACRTRO', 'ACORDO', 'VERBA')
              OR T.CODESPECIE LIKE 'ACR%'
          )
          AND T.DTAINCLUSAO >= TRUNC(SYSDATE) - 365
          AND T.DTAVENCIMENTO <= TRUNC(SYSDATE) + 180
    )
    SELECT
        T.SEQTITULO AS SEQ_TITULO,
        NVL(E.NOMEREDUZIDO, 'EMPRESA ' || T.NROEMPRESA) AS EMPRESA,
        T.NROTITULO AS TITULO,
        T.SERIETITULO AS SERIE,
        T.NROPARCELA AS PARCELA,
        T.CODESPECIE AS ESPECIE,
        CASE
            WHEN T.CODESPECIE = 'DEVREC' THEN 'DEVOLUCAO A RECEBER'
            WHEN T.CODESPECIE LIKE 'ACR%' OR T.CODESPECIE IN ('ACORDO', 'VERBA') THEN 'ACORDO / VERBA'
            ELSE 'OUTROS CREDITOS'
        END AS TIPO_DOCUMENTO,
        T.SEQPESSOA AS COD_FORNECEDOR,
        P.NOMERAZAO AS FORNECEDOR,
        SUBSTR(FC5MASKCNPJCPF(P.NROCGCCPF, P.DIGCGCCPF, P.FISICAJURIDICA), 1, 20) AS CNPJ_CPF,
        NVL(COMP.APELIDO, NVL(COMP.COMPRADOR, 'GERAL')) AS COMPRADOR,
        TO_CHAR(T.DTAINCLUSAO, 'DD/MM/YYYY') AS DATA_LANCAMENTO,
        TO_CHAR(T.DTAEMISSAO, 'DD/MM/YYYY') AS DATA_EMISSAO,
        TO_CHAR(T.DTAVENCIMENTO, 'DD/MM/YYYY') AS DATA_VENCIMENTO,
        TO_CHAR(T.DTAQUITACAO, 'DD/MM/YYYY') AS DATA_QUITACAO,
        ROUND(NVL(T.VLRNOMINAL, 0), 2) AS VALOR_NOMINAL,
        ROUND(NVL(T.VLRPAGO, 0), 2) AS VALOR_ABATIDO_PAGO,
        ROUND(NVL(T.VLRNOMINAL, 0) - NVL(T.VLRPAGO, 0), 2) AS SALDO_ABERTO,
        CASE
            WHEN T.ABERTOQUITADO = 'Q' THEN 'QUITADO / ABATIDO'
            WHEN NVL(T.VLRPAGO, 0) > 0 THEN 'ABATIDO PARCIAL'
            ELSE 'PENDENTE ABATIMENTO'
        END AS STATUS_PAGAMENTO,
        T.SITUACAO AS SITUACAO_TITULO,
        T.OBSERVACAO AS OBSERVACAO_TITULO,
        NF.CHAVE_XML AS CHAVE_XML_NOTA
    FROM CTE_TITULOS T
    LEFT JOIN MAX_EMPRESA E ON E.NROEMPRESA = T.NROEMPRESA
    LEFT JOIN GE_PESSOA P ON P.SEQPESSOA = T.SEQPESSOA
    LEFT JOIN CTE_COMPRADOR_TITULO TC ON TC.SEQTITULO = T.SEQTITULO
    LEFT JOIN CTE_COMPRADOR_SUGERIDO CS ON CS.SEQFORNECEDOR = T.SEQPESSOA
    LEFT JOIN MAX_COMPRADOR COMP ON COMP.SEQCOMPRADOR = COALESCE(TC.SEQCOMPRADOR, CS.SEQCOMPRADOR)
    LEFT JOIN CTE_CHAVE_XML NF ON NF.NROEMPRESA = T.NROEMPRESA 
                              AND NF.SEQPESSOA = T.SEQPESSOA 
                              AND NF.NUMERONF = T.NROTITULO
                              AND NVL(NF.SERIENF, 'X') = NVL(T.SERIETITULO, 'X')
    ORDER BY
        T.DTAVENCIMENTO ASC,
        T.NROEMPRESA ASC,
        T.SEQTITULO ASC
)
