SELECT 
    C.CATEGORIA AS DEPARTAMENTO,
    NVL(COMP.COMPRADOR, 'SEM GESTOR') AS COMPRADOR,
    Y.NROEMPRESA AS CODIGO_EMPRESA,
    A.SEQPRODUTO AS CODIGO_PRODUTO,
    A.DESCCOMPLETA AS DESCRICAO_PRODUTO,
    Y.STATUSCOMPRA AS STATUS_COMPRA,
    FD.PADRAOEMBCOMPRA AS EMBL_COMPRA,
    FD.PADRAOEMBTRANSF AS EMBL_TRANSFERENCIA,
    NVL(Y.ESTQLOJA, 0) AS ESTOQUE_ATUAL
FROM MAP_PRODUTO A
INNER JOIN MRL_PRODUTOEMPRESA Y ON A.SEQPRODUTO = Y.SEQPRODUTO
LEFT JOIN MAP_FAMDIVISAO FD ON A.SEQFAMILIA = FD.SEQFAMILIA AND FD.NRODIVISAO = 1
LEFT JOIN MAX_COMPRADOR COMP ON COMP.SEQCOMPRADOR = FD.SEQCOMPRADOR
INNER JOIN MAP_FAMDIVCATEG FDC ON FDC.SEQFAMILIA = A.SEQFAMILIA AND FDC.NRODIVISAO = 1 AND FDC.STATUS = 'A'
INNER JOIN MAP_CATEGORIA C ON C.SEQCATEGORIA = FDC.SEQCATEGORIA AND C.NRODIVISAO = 1 AND C.STATUSCATEGOR = 'A'
WHERE Y.STATUSCOMPRA = 'A'
  AND Y.NROEMPRESA IN (3, 15, 50)
  AND FD.FINALIDADEFAMILIA = 'R'
  AND UPPER(C.CATEGORIA) LIKE '%LIVRARIA%'
ORDER BY C.CATEGORIA, Y.NROEMPRESA, A.DESCCOMPLETA
