SELECT
    A.NUMERONF,
    A.SERIENF,
    C.NOMEREDUZIDO AS EMPRESA,
    TO_CHAR(A.DTAEMISSAO, 'DD/MM/YYYY') AS DTAEMISSAO,
    TO_CHAR(A.DTAENTRADA, 'DD/MM/YYYY') AS DTAENTRADA,
    TO_CHAR(
        NVL((SELECT SUM(NVL(I.VLRITEM, 0))
           FROM MLF_NFITEM I 
          WHERE I.NUMERONF = A.NUMERONF 
            AND I.SERIENF = A.SERIENF 
            AND I.NROEMPRESA = A.NROEMPRESA 
            AND I.TIPNOTAFISCAL = A.TIPNOTAFISCAL
            AND NVL(A.SEQNF,0) = NVL(I.SEQNF,NVL(A.SEQNF,0))), 0), 
        'FM999G999G990D00', 'NLS_NUMERIC_CHARACTERS='',.''') AS VLRTOTALNF,
    DECODE(A.STATUSNF, 'N', 'NORMAL', 'C', 'CANCELADA', 'V', 'VALIDADA', A.STATUSNF) AS SITUACAO_DESC,
    A.STATUSNF AS SITUACAO,
    A.SEQNOTAFISCAL,
    NULL AS SEQAUXNOTAFISCAL,
    A.SEQPESSOA,
    (SELECT P.SEQPESSOA || ' - ' || P.FANTASIA FROM GE_PESSOA P WHERE P.SEQPESSOA = A.SEQPESSOA) AS FORNECEDOR,
    NULL AS STATUSCARGA,
    A.USULANCTO AS USUARIORF,
    A.NFECHAVEACESSO,
    A.CODGERALOPER,
    (
      SELECT LISTAGG(I.SEQPRODUTO, ' / ') WITHIN GROUP (ORDER BY I.SEQPRODUTO)
        FROM MLF_NFITEM I
       WHERE I.NUMERONF = A.NUMERONF
         AND I.SERIENF = A.SERIENF
         AND I.NROEMPRESA = A.NROEMPRESA
         AND I.TIPNOTAFISCAL = A.TIPNOTAFISCAL
         AND NVL(A.SEQNF,0) = NVL(I.SEQNF,NVL(A.SEQNF,0))
    ) AS ITENS_CODIGO,
    (
      SELECT LISTAGG(P.DESCCOMPLETA, ' / ') WITHIN GROUP (ORDER BY I.SEQPRODUTO)
        FROM MLF_NFITEM I
        JOIN MAP_PRODUTO P ON P.SEQPRODUTO = I.SEQPRODUTO
       WHERE I.NUMERONF = A.NUMERONF
         AND I.SERIENF = A.SERIENF
         AND I.NROEMPRESA = A.NROEMPRESA
         AND I.TIPNOTAFISCAL = A.TIPNOTAFISCAL
         AND NVL(A.SEQNF,0) = NVL(I.SEQNF,NVL(A.SEQNF,0))
    ) AS ITENS_DESCRICAO,
    (
      SELECT LISTAGG(TO_CHAR(I.QUANTIDADE), ' / ') WITHIN GROUP (ORDER BY I.SEQPRODUTO)
        FROM MLF_NFITEM I
       WHERE I.NUMERONF = A.NUMERONF
         AND I.SERIENF = A.SERIENF
         AND I.NROEMPRESA = A.NROEMPRESA
         AND I.TIPNOTAFISCAL = A.TIPNOTAFISCAL
         AND NVL(A.SEQNF,0) = NVL(I.SEQNF,NVL(A.SEQNF,0))
    ) AS ITENS_QUANTIDADE
FROM MLF_NOTAFISCAL A
INNER JOIN MAX_EMPRESA C ON A.NROEMPRESA = C.NROEMPRESA
WHERE (NVL(TRIM(:LT1), '0') = '0' OR A.NROEMPRESA IN (#LT1))
  AND A.TIPNOTAFISCAL = 'E'
  AND A.DTAENTRADA >= TRUNC(:DT1)
  AND A.DTAENTRADA < TRUNC(:DT2) + 1
  AND (NVL(TRIM(:LT2), '0') = '0' OR TO_CHAR(A.SEQPESSOA) = TRIM(:LT2))
  AND (NVL(TRIM(:LT3), '0') = '0' OR TO_CHAR(A.NUMERONF) = TRIM(:LT3))
  AND (
        NVL(TRIM(:LT4), '0') = '0' 
        OR A.CODGERALOPER IN (#LT4)
        OR EXISTS (
            SELECT 1 
              FROM MLF_NFITEM I 
              LEFT JOIN MAX_PARAMETRO MP ON MP.NROEMPRESA = I.NROEMPRESA AND MP.PARAMETRO = 'CGO_ENTR_BONIF_NFCOMPRA'
             WHERE I.NUMERONF = A.NUMERONF
               AND I.SERIENF = A.SERIENF
               AND I.NROEMPRESA = A.NROEMPRESA
               AND I.TIPNOTAFISCAL = A.TIPNOTAFISCAL
               AND NVL(A.SEQNF,0) = NVL(I.SEQNF,NVL(A.SEQNF,0))
               AND I.TIPPEDCOMPRAITEM = 'B' 
               AND A.TIPPEDIDOCOMPRA = 'C'
               AND REGEXP_LIKE(MP.VALOR, '^[0-9]+$') 
               AND TO_NUMBER(MP.VALOR) IN (#LT4)
        )
      )
  AND (
        (NVL(TRIM(:LS2), 'N') <> 'E' AND (:LS1 = 'T' OR A.STATUSNF = :LS1 OR :LS1 = 'I'))
        OR
        (NVL(TRIM(:LS2), 'N') = 'E' AND A.STATUSNF <> NVL(NULLIF(TRIM(:LS1), 'T'), 'I'))
      )
ORDER BY A.DTAENTRADA ASC, C.NOMEREDUZIDO ASC, A.NUMERONF ASC