SELECT
  X.PROMOCAO,
  X.DTAINICIO,
  X.DTAFIM,
  X.NOME,
  X.COD,
  X.DESCRICAO,
  X.PRECO,
  X.MGNORMAL,
  X.PROMO,
  X.MGPROMOC,
  X.QTD_ATUAL,
  X.QTD_ANTERIOR,
  'R$    ' || TO_CHAR(ROUND(NVL(X.PROMO_NUM, 0) * NVL(X.QTD_ATUAL, 0), 2), 'FM999G999D00') AS VALOR_TOTAL_VENDIDO
FROM (
  SELECT
    M.PROMOCAO,
    TO_CHAR(M.DTAINICIO, 'DD/MM/YYYY') AS DTAINICIO,
    TO_CHAR(M.DTAFIM, 'DD/MM/YYYY') AS DTAFIM,
    M.SEQPROMOCAO AS NOME,
    M.SEQPRODUTO AS COD,
    M.DESCCOMPLETA AS DESCRICAO,
    'R$ ' ||TO_CHAR(ROUND(MIN(M.PRECONORMAL),2), 'FM999G999D00') AS PRECO,
    '   ' || TO_CHAR(MIN(M.MGMNORMAL), 'FM999G999D99') AS MGNORMAL,
    'R$ ' ||TO_CHAR(ROUND(MIN(M.PRECOPROMOCIONAL),2), 'FM999G999D00') AS PROMO,
    MIN(M.PRECOPROMOCIONAL) AS PROMO_NUM,
    '   ' || TO_CHAR(MIN(M.MGMPROMOC), 'FM999G999D99') AS MGPROMOC,
    '   ' || NVL(Q1.QTD_ATUAL, 0) AS QTD_ATUAL,
    '   ' || NVL(Q2.QTD_ANTERIOR, 0) AS QTD_ANTERIOR
  FROM
    MRLV_BASEPRODPROMOC M
    JOIN MAD_SEGMENTO S ON M.NROSEGMENTO = S.NROSEGMENTO
    LEFT JOIN (
      SELECT V.SEQPRODUTO, SUM(V.QTDVDA) AS QTD_ATUAL
        FROM MRL_PRODVENDADIA V
       WHERE V.NROEMPRESA IN (SELECT DISTINCT NROEMPRESA FROM MRLV_BASEPRODPROMOC WHERE PROMOCAO = #LS1 AND PRINCIPAL = 'S' AND CENTRALLOJA = 'C')
         AND V.DTAVDA BETWEEN :DT3 AND :DT4
       GROUP BY V.SEQPRODUTO
    ) Q1 ON Q1.SEQPRODUTO = M.SEQPRODUTO
    LEFT JOIN (
      SELECT V.SEQPRODUTO, SUM(V.QTDVDA) AS QTD_ANTERIOR
        FROM MRL_PRODVENDADIA V
       WHERE V.NROEMPRESA IN (SELECT DISTINCT NROEMPRESA FROM MRLV_BASEPRODPROMOC WHERE PROMOCAO = #LS1 AND PRINCIPAL = 'S' AND CENTRALLOJA = 'C')
         AND V.DTAVDA BETWEEN :DT1 AND :DT2
       GROUP BY V.SEQPRODUTO
    ) Q2 ON Q2.SEQPRODUTO = M.SEQPRODUTO
  WHERE
    M.CENTRALLOJA = 'C'
    AND M.PRINCIPAL = 'S'
    AND M.PROMOCAO = #LS1
    AND M.DTAINICIO <= :DT4
    AND M.DTAFIM >= :DT3
  GROUP BY
    M.PROMOCAO,
    M.DTAINICIO,
    M.DTAFIM,
    M.SEQPROMOCAO,
    M.SEQPRODUTO,
    M.DESCCOMPLETA,
    Q1.QTD_ATUAL,
    Q2.QTD_ANTERIOR
) X
ORDER BY
  X.DTAINICIO DESC, X.DTAFIM DESC, X.NOME, X.DESCRICAO