
-- Consulta de Alteração de Preços por Produto e Período (Histórico real no ambiente Consinco)
-- Tabela: MRL_PRODEMPSEG | Coluna de data: DTAALTERACAO
-- Variáveis esperadas: :VAR_SEQPRODUTO (NR1), :VAR_DTINI (DT1), :VAR_DTFIM (DT2)

SELECT
  S.SEQPRODUTO,
  S.NROEMPRESA,
  S.QTDEMBALAGEM,
  S.PRECOBASENORMAL,
  S.PRECOVALIDNORMAL,
  TO_CHAR(S.DTAALTERACAO, 'DD/MM/YYYY HH24:MI') AS DTAALTERACAO,
  S.USUALTERACAO,
  S.MOTIVOPRECOBASE,
  S.MOTIVOPRECOVALIDO
FROM
  MRL_PRODEMPSEG S
WHERE
  S.SEQPRODUTO = :NR1
  AND S.DTAALTERACAO BETWEEN :DT1 AND :DT2
ORDER BY
  S.DTAALTERACAO DESC;



  