SELECT
  M.PROMOCAO,
  TO_CHAR(M.DTAINICIO, 'DD/MM/YYYY') AS DTAINICIO,
  TO_CHAR(M.DTAFIM, 'DD/MM/YYYY') AS DTAFIM,
  0 AS LOJA,
  M.SEQPROMOCAO AS NOME,
  M.SEQPRODUTO AS COD,
  M.DESCCOMPLETA AS DESCRICAO,
  MIN(M.PRECONORMAL) AS PRECO,
  TO_CHAR(MIN(M.MGMNORMAL), 'FM999G999D99') AS MGNORMAL,
  MIN(M.PRECOPROMOCIONAL) AS PROMO,
  TO_CHAR(MIN(M.MGMPROMOC), 'FM999G999D99') AS MGPROMOC,
  NVL(Q1.QTD_ATUAL, 0) AS QTD_ATUAL,
  NVL(Q2.QTD_ANTERIOR, 0) AS QTD_ANTERIOR
FROM
  MRLV_BASEPRODPROMOC M
  JOIN MAD_SEGMENTO S ON M.NROSEGMENTO = S.NROSEGMENTO
  LEFT JOIN (
    SELECT V.SEQPRODUTO, SUM(V.QTDVDA) AS QTD_ATUAL
      FROM MRL_PRODVENDADIA V
     WHERE V.NROEMPRESA IN (SELECT DISTINCT NROEMPRESA FROM MRLV_BASEPRODPROMOC WHERE PROMOCAO = #LS1 AND PRINCIPAL = 'S' AND CENTRALLOJA = 'C')
       AND V.DTAVDA BETWEEN :DT3 AND :DT4
     GROUP BY V.SEQPRODUTO
  ) Q1 ON Q1.SEQPRODUTO = M.SEQPRODUTO
  LEFT JOIN (
    SELECT V.SEQPRODUTO, SUM(V.QTDVDA) AS QTD_ANTERIOR
      FROM MRL_PRODVENDADIA V
     WHERE V.NROEMPRESA IN (SELECT DISTINCT NROEMPRESA FROM MRLV_BASEPRODPROMOC WHERE PROMOCAO = #LS1 AND PRINCIPAL = 'S' AND CENTRALLOJA = 'C')
       AND V.DTAVDA BETWEEN :DT1 AND :DT2
     GROUP BY V.SEQPRODUTO
  ) Q2 ON Q2.SEQPRODUTO = M.SEQPRODUTO
WHERE
  M.CENTRALLOJA = 'C'
  AND M.PRINCIPAL = 'S'
  AND M.PROMOCAO = #LS1
  AND M.DTAINICIO <= :DT4
  AND M.DTAFIM >= :DT3
GROUP BY
  M.PROMOCAO,
  M.DTAINICIO,
  M.DTAFIM,
  M.SEQPROMOCAO,
  M.SEQPRODUTO,
  M.DESCCOMPLETA,
  Q1.QTD_ATUAL,
  Q2.QTD_ANTERIOR
ORDER BY
  M.DTAINICIO DESC, M.DTAFIM DESC, NOME, DESCRICAO, LOJA