SELECT * FROM (
WITH PEND_COMPRA AS (
    SELECT /*+ MATERIALIZE */ SEQPRODUTO, NROEMPRESA, 
           NVL(SUM(CASE WHEN NVL(QTDSOLICITADA, 0) > NVL(QTDRECCANC, 0) THEN NVL(QTDSOLICITADA, 0) - NVL(QTDRECCANC, 0) ELSE 0 END), 0) AS QTD
    FROM MAXV_MSUPEDIDOSUPRIMREC
    WHERE TIPPEDIDOSUPRIM = 'C'
      AND NROEMPRESA IN (1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 14, 15, 17, 18)
    GROUP BY SEQPRODUTO, NROEMPRESA
),
PEND_TRANSF AS (
    SELECT /*+ MATERIALIZE */ SEQPRODUTO, NROEMPDESTINO, 
           NVL(SUM(NVL(QTDSOLICITADA, 0) - NVL(QTDEXPCANC, 0)), 0) AS QTD
    FROM MAXV_MSUPEDIDOSUPRIMEXP
    WHERE NROEMPRESA IN (15, 16, 50)
      AND NROEMPDESTINO IN (1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 14, 15, 17, 18)
    GROUP BY SEQPRODUTO, NROEMPDESTINO
),
TRANSITO AS (
    SELECT /*+ MATERIALIZE */ R.SEQPRODUTO, R.NROEMPRESA, 
           NVL(SUM(NVL(R.QTDTOTTRANSITO, 0)), 0) AS QTD
    FROM MSU_PSITEMRECEBER R
    JOIN MSU_PEDIDOSUPRIM PS ON PS.NROPEDIDOSUPRIM = R.NROPEDIDOSUPRIM AND PS.NROEMPRESA = R.NROEMPRESA
    WHERE PS.SEQFORNECEDOR IN (15, 16, 50)
      AND R.NROEMPRESA IN (1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 14, 15, 17, 18)
    GROUP BY R.SEQPRODUTO, R.NROEMPRESA
),
VENDAS AS (
    SELECT /*+ MATERIALIZE */ SEQPRODUTO, NROEMPRESA, 
           ROUND(NVL(SUM(QTDVDA), 0), 2) AS QTD
    FROM MRL_CUSTODIA
    WHERE DTAENTRADASAIDA >= TRUNC(SYSDATE) - NVL(:NR1, 90)
      AND DTAENTRADASAIDA < TRUNC(SYSDATE)
      AND NROEMPRESA IN (1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 14, 15, 17, 18)
    GROUP BY SEQPRODUTO, NROEMPRESA
),
PONTO_EXTRA AS (
    SELECT /*+ MATERIALIZE */
        PEPE.SEQPRODUTO,
        PEPE.NROEMPRESA,
        NVL(SUM(PEPE.ESTQMINIMO), 0) AS ESTQMINIMO_PE,
        NVL(SUM(PEPE.ESTQMAXIMO), 0) AS ESTQMAXIMO_PE
    FROM MRL_PONTOEXTRA PE
    JOIN MRL_PONTOEXTRAPRODUTO PEP ON PEP.SEQPONTOEXTRA = PE.SEQPONTOEXTRA
    JOIN MRL_PONTOEXTRAPRODUTOEMPRESA PEPE ON PEPE.SEQPONTOEXTRA = PEP.SEQPONTOEXTRA AND PEPE.SEQPRODUTO = PEP.SEQPRODUTO
    WHERE PE.STATUS = 'A'
      AND PEPE.STATUS = 'A'
      AND TRUNC(SYSDATE) BETWEEN TRUNC(PEPE.DTAVIGENCIAINICIO) AND TRUNC(PEPE.DTAVIGENCIAFIM)
      AND PEPE.NROEMPRESA IN (1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 14, 15, 17, 18)
    GROUP BY PEPE.SEQPRODUTO, PEPE.NROEMPRESA
)
SELECT 
    C.CATEGORIA AS DEPARTAMENTO,
    NVL(COMP.COMPRADOR, 'SEM GESTOR') AS COMPRADOR,
    Y.NROEMPRESA AS CODIGO_EMPRESA,
    A.SEQPRODUTO AS CODIGO_PRODUTO,
    A.DESCCOMPLETA AS DESCRICAO_PRODUTO,
    FD.FORMAABASTECIMENTO AS FORMA_ABASTECIMENTO,
    TO_CHAR(TRUNC(A.DTAHORINCLUSAO), 'DD/MM/YYYY') AS DATA_CADASTRO_PRODUTO,
    CASE WHEN Y.STATUSCOMPRA = 'A' THEN 'Ativo' ELSE 'Inativo' END AS STATUS_COMPRA,
    FD.PADRAOEMBCOMPRA AS EMBL_COMPRA,
    FD.PADRAOEMBTRANSF AS EMBL_TRANSFERENCIA,
    (NVL(Y.ESTQLOJA, 0) + NVL(Y.ESTQDEPOSITO, 0) - NVL(Y.QTDRESERVADAVDA, 0) - NVL(Y.QTDRESERVADARECEB, 0)) AS QUANTIDADE_DISPONIVEL,
    NVL(PC.QTD, 0) AS QTD_PEND_PEDCOMPRA,
    NVL(PT.QTD, 0) AS QTD_PEND_PEDTRANSF,
    NVL(TR.QTD, 0) AS QTD_EM_TRANSITO,
    NVL(V.QTD, 0) AS QTD_VENDIDA_PERIODO,
    NVL(Y.ESTQMINIMOLOJA, 0) AS QUANTIDADE_ESTOQUE_MINIMO,
    NVL(Y.ESTQMAXIMOLOJA, 0) AS QUANTIDADE_ESTOQUE_MAXIMO,
    NVL(PX.ESTQMINIMO_PE, 0) AS MINIMO_PONTO_EXTRA,
    NVL(PX.ESTQMAXIMO_PE, 0) AS MAXIMO_PONTO_EXTRA,
    NVL(:NR1, 90) AS DIAS_PESQUISA
FROM MAP_PRODUTO A
INNER JOIN MRL_PRODUTOEMPRESA Y ON A.SEQPRODUTO = Y.SEQPRODUTO
INNER JOIN GE_EMPRESA E ON Y.NROEMPRESA = E.NROEMPRESA
INNER JOIN MAP_FAMILIA B ON A.SEQFAMILIA = B.SEQFAMILIA
LEFT JOIN MAP_FAMDIVISAO FD ON A.SEQFAMILIA = FD.SEQFAMILIA AND FD.NRODIVISAO = 1
LEFT JOIN MAX_COMPRADOR COMP ON COMP.SEQCOMPRADOR = FD.SEQCOMPRADOR
INNER JOIN MAP_FAMDIVCATEG FDC ON FDC.SEQFAMILIA = A.SEQFAMILIA AND FDC.NRODIVISAO = 1 AND FDC.STATUS = 'A'
INNER JOIN MAP_CATEGORIA C ON C.SEQCATEGORIA = FDC.SEQCATEGORIA AND C.NRODIVISAO = 1 AND C.NIVELHIERARQUIA = 1 AND C.STATUSCATEGOR = 'A'
LEFT JOIN PEND_COMPRA PC ON PC.SEQPRODUTO = A.SEQPRODUTO AND PC.NROEMPRESA = Y.NROEMPRESA
LEFT JOIN PEND_TRANSF PT ON PT.SEQPRODUTO = A.SEQPRODUTO AND PT.NROEMPDESTINO = Y.NROEMPRESA
LEFT JOIN TRANSITO TR ON TR.SEQPRODUTO = A.SEQPRODUTO AND TR.NROEMPRESA = Y.NROEMPRESA
LEFT JOIN VENDAS V ON V.SEQPRODUTO = A.SEQPRODUTO AND V.NROEMPRESA = Y.NROEMPRESA
LEFT JOIN PONTO_EXTRA PX ON PX.SEQPRODUTO = A.SEQPRODUTO AND PX.NROEMPRESA = Y.NROEMPRESA
WHERE Y.STATUSCOMPRA = 'A'
  AND Y.NROEMPRESA IN (1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 14, 15, 17, 18)
  AND FD.FINALIDADEFAMILIA = 'R'
  AND (NVL(:NR2, 0) = 0 OR A.SEQPRODUTO = :NR2)
  AND (
      UPPER(C.CATEGORIA) IN ('BEBIDAS', 'MERCEARIA', 'PERFUMARIA E LIMPEZA', 'PRODUTOS PET')
      OR EXISTS (
          SELECT 1 
          FROM MAP_FAMDIVCATEG FDC2
          INNER JOIN MAP_CATEGORIA C2 ON FDC2.SEQCATEGORIA = C2.SEQCATEGORIA
          WHERE FDC2.SEQFAMILIA = A.SEQFAMILIA 
            AND FDC2.NRODIVISAO = 1 
            AND FDC2.STATUS = 'A' 
            AND C2.NRODIVISAO = 1 
            AND C2.STATUSCATEGOR = 'A'
            AND (UPPER(C2.CATEGORIA) LIKE '%LEITE%' OR UPPER(C2.CATEGORIA) LIKE '%CARV%O%')
      )
  )
)
ORDER BY DEPARTAMENTO, CODIGO_EMPRESA, DESCRICAO_PRODUTO
