SELECT
    C.NROEMPRESA AS CODIGO_LOJA,
    A.SEQPRODUTO AS CODIGO_PRODUTO,
    A.DESCCOMPLETA AS DESCRICAO,
    B.CODACESSO AS EAN_DUN,
    D.CATEGORIA AS DEPARTAMENTO,
    E.CATEGORIA AS GRUPO,
    F.CATEGORIA AS SUBGRUPO,
    G.CATEGORIA AS NIVEL_4,
    NVL((SELECT MAX(SEG.PRECOVALIDNORMAL) FROM MRL_PRODEMPSEG SEG WHERE SEG.SEQPRODUTO = C.SEQPRODUTO AND SEG.NROEMPRESA = C.NROEMPRESA AND SEG.QTDEMBALAGEM = 1), 0) AS PRECO_VENDA,
    (NVL(C.ESTQLOJA, 0) + NVL(C.ESTQDEPOSITO, 0) - NVL(C.QTDRESERVADAVDA, 0) - NVL(C.QTDRESERVADARECEB, 0)) AS ESTOQUE_ATUAL,
    (
        SELECT ROUND(NVL(SUM(CUST.QTDVDA), 0), 2)
        FROM MRL_CUSTODIA CUST
        WHERE CUST.SEQPRODUTO = A.SEQPRODUTO
          AND CUST.NROEMPRESA = C.NROEMPRESA
          AND CUST.DTAENTRADASAIDA >= TRUNC(SYSDATE) - 90
    ) AS QTD_VENDIDA_90D
FROM MAP_PRODUTO A
INNER JOIN MAP_PRODCODIGO B ON A.SEQPRODUTO = B.SEQPRODUTO
INNER JOIN MRL_PRODUTOEMPRESA C ON A.SEQPRODUTO = C.SEQPRODUTO
LEFT JOIN (
    SELECT X.SEQFAMILIA, Y.CATEGORIA 
    FROM MAP_FAMDIVCATEG X 
    INNER JOIN MAP_CATEGORIA Y ON X.SEQCATEGORIA = Y.SEQCATEGORIA 
    WHERE Y.NIVELHIERARQUIA = 1 AND X.NRODIVISAO = 1 AND Y.NRODIVISAO = 1 AND X.STATUS = 'A' AND Y.STATUSCATEGOR = 'A'
) D ON D.SEQFAMILIA = A.SEQFAMILIA
LEFT JOIN (
    SELECT X.SEQFAMILIA, Y.CATEGORIA 
    FROM MAP_FAMDIVCATEG X 
    INNER JOIN MAP_CATEGORIA Y ON X.SEQCATEGORIA = Y.SEQCATEGORIA 
    WHERE Y.NIVELHIERARQUIA = 2 AND X.NRODIVISAO = 1 AND Y.NRODIVISAO = 1 AND X.STATUS = 'A' AND Y.STATUSCATEGOR = 'A'
) E ON E.SEQFAMILIA = A.SEQFAMILIA
LEFT JOIN (
    SELECT X.SEQFAMILIA, Y.CATEGORIA 
    FROM MAP_FAMDIVCATEG X 
    INNER JOIN MAP_CATEGORIA Y ON X.SEQCATEGORIA = Y.SEQCATEGORIA 
    WHERE Y.NIVELHIERARQUIA = 3 AND X.NRODIVISAO = 1 AND Y.NRODIVISAO = 1 AND X.STATUS = 'A' AND Y.STATUSCATEGOR = 'A'
) F ON F.SEQFAMILIA = A.SEQFAMILIA
LEFT JOIN (
    SELECT X.SEQFAMILIA, Y.CATEGORIA 
    FROM MAP_FAMDIVCATEG X 
    INNER JOIN MAP_CATEGORIA Y ON X.SEQCATEGORIA = Y.SEQCATEGORIA 
    WHERE Y.NIVELHIERARQUIA = 4 AND X.NRODIVISAO = 1 AND Y.NRODIVISAO = 1 AND X.STATUS = 'A' AND Y.STATUSCATEGOR = 'A'
) G ON G.SEQFAMILIA = A.SEQFAMILIA
WHERE B.TIPCODIGO IN ('E', 'D')
  AND C.STATUSCOMPRA = 'A'
  AND C.NROEMPRESA IN (1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 14, 15, 17, 18)
  AND UPPER(D.CATEGORIA) NOT IN ('INATIVAR', 'A CLASSIFICAR', 'ALMOXARIFADO', 'SERVICOS')
  AND (
       UPPER(D.CATEGORIA) <> 'PERECIVEIS' 
       OR (UPPER(D.CATEGORIA) = 'PERECIVEIS' AND UPPER(E.CATEGORIA) LIKE '%LEITE%')
  )
ORDER BY C.NROEMPRESA, A.DESCCOMPLETA
