SELECT 
  REPLACE(C.CATEGORIA, '_', ' ') AS DEPARTAMENTO,
  NVL(COMP.COMPRADOR, 'SEM GESTOR') AS COMPRADOR,
  Y.NROEMPRESA AS CODIGO_EMPRESA,
  A.SEQPRODUTO AS CODIGO_PRODUTO,
  A.DESCCOMPLETA AS DESCRICAO_PRODUTO,
  CASE WHEN Y.STATUSCOMPRA = 'A' THEN 'Ativo' ELSE 'Inativo' END AS STATUS_COMPRA,
  FD.PADRAOEMBCOMPRA AS EMBL_COMPRA,
  FD.PADRAOEMBTRANSF AS EMBL_TRANSFERENCIA,
  NVL(Y.ESTQMINIMOLOJA, 0) AS QUANTIDADE_ESTOQUE_MINIMO,
  NVL(Y.ESTQMAXIMOLOJA, 0) AS QUANTIDADE_ESTOQUE_MAXIMO
FROM MAP_PRODUTO A
INNER JOIN MRL_PRODUTOEMPRESA Y ON A.SEQPRODUTO = Y.SEQPRODUTO
INNER JOIN MAX_EMPRESA E ON Y.NROEMPRESA = E.NROEMPRESA
INNER JOIN MAP_FAMILIA B ON A.SEQFAMILIA = B.SEQFAMILIA
LEFT JOIN MAP_FAMDIVISAO FD ON A.SEQFAMILIA = FD.SEQFAMILIA AND FD.NRODIVISAO = 1
LEFT JOIN MAX_COMPRADOR COMP ON COMP.SEQCOMPRADOR = FD.SEQCOMPRADOR
INNER JOIN MAP_FAMDIVCATEG FDC ON FDC.SEQFAMILIA = A.SEQFAMILIA AND FDC.NRODIVISAO = 1 AND FDC.STATUS = 'A'
INNER JOIN MAP_CATEGORIA C ON C.SEQCATEGORIA = FDC.SEQCATEGORIA AND C.NRODIVISAO = 1 AND C.NIVELHIERARQUIA = 1 AND C.STATUSCATEGOR = 'A'
WHERE Y.STATUSCOMPRA = 'A'
  AND Y.NROEMPRESA = 16
  AND FD.FINALIDADEFAMILIA = 'R'
  AND REPLACE(UPPER(C.CATEGORIA), '_', ' ') = 'PERECIVEIS'
  AND NOT EXISTS (
    SELECT 1
      FROM MAP_FAMDIVCATEG FDC2
      JOIN MAP_CATEGORIA C2 ON C2.SEQCATEGORIA = FDC2.SEQCATEGORIA AND C2.NRODIVISAO = 1 AND C2.NIVELHIERARQUIA = 2 AND C2.STATUSCATEGOR = 'A'
    WHERE FDC2.SEQFAMILIA = A.SEQFAMILIA
      AND NVL(UPPER(C2.CATEGORIA), 'X') IN (
        'FRUTAS E VERDURAS',
        'PADARIA BAKLIZI',
        'PADARIA INDUSTRIAL'
      )
  )
  AND NOT EXISTS (
    SELECT 1
      FROM MAP_FAMDIVCATEG FDC3
      JOIN MAP_CATEGORIA C3 ON C3.SEQCATEGORIA = FDC3.SEQCATEGORIA AND C3.NRODIVISAO = 1 AND C3.NIVELHIERARQUIA = 3 AND C3.STATUSCATEGOR = 'A'
      JOIN MAP_CATEGORIA C2 ON C3.SEQCATEGORIAPAI = C2.SEQCATEGORIA AND C2.NRODIVISAO = 1 AND C2.NIVELHIERARQUIA = 2 AND C2.STATUSCATEGOR = 'A'
    WHERE FDC3.SEQFAMILIA = A.SEQFAMILIA
      AND NVL(UPPER(C2.CATEGORIA), 'X') = 'OPLS'
      AND NVL(UPPER(C3.CATEGORIA), 'X') IN (
        'BEBIDAS LACTEAS',
        'COMIDAS CONG-PRATOS PRONT',
        'CONSERVAS EMBALADAS',
        'EMBUTIDOS-FRIOS PECA',
        'FRUTAS SECAS EMBALADAS',
        'IOGURTES E SOBREMESAS',
        'LATICINIOS AUTO SERVICOS',
        'LEITE LONGA VIDA',
        'LEITES',
        'MANT-MARG-FERMENTO-BANHA',
        'MASSA FRESCA DORNECEDOR',
        'OPLS',
        'PEIXE CONGELADO EMBALADO',
        'SORVETES E GELO',
        'SUCOS E COCO CONGELADOS'
      )
  )
  AND EXISTS (
      SELECT 1
        FROM MRL_PRODUTOEMPRESA Y2
       WHERE Y2.SEQPRODUTO = A.SEQPRODUTO
         AND Y2.STATUSCOMPRA = 'A'
         AND Y2.NROEMPRESA IN (1,2,3,4,5,6,7,8,11,12,13,14,15,17,18)
  )
ORDER BY C.CATEGORIA, Y.NROEMPRESA, A.DESCCOMPLETA
