SELECT
  M.PROMOCAO,
  TO_CHAR(M.DTAINICIO, 'DD/MM/YYYY') AS DTAINICIO,
  TO_CHAR(M.DTAFIM, 'DD/MM/YYYY') AS DTAFIM,
  M.NROEMPRESA AS LOJA,
  M.SEQPROMOCAO AS NOME,
  M.SEQPRODUTO AS COD,
  M.DESCCOMPLETA AS DESCRICAO,
  M.PRECONORMAL AS PRECO_NORMAL,
  M.PRECOPROMOCIONAL AS PRECO_PROMOCIONAL,
  TO_CHAR(M.MGMNORMAL, 'FM999G999D99') AS MGNORMAL,
  TO_CHAR(M.MGMPROMOC, 'FM999G999D99') AS MGPROMOC,
  NVL((SELECT SUM(V1.QTDVDA)
         FROM MRL_PRODVENDADIA V1
        WHERE V1.SEQPRODUTO = M.SEQPRODUTO
          AND V1.NROEMPRESA = M.NROEMPRESA
          AND V1.DTAVDA BETWEEN TO_DATE('01/04/2026', 'DD/MM/YYYY') AND TO_DATE('30/04/2026', 'DD/MM/YYYY')), 0) AS QTD_ANTERIOR,
  NVL((SELECT SUM(V2.QTDVDA)
         FROM MRL_PRODVENDADIA V2
        WHERE V2.SEQPRODUTO = M.SEQPRODUTO
          AND V2.NROEMPRESA = M.NROEMPRESA
          AND V2.DTAVDA BETWEEN TO_DATE('01/05/2026', 'DD/MM/YYYY') AND TO_DATE('30/05/2026', 'DD/MM/YYYY')), 0) AS QTD_ATUAL,
  ROUND(NVL(M.PRECOPROMOCIONAL, 0) * NVL((SELECT SUM(V2.QTDVDA)
         FROM MRL_PRODVENDADIA V2
        WHERE V2.SEQPRODUTO = M.SEQPRODUTO
          AND V2.NROEMPRESA = M.NROEMPRESA
          AND V2.DTAVDA BETWEEN TO_DATE('01/05/2026', 'DD/MM/YYYY') AND TO_DATE('30/05/2026', 'DD/MM/YYYY')), 0), 2) AS VALOR_TOTAL_VENDIDO
FROM
  MRLV_BASEPRODPROMOC M
  JOIN MAD_SEGMENTO S ON M.NROSEGMENTO = S.NROSEGMENTO
WHERE
  M.CENTRALLOJA = 'C'
  AND M.PRINCIPAL = 'S'
  AND M.PROMOCAO = 'VERDINHA'
  AND M.DTAINICIO <= TO_DATE('30/05/2026', 'DD/MM/YYYY')
  AND M.DTAFIM >= TO_DATE('01/05/2026', 'DD/MM/YYYY')
ORDER BY
  M.NROEMPRESA,
  M.SEQPROMOCAO,
  M.DESCCOMPLETA