SELECT X.SEQPRODUTO AS CODIGO,
       Z.DESCCOMPLETA AS PRODUTO,
       CASE 
           WHEN X.QTDEMBALAGEM = 1 THEN 'UN - ' || X.QTDEMBALAGEM
           WHEN X.QTDEMBALAGEM > 1 THEN 'CX - ' || X.QTDEMBALAGEM
           ELSE TO_CHAR(X.QTDEMBALAGEM) 
       END AS EMBALAGEM,
       X.CODRUA || '.' || X.NROPREDIO || '.' || X.NROAPARTAMENTO || '.' || X.NROSALA AS ENDERECO,
         X.ESPECIEENDERECO AS TIPO_ENDERECO,
         NVL(X.QTDATUAL, 0) AS ESTOQUE_POSICAO
  FROM CONSINCO.MLO_ENDERECO X, 
        CONSINCO.MLO_PRODUTO Z
 WHERE X.NROEMPRESA = Z.NROEMPRESA
   AND X.SEQPRODUTO = Z.SEQPRODUTO
   AND X.NROEMPRESA = 15
   AND X.SEQPRODUTO > 0
   AND X.ESPECIEENDERECO IN ('A', 'P')
       AND NVL(X.QTDATUAL, 0) > 0
   AND (X.SEQPRODUTO = (:NR1) OR :NR1 = 0)
 ORDER BY X.SEQPRODUTO,
          X.CODRUA,
          X.NROPREDIO,
          X.NROAPARTAMENTO,
          X.NROSALA