SELECT * FROM (
    WITH ITENS_EMITIDOS AS (
        SELECT /*+ MATERIALIZE */
            N.NROEMPRESA AS CODIGO_EMPRESA,
            E.NOMEREDUZIDO AS EMPRESA,
            N.DTAEMISSAO,
            CASE
                WHEN N.APPORIGEM = 26 THEN N.NUMERONFSE
                ELSE N.NUMERONF
            END AS NUMERO_NF,
            N.CODGERALOPER AS CGO,
            N.SEQPESSOA AS SEQPESSOA_NF,
            I.SEQPRODUTO,
            P.DESCCOMPLETA AS DESCRICAO_PRODUTO,
            P.SEQFAMILIA,
            NVL(I.QUANTIDADE, 0) AS QTD_NF_NUM,
            NVL(I.VLRITEM, 0) AS VLR_NF_NUM
        FROM MLFV_BASENFE N
        INNER JOIN MFLV_BASEDFITEM I
            ON I.NROEMPRESA = N.NROEMPRESA
           AND I.SEQNF = N.SEQNF
           AND I.TIPNOTAFISCAL = N.TIPNOTAFISCAL
        INNER JOIN MAX_EMPRESA E
            ON E.NROEMPRESA = N.NROEMPRESA
        INNER JOIN MAP_PRODUTO P
            ON P.SEQPRODUTO = I.SEQPRODUTO
        WHERE N.CODGERALOPER IN (#LT1)
          AND N.TIPNOTAFISCAL = 'S'
          AND NVL(N.STATUSNF, 'A') != 'C'
          AND NVL(N.MODELO, '0') <> '65'
          AND N.DTAEMISSAO >= TRUNC(:DT1)
          AND N.DTAEMISSAO < TRUNC(:DT2) + 1
          AND (
              NVL(TRIM(:LT3), '0') IN ('0', 'TODOS', 'TODAS', '')
              OR INSTR(',' || REPLACE(TRIM(:LT3), ' ', '') || ',', ',' || TO_CHAR(N.NROEMPRESA) || ',') > 0
          )
          AND (
              NVL(:NR1, 0) = 0 
              OR CASE WHEN N.APPORIGEM = 26 THEN N.NUMERONFSE ELSE N.NUMERONF END = :NR1
          )
    ),
    FAMILIAS_DISTINTAS AS (
        SELECT /*+ MATERIALIZE */ DISTINCT
            SEQFAMILIA
        FROM ITENS_EMITIDOS
    ),
    CTE_DEPARTAMENTOS AS (
        SELECT /*+ MATERIALIZE */
            FDC.SEQFAMILIA,
            MAX(
                CASE 
                    WHEN C1.NIVELHIERARQUIA = 1 THEN C1.CATEGORIA
                    WHEN C2.NIVELHIERARQUIA = 1 THEN C2.CATEGORIA
                    WHEN C3.NIVELHIERARQUIA = 1 THEN C3.CATEGORIA
                    WHEN C4.NIVELHIERARQUIA = 1 THEN C4.CATEGORIA
                    WHEN C5.NIVELHIERARQUIA = 1 THEN C5.CATEGORIA
                END
            ) AS DEPARTAMENTO
        FROM FAMILIAS_DISTINTAS FDIST
        INNER JOIN MAP_FAMDIVCATEG FDC
            ON FDC.SEQFAMILIA = FDIST.SEQFAMILIA
        INNER JOIN MAP_CATEGORIA C1 
            ON C1.SEQCATEGORIA = FDC.SEQCATEGORIA 
           AND C1.NRODIVISAO = FDC.NRODIVISAO
           AND C1.TIPCATEGORIA = 'M'
        LEFT JOIN MAP_CATEGORIA C2 
            ON C2.SEQCATEGORIA = C1.SEQCATEGORIAPAI 
           AND C2.NRODIVISAO = C1.NRODIVISAO
        LEFT JOIN MAP_CATEGORIA C3 
            ON C3.SEQCATEGORIA = C2.SEQCATEGORIAPAI 
           AND C3.NRODIVISAO = C2.NRODIVISAO
        LEFT JOIN MAP_CATEGORIA C4 
            ON C4.SEQCATEGORIA = C3.SEQCATEGORIAPAI 
           AND C4.NRODIVISAO = C3.NRODIVISAO
        LEFT JOIN MAP_CATEGORIA C5 
            ON C5.SEQCATEGORIA = C4.SEQCATEGORIAPAI 
           AND C5.NRODIVISAO = C4.NRODIVISAO
        WHERE FDC.NRODIVISAO = 1
          AND FDC.STATUS = 'A'
          AND UPPER(NVL(C1.CATEGORIA, 'X')) NOT IN ('A CLASSIFICAR', 'ALMOXARIFADO', 'INATIVAR', 'SERVICOS')
        GROUP BY FDC.SEQFAMILIA
    ),
    CTE_FORNEC_FAM AS (
        SELECT /*+ MATERIALIZE */
            F.SEQFAMILIA,
            MAX(CASE WHEN F.PRINCIPAL = 'S' THEN F.SEQFORNECEDOR ELSE NULL END) AS COD_FORN_PRINC,
            MAX(F.SEQFORNECEDOR) AS COD_FORN_QUALQUER,
            MAX(CASE WHEN F.PRINCIPAL = 'S' THEN G.NOMERAZAO ELSE NULL END) AS FORN_PRINC,
            MAX(G.NOMERAZAO) AS FORN_QUALQUER,
            MAX(CASE WHEN F.PRINCIPAL = 'S' THEN R.DESCRICAO ELSE NULL END) AS REDE_PRINC,
            MAX(R.DESCRICAO) AS REDE_QUALQUER
        FROM FAMILIAS_DISTINTAS FDIST
        INNER JOIN MAP_FAMFORNEC F
            ON F.SEQFAMILIA = FDIST.SEQFAMILIA
        INNER JOIN GE_PESSOA G
            ON G.SEQPESSOA = F.SEQFORNECEDOR
        LEFT JOIN GE_REDEPESSOA RP
            ON RP.SEQPESSOA = F.SEQFORNECEDOR
        LEFT JOIN GE_REDE R
            ON R.SEQREDE = RP.SEQREDE
        GROUP BY F.SEQFAMILIA
    ),
    DADOS_BASE AS (
        SELECT /*+ MATERIALIZE */
            IE.CODIGO_EMPRESA,
            IE.EMPRESA,
            IE.DTAEMISSAO,
            IE.NUMERO_NF,
            IE.CGO,
            NVL(DEP.DEPARTAMENTO, 'SEM DEPARTAMENTO') AS DEPARTAMENTO,
            NVL(COMP.COMPRADOR, 'SEM COMPRADOR') AS COMPRADOR,
            COALESCE(R_NF.DESCRICAO, FORN.REDE_PRINC, FORN.REDE_QUALQUER, 'SEM REDE') AS REDE,
            CASE
                WHEN NVL(TRIM(:LT2), '0') != '0' THEN TO_NUMBER(TRIM(:LT2))
                WHEN IE.CGO IN (802, 860) AND IE.SEQPESSOA_NF > 0 THEN IE.SEQPESSOA_NF
                ELSE COALESCE(FORN.COD_FORN_PRINC, FORN.COD_FORN_QUALQUER, 0)
            END AS CODIGO_FORNECEDOR,
            CASE
                WHEN NVL(TRIM(:LT2), '0') != '0' THEN (SELECT MAX(NOMERAZAO) FROM GE_PESSOA WHERE SEQPESSOA = TO_NUMBER(TRIM(:LT2)))
                WHEN IE.CGO IN (802, 860) AND IE.SEQPESSOA_NF > 0 THEN NVL(PESSOA_NF.NOMERAZAO, 'FORNECEDOR ' || IE.SEQPESSOA_NF)
                ELSE COALESCE(FORN.FORN_PRINC, FORN.FORN_QUALQUER, 'SEM FORNECEDOR')
            END AS FORNECEDOR,
            IE.SEQPRODUTO AS CODIGO_PRODUTO,
            IE.DESCRICAO_PRODUTO,
            IE.QTD_NF_NUM,
            IE.VLR_NF_NUM
        FROM ITENS_EMITIDOS IE
        LEFT JOIN GE_PESSOA PESSOA_NF
            ON PESSOA_NF.SEQPESSOA = IE.SEQPESSOA_NF
        LEFT JOIN GE_REDEPESSOA RP_NF
            ON RP_NF.SEQPESSOA = IE.SEQPESSOA_NF
        LEFT JOIN GE_REDE R_NF
            ON R_NF.SEQREDE = RP_NF.SEQREDE
        LEFT JOIN CTE_DEPARTAMENTOS DEP
            ON DEP.SEQFAMILIA = IE.SEQFAMILIA
        LEFT JOIN CTE_FORNEC_FAM FORN
            ON FORN.SEQFAMILIA = IE.SEQFAMILIA
        LEFT JOIN MAP_FAMDIVISAO FD
            ON FD.SEQFAMILIA = IE.SEQFAMILIA
           AND FD.NRODIVISAO = 1
        LEFT JOIN MAX_COMPRADOR COMP
            ON COMP.SEQCOMPRADOR = FD.SEQCOMPRADOR
        WHERE (
            NVL(TRIM(:LT2), '0') = '0' 
            OR TO_CHAR(IE.SEQPESSOA_NF) = TRIM(:LT2)
            OR TO_CHAR(NVL(FORN.COD_FORN_PRINC, 0)) = TRIM(:LT2)
            OR TO_CHAR(NVL(FORN.COD_FORN_QUALQUER, 0)) = TRIM(:LT2)
        )
        AND (
            :LS1 = ' TODAS AS REDES'
            OR NVL(TRIM(:LS1), 'TODOS') IN ('TODOS', '0 - TODOS', '0', '', ' TODAS AS REDES', 'TODAS AS REDES')
            OR UPPER(TRIM(NVL(R_NF.DESCRICAO, ''))) = UPPER(TRIM(:LS1))
            OR UPPER(TRIM(NVL(FORN.REDE_PRINC, ''))) = UPPER(TRIM(:LS1))
            OR UPPER(TRIM(NVL(FORN.REDE_QUALQUER, ''))) = UPPER(TRIM(:LS1))
        )
    ),
    SUBTOTAIS_COMPRADOR AS (
        SELECT /*+ MATERIALIZE */
            D.COMPRADOR,
            SUM(D.VLR_NF_NUM) AS TOTAL_VLR_NF_COMPRADOR
        FROM DADOS_BASE D
        GROUP BY D.COMPRADOR
    ),
    UNIAO_RELATORIO AS (
        SELECT
            1 AS ORDEM_BLOCO,
            CODIGO_EMPRESA,
            EMPRESA,
            DTAEMISSAO,
            TO_CHAR(DTAEMISSAO, 'DD/MM/YYYY') AS DATA_EMISSAO,
            NUMERO_NF,
            CGO,
            DEPARTAMENTO,
            COMPRADOR,
            REDE,
            CODIGO_FORNECEDOR,
            FORNECEDOR,
            CODIGO_PRODUTO,
            DESCRICAO_PRODUTO,
            '    ' || TO_CHAR(ROUND(QTD_NF_NUM, 2), 'FM999G999G990D00') AS QUANTIDADE_NF,
            'R$     ' || TO_CHAR(ROUND(VLR_NF_NUM, 2), 'FM999G999G999G990D00') AS VALOR_PRODUTO_NF
        FROM DADOS_BASE
        
        UNION ALL
        
        SELECT
            2 AS ORDEM_BLOCO,
            998 AS CODIGO_EMPRESA,
            'SUBTOTAL COMPRADOR' AS EMPRESA,
            TO_DATE('30/12/2099', 'DD/MM/YYYY') AS DTAEMISSAO,
            '--/--/----' AS DATA_EMISSAO,
            0 AS NUMERO_NF,
            0 AS CGO,
            '--' AS DEPARTAMENTO,
            SC.COMPRADOR AS COMPRADOR,
            '--' AS REDE,
            0 AS CODIGO_FORNECEDOR,
            'SUBTOTAL -> ' || SC.COMPRADOR AS FORNECEDOR,
            0 AS CODIGO_PRODUTO,
            'SUBTOTAL DO COMPRADOR' AS DESCRICAO_PRODUTO,
            '--' AS QUANTIDADE_NF,
            'R$     ' || TO_CHAR(ROUND(SC.TOTAL_VLR_NF_COMPRADOR, 2), 'FM999G999G999G990D00') AS VALOR_PRODUTO_NF
        FROM SUBTOTAIS_COMPRADOR SC
        
        UNION ALL
        
        SELECT
            3 AS ORDEM_BLOCO,
            999 AS CODIGO_EMPRESA,
            'TOTAL GERAL' AS EMPRESA,
            TO_DATE('31/12/2099', 'DD/MM/YYYY') AS DTAEMISSAO,
            '--/--/----' AS DATA_EMISSAO,
            0 AS NUMERO_NF,
            0 AS CGO,
            '--' AS DEPARTAMENTO,
            '--' AS COMPRADOR,
            '--' AS REDE,
            0 AS CODIGO_FORNECEDOR,
            'TOTAL GERAL ->' AS FORNECEDOR,
            0 AS CODIGO_PRODUTO,
            'TOTAL GERAL CONSOLIDADO' AS DESCRICAO_PRODUTO,
            '--' AS QUANTIDADE_NF,
            'R$     ' || TO_CHAR(ROUND(NVL(SUM(D.VLR_NF_NUM), 0), 2), 'FM999G999G999G990D00') AS VALOR_PRODUTO_NF
        FROM DADOS_BASE D
    )
    SELECT
        CODIGO_EMPRESA,
        EMPRESA,
        DATA_EMISSAO,
        NUMERO_NF,
        CGO,
        DEPARTAMENTO,
        COMPRADOR,
        REDE,
        CODIGO_FORNECEDOR,
        FORNECEDOR,
        CODIGO_PRODUTO,
        DESCRICAO_PRODUTO,
        QUANTIDADE_NF,
        VALOR_PRODUTO_NF
    FROM UNIAO_RELATORIO
    ORDER BY
        ORDEM_BLOCO ASC,
        CASE WHEN ORDEM_BLOCO = 2 THEN COMPRADOR ELSE NULL END ASC,
        DTAEMISSAO ASC,
        NUMERO_NF ASC,
        CODIGO_PRODUTO ASC
)
