SELECT
    A.NROEMPDESTINO AS CODIGO_EMPRESA,
    A.SEQPRODUTO AS CODIGO_PRODUTO,
    B.DESCCOMPLETA AS DESCRICAO_PRODUTO,
    NVL(DEP.DEPARTAMENTO, 'SEM DEPARTAMENTO') AS DEPARTAMENTO,
    A.NROPEDIDOSUPRIM AS NRO_PEDIDO_SUPRIMENTO,
    TO_CHAR(TRUNC(A.DTAEMISSAO), 'DD/MM/YYYY') AS DATA_PEDIDO_SUPRIMENTO,
    P.NROPEDVENDA AS NRO_PED_VENDA,
    MV.NROCARGA AS NROCARGA,
    A.QTDEMBALAGEM AS EMBALAGEM,
    NVL(C.ESTQLOJA, 0) + NVL(C.ESTQDEPOSITO, 0) - NVL(C.QTDRESERVADAVDA, 0) - NVL(C.QTDRESERVADARECEB, 0) AS ESTOQUE_DISPONIVEL_CD,
    ROUND(A.QUANTIDADE_A_EXPEDIR / NULLIF(A.QTDEMBALAGEM, 0), 3) AS QUANTIDADE_A_EXPEDIR,
    NVL(SUM(CP.QTDEMBSEPARADA), 0) AS QTD_SEPARADA,
    ATS.USUARIO_SEPARACAO AS USUARIO_SEPARACAO,
    CASE
        WHEN TRUNC(ATV.DTAHORFIMTAREFA) IS NOT NULL
             AND ATV.USUARIO_CONFERENCIA IS NOT NULL
        THEN NVL(SUM(CC.QTDCONTADA / CP.QTDEMBALAGEM), 0)
        ELSE 0
    END AS QTD_CONFERIDA,
    GREATEST(
        NVL(SUM(CP.QTDEMBSEPARADA), 0) -
        CASE
            WHEN TRUNC(ATV.DTAHORFIMTAREFA) IS NOT NULL
                 AND ATV.USUARIO_CONFERENCIA IS NOT NULL
            THEN NVL(SUM(CC.QTDCONTADA / CP.QTDEMBALAGEM), 0)
            ELSE 0
        END,
        0
    ) AS SALDO_A_CONFERIR,
    TO_CHAR(TRUNC(ATV.DTAHORFIMTAREFA), 'DD/MM/YYYY') AS DATA_CONFERENCIA,
    ATV.USUARIO_CONFERENCIA AS USUARIO_CONFERENCIA,
    NVL(D.ESTQLOJA, 0) + NVL(D.ESTQDEPOSITO, 0) - NVL(D.QTDRESERVADAVDA, 0) - NVL(D.QTDRESERVADARECEB, 0) AS ESTOQUE_DISPONIVEL_LOJA,
    CASE
        WHEN A.QUANTIDADE_A_EXPEDIR = 0 THEN 'Cancelado'
        WHEN P.NROPEDVENDA IS NULL THEN 'Aguardando Pedido Venda'
        WHEN MV.NROCARGA IS NULL THEN 'Pedido Venda Criado'
        WHEN NVL(SUM(CP.QTDEMBSEPARADA), 0) = 0 THEN 'Aguardando Separacao'
        WHEN (
                CASE
                    WHEN TRUNC(ATV.DTAHORFIMTAREFA) IS NOT NULL
                         AND ATV.USUARIO_CONFERENCIA IS NOT NULL
                    THEN NVL(SUM(CC.QTDCONTADA / CP.QTDEMBALAGEM), 0)
                    ELSE 0
                END
             ) = 0
             AND NVL(SUM(CP.QTDEMBSEPARADA), 0) > 0 THEN 'Separado - Sem Conferencia'
        WHEN (
                CASE
                    WHEN TRUNC(ATV.DTAHORFIMTAREFA) IS NOT NULL
                         AND ATV.USUARIO_CONFERENCIA IS NOT NULL
                    THEN NVL(SUM(CC.QTDCONTADA / CP.QTDEMBALAGEM), 0)
                    ELSE 0
                END
             ) < NVL(SUM(CP.QTDEMBSEPARADA), 0) THEN 'Conferencia Parcial'
           WHEN (
                    CASE
                        WHEN TRUNC(ATV.DTAHORFIMTAREFA) IS NOT NULL
                             AND ATV.USUARIO_CONFERENCIA IS NOT NULL
                        THEN NVL(SUM(CC.QTDCONTADA / CP.QTDEMBALAGEM), 0)
                        ELSE 0
                    END
                ) = NVL(SUM(CP.QTDEMBSEPARADA), 0)
               AND NVL(SUM(CP.QTDEMBSEPARADA), 0) > 0
               AND TRUNC(ATV.DTAHORFIMTAREFA) IS NOT NULL
               AND ATV.USUARIO_CONFERENCIA IS NOT NULL THEN 'Conferido'
           WHEN (
                    CASE
                        WHEN TRUNC(ATV.DTAHORFIMTAREFA) IS NOT NULL
                             AND ATV.USUARIO_CONFERENCIA IS NOT NULL
                        THEN NVL(SUM(CC.QTDCONTADA / CP.QTDEMBALAGEM), 0)
                        ELSE 0
                    END
                ) = NVL(SUM(CP.QTDEMBSEPARADA), 0)
               AND NVL(SUM(CP.QTDEMBSEPARADA), 0) > 0
               AND (TRUNC(ATV.DTAHORFIMTAREFA) IS NULL OR ATV.USUARIO_CONFERENCIA IS NULL) THEN 'Separado - Sem Conferencia'
        ELSE 'Em Andamento'
    END AS ETAPA_ATUAL
FROM (
    SELECT
        X.NROEMPDESTINO,
        X.SEQPRODUTO,
        X.NROPEDIDOSUPRIM,
        TRUNC(X.DTAEMISSAO) AS DTAEMISSAO,
        X.QTDEMBALAGEM,
        X.NROEMPRESA,
        SUM(X.QTDSOLICITADA) - SUM(X.QTDEXPCANC) AS QUANTIDADE_A_EXPEDIR
    FROM MAXV_MSUPEDIDOSUPRIMEXP X
    WHERE X.DTAEMISSAO >= TRUNC(:DT1)
      AND X.DTAEMISSAO < TRUNC(:DT2) + 1
      AND X.NROEMPRESA = 15
      AND (
          NVL(TRIM(:LT2), 'TODOS') = 'TODOS'
          OR X.NROEMPDESTINO = TO_NUMBER(REGEXP_SUBSTR(TRIM(:LT2), '[0-9]+'))
      )
      AND (NVL(:NR1, 0) = 0 OR X.SEQPRODUTO = :NR1)
    GROUP BY
        X.NROEMPDESTINO,
        X.SEQPRODUTO,
        X.NROPEDIDOSUPRIM,
        TRUNC(X.DTAEMISSAO),
        X.QTDEMBALAGEM,
        X.NROEMPRESA
    HAVING SUM(X.QTDSOLICITADA) > SUM(X.QTDEXPCANC)
) A
INNER JOIN MAP_PRODUTO B
    ON A.SEQPRODUTO = B.SEQPRODUTO
LEFT JOIN (
    SELECT
        X.SEQFAMILIA,
        MAX(Y.CATEGORIA) AS DEPARTAMENTO
    FROM MAP_FAMDIVCATEG X
    INNER JOIN MAP_CATEGORIA Y
        ON Y.SEQCATEGORIA = X.SEQCATEGORIA
    WHERE X.NRODIVISAO = 1
      AND Y.NRODIVISAO = 1
      AND Y.NIVELHIERARQUIA = 1
      AND UPPER(Y.CATEGORIA) NOT IN ('A CLASSIFICAR', 'ALMOXARIFADO', 'INATIVAR')
      AND UPPER(Y.CATEGORIA) NOT LIKE 'SERVIC%'
    GROUP BY X.SEQFAMILIA
) DEP
    ON B.SEQFAMILIA = DEP.SEQFAMILIA
LEFT JOIN MRL_PRODUTOEMPRESA C
    ON A.SEQPRODUTO = C.SEQPRODUTO AND C.NROEMPRESA = 15
LEFT JOIN MRL_PRODUTOEMPRESA D
    ON A.SEQPRODUTO = D.SEQPRODUTO AND D.NROEMPRESA = A.NROEMPDESTINO
LEFT JOIN (
    SELECT
        P1.NROPEDIDOSUPRIM,
        P1.SEQPRODUTO,
        P1.NROEMPRESA,
        P1.NROEMPDESTINO,
        P1.NROEMPRESAPEDVENDA,
        P1.NROPEDVENDA
    FROM (
        SELECT
            P0.NROPEDIDOSUPRIM,
            P0.SEQPRODUTO,
            P0.NROEMPRESA,
            P0.NROEMPDESTINO,
            P0.NROEMPRESAPEDVENDA,
            P0.NROPEDVENDA,
            ROW_NUMBER() OVER (
                PARTITION BY P0.NROPEDIDOSUPRIM, P0.SEQPRODUTO, P0.NROEMPRESA, P0.NROEMPDESTINO
                ORDER BY
                    CASE WHEN P0.NROEMPRESAPEDVENDA IS NOT NULL THEN 0 ELSE 1 END,
                    CASE WHEN P0.NROPEDVENDA IS NOT NULL THEN 0 ELSE 1 END,
                    P0.NROEMPRESAPEDVENDA DESC,
                    P0.NROPEDVENDA DESC
            ) AS RN
        FROM MSU_PSITEMEXPEDIDO P0
    ) P1
    WHERE P1.RN = 1
) P
    ON A.NROPEDIDOSUPRIM = P.NROPEDIDOSUPRIM
    AND A.SEQPRODUTO = P.SEQPRODUTO
    AND A.NROEMPRESA = P.NROEMPRESA
    AND A.NROEMPDESTINO = P.NROEMPDESTINO
LEFT JOIN MAD_PEDVENDA MV
    ON P.NROPEDVENDA = MV.NROPEDVENDA
    AND P.NROEMPRESAPEDVENDA = MV.NROEMPRESA
LEFT JOIN MLO_CARGAECLIPROD CP
    ON MV.NROCARGA = CP.NROCARGA
    AND A.SEQPRODUTO = CP.SEQPRODUTO
    AND MV.SEQPESSOA = CP.SEQPESSOA
    AND CP.NROEMPRESA = 15
LEFT JOIN MLO_CARGAECOLETOR CC
    ON CP.NROCARGA = CC.NROCARGA
    AND CP.CODDEPOSSEPAR = CC.CODDEPOSSEPAR
    AND CP.SEQLOTE = CC.SEQLOTE
    AND CP.NROQUEBRA = CC.NROQUEBRA
    AND CP.NROPEDVENDA = CC.NROPEDVENDA
    AND CP.SEQPRODUTO = CC.SEQPRODUTO
    AND CP.CODDEPOSITANTE = CC.CODDEPOSITANTE
    AND CP.QTDEMBALAGEM = CC.QTDEMBALAGEM
    AND CP.NROEMPRESA = CC.NROEMPRESA
LEFT JOIN (
    SELECT
        A.NROCARGA,
        A.CODDEPOSSEPAR,
        A.SEQLOTE,
        A.NROQUEBRA,
        A.NROEMPRESA,
        MAX(T.DTAHORFIMTAREFA) AS DTAHORFIMTAREFA,
        MAX(P.NOMEREDUZ) KEEP (DENSE_RANK LAST ORDER BY T.DTAHORFIMTAREFA) AS USUARIO_SEPARACAO
    FROM MLO_ATIVIDADE A
    INNER JOIN MLO_TAREFA T
        ON A.MESANO = T.MESANO
       AND A.SEQTAREFA = T.SEQTAREFA
       AND A.NROEMPRESA = T.NROEMPRESA
    LEFT JOIN MLO_TAREFAPRODUT TP
        ON T.MESANO = TP.MESANO
       AND T.SEQTAREFA = TP.SEQTAREFA
       AND T.NROEMPRESA = TP.NROEMPRESA
    LEFT JOIN MLO_PRODUTIVO P
        ON TP.CODPRODUTIVO = P.CODPRODUTIVO
       AND TP.NROEMPRESA = P.NROEMPRESA
    WHERE A.CODTIPATIVIDADE <> 'CS'
      AND A.INDEXCLUSAO = 'N'
    GROUP BY
        A.NROCARGA,
        A.CODDEPOSSEPAR,
        A.SEQLOTE,
        A.NROQUEBRA,
        A.NROEMPRESA
) ATS
    ON CP.NROCARGA = ATS.NROCARGA
    AND CP.CODDEPOSSEPAR = ATS.CODDEPOSSEPAR
    AND CP.SEQLOTE = ATS.SEQLOTE
    AND CP.NROQUEBRA = ATS.NROQUEBRA
    AND CP.NROEMPRESA = ATS.NROEMPRESA
LEFT JOIN (
    SELECT
        A.NROCARGA,
        A.CODDEPOSSEPAR,
        A.SEQLOTE,
        A.NROQUEBRA,
        A.NROEMPRESA,
        MAX(T.DTAHORFIMTAREFA) AS DTAHORFIMTAREFA,
        MAX(P.NOMEREDUZ) KEEP (DENSE_RANK LAST ORDER BY T.DTAHORFIMTAREFA) AS USUARIO_CONFERENCIA
    FROM MLO_ATIVIDADE A
    INNER JOIN MLO_TAREFA T
        ON A.MESANO = T.MESANO
       AND A.SEQTAREFA = T.SEQTAREFA
       AND A.NROEMPRESA = T.NROEMPRESA
    LEFT JOIN MLO_TAREFAPRODUT TP
        ON T.MESANO = TP.MESANO
       AND T.SEQTAREFA = TP.SEQTAREFA
       AND T.NROEMPRESA = TP.NROEMPRESA
    LEFT JOIN MLO_PRODUTIVO P
        ON TP.CODPRODUTIVO = P.CODPRODUTIVO
       AND TP.NROEMPRESA = P.NROEMPRESA
    WHERE A.CODTIPATIVIDADE = 'CS'
      AND A.INDEXCLUSAO = 'N'
    GROUP BY
        A.NROCARGA,
        A.CODDEPOSSEPAR,
        A.SEQLOTE,
        A.NROQUEBRA,
        A.NROEMPRESA
) ATV
    ON CC.NROCARGA = ATV.NROCARGA
    AND CC.CODDEPOSSEPAR = ATV.CODDEPOSSEPAR
    AND CC.SEQLOTE = ATV.SEQLOTE
    AND CC.NROQUEBRA = ATV.NROQUEBRA
    AND CC.NROEMPRESA = ATV.NROEMPRESA
WHERE (NVL(TRIM(:LT1), 'TODOS') = 'TODOS' OR UPPER(NVL(DEP.DEPARTAMENTO, 'SEM DEPARTAMENTO')) = UPPER(TRIM(:LT1)))
GROUP BY
    A.NROEMPDESTINO,
    A.SEQPRODUTO,
    B.DESCCOMPLETA,
    NVL(DEP.DEPARTAMENTO, 'SEM DEPARTAMENTO'),
    A.NROPEDIDOSUPRIM,
    TRUNC(A.DTAEMISSAO),
    P.NROPEDVENDA,
    MV.NROCARGA,
    A.QTDEMBALAGEM,
    A.QUANTIDADE_A_EXPEDIR,
    ATS.USUARIO_SEPARACAO,
    TRUNC(ATV.DTAHORFIMTAREFA),
    ATV.USUARIO_CONFERENCIA,
    NVL(C.ESTQLOJA, 0) + NVL(C.ESTQDEPOSITO, 0) - NVL(C.QTDRESERVADAVDA, 0) - NVL(C.QTDRESERVADARECEB, 0),
    NVL(D.ESTQLOJA, 0) + NVL(D.ESTQDEPOSITO, 0) - NVL(D.QTDRESERVADAVDA, 0) - NVL(D.QTDRESERVADARECEB, 0)
ORDER BY
    TRUNC(A.DTAEMISSAO),
    A.NROEMPDESTINO,
    A.NROPEDIDOSUPRIM
