SELECT * FROM (
    WITH CAPA_PEDIDOS AS (
        SELECT /*+ MATERIALIZE */
            P.NROPEDIDOSUPRIM,
            P.NROEMPRESA AS LOJA_DESTINO,
            P.SEQFORNECEDOR AS CD_ORIGEM,
            P.DTAEMISSAO,
            P.SITUACAOPED,
            P.TIPPEDIDOSUPRIM
        FROM MSU_PEDIDOSUPRIM P
        WHERE P.TIPPEDIDOSUPRIM != 'C'
          AND TRUNC(P.DTAEMISSAO) BETWEEN TRUNC(:DT1) AND TRUNC(:DT2)
          AND (
              NVL(TRIM(:LT1), 'TODOS') IN ('TODOS', '0 - TODOS', '0', '')
              OR INSTR(',' || REPLACE(TRIM(:LT1), ' ', '') || ',', ',' || TO_CHAR(P.NROEMPRESA) || ',') > 0
          )
          AND (
              NVL(TRIM(:LT2), 'TODOS') IN ('TODOS', '0 - TODOS', '0', '')
              OR INSTR(',' || REPLACE(TRIM(:LT2), ' ', '') || ',', ',' || TO_CHAR(P.SEQFORNECEDOR) || ',') > 0
          )
    ),
    ITENS_SOLICITADOS AS (
        SELECT /*+ MATERIALIZE */
            R.NROPEDIDOSUPRIM,
            R.NROEMPRESA,
            R.SEQPRODUTO,
            SUM(NVL(R.QTDSOLICITADAORIGINAL, R.QTDSOLICITADA)) AS QTD_SOLICITADA,
            SUM(NVL(R.QTDTOTTRANSITO, 0)) AS QTD_TRANSITO_ATUAL,
            SUM(NVL(R.QTDTOTCANCELADA, 0)) AS QTD_CANCELADA_ATUAL,
            MAX(R.STATUSITEM) AS STATUS_ITEM_ATUAL
        FROM MSU_PSITEMRECEBER R
        INNER JOIN CAPA_PEDIDOS C ON C.NROPEDIDOSUPRIM = R.NROPEDIDOSUPRIM AND C.LOJA_DESTINO = R.NROEMPRESA
        WHERE (NVL(TRIM(:NR1), '0') IN ('0', '') OR R.SEQPRODUTO = TO_NUMBER(:NR1))
        GROUP BY R.NROPEDIDOSUPRIM, R.NROEMPRESA, R.SEQPRODUTO
    ),
    ITENS_EXPEDIDOS_CD AS (
        SELECT /*+ MATERIALIZE */
            E.NROPEDIDOSUPRIM,
            E.NROEMPRESA AS CD_ORIGEM,
            E.SEQPRODUTO,
            SUM(NVL(E.QTDEXPEDIDA, 0)) AS QTD_EXPEDIDA_CD,
            SUM(NVL(E.QTDCANCELADA, 0)) AS QTD_CORTADA_CD,
            MAX(E.NUMERONF) AS NF_SAIDA_CD,
            MAX(NVL(E.DTAINCLUSAO, E.DTAALTERACAO)) AS DTA_EXPEDICAO_CD
        FROM MSU_PSITEMEXPEDIDO E
        INNER JOIN CAPA_PEDIDOS C ON C.NROPEDIDOSUPRIM = E.NROPEDIDOSUPRIM AND C.CD_ORIGEM = E.NROEMPRESA
        WHERE (NVL(TRIM(:NR1), '0') IN ('0', '') OR E.SEQPRODUTO = TO_NUMBER(:NR1))
        GROUP BY E.NROPEDIDOSUPRIM, E.NROEMPRESA, E.SEQPRODUTO
    ),
    ITENS_RECEBIDOS_LOJA AS (
        SELECT /*+ MATERIALIZE */
            L.NROPEDIDOSUPRIM,
            L.NROEMPRESA,
            L.SEQPRODUTO,
            SUM(NVL(L.QTDRECEBIDA, 0)) AS QTD_RECEBIDA_LOJA,
            MAX(L.NUMERONF) AS NF_ENTRADA_LOJA,
            MAX(NVL(L.DTAMOVIMENTO, L.DTAINCLUSAO)) AS DTA_RECEBIMENTO_LOJA
        FROM MSU_PSITEMRECEBIDO L
        INNER JOIN CAPA_PEDIDOS C ON C.NROPEDIDOSUPRIM = L.NROPEDIDOSUPRIM AND C.LOJA_DESTINO = L.NROEMPRESA
        WHERE (NVL(TRIM(:NR1), '0') IN ('0', '') OR L.SEQPRODUTO = TO_NUMBER(:NR1))
        GROUP BY L.NROPEDIDOSUPRIM, L.NROEMPRESA, L.SEQPRODUTO
    ),
    PRODUTOS_DISTINTOS AS (
        SELECT /*+ MATERIALIZE */ DISTINCT SEQPRODUTO
        FROM ITENS_SOLICITADOS
    ),
    DADOS_PRODUTO AS (
        SELECT /*+ MATERIALIZE */
            P.SEQPRODUTO,
            MP.DESCCOMPLETA
        FROM PRODUTOS_DISTINTOS P
        INNER JOIN MAP_PRODUTO MP ON MP.SEQPRODUTO = P.SEQPRODUTO
    ),
    ESTOQUE_CD AS (
        SELECT /*+ MATERIALIZE */
            P.SEQPRODUTO,
            PE.NROEMPRESA AS CD_ORIGEM,
            NVL(PE.ESTQLOJA, 0) + NVL(PE.ESTQDEPOSITO, 0) - NVL(PE.QTDRESERVADAVDA, 0) - NVL(PE.QTDRESERVADARECEB, 0) - NVL(PE.QTDRESERVADAFIXA, 0) AS QTD_ESTOQUE_ATUAL
        FROM PRODUTOS_DISTINTOS P
        INNER JOIN MRL_PRODUTOEMPRESA PE ON PE.SEQPRODUTO = P.SEQPRODUTO
    ),
    BASE_RELATORIO_PRE AS (
        SELECT /*+ MATERIALIZE */
            C.NROPEDIDOSUPRIM AS NUMERO_PEDIDO,
            S.SEQPRODUTO AS CODIGO_PRODUTO,
            PR.DESCCOMPLETA AS DESCRICAO_PRODUTO,
            NVL(EST.QTD_ESTOQUE_ATUAL, 0) AS ESTOQUE_ATUAL_CD,
            S.QTD_SOLICITADA,
            CASE 
                WHEN NVL(X.QTD_EXPEDIDA_CD, 0) > 0 THEN NVL(X.QTD_EXPEDIDA_CD, 0)
                ELSE (NVL(REC.QTD_RECEBIDA_LOJA, 0) + NVL(S.QTD_TRANSITO_ATUAL, 0))
            END AS QTD_EXPEDIDA_CD,
            NVL(REC.QTD_RECEBIDA_LOJA, 0) AS QTD_RECEBIDA_LOJA,
            NVL(X.NF_SAIDA_CD, REC.NF_ENTRADA_LOJA) AS NUMERO_NOTA_FISCAL,
            NVL(X.DTA_EXPEDICAO_CD, REC.DTA_RECEBIMENTO_LOJA) AS DATA_EXPEDICAO_ORDEM,
            CASE
                WHEN NVL(REC.QTD_RECEBIDA_LOJA, 0) >= S.QTD_SOLICITADA AND S.QTD_SOLICITADA > 0 THEN 'ATENDIDO TOTAL'
                WHEN NVL(REC.QTD_RECEBIDA_LOJA, 0) > 0 AND NVL(REC.QTD_RECEBIDA_LOJA, 0) < S.QTD_SOLICITADA THEN 'ATENDIDO PARCIAL'
                WHEN CASE WHEN NVL(X.QTD_EXPEDIDA_CD, 0) > 0 THEN NVL(X.QTD_EXPEDIDA_CD, 0) ELSE (NVL(REC.QTD_RECEBIDA_LOJA, 0) + NVL(S.QTD_TRANSITO_ATUAL, 0)) END > 0 AND NVL(REC.QTD_RECEBIDA_LOJA, 0) = 0 THEN 'EM TRANSITO'
                WHEN S.QTD_TRANSITO_ATUAL > 0 THEN 'EM TRANSITO'
                WHEN C.SITUACAOPED = 'C' OR S.STATUS_ITEM_ATUAL = 'C' THEN 'CANCELADO'
                WHEN C.SITUACAOPED IN ('D', 'A', 'L', 'P', 'S', 'W', 'R') AND CASE WHEN NVL(X.QTD_EXPEDIDA_CD, 0) > 0 THEN NVL(X.QTD_EXPEDIDA_CD, 0) ELSE (NVL(REC.QTD_RECEBIDA_LOJA, 0) + NVL(S.QTD_TRANSITO_ATUAL, 0)) END = 0 THEN 'EM SEPARACAO CD'
                WHEN C.SITUACAOPED = 'F' AND CASE WHEN NVL(X.QTD_EXPEDIDA_CD, 0) > 0 THEN NVL(X.QTD_EXPEDIDA_CD, 0) ELSE (NVL(REC.QTD_RECEBIDA_LOJA, 0) + NVL(S.QTD_TRANSITO_ATUAL, 0)) END = 0 THEN 'CORTADO NF'
                ELSE 'NAO ATENDIDO'
            END AS STATUS_ATENDIMENTO
        FROM ITENS_SOLICITADOS S
        INNER JOIN CAPA_PEDIDOS C ON C.NROPEDIDOSUPRIM = S.NROPEDIDOSUPRIM AND C.LOJA_DESTINO = S.NROEMPRESA
        INNER JOIN DADOS_PRODUTO PR ON PR.SEQPRODUTO = S.SEQPRODUTO
        LEFT JOIN ITENS_EXPEDIDOS_CD X ON X.NROPEDIDOSUPRIM = S.NROPEDIDOSUPRIM AND X.CD_ORIGEM = C.CD_ORIGEM AND X.SEQPRODUTO = S.SEQPRODUTO
        LEFT JOIN ITENS_RECEBIDOS_LOJA REC ON REC.NROPEDIDOSUPRIM = S.NROPEDIDOSUPRIM AND REC.NROEMPRESA = S.NROEMPRESA AND REC.SEQPRODUTO = S.SEQPRODUTO
        LEFT JOIN ESTOQUE_CD EST ON EST.SEQPRODUTO = S.SEQPRODUTO AND EST.CD_ORIGEM = C.CD_ORIGEM
    ),
    BASE_RELATORIO AS (
        SELECT /*+ MATERIALIZE */ *
        FROM BASE_RELATORIO_PRE
        WHERE (
            NVL(TRIM(:LS1), 'TODOS') IN ('TODOS', '0 - TODOS', '0', '')
            OR INSTR(TRIM(:LS1), 'TODOS') > 0
            OR STATUS_ATENDIMENTO = TRIM(:LS1)
            OR INSTR(STATUS_ATENDIMENTO, TRIM(:LS1)) > 0
            OR INSTR(TRIM(:LS1), STATUS_ATENDIMENTO) > 0
        )
    ),
    RESUMO_PRODUTO AS (
        SELECT /*+ MATERIALIZE */
            CODIGO_PRODUTO,
            DESCRICAO_PRODUTO,
            COUNT(DISTINCT NUMERO_PEDIDO) AS QTD_PEDIDOS,
            SUM(CASE WHEN STATUS_ATENDIMENTO = 'ATENDIDO TOTAL' THEN 1 ELSE 0 END) AS VEZES_ATENDIDO_TOTAL,
            SUM(CASE WHEN STATUS_ATENDIMENTO = 'ATENDIDO PARCIAL' THEN 1 ELSE 0 END) AS VEZES_ATENDIDO_PARCIAL,
            SUM(CASE WHEN STATUS_ATENDIMENTO IN ('CANCELADO', 'CORTADO NF') THEN 1 ELSE 0 END) AS VEZES_CORTADO_CANCELADO,
            SUM(CASE WHEN STATUS_ATENDIMENTO = 'EM TRANSITO' THEN 1 ELSE 0 END) AS VEZES_EM_TRANSITO,
            SUM(CASE WHEN STATUS_ATENDIMENTO = 'EM SEPARACAO CD' THEN 1 ELSE 0 END) AS VEZES_EM_SEPARACAO,
            SUM(CASE WHEN STATUS_ATENDIMENTO = 'NAO ATENDIDO' THEN 1 ELSE 0 END) AS VEZES_NAO_ATENDIDO,
            COUNT(DISTINCT NUMERO_NOTA_FISCAL) AS QTD_NFS_EMITIDAS,
            SUM(QTD_SOLICITADA) AS TOTAL_QTD_SOLICITADA,
            SUM(QTD_EXPEDIDA_CD) AS TOTAL_QTD_EXPEDIDA,
            MAX(DATA_EXPEDICAO_ORDEM) AS MAX_DATA_EXPEDICAO,
            MAX(ESTOQUE_ATUAL_CD) AS ESTOQUE_ATUAL_CD
        FROM BASE_RELATORIO
        GROUP BY CODIGO_PRODUTO, DESCRICAO_PRODUTO
    )
    SELECT
        CODIGO_PRODUTO,
        DESCRICAO_PRODUTO,
        ESTOQUE_ATUAL_CD,
        QTD_PEDIDOS,
        VEZES_ATENDIDO_TOTAL,
        VEZES_ATENDIDO_PARCIAL,
        VEZES_CORTADO_CANCELADO,
        VEZES_EM_TRANSITO,
        VEZES_EM_SEPARACAO,
        VEZES_NAO_ATENDIDO,
        QTD_NFS_EMITIDAS,
        TOTAL_QTD_SOLICITADA,
        TOTAL_QTD_EXPEDIDA,
        TO_CHAR(MAX_DATA_EXPEDICAO, 'DD/MM/YYYY') AS ULTIMA_EXPEDICAO
    FROM RESUMO_PRODUTO
    ORDER BY QTD_PEDIDOS DESC, CODIGO_PRODUTO
)
