SELECT 
    MLF_NOTAFISCAL.SEQPESSOA AS CODIGO_FORNECEDOR,
    GE_PESSOA.NOMERAZAO AS DESCRICAO_FORNECEDOR,
    SUBSTR(FC5MASKCNPJCPF(GE_PESSOA.NROCGCCPF, GE_PESSOA.DIGCGCCPF, GE_PESSOA.FISICAJURIDICA), 1, 20) AS CNPJ,
    'R$ ' || TO_CHAR(SUM(NVL(MLF_NFITEM.VLRTOTALITEM, 0)), 'FM999G999G990D00', 'NLS_NUMERIC_CHARACTERS='',.''') AS VALOR_TOTAL_FATURADO
FROM MLF_NOTAFISCAL
INNER JOIN MLF_NFITEM ON MLF_NFITEM.NUMERONF = MLF_NOTAFISCAL.NUMERONF 
                     AND MLF_NFITEM.SERIENF = MLF_NOTAFISCAL.SERIENF 
                     AND MLF_NFITEM.NROEMPRESA = MLF_NOTAFISCAL.NROEMPRESA 
                     AND MLF_NFITEM.TIPNOTAFISCAL = MLF_NOTAFISCAL.TIPNOTAFISCAL
                     AND NVL(MLF_NFITEM.SEQNF, 0) = NVL(MLF_NOTAFISCAL.SEQNF, 0)
INNER JOIN GE_PESSOA ON GE_PESSOA.SEQPESSOA = MLF_NOTAFISCAL.SEQPESSOA
WHERE MLF_NOTAFISCAL.DTAENTRADA BETWEEN :DT1 AND :DT2
  AND MLF_NOTAFISCAL.STATUSNF <> 'C'
  AND (
      NVL(TRIM(:LT1), '0') IN ('0', 'TODOS', '')
      OR INSTR(',' || REPLACE(TRIM(:LT1), ' ', '') || ',', ',' || MLF_NOTAFISCAL.CODGERALOPER || ',') > 0
  )
  AND (
      NVL(TRIM(:LS1), 'TODOS') IN ('TODOS', '0 - TODOS', '0', '')
      OR INSTR(TRIM(:LS1), 'TODOS') > 0
      OR TO_CHAR(MLF_NOTAFISCAL.SEQPESSOA) = TRIM(:LS1)
      OR INSTR(TRIM(:LS1), TO_CHAR(MLF_NOTAFISCAL.SEQPESSOA) || ' - ') = 1
      OR INSTR(TRIM(:LS1), TO_CHAR(MLF_NOTAFISCAL.SEQPESSOA) || '-') = 1
  )
GROUP BY 
    MLF_NOTAFISCAL.SEQPESSOA,
    GE_PESSOA.NOMERAZAO,
    GE_PESSOA.NROCGCCPF,
    GE_PESSOA.DIGCGCCPF,
    GE_PESSOA.FISICAJURIDICA
ORDER BY SUM(NVL(MLF_NFITEM.VLRTOTALITEM, 0)) DESC, DESCRICAO_FORNECEDOR
