SELECT * FROM (
    WITH FILTRO_PRODUTOS AS (
        SELECT /*+ MATERIALIZE */ TO_NUMBER(TRIM(:NR1)) AS SEQPRODUTO
        FROM DUAL
        WHERE TRIM(:NR1) IS NOT NULL AND TRIM(:NR1) <> '0'
    ),
    OFERTAS_PRODUTO AS (
        SELECT /*+ MATERIALIZE */ DISTINCT
            M.SEQPRODUTO,
            TRIM(M.PROMOCAO) AS NOME_OFERTA,
            TRUNC(M.DTAINICIO) AS DTAINICIO,
            TRUNC(M.DTAFIM) AS DTAFIM
        FROM MRLV_BASEPRODPROMOC M
        INNER JOIN FILTRO_PRODUTOS FP ON FP.SEQPRODUTO = M.SEQPRODUTO
    ),
    ITENS_SOLICITADOS AS (
        SELECT /*+ MATERIALIZE */
            R.NROPEDIDOSUPRIM,
            R.NROEMPRESA,
            R.SEQPRODUTO,
            C.SEQFORNECEDOR AS CD_ORIGEM,
            C.DTAEMISSAO,
            C.SITUACAOPED,
            SUM(NVL(R.QTDSOLICITADAORIGINAL, R.QTDSOLICITADA)) AS QTD_SOLICITADA,
            SUM(NVL(R.QTDTOTTRANSITO, 0)) AS QTD_TRANSITO_ATUAL,
            SUM(NVL(R.QTDTOTCANCELADA, 0)) AS QTD_CANCELADA_ATUAL,
            MAX(R.STATUSITEM) AS STATUS_ITEM_ATUAL
        FROM MSU_PSITEMRECEBER R
        INNER JOIN MSU_PEDIDOSUPRIM C ON C.NROPEDIDOSUPRIM = R.NROPEDIDOSUPRIM AND C.NROEMPRESA = R.NROEMPRESA
        INNER JOIN FILTRO_PRODUTOS FP ON FP.SEQPRODUTO = R.SEQPRODUTO
        WHERE C.TIPPEDIDOSUPRIM != 'C'
          AND TRUNC(C.DTAEMISSAO) BETWEEN TRUNC(:DT1) AND TRUNC(:DT2)
          AND (
              NVL(TRIM(:LT1), 'TODOS') IN ('TODOS', '0 - TODOS', '0', '')
              OR INSTR(',' || REPLACE(TRIM(:LT1), ' ', '') || ',', ',' || TO_CHAR(C.NROEMPRESA) || ',') > 0
          )
          AND (
              NVL(TRIM(:LT2), 'TODOS') IN ('TODOS', '0 - TODOS', '0', '')
              OR INSTR(',' || REPLACE(TRIM(:LT2), ' ', '') || ',', ',' || TO_CHAR(C.SEQFORNECEDOR) || ',') > 0
          )
        GROUP BY R.NROPEDIDOSUPRIM, R.NROEMPRESA, R.SEQPRODUTO, C.SEQFORNECEDOR, C.DTAEMISSAO, C.SITUACAOPED
    ),
    PEDIDOS_COM_OFERTAS AS (
        SELECT /*+ MATERIALIZE */
            S.NROPEDIDOSUPRIM,
            S.NROEMPRESA,
            S.SEQPRODUTO,
            LISTAGG(O.NOME_OFERTA, ' | ') WITHIN GROUP (ORDER BY O.NOME_OFERTA) AS OFERTAS_VIGENTES
        FROM ITENS_SOLICITADOS S
        INNER JOIN OFERTAS_PRODUTO O ON O.SEQPRODUTO = S.SEQPRODUTO 
            AND TRUNC(S.DTAEMISSAO) BETWEEN O.DTAINICIO AND O.DTAFIM
        GROUP BY S.NROPEDIDOSUPRIM, S.NROEMPRESA, S.SEQPRODUTO
    ),
    ITENS_EXPEDIDOS_CD AS (
        SELECT /*+ MATERIALIZE */
            E.NROPEDIDOSUPRIM,
            E.NROEMPDESTINO AS NROEMPRESA,
            E.SEQPRODUTO,
            SUM(NVL(E.QTDEXPEDIDA, 0)) AS QTD_EXPEDIDA_CD,
            SUM(NVL(E.QTDCANCELADA, 0)) AS QTD_CORTADA_CD,
            MAX(E.NUMERONF) AS NF_SAIDA_CD,
            MAX(NVL(E.DTAINCLUSAO, E.DTAALTERACAO)) AS DTA_EXPEDICAO_CD
        FROM MSU_PSITEMEXPEDIDO E
        INNER JOIN ITENS_SOLICITADOS S ON S.NROPEDIDOSUPRIM = E.NROPEDIDOSUPRIM AND S.NROEMPRESA = E.NROEMPDESTINO AND S.SEQPRODUTO = E.SEQPRODUTO
        GROUP BY E.NROPEDIDOSUPRIM, E.NROEMPDESTINO, E.SEQPRODUTO
    ),
    ITENS_RECEBIDOS_LOJA AS (
        SELECT /*+ MATERIALIZE */
            L.NROPEDIDOSUPRIM,
            L.NROEMPRESA,
            L.SEQPRODUTO,
            SUM(NVL(L.QTDRECEBIDA, 0)) AS QTD_RECEBIDA_LOJA,
            MAX(L.NUMERONF) AS NF_ENTRADA_LOJA,
            MAX(NVL(L.DTAMOVIMENTO, L.DTAINCLUSAO)) AS DTA_RECEBIMENTO_LOJA
        FROM MSU_PSITEMRECEBIDO L
        INNER JOIN ITENS_SOLICITADOS S ON S.NROPEDIDOSUPRIM = L.NROPEDIDOSUPRIM AND S.NROEMPRESA = L.NROEMPRESA AND S.SEQPRODUTO = L.SEQPRODUTO
        GROUP BY L.NROPEDIDOSUPRIM, L.NROEMPRESA, L.SEQPRODUTO
    ),
    DADOS_PRODUTO AS (
        SELECT /*+ MATERIALIZE */
            MP.SEQPRODUTO,
            MP.DESCCOMPLETA
        FROM MAP_PRODUTO MP
        INNER JOIN FILTRO_PRODUTOS FP ON FP.SEQPRODUTO = MP.SEQPRODUTO
    ),
    ESTOQUE_CD AS (
        SELECT /*+ MATERIALIZE */
            PE.SEQPRODUTO,
            PE.NROEMPRESA AS CD_ORIGEM,
            NVL(PE.ESTQLOJA, 0) + NVL(PE.ESTQDEPOSITO, 0) - NVL(PE.QTDRESERVADAVDA, 0) - NVL(PE.QTDRESERVADARECEB, 0) - NVL(PE.QTDRESERVADAFIXA, 0) AS QTD_ESTOQUE_ATUAL,
            PE.DTAULTCOMPRA
        FROM MRL_PRODUTOEMPRESA PE
        INNER JOIN FILTRO_PRODUTOS FP ON FP.SEQPRODUTO = PE.SEQPRODUTO
    ),
    BASE_RELATORIO AS (
        SELECT /*+ MATERIALIZE */
            S.NROPEDIDOSUPRIM AS NUMERO_PEDIDO,
            S.CD_ORIGEM,
            S.NROEMPRESA AS LOJA_DESTINO,
            TO_CHAR(S.DTAEMISSAO, 'DD/MM/YYYY') AS DATA_EMISSAO,
            S.SEQPRODUTO AS CODIGO_PRODUTO,
            PR.DESCCOMPLETA AS DESCRICAO_PRODUTO,
            S.QTD_SOLICITADA,
            NVL(X.QTD_CORTADA_CD, S.QTD_CANCELADA_ATUAL) AS QTD_CORTADA_CD,
            NVL(X.QTD_EXPEDIDA_CD, 0) AS QTD_EXPEDIDA_CD,
            S.QTD_TRANSITO_ATUAL AS QTD_EM_TRANSITO,
            NVL(REC.QTD_RECEBIDA_LOJA, 0) AS QTD_RECEBIDA_LOJA,
            NVL(X.NF_SAIDA_CD, REC.NF_ENTRADA_LOJA) AS NUMERO_NOTA_FISCAL,
            TO_CHAR(NVL(X.DTA_EXPEDICAO_CD, REC.DTA_RECEBIMENTO_LOJA), 'DD/MM/YYYY') AS DATA_EXPEDICAO,
            CASE
                WHEN NVL(REC.QTD_RECEBIDA_LOJA, 0) >= S.QTD_SOLICITADA AND S.QTD_SOLICITADA > 0 THEN 'ATENDIDO TOTAL'
                WHEN NVL(REC.QTD_RECEBIDA_LOJA, 0) > 0 AND NVL(REC.QTD_RECEBIDA_LOJA, 0) < S.QTD_SOLICITADA THEN 'ATENDIDO PARCIAL'
                WHEN NVL(X.QTD_EXPEDIDA_CD, 0) > 0 AND NVL(REC.QTD_RECEBIDA_LOJA, 0) = 0 THEN 'EM TRANSITO'
                WHEN S.QTD_TRANSITO_ATUAL > 0 THEN 'EM TRANSITO'
                WHEN S.SITUACAOPED = 'C' OR S.STATUS_ITEM_ATUAL = 'C' THEN 'CANCELADO'
                WHEN S.SITUACAOPED IN ('D', 'A', 'L', 'P', 'S', 'W', 'R') AND NVL(X.QTD_EXPEDIDA_CD, 0) = 0 THEN 'EM SEPARACAO CD'
                WHEN S.SITUACAOPED = 'F' AND NVL(X.QTD_EXPEDIDA_CD, 0) = 0 THEN 'CORTADO NF'
                ELSE 'NAO ATENDIDO'
            END AS STATUS_ATENDIMENTO,
            PO.OFERTAS_VIGENTES
        FROM ITENS_SOLICITADOS S
        INNER JOIN DADOS_PRODUTO PR ON PR.SEQPRODUTO = S.SEQPRODUTO
        LEFT JOIN ITENS_EXPEDIDOS_CD X ON X.NROPEDIDOSUPRIM = S.NROPEDIDOSUPRIM AND X.NROEMPRESA = S.NROEMPRESA AND X.SEQPRODUTO = S.SEQPRODUTO
        LEFT JOIN ITENS_RECEBIDOS_LOJA REC ON REC.NROPEDIDOSUPRIM = S.NROPEDIDOSUPRIM AND REC.NROEMPRESA = S.NROEMPRESA AND REC.SEQPRODUTO = S.SEQPRODUTO
        LEFT JOIN PEDIDOS_COM_OFERTAS PO ON PO.NROPEDIDOSUPRIM = S.NROPEDIDOSUPRIM AND PO.NROEMPRESA = S.NROEMPRESA AND PO.SEQPRODUTO = S.SEQPRODUTO
        
        UNION ALL
        
        SELECT /*+ MATERIALIZE */
            999999999 AS NUMERO_PEDIDO,
            E.CD_ORIGEM,
            0 AS LOJA_DESTINO,
            TO_CHAR(SYSDATE + 1000, 'DD/MM/YYYY') AS DATA_EMISSAO,
            E.SEQPRODUTO AS CODIGO_PRODUTO,
            '---> ESTOQUE ATUAL DISPONIVEL NO CD: ' || TO_CHAR(E.QTD_ESTOQUE_ATUAL) || ' UN <---' AS DESCRICAO_PRODUTO,
            0 AS QTD_SOLICITADA,
            0 AS QTD_CORTADA_CD,
            0 AS QTD_EXPEDIDA_CD,
            0 AS QTD_EM_TRANSITO,
            0 AS QTD_RECEBIDA_LOJA,
            0 AS NUMERO_NOTA_FISCAL,
            '--/--/----' AS DATA_EXPEDICAO,
            'INFO ESTOQUE' AS STATUS_ATENDIMENTO,
            'ULT. COMPRA: ' || NVL(TO_CHAR(E.DTAULTCOMPRA, 'DD/MM/YYYY'), 'S/DADOS') AS OFERTAS_VIGENTES
        FROM ESTOQUE_CD E
        INNER JOIN (SELECT DISTINCT CD_ORIGEM FROM ITENS_SOLICITADOS) SOL ON SOL.CD_ORIGEM = E.CD_ORIGEM
    )
    SELECT
        NUMERO_PEDIDO AS PEDIDO,
        CD_ORIGEM AS CD,
        LOJA_DESTINO AS LOJA,
        DATA_EMISSAO AS DTA_EMISSAO,
        CODIGO_PRODUTO AS PRODUTO,
        DESCRICAO_PRODUTO AS DESCRICAO,
        QTD_SOLICITADA AS QTD_SOLIC,
        QTD_CORTADA_CD AS QTD_CORT,
        QTD_EXPEDIDA_CD AS QTD_EXP,
        QTD_EM_TRANSITO AS QTD_TRANS,
        QTD_RECEBIDA_LOJA AS QTD_REC,
        NUMERO_NOTA_FISCAL AS NF,
        DATA_EXPEDICAO AS DTA_EXP,
        STATUS_ATENDIMENTO AS STATUS,
        OFERTAS_VIGENTES AS OFERTAS
    FROM BASE_RELATORIO
    WHERE (
        NVL(TRIM(:LS1), 'TODOS') IN ('TODOS', '0 - TODOS', '0', '')
        OR INSTR(TRIM(:LS1), 'TODOS') > 0
        OR STATUS_ATENDIMENTO = TRIM(:LS1)
        OR INSTR(STATUS_ATENDIMENTO, TRIM(:LS1)) > 0
        OR INSTR(TRIM(:LS1), STATUS_ATENDIMENTO) > 0
        OR STATUS_ATENDIMENTO = 'INFO ESTOQUE'
    )
)
ORDER BY TO_DATE(DTA_EMISSAO, 'DD/MM/YYYY') DESC, PEDIDO DESC
