SELECT * FROM (
    WITH CAPA_PEDIDOS AS (
        SELECT /*+ MATERIALIZE */
            P.NROPEDIDOSUPRIM,
            P.NROEMPRESA,
            P.CENTRALLOJA,
            P.SEQFORNECEDOR,
            P.SEQCOMPRADOR,
            P.DTAEMISSAO,
            P.DTARECEBTO,
            P.DTALIMITERECEBTO
        FROM MSU_PEDIDOSUPRIM P
        WHERE P.TIPPEDIDOSUPRIM = 'C'
          AND TRUNC(P.DTAEMISSAO) BETWEEN TRUNC(:DT1) AND TRUNC(:DT2)
          AND (:NR1 = 0 OR P.SEQFORNECEDOR = :NR1)
          AND (:DT3 IS NULL OR TRUNC(P.DTALIMITERECEBTO) <= TRUNC(:DT3))
    ),
    CANCELAMENTOS_HUMANOS AS (
        SELECT /*+ MATERIALIZE */
            H.NROPEDIDOSUPRIM,
            H.NROEMPRESA,
            H.SEQPRODUTO
        FROM MSU_PSITEMRECEBIDO H
        INNER JOIN CAPA_PEDIDOS C
            ON C.NROPEDIDOSUPRIM = H.NROPEDIDOSUPRIM
           AND C.NROEMPRESA = H.NROEMPRESA
        WHERE NVL(H.QTDCANCELADA, 0) > 0
          AND UPPER(TRIM(NVL(H.USUCANCELAMENTO, 'X'))) != 'JOBAUTOM'
        GROUP BY
            H.NROPEDIDOSUPRIM,
            H.NROEMPRESA,
            H.SEQPRODUTO
    ),
    ITENS_PEDIDOS AS (
        SELECT /*+ MATERIALIZE */
            R.NROPEDIDOSUPRIM,
            R.NROEMPRESA,
            R.CENTRALLOJA,
            R.SEQPRODUTO,
            R.STATUSITEM,
            MAX(NVL(R.QTDEMBALAGEM, 1)) AS QTD_EMBALAGEM,
            SUM(NVL(R.QTDSOLICITADA, 0)) AS QUANTIDADE_PEDIDA
        FROM MSU_PSITEMRECEBER R
        INNER JOIN CAPA_PEDIDOS C
            ON C.NROPEDIDOSUPRIM = R.NROPEDIDOSUPRIM
           AND C.NROEMPRESA = R.NROEMPRESA
           AND C.CENTRALLOJA = R.CENTRALLOJA
        LEFT JOIN CANCELAMENTOS_HUMANOS CH
            ON CH.NROPEDIDOSUPRIM = R.NROPEDIDOSUPRIM
           AND CH.NROEMPRESA = R.NROEMPRESA
           AND CH.SEQPRODUTO = R.SEQPRODUTO
        WHERE CH.SEQPRODUTO IS NULL
        GROUP BY
            R.NROPEDIDOSUPRIM,
            R.NROEMPRESA,
            R.CENTRALLOJA,
            R.SEQPRODUTO,
            R.STATUSITEM
    ),
    ITENS_RECEBIDOS AS (
        SELECT /*+ MATERIALIZE */
            L.NROPEDIDOSUPRIM,
            L.NROEMPRESA,
            L.SEQPRODUTO,
            SUM(NVL(L.QTDRECEBIDA, 0)) AS QUANTIDADE_ATENDIDA
        FROM MSU_PSITEMRECEBIDO L
        INNER JOIN CAPA_PEDIDOS C
            ON C.NROPEDIDOSUPRIM = L.NROPEDIDOSUPRIM
           AND C.NROEMPRESA = L.NROEMPRESA
        GROUP BY
            L.NROPEDIDOSUPRIM,
            L.NROEMPRESA,
            L.SEQPRODUTO
    ),
    BASE_FINAL AS (
        SELECT /*+ MATERIALIZE */
            NVL(COMP.APELIDO, NVL(COMP.COMPRADOR, 'SEM COMPRADOR')) AS COMPRADOR,
            TO_CHAR(C.SEQFORNECEDOR) || ' - ' || GP.NOMERAZAO AS FORNECEDOR,
            C.NROPEDIDOSUPRIM AS NUMERO_PEDIDO,
            C.NROEMPRESA AS LOJA_DESTINO,
            TO_CHAR(C.DTAEMISSAO, 'DD/MM/YYYY') AS DATA_EMISSAO,
            TO_CHAR(C.DTARECEBTO, 'DD/MM/YYYY') AS DATA_PREV_ENTREGA,
            TO_CHAR(C.DTALIMITERECEBTO, 'DD/MM/YYYY') AS DATA_LIMITE_ENTREGA,
            I.SEQPRODUTO AS CODIGO_PRODUTO,
            PR.DESCCOMPLETA AS DESCRICAO,
            NVL(NULLIF(NVL(I.QTD_EMBALAGEM, NVL(FD.PADRAOEMBCOMPRA, 1)), 0), 1) AS QTD_EMBALAGEM,
            ROUND(I.QUANTIDADE_PEDIDA / NVL(NULLIF(NVL(I.QTD_EMBALAGEM, NVL(FD.PADRAOEMBCOMPRA, 1)), 0), 1), 2) AS QUANTIDADE_PEDIDA,
            ROUND(NVL(REC.QUANTIDADE_ATENDIDA, 0) / NVL(NULLIF(NVL(I.QTD_EMBALAGEM, NVL(FD.PADRAOEMBCOMPRA, 1)), 0), 1), 2) AS QUANTIDADE_ATENDIDA,
            CASE
                WHEN NVL(I.QUANTIDADE_PEDIDA, 0) = 0 THEN 0
                ELSE ROUND((NVL(REC.QUANTIDADE_ATENDIDA, 0) / I.QUANTIDADE_PEDIDA) * 100, 2)
            END AS PERC_ATENDIMENTO,
            CASE
                WHEN NVL(I.QUANTIDADE_PEDIDA, 0) > 0 AND NVL(REC.QUANTIDADE_ATENDIDA, 0) >= I.QUANTIDADE_PEDIDA THEN 'TOT_ATEND'
                WHEN NVL(REC.QUANTIDADE_ATENDIDA, 0) > 0 AND NVL(REC.QUANTIDADE_ATENDIDA, 0) < NVL(I.QUANTIDADE_PEDIDA, 0) THEN 'ATEND_PARC'
                WHEN C.DTALIMITERECEBTO IS NOT NULL AND TRUNC(C.DTALIMITERECEBTO) < TRUNC(SYSDATE) THEN 'NÃO_ATENDIDO'
                WHEN C.DTARECEBTO IS NOT NULL AND TRUNC(C.DTARECEBTO) < TRUNC(SYSDATE) THEN 'ATRASO'
                ELSE 'AGUARDANDO'
            END AS STATUS_ENTREGA,
            CASE I.STATUSITEM
                WHEN 'A' THEN 'A - ATIVO'
                WHEN 'L' THEN 'L - LIQUIDADO'
                WHEN 'C' THEN 'C - CANCELADO'
                WHEN 'P' THEN 'P - PARCIAL'
                ELSE NVL(I.STATUSITEM, 'INDEFINIDO')
            END AS STATUS_ITEM,
            C.DTAEMISSAO AS DTAEMISSAO_ORDEM,
            COMP.SEQCOMPRADOR AS SEQCOMPRADOR_FILTRO
        FROM ITENS_PEDIDOS I
        INNER JOIN CAPA_PEDIDOS C
            ON C.NROPEDIDOSUPRIM = I.NROPEDIDOSUPRIM
           AND C.NROEMPRESA = I.NROEMPRESA
           AND C.CENTRALLOJA = I.CENTRALLOJA
        LEFT JOIN ITENS_RECEBIDOS REC
            ON REC.NROPEDIDOSUPRIM = I.NROPEDIDOSUPRIM
           AND REC.NROEMPRESA = I.NROEMPRESA
           AND REC.SEQPRODUTO = I.SEQPRODUTO
        INNER JOIN MAP_PRODUTO PR
            ON PR.SEQPRODUTO = I.SEQPRODUTO
        INNER JOIN GE_PESSOA GP
            ON GP.SEQPESSOA = C.SEQFORNECEDOR
        LEFT JOIN MAP_FAMDIVISAO FD
            ON FD.SEQFAMILIA = PR.SEQFAMILIA
           AND FD.NRODIVISAO = 1
        LEFT JOIN MAX_COMPRADOR COMP
            ON COMP.SEQCOMPRADOR = NVL(C.SEQCOMPRADOR, FD.SEQCOMPRADOR)
    )
    SELECT
        COMPRADOR,
        FORNECEDOR,
        NUMERO_PEDIDO,
        LOJA_DESTINO,
        DATA_EMISSAO,
        DATA_PREV_ENTREGA,
        DATA_LIMITE_ENTREGA,
        CODIGO_PRODUTO,
        DESCRICAO,
        QTD_EMBALAGEM,
        QUANTIDADE_PEDIDA,
        QUANTIDADE_ATENDIDA,
        PERC_ATENDIMENTO,
        STATUS_ENTREGA,
        STATUS_ITEM
    FROM BASE_FINAL
    WHERE (
        NVL(TRIM(:LS1), 'TODOS') IN ('TODOS', '0 - TODOS', '0', '')
        OR INSTR(UPPER(TRIM(:LS1)), 'TODOS') > 0
        OR UPPER(COMPRADOR) = UPPER(TRIM(:LS1))
        OR TO_CHAR(SEQCOMPRADOR_FILTRO) = TRIM(:LS1)
        OR INSTR(TRIM(:LS1), TO_CHAR(SEQCOMPRADOR_FILTRO) || ' -') = 1
        OR INSTR(UPPER(COMPRADOR), UPPER(TRIM(:LS1))) > 0
        OR INSTR(UPPER(TRIM(:LS1)), UPPER(COMPRADOR)) > 0
    )
    AND (
        NVL(TRIM(:LS2), 'TODOS') IN ('TODOS', '0 - TODOS', '0', '')
        OR INSTR(UPPER(TRIM(:LS2)), 'TODOS') > 0
        OR STATUS_ENTREGA = TRIM(:LS2)
    )
    ORDER BY DTAEMISSAO_ORDEM DESC, NUMERO_PEDIDO DESC, CODIGO_PRODUTO ASC
)
