SELECT 
    REPLACE(C.CATEGORIA, '_', ' ') AS DEPARTAMENTO,
    NVL(COMP.COMPRADOR, 'SEM GESTOR') AS COMPRADOR,
    Y.NROEMPRESA AS CODIGO_EMPRESA,
    A.SEQPRODUTO AS CODIGO_PRODUTO,
    A.DESCCOMPLETA AS DESCRICAO_PRODUTO,
    CASE WHEN Y.STATUSCOMPRA = 'A' THEN 'Ativo' ELSE 'Inativo' END AS STATUS_COMPRA,
    FD.PADRAOEMBCOMPRA AS EMBL_COMPRA,
    FD.PADRAOEMBTRANSF AS EMBL_TRANSFERENCIA,
    (NVL(Y.ESTQLOJA, 0) + NVL(Y.ESTQDEPOSITO, 0) - NVL(Y.QTDRESERVADAVDA, 0) - NVL(Y.QTDRESERVADARECEB, 0)) AS QUANTIDADE_DISPONIVEL,
    (
        SELECT NVL(SUM(CASE WHEN NVL(X.QTDSOLICITADA, 0) > NVL(X.QTDRECCANC, 0) THEN NVL(X.QTDSOLICITADA, 0) - NVL(X.QTDRECCANC, 0) ELSE 0 END), 0)
        FROM MAXV_MSUPEDIDOSUPRIMREC X
        WHERE X.SEQPRODUTO = A.SEQPRODUTO
          AND X.TIPPEDIDOSUPRIM = 'C'
          AND X.NROEMPRESA = Y.NROEMPRESA
    ) AS QTD_PEND_PEDCOMPRA,
    (
        SELECT NVL(SUM(NVL(X.QTDSOLICITADA, 0) - NVL(X.QTDEXPCANC, 0)), 0)
        FROM MAXV_MSUPEDIDOSUPRIMEXP X
        WHERE X.SEQPRODUTO = A.SEQPRODUTO
          AND X.NROEMPDESTINO = Y.NROEMPRESA
          AND X.NROEMPRESA = 15
    ) + (
        SELECT NVL(SUM(I.QUANTIDADE), 0)
        FROM MFLV_BASEDFITEM I
        INNER JOIN MLF_NOTAFISCAL N ON I.NROEMPRESA = N.NROEMPRESA AND I.SEQNF = N.SEQNF AND I.TIPNOTAFISCAL = N.TIPNOTAFISCAL AND I.SERIEDF = N.SERIENF AND I.NUMERODF = N.NUMERONF AND I.SEQPESSOA = N.SEQPESSOA
        WHERE I.SEQPRODUTO = A.SEQPRODUTO
          AND N.TIPNOTAFISCAL = 'S'
          AND NVL(N.STATUSNF, 'A') != 'C'
          AND N.SEQPESSOA = E.SEQPESSOA
          AND N.NROEMPRESA = 15
          AND NOT EXISTS (
              SELECT 1
              FROM MLF_NOTAFISCAL R
              WHERE R.SEQAUXNOTAFISCALORIGEM = N.SEQAUXNOTAFISCAL
                AND R.TIPNOTAFISCAL = 'E'
                AND R.STATUSNF != 'C'
          )
    ) AS QTD_PEND_PEDTRANSF,
    (
        SELECT ROUND(NVL(SUM(CUST.QTDVDA), 0), 2)
        FROM MRL_CUSTODIA CUST
        WHERE CUST.SEQPRODUTO = A.SEQPRODUTO
          AND CUST.NROEMPRESA = Y.NROEMPRESA
          AND CUST.DTAENTRADASAIDA >= TRUNC(SYSDATE) - :NR1
    ) AS QTD_VENDIDA,
    NVL(Y.ESTQMINIMOLOJA, 0) AS QUANTIDADE_ESTOQUE_MINIMO,
    NVL(Y.ESTQMAXIMOLOJA, 0) AS QUANTIDADE_ESTOQUE_MAXIMO,
    TO_CHAR(TRUNC(A.DTAHORINCLUSAO), 'DD/MM/YYYY') AS DATA_CADASTRO_PRODUTO,
    NVL(:NR1, 90) AS DIAS_PESQUISA
FROM MAP_PRODUTO A
INNER JOIN MRL_PRODUTOEMPRESA Y ON A.SEQPRODUTO = Y.SEQPRODUTO
INNER JOIN GE_EMPRESA E ON Y.NROEMPRESA = E.NROEMPRESA
INNER JOIN MAP_FAMILIA B ON A.SEQFAMILIA = B.SEQFAMILIA
LEFT JOIN MAP_FAMDIVISAO FD ON A.SEQFAMILIA = FD.SEQFAMILIA AND FD.NRODIVISAO = 1
LEFT JOIN MAX_COMPRADOR COMP ON COMP.SEQCOMPRADOR = FD.SEQCOMPRADOR
INNER JOIN MAP_FAMDIVCATEG FDC ON FDC.SEQFAMILIA = A.SEQFAMILIA AND FDC.NRODIVISAO = 1 AND FDC.STATUS = 'A'
INNER JOIN MAP_CATEGORIA C ON C.SEQCATEGORIA = FDC.SEQCATEGORIA AND C.NRODIVISAO = 1 AND C.NIVELHIERARQUIA = 1 AND C.STATUSCATEGOR = 'A'
WHERE Y.STATUSCOMPRA = 'A'
  AND Y.NROEMPRESA IN (1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 14, 16, 17, 18)
  AND FD.FINALIDADEFAMILIA = 'R'
  AND (NVL(:NR2, 0) = 0 OR A.SEQPRODUTO = :NR2)
  AND REPLACE(REPLACE(UPPER(C.CATEGORIA), '_', ' '), 'Í', 'I') IN ('PERECIVEL', 'PERECIVEIS')
  AND NOT EXISTS (
    SELECT 1
      FROM MAP_FAMDIVCATEG FDC2
      JOIN MAP_CATEGORIA C2 ON C2.SEQCATEGORIA = FDC2.SEQCATEGORIA AND C2.NRODIVISAO = 1 AND C2.NIVELHIERARQUIA = 2 AND C2.STATUSCATEGOR = 'A'
    WHERE FDC2.SEQFAMILIA = A.SEQFAMILIA
      AND REPLACE(UPPER(C2.CATEGORIA), '_', ' ') IN (
        'FRUTAS E VERDURAS',
        'PADARIA BAKLIZI',
        'PADARIA INDUSTRIAL'
      )
  )
ORDER BY C.CATEGORIA, Y.NROEMPRESA, A.DESCCOMPLETA