SELECT
  M.PROMOCAO,
  TO_CHAR(M.DTAINICIO, 'DD/MM/YYYY') AS DTAINICIO,
  TO_CHAR(M.DTAFIM, 'DD/MM/YYYY') AS DTAFIM,
  M.NROEMPRESA AS LOJA,
  M.SEQPROMOCAO AS NOME,
  M.SEQPRODUTO AS COD,
  M.DESCCOMPLETA AS DESCRICAO,
  M.PRECONORMAL AS PRECO,
  TO_CHAR(M.MGMNORMAL, 'FM999G999D99') AS MGNORMAL,
  M.PRECOPROMOCIONAL AS PROMO,
  TO_CHAR(M.MGMPROMOC, 'FM999G999D99') AS MGPROMOC,
  NVL((SELECT SUM(V1.QTDVDA)
         FROM MRL_PRODVENDADIA V1
        WHERE V1.SEQPRODUTO = M.SEQPRODUTO
          AND V1.NROEMPRESA = M.NROEMPRESA
          AND V1.DTAVDA BETWEEN :DT1 AND :DT2), 0) AS QTD_ANTERIOR,
  NVL((SELECT SUM(V2.QTDVDA)
         FROM MRL_PRODVENDADIA V2
        WHERE V2.SEQPRODUTO = M.SEQPRODUTO
          AND V2.NROEMPRESA = M.NROEMPRESA
          AND V2.DTAVDA BETWEEN :DT3 AND :DT4), 0) AS QTD_ATUAL
FROM
  MRLV_BASEPRODPROMOC M
  JOIN MAD_SEGMENTO S ON M.NROSEGMENTO = S.NROSEGMENTO
WHERE
  M.CENTRALLOJA = 'C'
  AND M.NROEMPRESA IN (#LT2)
  AND M.PRINCIPAL = 'S'
  AND M.PROMOCAO = :LT1
  AND M.DTAINICIO <= :DT4
  AND M.DTAFIM >= :DT3
ORDER BY
  M.SEQPROMOCAO, M.DESCCOMPLETA, M.NROEMPRESA