SELECT
    A.NUMERONF,
    A.SERIENF,
    C.NOMEREDUZIDO AS EMPRESA,
    TO_CHAR(A.DTAEMISSAO, 'DD/MM/YYYY') AS DTAEMISSAO,
    TO_CHAR(A.DTAENTRADA, 'DD/MM/YYYY') AS DTAENTRADA,
    TO_CHAR(A.VLRTOTALNF, 'FM999G999G990D00', 'NLS_NUMERIC_CHARACTERS='',.''') AS VLRTOTALNF,
    DECODE(A.SITUACAO, 'R', 'RECEBIMENTO', 'L', 'NOTA LIBERADA', 'C', 'CONFERENCIA', 'X', 'XML', 'RECEBIDA') AS SITUACAO_DESC,
    A.SITUACAO,
    A.SEQNOTAFISCAL,
    A.SEQAUXNOTAFISCAL,
    A.SEQPESSOA,
    (SELECT P.SEQPESSOA || ' - ' || P.FANTASIA FROM GE_PESSOA P WHERE P.SEQPESSOA = A.SEQPESSOA) AS FORNECEDOR,
    A.STATUSCARGA,
    A.USUARIORF,
    A.NFECHAVEACESSO,
    A.CODGERALOPER,
    (
      SELECT LISTAGG(I.SEQPRODUTO, ' / ') WITHIN GROUP (ORDER BY I.SEQPRODUTO)
        FROM MLF_NFITEM I
       WHERE I.NROEMPRESA = A.NROEMPRESA
         AND I.NUMERONF = A.NUMERONF
         AND I.SERIENF = A.SERIENF
    ) AS ITENS_CODIGO,
    (
      SELECT LISTAGG(P.DESCCOMPLETA, ' / ') WITHIN GROUP (ORDER BY I.SEQPRODUTO)
        FROM MLF_NFITEM I
        JOIN MAP_PRODUTO P ON P.SEQPRODUTO = I.SEQPRODUTO
       WHERE I.NROEMPRESA = A.NROEMPRESA
         AND I.NUMERONF = A.NUMERONF
         AND I.SERIENF = A.SERIENF
    ) AS ITENS_DESCRICAO,
    (
      SELECT LISTAGG(TO_CHAR(I.QUANTIDADE), ' / ') WITHIN GROUP (ORDER BY I.SEQPRODUTO)
        FROM MLF_NFITEM I
       WHERE I.NROEMPRESA = A.NROEMPRESA
         AND I.NUMERONF = A.NUMERONF
         AND I.SERIENF = A.SERIENF
    ) AS ITENS_QUANTIDADE
FROM MLFV_NFENTRADA A
INNER JOIN MAX_EMPRESA C ON A.NROEMPRESA = C.NROEMPRESA
WHERE (NVL(TRIM(:LT1), '0') = '0' OR A.NROEMPRESA IN (#LT1))
  AND A.DTAEMISSAO >= TRUNC(:DT1)
  AND A.DTAEMISSAO < TRUNC(:DT2) + 1
  AND (NVL(TRIM(:LT2), '0') = '0' OR TO_CHAR(A.SEQPESSOA) = TRIM(:LT2))
  AND (NVL(TRIM(:LT3), '0') = '0' OR TO_CHAR(A.NUMERONF) = TRIM(:LT3))
  AND (NVL(TRIM(:LT4), '0') = '0' OR A.CODGERALOPER = TRIM(:LT4))
  AND (:LS1 = 'T' OR A.SITUACAO = :LS1)
ORDER BY A.DTAEMISSAO ASC, C.NOMEREDUZIDO ASC, A.NUMERONF ASC