SELECT
    A.NROEMPDESTINO AS CODIGO_EMPRESA,
    A.SEQPRODUTO AS CODIGO_PRODUTO,
    B.DESCCOMPLETA AS DESCRICAO_PRODUTO,
    A.NROPEDIDOSUPRIM AS NRO_PEDIDO,
    A.DTAEMISSAO AS DATA,
    P.NROPEDVENDA AS NRO_PED_EXPEDICAO,
    MV.NROCARGA AS CARGA,
    A.QTDEMBALAGEM AS EMBALAGEM,
    NVL(C.ESTQLOJA, 0) + NVL(C.ESTQDEPOSITO, 0) - NVL(C.QTDRESERVADAVDA, 0) - NVL(C.QTDRESERVADARECEB, 0) AS ESTOQUE_DISPONIVEL_CD,
    SUM(A.QTDSOLICITADA) - SUM(A.QTDEXPCANC) AS QUANTIDADE_A_EXPEDIR,
    NVL(SUM(CP.QTDEMBSEPARADA), 0) AS QTD_SEPARADA,
    NVL(SUM(CC.QTDCONTADA / CP.QTDEMBALAGEM), 0) AS QTD_CONFERIDA
FROM MAXV_MSUPEDIDOSUPRIMEXP A
INNER JOIN MAP_PRODUTO B
    ON A.SEQPRODUTO = B.SEQPRODUTO
LEFT JOIN MRL_PRODUTOEMPRESA C
    ON A.SEQPRODUTO = C.SEQPRODUTO AND C.NROEMPRESA = 15
LEFT JOIN MSU_PSITEMEXPEDIDO P
    ON A.NROPEDIDOSUPRIM = P.NROPEDIDOSUPRIM
    AND A.SEQPRODUTO = P.SEQPRODUTO
    AND A.NROEMPRESA = P.NROEMPRESA
LEFT JOIN MAD_PEDVENDA MV
    ON P.NROPEDVENDA = MV.NROPEDVENDA
    AND P.NROEMPRESAPEDVENDA = MV.NROEMPRESA
LEFT JOIN MLO_CARGAECLIPROD CP
    ON MV.NROCARGA = CP.NROCARGA
    AND A.SEQPRODUTO = CP.SEQPRODUTO
    AND MV.SEQPESSOA = CP.SEQPESSOA
    AND CP.NROEMPRESA = 15
LEFT JOIN MLO_CARGAECOLETOR CC
    ON CP.NROCARGA = CC.NROCARGA
    AND CP.CODDEPOSSEPAR = CC.CODDEPOSSEPAR
    AND CP.SEQLOTE = CC.SEQLOTE
    AND CP.NROQUEBRA = CC.NROQUEBRA
    AND CP.NROPEDVENDA = CC.NROPEDVENDA
    AND CP.SEQPRODUTO = CC.SEQPRODUTO
    AND CP.CODDEPOSITANTE = CC.CODDEPOSITANTE
    AND CP.QTDEMBALAGEM = CC.QTDEMBALAGEM
    AND CP.NROEMPRESA = CC.NROEMPRESA
WHERE A.DTAEMISSAO BETWEEN TRUNC(SYSDATE) - 34 AND TRUNC(SYSDATE) - 4
  AND A.NROEMPRESA = 15
GROUP BY
    A.NROEMPDESTINO,
    A.SEQPRODUTO,
    B.DESCCOMPLETA,
    A.NROPEDIDOSUPRIM,
    A.DTAEMISSAO,
    P.NROPEDVENDA,
    MV.NROCARGA,
    A.QTDEMBALAGEM,
    NVL(C.ESTQLOJA, 0) + NVL(C.ESTQDEPOSITO, 0) - NVL(C.QTDRESERVADAVDA, 0) - NVL(C.QTDRESERVADARECEB, 0)
HAVING SUM(A.QTDSOLICITADA) > SUM(A.QTDEXPCANC)
ORDER BY
    A.NROEMPDESTINO,
    A.NROPEDIDOSUPRIM
