SELECT
    A.SEQPRODUTO AS CODIGO_PRODUTO,
    A.DESCCOMPLETA AS DESCRICAO_PRODUTO,
    B.NROEMPRESA AS EMPRESA,
    B.STATUSCOMPRA AS STATUS,
    (B.ESTQLOJA + B.ESTQDEPOSITO - B.QTDRESERVADAVDA - B.QTDRESERVADARECEB - B.QTDRESERVADAFIXA) AS ESTOQUE
FROM MAP_PRODUTO A
INNER JOIN MRL_PRODUTOEMPRESA B
    ON A.SEQPRODUTO = B.SEQPRODUTO
INNER JOIN MAX_EMPRESA C
    ON B.NROEMPRESA = C.NROEMPRESA
INNER JOIN MAP_FAMDIVISAO D
    ON A.SEQFAMILIA = D.SEQFAMILIA
   AND C.NRODIVISAO = D.NRODIVISAO
INNER JOIN MAP_FAMDIVCATEG E
    ON A.SEQFAMILIA = E.SEQFAMILIA
   AND C.NRODIVISAO = E.NRODIVISAO
   AND E.STATUS = 'A'
INNER JOIN MAP_CATEGORIA F
    ON E.SEQCATEGORIA = F.SEQCATEGORIA
   AND C.NRODIVISAO = F.NRODIVISAO
WHERE B.NROEMPRESA IN (#LT1)
  AND B.STATUSCOMPRA = 'A'
  AND D.FINALIDADEFAMILIA = 'R'
  AND F.STATUSCATEGOR = 'A'
  AND F.TIPCATEGORIA = 'M'
  AND F.NIVELHIERARQUIA = 1
  AND UPPER(F.CATEGORIA) = UPPER(#LS1)
  AND A.DESCCOMPLETA NOT LIKE '%EXCLUIR%'
  AND A.DESCCOMPLETA NOT LIKE 'INA%'
  AND (B.ESTQLOJA + B.ESTQDEPOSITO - B.QTDRESERVADAVDA - B.QTDRESERVADARECEB - B.QTDRESERVADAFIXA) > :NR1
ORDER BY
    B.NROEMPRESA,
    A.DESCCOMPLETA
