-- Consulta de Monitoramento de Pessoas Jurídicas
-- SQL principal para Consulta Criação Consinco
SELECT 
    GE_PESSOA.SEQPESSOA AS CODIGO_PESSOA,
    CASE GE_PESSOA.FISICAJURIDICA
        WHEN 'F' THEN 'Pessoa Física'
        WHEN 'J' THEN 'Pessoa Jurídica'
        ELSE 'Indefinido'
    END AS TIPO_PESSOA,
    CASE GE_PESSOA.STATUS
        WHEN 'A' THEN 'Ativo'
        WHEN 'I' THEN 'Inativo'
        WHEN 'P' THEN 'Prospect'
        ELSE 'Indefinido'
    END AS STATUS_PESSOA,
    GE_PESSOA.NOMERAZAO,
    SUBSTR(FC5MASKCNPJCPF(GE_PESSOA.NROCGCCPF, GE_PESSOA.DIGCGCCPF, GE_PESSOA.FISICAJURIDICA),1,20) AS CNPJ_CPF,
    GE_PESSOA.INSCRICAORG,
    GE_PESSOA.LOGRADOURO,
    GE_PESSOA.BAIRRO,
    GE_PESSOA.EMAIL,
    GE_PESSOA.NROLOGRADOURO,
    GE_PESSOA.CIDADE
FROM GE_PESSOA
ORDER BY GE_PESSOA.NOMERAZAO;