SELECT DISTINCT
    A.SEQPRODUTO AS CODIGO_PRODUTO,
    A.DESCCOMPLETA AS DESCRICAO,
    B.CODACESSO AS EAN_DUN,
    D.CATEGORIA AS DEPARTAMENTO,
    E.CATEGORIA AS GRUPO,
    F.CATEGORIA AS SUBGRUPO,
    G.CATEGORIA AS NIVEL_4
FROM MAP_PRODUTO A
INNER JOIN MAP_PRODCODIGO B ON A.SEQPRODUTO = B.SEQPRODUTO
LEFT JOIN (
    SELECT X.SEQFAMILIA, Y.CATEGORIA 
    FROM MAP_FAMDIVCATEG X 
    INNER JOIN MAP_CATEGORIA Y ON X.SEQCATEGORIA = Y.SEQCATEGORIA 
    WHERE Y.NIVELHIERARQUIA = 1 AND X.NRODIVISAO = 1 AND Y.NRODIVISAO = 1 AND X.STATUS = 'A' AND Y.STATUSCATEGOR = 'A'
) D ON D.SEQFAMILIA = A.SEQFAMILIA
LEFT JOIN (
    SELECT X.SEQFAMILIA, Y.CATEGORIA 
    FROM MAP_FAMDIVCATEG X 
    INNER JOIN MAP_CATEGORIA Y ON X.SEQCATEGORIA = Y.SEQCATEGORIA 
    WHERE Y.NIVELHIERARQUIA = 2 AND X.NRODIVISAO = 1 AND Y.NRODIVISAO = 1 AND X.STATUS = 'A' AND Y.STATUSCATEGOR = 'A'
) E ON E.SEQFAMILIA = A.SEQFAMILIA
LEFT JOIN (
    SELECT X.SEQFAMILIA, Y.CATEGORIA 
    FROM MAP_FAMDIVCATEG X 
    INNER JOIN MAP_CATEGORIA Y ON X.SEQCATEGORIA = Y.SEQCATEGORIA 
    WHERE Y.NIVELHIERARQUIA = 3 AND X.NRODIVISAO = 1 AND Y.NRODIVISAO = 1 AND X.STATUS = 'A' AND Y.STATUSCATEGOR = 'A'
) F ON F.SEQFAMILIA = A.SEQFAMILIA
LEFT JOIN (
    SELECT X.SEQFAMILIA, Y.CATEGORIA 
    FROM MAP_FAMDIVCATEG X 
    INNER JOIN MAP_CATEGORIA Y ON X.SEQCATEGORIA = Y.SEQCATEGORIA 
    WHERE Y.NIVELHIERARQUIA = 4 AND X.NRODIVISAO = 1 AND Y.NRODIVISAO = 1 AND X.STATUS = 'A' AND Y.STATUSCATEGOR = 'A'
) G ON G.SEQFAMILIA = A.SEQFAMILIA
WHERE B.TIPCODIGO IN ('E', 'D')
    AND EXISTS (
            SELECT 1
            FROM MRL_PRODUTOEMPRESA C
            WHERE C.SEQPRODUTO = A.SEQPRODUTO
                AND C.STATUSCOMPRA = 'A'
                AND C.NROEMPRESA IN (1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 14, 15, 17, 18)
    )
  AND UPPER(D.CATEGORIA) NOT IN ('INATIVAR', 'A CLASSIFICAR', 'ALMOXARIFADO', 'SERVICOS')
    AND (
             UPPER(D.CATEGORIA) <> 'PERECIVEIS' 
             OR (UPPER(D.CATEGORIA) = 'PERECIVEIS' AND UPPER(E.CATEGORIA) LIKE '%LEITE%')
    )
    AND (:NR1 = 0 OR A.SEQPRODUTO = :NR1)
    AND (NVL(UPPER(TRIM(:LT1)), 'TODOS') = 'TODOS' OR UPPER(TRIM(D.CATEGORIA)) = UPPER(TRIM(:LT1)))
ORDER BY A.SEQPRODUTO, B.CODACESSO