SELECT
	N.NROEMPRESA AS CODIGO_EMPRESA,
	E.NOMEREDUZIDO AS EMPRESA,
	N.DTAEMISSAO AS DATA_EMISSAO,
	CASE
		WHEN N.APPORIGEM = 26 THEN N.NUMERONFSE
		ELSE N.NUMERONF
	END AS NUMERO_NF,
	NVL(DEP.DEPARTAMENTO, 'SEM DEPARTAMENTO') AS DEPARTAMENTO,
	NVL(FORN.CODIGO_FORNECEDOR, 0) AS CODIGO_FORNECEDOR,
	NVL(FORN.FORNECEDOR, 'SEM FORNECEDOR') AS FORNECEDOR,
	I.SEQPRODUTO AS CODIGO_PRODUTO,
	P.DESCCOMPLETA AS DESCRICAO_PRODUTO,
	ROUND(NVL(I.QUANTIDADE, 0), 2) AS QUANTIDADE_NF,
	ROUND(NVL(I.VLRITEM, 0), 2) AS VALOR_PRODUTO_NF
FROM MLFV_BASENFE N
INNER JOIN MFLV_BASEDFITEM I
	ON I.NROEMPRESA = N.NROEMPRESA
   AND I.SEQNF = N.SEQNF
   AND I.TIPNOTAFISCAL = N.TIPNOTAFISCAL
   AND I.SERIEDF = N.SERIENF
   AND I.NUMERODF = N.NUMERONF
   AND I.SEQPESSOA = N.SEQPESSOA
INNER JOIN MAX_EMPRESA E
	ON E.NROEMPRESA = N.NROEMPRESA
INNER JOIN MAP_PRODUTO P
	ON P.SEQPRODUTO = I.SEQPRODUTO
LEFT JOIN (
	SELECT
		X.SEQFAMILIA,
		MAX(Y.CATEGORIA) AS DEPARTAMENTO
	FROM MAP_FAMDIVCATEG X
	INNER JOIN MAP_CATEGORIA Y
		ON Y.SEQCATEGORIA = X.SEQCATEGORIA
	WHERE X.NRODIVISAO = 1
	  AND Y.NRODIVISAO = 1
	  AND Y.NIVELHIERARQUIA = 1
	  AND UPPER(Y.CATEGORIA) NOT IN ('A CLASSIFICAR', 'ALMOXARIFADO', 'INATIVAR', 'SERVICOS')
	GROUP BY X.SEQFAMILIA
) DEP
	ON DEP.SEQFAMILIA = P.SEQFAMILIA
LEFT JOIN (
	SELECT
		F.SEQFAMILIA,
		MAX(F.SEQFORNECEDOR) AS CODIGO_FORNECEDOR,
		MAX(G.NOMERAZAO) AS FORNECEDOR
	FROM MAP_FAMFORNEC F
	INNER JOIN GE_PESSOA G
		ON G.SEQPESSOA = F.SEQFORNECEDOR
	WHERE F.PRINCIPAL = 'S'
	GROUP BY F.SEQFAMILIA
) FORN
	ON FORN.SEQFAMILIA = P.SEQFAMILIA
WHERE N.CODGERALOPER = 831
  AND N.TIPNOTAFISCAL = 'S'
  AND NVL(N.MODELO, '0') <> '65'
  AND N.NROEMPRESA IN (1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 14, 15, 17, 18)
	AND N.DTAEMISSAO >= TRUNC(:DT1)
	AND N.DTAEMISSAO < TRUNC(:DT2) + 1
	AND (NVL(TRIM(:LT2), '0') = '0' OR TO_CHAR(NVL(FORN.CODIGO_FORNECEDOR, 0)) = TRIM(:LT2))
	AND (NVL(TRIM(:LT3), 'TODOS') = 'TODOS' OR UPPER(NVL(DEP.DEPARTAMENTO, 'SEM DEPARTAMENTO')) = UPPER(TRIM(:LT3)))
ORDER BY
	N.DTAEMISSAO,
	NUMERO_NF,
	I.SEQPRODUTO
