SELECT
  M.PROMOCAO,
  TO_CHAR(M.DTAINICIO, 'DD/MM/YYYY') AS DTAINICIO,
  TO_CHAR(M.DTAFIM, 'DD/MM/YYYY') AS DTAFIM,
  M.NROEMPRESA AS LOJA,
  M.SEQPROMOCAO AS NOME,
  M.SEQPRODUTO AS COD,
  M.DESCCOMPLETA AS DESCRICAO,
  M.PRECONORMAL AS PRECO,
  TO_CHAR(M.MGMNORMAL, 'FM999G999D99') AS MGNORMAL,
  M.PRECOPROMOCIONAL AS PROMO,
  TO_CHAR(M.MGMPROMOC, 'FM999G999D99') AS MGPROMOC,
  NVL(Q1.QTD_ANTERIOR, 0) AS QTD_ANTERIOR,
  NVL(Q2.QTD_ATUAL, 0) AS QTD_ATUAL,
  ROUND(NVL(M.PRECOPROMOCIONAL, 0) * NVL(Q2.QTD_ATUAL, 0), 2) AS VALOR_TOTAL_VENDIDO
FROM
  MRLV_BASEPRODPROMOC M
  JOIN MAD_SEGMENTO S ON M.NROSEGMENTO = S.NROSEGMENTO
  LEFT JOIN (
    SELECT
      V.SEQPRODUTO,
      V.NROEMPRESA,
      SUM(V.QTDVDA) AS QTD_ANTERIOR
    FROM
      MRL_PRODVENDADIA V
    WHERE
      V.DTAVDA BETWEEN :DT1 AND :DT2
    GROUP BY
      V.SEQPRODUTO,
      V.NROEMPRESA
  ) Q1 ON Q1.SEQPRODUTO = M.SEQPRODUTO AND Q1.NROEMPRESA = M.NROEMPRESA
  LEFT JOIN (
    SELECT
      V.SEQPRODUTO,
      V.NROEMPRESA,
      SUM(V.QTDVDA) AS QTD_ATUAL
    FROM
      MRL_PRODVENDADIA V
    WHERE
      V.DTAVDA BETWEEN :DT3 AND :DT4
    GROUP BY
      V.SEQPRODUTO,
      V.NROEMPRESA
  ) Q2 ON Q2.SEQPRODUTO = M.SEQPRODUTO AND Q2.NROEMPRESA = M.NROEMPRESA
WHERE
  M.CENTRALLOJA = 'C'
  AND M.NROEMPRESA IN (#LT1)
  AND M.PRINCIPAL = 'S'
  AND M.PROMOCAO = :LS1
  AND M.DTAINICIO <= :DT4
  AND M.DTAFIM >= :DT3
ORDER BY
  M.SEQPROMOCAO, M.DESCCOMPLETA, M.NROEMPRESA