SELECT * FROM (
    WITH FAMILIAS_ATIVAS AS (
        SELECT /*+ MATERIALIZE */ DISTINCT 
            MP.SEQFAMILIA
        FROM MAP_PRODUTO MP
        INNER JOIN MRL_PRODUTOEMPRESA PE ON PE.SEQPRODUTO = MP.SEQPRODUTO
        WHERE PE.STATUSCOMPRA = 'A'
    ),
    COMPRADORES_FORNEC AS (
        SELECT /*+ MATERIALIZE */ DISTINCT 
            FF.SEQFORNECEDOR,
            MFD.NRODIVISAO,
            NVL(C.APELIDO, C.COMPRADOR) AS APELIDO
        FROM FAMILIAS_ATIVAS FA
        INNER JOIN MAP_FAMFORNEC FF ON FF.SEQFAMILIA = FA.SEQFAMILIA
        INNER JOIN MAP_FAMDIVISAO MFD ON MFD.SEQFAMILIA = FA.SEQFAMILIA
        INNER JOIN MAX_COMPRADOR C ON C.SEQCOMPRADOR = MFD.SEQCOMPRADOR
    ),
    COMP_ATIVOS AS (
        SELECT /*+ MATERIALIZE */
            CF.SEQFORNECEDOR,
            CF.NRODIVISAO,
            LISTAGG(CF.APELIDO, ', ') WITHIN GROUP (ORDER BY CF.APELIDO) AS COMPRADORES_ITENS_ATIVOS
        FROM COMPRADORES_FORNEC CF
        GROUP BY CF.SEQFORNECEDOR, CF.NRODIVISAO
    )
    SELECT 
        F.SEQFORNECEDOR AS CODIGO_FORNECEDOR,
        P.NOMERAZAO AS RAZAO_SOCIAL,
        SUBSTR(fc5MaskCNPJCPF(P.NROCGCCPF, P.DIGCGCCPF, P.FISICAJURIDICA), 1, 20) AS CNPJ,
        R.DESCRICAO AS NOME_REDE,
        F.STATUSGERAL AS STATUS,
        P.CIDADE,
        P.UF,
        FD.NRODIVISAO AS DIVISAO,
        COMP.COMPRADOR AS COMPRADOR_CADASTRO,
        CA.COMPRADORES_ITENS_ATIVOS,
        FD.PZOPAGAMENTO AS PRAZO_PAGAMENTO_DIAS,
        FD.PZOMEDENTREGA AS PRAZO_MEDIO_ENTREGA_DIAS,
        FD.PERCDESCFINACORDO AS PERC_ACORDO_DESC_FINANC,
        FD.PERCDESCDEVFORNEC AS PERC_DESC_DEV_FORNECEDOR,
        FPD.FORMAPAGTO AS FORMA_PAGTO_DEVOLUCAO,
        FC.NOMERAZAO AS NOME_CONTATO,
        FC.CARGO AS CARGO_CONTATO,
        FC.FONE AS TELEFONE_CONTATO,
        FC.CELULAR AS CELULAR_CONTATO,
        FC.EMAIL AS EMAIL_PRINCIPAL,
        FC.EMAILPEDCOMPRA AS EMAIL_PEDIDO_COMPRA,
        FC.EMAILAGEFORNEC AS EMAIL_AGENDA,
        FC.EMAILDEVFORNEC AS EMAIL_DEVOLUCAO,
        FC.EMAILACORDO AS EMAIL_ACORDO,
        FC.EMAILTITULO AS EMAIL_TITULO,
        FC.EMAILLANCPROMO AS EMAIL_EVENTO_PROMO,
        FC.EMAILREGDEVFORNEC AS EMAIL_REG_DEVOLUCAO
    FROM MAF_FORNECEDOR F
    INNER JOIN GE_PESSOA P ON P.SEQPESSOA = F.SEQFORNECEDOR
    LEFT JOIN GE_REDEPESSOA RP ON RP.SEQPESSOA = F.SEQFORNECEDOR
    LEFT JOIN GE_REDE R ON R.SEQREDE = RP.SEQREDE
    LEFT JOIN MAF_FORNECDIVISAO FD ON FD.SEQFORNECEDOR = F.SEQFORNECEDOR
    LEFT JOIN MAX_COMPRADOR COMP ON COMP.SEQCOMPRADOR = FD.SEQCOMPRADOR
    LEFT JOIN COMP_ATIVOS CA ON CA.SEQFORNECEDOR = F.SEQFORNECEDOR 
                            AND (FD.NRODIVISAO IS NULL OR CA.NRODIVISAO = FD.NRODIVISAO)
    LEFT JOIN MRL_FORMAPAGTO FPD ON FPD.NROFORMAPAGTO = FD.NROFORMAPAGTODEV
    LEFT JOIN MAF_FORNECCONTATO FC ON FC.SEQFORNECEDOR = F.SEQFORNECEDOR AND FC.INDPRINCIPAL = 'S'
    WHERE ( NVL(:NR1, 0) = 0 OR F.SEQFORNECEDOR = :NR1 )
      AND ( :LS1 = ' TODAS AS REDES' OR R.DESCRICAO = :LS1 )
)
