SELECT
    PE.NROEMPRESA AS LOJA,
    DEP.DEPARTAMENTO,
    P.SEQPRODUTO AS CODIGO_PRODUTO,
    P.DESCCOMPLETA AS DESCRICAO_PRODUTO,
    PE.STATUSCOMPRA AS STATUS_COMPRA,
    ROUND(NVL(PE.CMULTVLRNF, 0), 2) AS CUSTO_BRUTO,
    ROUND(NVL(PE.CMULTCUSLIQUIDOEMP, 0), 2) AS CUSTO_LIQUIDO,
    NVL(TC.CODIGO_TRANSICAO, TO_CHAR(P.SEQPRODUTOBASEANTIGO)) AS CODIGO_TRANSICAO
FROM MAP_PRODUTO P
INNER JOIN MRL_PRODUTOEMPRESA PE
    ON PE.SEQPRODUTO = P.SEQPRODUTO
INNER JOIN MAX_EMPRESA E
    ON E.NROEMPRESA = PE.NROEMPRESA
INNER JOIN MAP_FAMDIVISAO FD
    ON FD.SEQFAMILIA = P.SEQFAMILIA
   AND FD.NRODIVISAO = E.NRODIVISAO
INNER JOIN (
    SELECT
        X.SEQFAMILIA,
        X.NRODIVISAO,
        MAX(Y.CATEGORIA) AS DEPARTAMENTO
    FROM MAP_FAMDIVCATEG X
    INNER JOIN MAP_CATEGORIA Y
        ON Y.SEQCATEGORIA = X.SEQCATEGORIA
       AND Y.NRODIVISAO = X.NRODIVISAO
        WHERE Y.TIPCATEGORIA = 'M'
      AND Y.NIVELHIERARQUIA = 1
      AND UPPER(Y.CATEGORIA) NOT IN ('A CLASSIFICAR', 'ALMOXARIFADO', 'INATIVAR', 'SERVICOS')
    GROUP BY
        X.SEQFAMILIA,
        X.NRODIVISAO
) DEP
    ON DEP.SEQFAMILIA = P.SEQFAMILIA
   AND DEP.NRODIVISAO = E.NRODIVISAO
LEFT JOIN (
    SELECT
        C.SEQPRODUTO,
        MAX(C.CODACESSO) KEEP (
            DENSE_RANK FIRST ORDER BY
                CASE
                    WHEN NVL(C.TIPCODIGO, 'X') = 'I' AND NVL(C.QTDEMBALAGEM, 0) = 1 THEN 0
                    WHEN NVL(C.TIPCODIGO, 'X') = 'I' THEN 1
                    WHEN C.DTAINIUTILCODTRANS IS NOT NULL OR C.DTAFINALUTILCODTRANS IS NOT NULL THEN 2
                    ELSE 3
                END,
                CASE
                    WHEN NVL(C.QTDEMBALAGEM, 0) = 1 THEN 0
                    ELSE 1
                END,
                NVL(C.DTAFINALUTILCODTRANS, DATE '2999-12-31') DESC,
                NVL(C.DTAINIUTILCODTRANS, DATE '1900-01-01') DESC,
                C.CODACESSO DESC
        ) AS CODIGO_TRANSICAO
    FROM MAP_PRODCODIGO C
    WHERE C.CODACESSO IS NOT NULL
      AND (
                        NVL(C.TIPCODIGO, 'X') = 'I'
            OR C.DTAINIUTILCODTRANS IS NOT NULL
            OR C.DTAFINALUTILCODTRANS IS NOT NULL
      )
    GROUP BY
        C.SEQPRODUTO
) TC
    ON TC.SEQPRODUTO = P.SEQPRODUTO
WHERE (NVL(:NR2, 0) = 0 OR PE.NROEMPRESA = :NR2)
  AND (NVL(:NR1, 0) = 0 OR P.SEQPRODUTO = :NR1)
  AND FD.FINALIDADEFAMILIA = 'R'
  AND PE.NROEMPRESA NOT IN (9, 10, 20, 21, 22, 23,900, 901, 902)
ORDER BY
    PE.NROEMPRESA,
    DEP.DEPARTAMENTO,
    P.DESCCOMPLETA,
    P.SEQPRODUTO
