SELECT DISTINCT
    B.CODACESSO AS EAN_DUN,
    A.SEQPRODUTO AS CODIGO_PRODUTO,
    A.DESCCOMPLETA AS DESCRICAO,
    D.CATEGORIA AS DEPARTAMENTO
FROM MAP_PRODUTO A
INNER JOIN MAP_PRODCODIGO B ON A.SEQPRODUTO = B.SEQPRODUTO
LEFT JOIN (
    SELECT X.SEQFAMILIA, Y.CATEGORIA 
    FROM MAP_FAMDIVCATEG X 
    INNER JOIN MAP_CATEGORIA Y ON X.SEQCATEGORIA = Y.SEQCATEGORIA 
    WHERE Y.NIVELHIERARQUIA = 1 AND X.NRODIVISAO = 1 AND Y.NRODIVISAO = 1 AND X.STATUS = 'A' AND Y.STATUSCATEGOR = 'A'
) D ON D.SEQFAMILIA = A.SEQFAMILIA
LEFT JOIN (
    SELECT X.SEQFAMILIA, Y.CATEGORIA 
    FROM MAP_FAMDIVCATEG X 
    INNER JOIN MAP_CATEGORIA Y ON X.SEQCATEGORIA = Y.SEQCATEGORIA 
    WHERE Y.NIVELHIERARQUIA = 2 AND X.NRODIVISAO = 1 AND Y.NRODIVISAO = 1 AND X.STATUS = 'A' AND Y.STATUSCATEGOR = 'A'
) E ON E.SEQFAMILIA = A.SEQFAMILIA
WHERE B.TIPCODIGO IN ('E', 'D')
  AND UPPER(D.CATEGORIA) NOT IN ('INATIVAR', 'A CLASSIFICAR', 'ALMOXARIFADO', 'SERVICOS')
  AND (
       UPPER(D.CATEGORIA) <> 'PERECIVEIS' 
       OR (UPPER(D.CATEGORIA) = 'PERECIVEIS' AND UPPER(E.CATEGORIA) LIKE '%LEITE%')
  )
  -- Garante que o item só saia se estiver com Venda Ativa ('A') em pelo menos uma das lojas listadas
  AND EXISTS (
      SELECT 1 FROM MRL_PRODUTOEMPRESA C 
      WHERE C.SEQPRODUTO = A.SEQPRODUTO 
        AND C.STATUSVENDA = 'A'
        AND C.NROEMPRESA IN (1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 14, 15, 17, 18)
  )
ORDER BY A.DESCCOMPLETA;
