SELECT
    A.NROEMPDESTINO AS CODIGO_EMPRESA,
    A.SEQPRODUTO AS CODIGO_PRODUTO,
    B.DESCCOMPLETA AS DESCRICAO_PRODUTO,
    A.NROPEDIDOSUPRIM AS NRO_PEDIDO,
    A.DTAEMISSAO AS DATA,
    A.QTDEMBALAGEM AS EMBALAGEM,
    NVL(C.ESTQLOJA, 0) + NVL(C.ESTQDEPOSITO, 0) - NVL(C.QTDRESERVADAVDA, 0) - NVL(C.QTDRESERVADARECEB, 0) AS ESTOQUE_DISPONIVEL_CD,
    SUM(A.QTDSOLICITADA) - SUM(A.QTDEXPCANC) AS QUANTIDADE_A_EXPEDIR
FROM MAXV_MSUPEDIDOSUPRIMEXP A
INNER JOIN MAP_PRODUTO B ON A.SEQPRODUTO = B.SEQPRODUTO
LEFT JOIN MRL_PRODUTOEMPRESA C ON A.SEQPRODUTO = C.SEQPRODUTO AND C.NROEMPRESA = 15
WHERE A.DTAEMISSAO BETWEEN TRUNC(SYSDATE) - 34 AND TRUNC(SYSDATE) - 4
  AND A.NROEMPRESA = 15
GROUP BY
    A.NROEMPDESTINO,
    A.SEQPRODUTO,
    B.DESCCOMPLETA,
    A.NROPEDIDOSUPRIM,
    A.DTAEMISSAO,
    A.QTDEMBALAGEM,
    NVL(C.ESTQLOJA, 0) + NVL(C.ESTQDEPOSITO, 0) - NVL(C.QTDRESERVADAVDA, 0) - NVL(C.QTDRESERVADARECEB, 0)
HAVING SUM(A.QTDSOLICITADA) > SUM(A.QTDEXPCANC)
ORDER BY
    A.NROEMPDESTINO,
    A.NROPEDIDOSUPRIM
