SELECT * FROM (
    SELECT
        C.CATEGORIA AS DEPTO,
        NVL(COMP.APELIDO, COMP.COMPRADOR) AS COMPRADOR,
        A.SEQPRODUTO AS CODIGO,
        A.DESCCOMPLETA AS DESCRICAO,
        B.NROEMPRESA AS LOJA,
        CASE D.FORMAABASTECIMENTO 
            WHEN 'C' THEN 'CD' 
            WHEN 'F' THEN 'FORNECEDOR' 
            ELSE D.FORMAABASTECIMENTO 
        END AS ABAST,
        NVL(B.ESTQLOJA, 0) + NVL(B.ESTQDEPOSITO, 0) - NVL(B.QTDRESERVADAVDA, 0) - NVL(B.QTDRESERVADARECEB, 0) AS ESTOQUE,
        TO_CHAR(TRUNC(B.DTAULTVENDA), 'DD/MM/YYYY') AS ULT_VENDA,
        CASE
            WHEN B.DTAULTVENDA IS NOT NULL THEN
                TRUNC(SYSDATE) - TRUNC(B.DTAULTVENDA)
            WHEN (TRUNC(SYSDATE) - TRUNC(A.DTAHORINCLUSAO)) <= 60 AND NVL(B.DTAULTMOVENTRADA, B.DTAULTCOMPRA) IS NOT NULL THEN
                TRUNC(SYSDATE) - TRUNC(NVL(B.DTAULTMOVENTRADA, B.DTAULTCOMPRA))
            WHEN (TRUNC(SYSDATE) - TRUNC(A.DTAHORINCLUSAO)) <= 60 AND NVL(B.DTAULTMOVENTRADA, B.DTAULTCOMPRA) IS NULL THEN
                0
            ELSE
                TRUNC(SYSDATE) - TRUNC(NVL(NVL(B.DTAULTMOVENTRADA, B.DTAULTCOMPRA), A.DTAHORINCLUSAO))
        END AS DIAS_SEM_VDA,
        TO_CHAR(TRUNC(NVL(B.DTAULTMOVENTRADA, B.DTAULTCOMPRA)), 'DD/MM/YYYY') AS ULT_ENTRADA,
        TRUNC(SYSDATE) - TRUNC(NVL(NVL(B.DTAULTMOVENTRADA, B.DTAULTCOMPRA), A.DTAHORINCLUSAO)) AS DIAS_SEM_ENT,
        TO_CHAR(TRUNC(A.DTAHORINCLUSAO), 'DD/MM/YYYY') AS CADASTRO
    FROM MAP_PRODUTO A
    INNER JOIN MRL_PRODUTOEMPRESA B ON A.SEQPRODUTO = B.SEQPRODUTO
    INNER JOIN MAP_FAMDIVCATEG F ON A.SEQFAMILIA = F.SEQFAMILIA AND F.NRODIVISAO = 1 AND F.STATUS = 'A'
    INNER JOIN MAP_CATEGORIA C ON F.SEQCATEGORIA = C.SEQCATEGORIA AND C.NIVELHIERARQUIA = 1 AND C.TIPCATEGORIA = 'M'
    INNER JOIN MAP_FAMDIVISAO D ON A.SEQFAMILIA = D.SEQFAMILIA AND D.NRODIVISAO = 1
    LEFT JOIN MAX_COMPRADOR COMP ON D.SEQCOMPRADOR = COMP.SEQCOMPRADOR
    WHERE B.STATUSCOMPRA = 'A'
      AND (',' || :LT1 || ',' LIKE '%,' || B.NROEMPRESA || ',%')
      AND D.FINALIDADEFAMILIA = 'R'
      AND UPPER(C.CATEGORIA) NOT LIKE '%ALMOX%'
      AND UPPER(C.CATEGORIA) NOT LIKE '%SERVI%'
      AND UPPER(C.CATEGORIA) NOT LIKE '%ALIMENTO%'
      AND UPPER(C.CATEGORIA) NOT LIKE '%INATIV%'
      AND NOT EXISTS (
          SELECT 1
          FROM MAP_FAMDIVCATEG FDC2
          JOIN MAP_CATEGORIA C2 ON C2.SEQCATEGORIA = FDC2.SEQCATEGORIA AND C2.NRODIVISAO = 1 AND C2.STATUSCATEGOR = 'A'
          WHERE FDC2.SEQFAMILIA = A.SEQFAMILIA
            AND FDC2.NRODIVISAO = 1
            AND FDC2.STATUS = 'A'
            AND (
                (C2.NIVELHIERARQUIA = 2 AND REPLACE(UPPER(C2.CATEGORIA), '_', ' ') IN ('FRUTAS E VERDURAS', 'PADARIA BAKLIZI', 'PADARIA INDUSTRIAL'))
                OR EXISTS (
                    SELECT 1 
                    FROM MAP_CATEGORIA PAI
                    WHERE PAI.SEQCATEGORIA = C2.SEQCATEGORIAPAI
                      AND PAI.NRODIVISAO = 1
                      AND PAI.NIVELHIERARQUIA = 2
                      AND PAI.STATUSCATEGOR = 'A'
                      AND REPLACE(UPPER(PAI.CATEGORIA), '_', ' ') IN ('FRUTAS E VERDURAS', 'PADARIA BAKLIZI', 'PADARIA INDUSTRIAL')
                )
            )
      )
)
WHERE ESTOQUE <> 0
  AND (
    TRIM(:LT2) IS NULL 
    OR ( :LT2 LIKE '>%'  AND :LT2 NOT LIKE '>=%' AND DIAS_SEM_VDA >  TO_NUMBER(REGEXP_REPLACE(:LT2, '[^0-9-]', '')) )
    OR ( :LT2 LIKE '<%'  AND :LT2 NOT LIKE '<=%' AND DIAS_SEM_VDA <  TO_NUMBER(REGEXP_REPLACE(:LT2, '[^0-9-]', '')) )
    OR ( :LT2 LIKE '=%'  AND DIAS_SEM_VDA =  TO_NUMBER(REGEXP_REPLACE(:LT2, '[^0-9-]', '')) )
    OR ( :LT2 LIKE '>=%' AND DIAS_SEM_VDA >= TO_NUMBER(REGEXP_REPLACE(:LT2, '[^0-9-]', '')) )
    OR ( :LT2 LIKE '<=%' AND DIAS_SEM_VDA <= TO_NUMBER(REGEXP_REPLACE(:LT2, '[^0-9-]', '')) )
    OR ( :LT2 NOT LIKE '<%' AND :LT2 NOT LIKE '>%' AND :LT2 NOT LIKE '=%' AND DIAS_SEM_VDA = TO_NUMBER(REGEXP_REPLACE(:LT2, '[^0-9-]', '')) )
  )
ORDER BY DEPTO ASC, LOJA ASC, DESCRICAO ASC
