SELECT
  PE.SEQPONTOEXTRA       AS COD_PONTO_EXTRA,
  PE.DESCRICAO           AS NOME_PONTO_EXTRA,
  PEPE.NROEMPRESA        AS LOJA,
  COMP.APELIDO           AS COMPRADOR,
  PEPE.SEQPRODUTO        AS COD_PRODUTO,
  PROD.DESCCOMPLETA      AS DESCRICAO_PRODUTO,
  PEPE.ESTQMINIMO        AS MINIMO_PONTO_EXTRA,
  PEPE.ESTQMAXIMO        AS MAXIMO_PONTO_EXTRA,
  TO_CHAR(PEPE.DTAVIGENCIAINICIO, 'DD/MM/YYYY') AS INICIO_VIGENCIA,
  TO_CHAR(PEPE.DTAVIGENCIAFIM, 'DD/MM/YYYY')    AS FIM_VIGENCIA,
  PEPE.STATUS            AS STATUS_ITEM_EMP,
  CASE 
    WHEN TRUNC(SYSDATE) BETWEEN TRUNC(PEPE.DTAVIGENCIAINICIO) AND TRUNC(PEPE.DTAVIGENCIAFIM) THEN 'VIGENTE'
    WHEN TRUNC(SYSDATE) < TRUNC(PEPE.DTAVIGENCIAINICIO) THEN 'FUTURO'
    ELSE 'ENCERRADO'
  END AS SITUACAO_VIGENCIA
FROM MRL_PONTOEXTRA PE
JOIN MRL_PONTOEXTRAPRODUTO PEP
  ON PEP.SEQPONTOEXTRA = PE.SEQPONTOEXTRA
JOIN MRL_PONTOEXTRAPRODUTOEMPRESA PEPE
  ON PEPE.SEQPONTOEXTRA = PEP.SEQPONTOEXTRA
 AND PEPE.SEQPRODUTO    = PEP.SEQPRODUTO
JOIN MAP_PRODUTO PROD
  ON PROD.SEQPRODUTO    = PEPE.SEQPRODUTO
JOIN MAX_EMPRESA EMP
  ON EMP.NROEMPRESA     = PEPE.NROEMPRESA
LEFT JOIN MAP_FAMDIVISAO FD
  ON FD.SEQFAMILIA      = PROD.SEQFAMILIA
 AND FD.NRODIVISAO      = 1
LEFT JOIN MAX_COMPRADOR COMP
  ON COMP.SEQCOMPRADOR  = FD.SEQCOMPRADOR
WHERE 1=1
  AND (NVL(:NR1, 0) = 0 OR PEPE.NROEMPRESA = :NR1)
  AND (NVL(:NR2, 0) = 0 OR PEPE.SEQPRODUTO = :NR2)
  AND (NVL(:NR3, 0) = 0 OR PE.SEQPONTOEXTRA = :NR3)
  AND (
    NVL(TRIM(:LS1), '0 - TODOS') IN ('0 - TODOS', 'TODOS', '')
    OR (
      INSTR(:LS1, ' - ') > 0
      AND FD.SEQCOMPRADOR = TO_NUMBER(SUBSTR(:LS1, 1, INSTR(:LS1, ' - ') - 1))
    )
  )
  AND (
    NVL(TRIM(:LS2), 'TODOS') IN ('TODOS', '0 - TODOS', '')
    OR CASE 
         WHEN TRUNC(SYSDATE) BETWEEN TRUNC(PEPE.DTAVIGENCIAINICIO) AND TRUNC(PEPE.DTAVIGENCIAFIM) THEN 'VIGENTE'
         WHEN TRUNC(SYSDATE) < TRUNC(PEPE.DTAVIGENCIAINICIO) THEN 'FUTURO'
         ELSE 'ENCERRADO'
       END = TRIM(:LS2)
  )
ORDER BY
  SITUACAO_VIGENCIA DESC,
  PE.SEQPONTOEXTRA DESC,
  PEPE.NROEMPRESA,
  PROD.DESCCOMPLETA;
