SELECT
    C.CATEGORIA AS DEPARTAMENTO,
    A.SEQPRODUTO AS CODIGO_PRODUTO,
    A.DESCCOMPLETA AS DESCRICAO_PRODUTO,
    Y.NROEMPRESA AS EMPRESA,
    CASE WHEN Y.STATUSCOMPRA = 'A' THEN 'ATIVO' ELSE 'INATIVO' END AS STATUS,
  FD.PADRAOEMBTRANSF AS EMBL_TRANSFERENCIA,
    (NVL(Y.ESTQLOJA, 0) + NVL(Y.ESTQDEPOSITO, 0) - NVL(Y.QTDRESERVADAVDA, 0) - NVL(Y.QTDRESERVADARECEB, 0)) AS ESTOQUE,
    NVL(Y.QTDPENDPEDCOMPRA, 0) AS PEDIDOS_PENDENTES,
    NVL(Y.ESTQMINIMOLOJA, 0) AS ESTOQUE_MINIMO,
  TO_CHAR(TRUNC(A.DTAHORINCLUSAO), 'DD/MM/YYYY') AS DATA_CADASTRO_PRODUTO,
  TRUNC(SYSDATE) - TRUNC(A.DTAHORINCLUSAO) AS DIAS_DESDE_CADASTRO
FROM MAP_PRODUTO A
INNER JOIN MRL_PRODUTOEMPRESA Y ON Y.SEQPRODUTO = A.SEQPRODUTO
INNER JOIN MAX_EMPRESA E ON E.NROEMPRESA = Y.NROEMPRESA
LEFT JOIN MAP_FAMDIVISAO FD ON FD.SEQFAMILIA = A.SEQFAMILIA AND FD.NRODIVISAO = 1
INNER JOIN MAP_FAMDIVCATEG FDC ON FDC.SEQFAMILIA = A.SEQFAMILIA AND FDC.NRODIVISAO = 1 AND FDC.STATUS = 'A'
INNER JOIN MAP_CATEGORIA C ON C.SEQCATEGORIA = FDC.SEQCATEGORIA AND C.NRODIVISAO = 1 AND C.NIVELHIERARQUIA = 1 AND C.STATUSCATEGOR = 'A'
WHERE Y.NROEMPRESA IN (1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 14, 15,16, 17, 18, 50)
  AND Y.STATUSCOMPRA = 'A'
  AND UPPER(C.CATEGORIA) NOT IN ('A CLASSIFICAR', 'ALMOXARIFADO', 'INATIVAR', 'SERVICOS', 'SEM CATEGORIA')
  AND (NVL(TRIM(:LT1), 'TODOS') = 'TODOS' OR UPPER(C.CATEGORIA) = UPPER(TRIM(:LT1)))
  AND TRUNC(A.DTAHORINCLUSAO) >= TRUNC(SYSDATE) - NVL(:NR1, 30)
  AND NVL(Y.ESTQMINIMOLOJA, 0) < NVL(:NR2, 1)
ORDER BY C.CATEGORIA, A.DESCCOMPLETA, Y.NROEMPRESA
