SELECT * FROM (
    WITH CAPA_PEDIDOS AS (
        SELECT /*+ MATERIALIZE */
            P.NROPEDIDOSUPRIM,
            P.NROEMPRESA AS LOJA_DESTINO,
            P.SEQFORNECEDOR AS CD_ORIGEM,
            P.DTAEMISSAO,
            P.SITUACAOPED,
            P.TIPPEDIDOSUPRIM
        FROM MSU_PEDIDOSUPRIM P
        WHERE P.TIPPEDIDOSUPRIM != 'C'
          AND TRUNC(P.DTAEMISSAO) BETWEEN TRUNC(:DT1) AND TRUNC(:DT2)
          AND (
              NVL(TRIM(:LT1), 'TODOS') IN ('TODOS', '0 - TODOS', '0', '')
              OR INSTR(',' || REPLACE(TRIM(:LT1), ' ', '') || ',', ',' || TO_CHAR(P.NROEMPRESA) || ',') > 0
          )
          AND (
              NVL(TRIM(:LT2), 'TODOS') IN ('TODOS', '0 - TODOS', '0', '')
              OR INSTR(',' || REPLACE(TRIM(:LT2), ' ', '') || ',', ',' || TO_CHAR(P.SEQFORNECEDOR) || ',') > 0
          )
    ),
    ITENS_SOLICITADOS AS (
        SELECT /*+ MATERIALIZE */
            R.NROPEDIDOSUPRIM,
            R.NROEMPRESA,
            R.SEQPRODUTO,
            SUM(NVL(R.QTDSOLICITADAORIGINAL, R.QTDSOLICITADA)) AS QTD_SOLICITADA,
            SUM(NVL(R.QTDTOTTRANSITO, 0)) AS QTD_TRANSITO_ATUAL,
            SUM(NVL(R.QTDTOTCANCELADA, 0)) AS QTD_CANCELADA_ATUAL,
            MAX(R.STATUSITEM) AS STATUS_ITEM_ATUAL
        FROM MSU_PSITEMRECEBER R
        INNER JOIN CAPA_PEDIDOS C ON C.NROPEDIDOSUPRIM = R.NROPEDIDOSUPRIM AND C.LOJA_DESTINO = R.NROEMPRESA
        WHERE R.SEQPRODUTO = TO_NUMBER(:NR1)
        GROUP BY R.NROPEDIDOSUPRIM, R.NROEMPRESA, R.SEQPRODUTO
    ),
    ITENS_EXPEDIDOS_CD AS (
        SELECT /*+ MATERIALIZE */
            E.NROPEDIDOSUPRIM,
            E.NROEMPDESTINO AS NROEMPRESA,
            E.SEQPRODUTO,
            SUM(NVL(E.QTDEXPEDIDA, 0)) AS QTD_EXPEDIDA_CD,
            SUM(NVL(E.QTDCANCELADA, 0)) AS QTD_CORTADA_CD,
            MAX(E.NUMERONF) AS NF_SAIDA_CD,
            MAX(NVL(E.DTAINCLUSAO, E.DTAALTERACAO)) AS DTA_EXPEDICAO_CD
        FROM MSU_PSITEMEXPEDIDO E
        INNER JOIN CAPA_PEDIDOS C ON C.NROPEDIDOSUPRIM = E.NROPEDIDOSUPRIM AND C.LOJA_DESTINO = E.NROEMPDESTINO
        WHERE E.SEQPRODUTO = TO_NUMBER(:NR1)
        GROUP BY E.NROPEDIDOSUPRIM, E.NROEMPDESTINO, E.SEQPRODUTO
    ),
    ITENS_RECEBIDOS_LOJA AS (
        SELECT /*+ MATERIALIZE */
            L.NROPEDIDOSUPRIM,
            L.NROEMPRESA,
            L.SEQPRODUTO,
            SUM(NVL(L.QTDRECEBIDA, 0)) AS QTD_RECEBIDA_LOJA,
            MAX(L.NUMERONF) AS NF_ENTRADA_LOJA,
            MAX(NVL(L.DTAMOVIMENTO, L.DTAINCLUSAO)) AS DTA_RECEBIMENTO_LOJA
        FROM MSU_PSITEMRECEBIDO L
        INNER JOIN CAPA_PEDIDOS C ON C.NROPEDIDOSUPRIM = L.NROPEDIDOSUPRIM AND C.LOJA_DESTINO = L.NROEMPRESA
        WHERE L.SEQPRODUTO = TO_NUMBER(:NR1)
        GROUP BY L.NROPEDIDOSUPRIM, L.NROEMPRESA, L.SEQPRODUTO
    ),
    DADOS_PRODUTO AS (
        SELECT /*+ MATERIALIZE */
            MP.SEQPRODUTO,
            MP.DESCCOMPLETA
        FROM MAP_PRODUTO MP
        WHERE MP.SEQPRODUTO = TO_NUMBER(:NR1)
    ),
    BASE_RELATORIO AS (
        SELECT /*+ MATERIALIZE */
            C.NROPEDIDOSUPRIM AS NUMERO_PEDIDO,
            C.CD_ORIGEM,
            C.LOJA_DESTINO,
            C.DTAEMISSAO AS DATA_EMISSAO_ORDEM,
            TO_CHAR(C.DTAEMISSAO, 'DD/MM/YYYY') AS DATA_EMISSAO,
            S.SEQPRODUTO AS CODIGO_PRODUTO,
            PR.DESCCOMPLETA AS DESCRICAO_PRODUTO,
            S.QTD_SOLICITADA,
            NVL(X.QTD_CORTADA_CD, S.QTD_CANCELADA_ATUAL) AS QTD_CORTADA_CD,
            NVL(X.QTD_EXPEDIDA_CD, 0) AS QTD_EXPEDIDA_CD,
            S.QTD_TRANSITO_ATUAL AS QTD_EM_TRANSITO,
            NVL(REC.QTD_RECEBIDA_LOJA, 0) AS QTD_RECEBIDA_LOJA,
            NVL(X.NF_SAIDA_CD, REC.NF_ENTRADA_LOJA) AS NUMERO_NOTA_FISCAL,
            TO_CHAR(NVL(X.DTA_EXPEDICAO_CD, REC.DTA_RECEBIMENTO_LOJA), 'DD/MM/YYYY') AS DATA_EXPEDICAO,
            CASE
                WHEN NVL(REC.QTD_RECEBIDA_LOJA, 0) >= S.QTD_SOLICITADA AND S.QTD_SOLICITADA > 0 THEN 'ATENDIDO TOTAL'
                WHEN NVL(REC.QTD_RECEBIDA_LOJA, 0) > 0 AND NVL(REC.QTD_RECEBIDA_LOJA, 0) < S.QTD_SOLICITADA THEN 'ATENDIDO PARCIAL'
                WHEN NVL(X.QTD_EXPEDIDA_CD, 0) > 0 AND NVL(REC.QTD_RECEBIDA_LOJA, 0) = 0 THEN 'EM TRANSITO'
                WHEN S.QTD_TRANSITO_ATUAL > 0 THEN 'EM TRANSITO'
                WHEN C.SITUACAOPED = 'C' OR S.STATUS_ITEM_ATUAL = 'C' THEN 'CANCELADO'
                WHEN C.SITUACAOPED IN ('D', 'A', 'L', 'P', 'S', 'W', 'R') AND NVL(X.QTD_EXPEDIDA_CD, 0) = 0 THEN 'EM SEPARACAO CD'
                WHEN C.SITUACAOPED = 'F' AND NVL(X.QTD_EXPEDIDA_CD, 0) = 0 THEN 'CORTADO NF'
                ELSE 'NAO ATENDIDO'
            END AS STATUS_ATENDIMENTO
        FROM ITENS_SOLICITADOS S
        INNER JOIN CAPA_PEDIDOS C ON C.NROPEDIDOSUPRIM = S.NROPEDIDOSUPRIM AND C.LOJA_DESTINO = S.NROEMPRESA
        INNER JOIN DADOS_PRODUTO PR ON PR.SEQPRODUTO = S.SEQPRODUTO
        LEFT JOIN ITENS_EXPEDIDOS_CD X ON X.NROPEDIDOSUPRIM = S.NROPEDIDOSUPRIM AND X.NROEMPRESA = S.NROEMPRESA AND X.SEQPRODUTO = S.SEQPRODUTO
        LEFT JOIN ITENS_RECEBIDOS_LOJA REC ON REC.NROPEDIDOSUPRIM = S.NROPEDIDOSUPRIM AND REC.NROEMPRESA = S.NROEMPRESA AND REC.SEQPRODUTO = S.SEQPRODUTO
    )
    SELECT
        NUMERO_PEDIDO,
        CD_ORIGEM,
        LOJA_DESTINO,
        DATA_EMISSAO,
        CODIGO_PRODUTO,
        DESCRICAO_PRODUTO,
        QTD_SOLICITADA,
        QTD_CORTADA_CD,
        QTD_EXPEDIDA_CD,
        QTD_EM_TRANSITO,
        QTD_RECEBIDA_LOJA,
        NUMERO_NOTA_FISCAL,
        DATA_EXPEDICAO,
        STATUS_ATENDIMENTO
    FROM BASE_RELATORIO
    WHERE (
        NVL(TRIM(:LS1), 'TODOS') IN ('TODOS', '0 - TODOS', '0', '')
        OR INSTR(TRIM(:LS1), 'TODOS') > 0
        OR STATUS_ATENDIMENTO = TRIM(:LS1)
        OR INSTR(STATUS_ATENDIMENTO, TRIM(:LS1)) > 0
        OR INSTR(TRIM(:LS1), STATUS_ATENDIMENTO) > 0
    )
    ORDER BY DATA_EMISSAO_ORDEM DESC, NUMERO_PEDIDO DESC
)
