SELECT
    A.NUMERONF,
    A.SERIENF,
    C.NOMEREDUZIDO AS EMPRESA,
    TO_CHAR(A.DTAEMISSAO, 'DD/MM/YYYY') AS DTAEMISSAO,
    TO_CHAR(A.DTAENTRADA, 'DD/MM/YYYY') AS DTAENTRADA,
    TO_CHAR(A.VLRTOTALNF, 'FM999G999G990D00', 'NLS_NUMERIC_CHARACTERS='',.''') AS VLRTOTALNF,
    (
      SELECT TO_CHAR(NVL(SUM(NVL(I.VLRTOTALITEM, 0)), 0), 'FM999G999G990D00', 'NLS_NUMERIC_CHARACTERS='',.''')
        FROM MLF_NFITEM I
       WHERE I.NROEMPRESA = A.NROEMPRESA
         AND I.NUMERONF = A.NUMERONF
         AND I.SERIENF = A.SERIENF
         AND (A.CODGERALOPER IN (100, 101, 103) OR I.CFOP IN (1910, 2910, 5910, 6910) OR I.CFOPORIGEM IN (1910, 2910, 5910, 6910))
    ) AS VLR_BONIFICADO,
    DECODE(A.SITUACAO, 'R', 'RECEBIMENTO', 'L', 'NOTA LIBERADA', 'C', 'CONFERENCIA', 'X', 'XML', 'RECEBIDA') AS SITUACAO_DESC,
    A.SITUACAO,
    A.SEQNOTAFISCAL,
    A.SEQAUXNOTAFISCAL,
    A.SEQPESSOA,
    (SELECT P.SEQPESSOA || ' - ' || P.FANTASIA FROM GE_PESSOA P WHERE P.SEQPESSOA = A.SEQPESSOA) AS FORNECEDOR,
    A.STATUSCARGA,
    A.USUARIORF,
    A.NFECHAVEACESSO,
    A.CODGERALOPER,
    (
      SELECT LISTAGG(C, ' / ') WITHIN GROUP (ORDER BY C)
        FROM (
            SELECT DISTINCT I.CFOPORIGEM AS C
            FROM MLF_NFITEM I
            WHERE I.NROEMPRESA = A.NROEMPRESA
              AND I.NUMERONF = A.NUMERONF
              AND I.SERIENF = A.SERIENF
        )
    ) AS CFOP_FORNECEDOR,
    (
      SELECT LISTAGG(C, ' / ') WITHIN GROUP (ORDER BY C)
        FROM (
            SELECT DISTINCT I.CFOP AS C
            FROM MLF_NFITEM I
            WHERE I.NROEMPRESA = A.NROEMPRESA
              AND I.NUMERONF = A.NUMERONF
              AND I.SERIENF = A.SERIENF
        )
    ) AS CFOP_INTERNO,
    (
      SELECT LISTAGG(I.SEQPRODUTO, ' / ') WITHIN GROUP (ORDER BY I.SEQPRODUTO)
        FROM MLF_NFITEM I
       WHERE I.NROEMPRESA = A.NROEMPRESA
         AND I.NUMERONF = A.NUMERONF
         AND I.SERIENF = A.SERIENF
    ) AS ITENS_CODIGO,
    (
      SELECT LISTAGG(P.DESCCOMPLETA, ' / ') WITHIN GROUP (ORDER BY I.SEQPRODUTO)
        FROM MLF_NFITEM I
        JOIN MAP_PRODUTO P ON P.SEQPRODUTO = I.SEQPRODUTO
       WHERE I.NROEMPRESA = A.NROEMPRESA
         AND I.NUMERONF = A.NUMERONF
         AND I.SERIENF = A.SERIENF
    ) AS ITENS_DESCRICAO,
    (
      SELECT LISTAGG(TO_CHAR(I.QUANTIDADE), ' / ') WITHIN GROUP (ORDER BY I.SEQPRODUTO)
        FROM MLF_NFITEM I
       WHERE I.NROEMPRESA = A.NROEMPRESA
         AND I.NUMERONF = A.NUMERONF
         AND I.SERIENF = A.SERIENF
    ) AS ITENS_QUANTIDADE
FROM MLFV_NFENTRADA A
INNER JOIN MAX_EMPRESA C ON A.NROEMPRESA = C.NROEMPRESA
WHERE (NVL(TRIM(:LT1), '0') = '0' OR A.NROEMPRESA IN (#LT1))
  AND A.DTAENTRADA >= TRUNC(:DT1)
  AND A.DTAENTRADA < TRUNC(:DT2) + 1
  AND (NVL(TRIM(:LT2), '0') = '0' OR TO_CHAR(A.SEQPESSOA) = TRIM(:LT2))
  AND (NVL(:NR1, 0) = 0 OR A.NUMERONF = :NR1)
  AND ('#LT3' = '0' OR EXISTS (
        SELECT 1 
        FROM MLF_NFITEM I_CFOP 
        WHERE I_CFOP.NROEMPRESA = A.NROEMPRESA 
          AND I_CFOP.NUMERONF = A.NUMERONF 
          AND I_CFOP.SERIENF = A.SERIENF 
          AND (I_CFOP.CFOP IN (#LT3) OR I_CFOP.CFOPORIGEM IN (#LT3))
      ))
  AND ('#LT4' = '0' OR A.CODGERALOPER IN (#LT4))
  AND (
        (NVL(SUBSTR(:LS2, 1, 1), 'N') <> 'E' AND (SUBSTR(:LS1, 1, 1) = 'T' OR A.SITUACAO = SUBSTR(:LS1, 1, 1)))
        OR
        (NVL(SUBSTR(:LS2, 1, 1), 'N') = 'E' AND A.SITUACAO <> NVL(NULLIF(SUBSTR(:LS1, 1, 1), 'T'), 'I'))
      )
ORDER BY A.DTAENTRADA ASC, C.NOMEREDUZIDO ASC, A.NUMERONF ASC