SELECT * FROM (
    WITH CTE_TITULOS_ACORDO AS (
        SELECT DISTINCT /*+ MATERIALIZE */
            NROACORDO, NROEMPRESA, SEQTITULO, ABERTOQUITADO, VLRPAGO, DTAVENCIMENTO
        FROM (
            SELECT TR.NROACORDO, TR.NROEMPRACORDOPROMOC AS NROEMPRESA, T.SEQTITULO, T.ABERTOQUITADO, NVL(T.VLRPAGO, 0) AS VLRPAGO, T.DTAVENCIMENTO
            FROM FI_TITULO T
            INNER JOIN MSU_ACORDOTITULORECEB TR ON TR.LINKERP = T.SEQTITULO
            WHERE T.SITUACAO != 'C'
            UNION
            SELECT TR.NROACORDO, TR.NROEMPRACORDOPROMOC AS NROEMPRESA, T.SEQTITULO, T.ABERTOQUITADO, NVL(T.VLRPAGO, 0) AS VLRPAGO, T.DTAVENCIMENTO
            FROM FI_TITULO T
            INNER JOIN MSU_ACORDOTITULORECEB TR ON TR.NUMERONF = T.NRODOCUMENTO AND TR.SEQPESSOA = T.SEQPESSOA AND TR.SERIENF = T.SERIEDOC
            WHERE T.SITUACAO != 'C'
            UNION
            SELECT CC.NROACORDO, CC.NROEMPRESAACORDO AS NROEMPRESA, T.SEQTITULO, T.ABERTOQUITADO, NVL(T.VLRPAGO, 0) AS VLRPAGO, T.DTAVENCIMENTO
            FROM FI_TITULO T
            INNER JOIN MSU_CCACORDOPROMOC CC ON CC.SEQTITULO = T.SEQTITULO
            WHERE CC.SEQTITULO IS NOT NULL AND T.SITUACAO != 'C'
            UNION
            SELECT CD.NROACORDO, CD.NROEMPRESA AS NROEMPRESA, T.SEQTITULO, T.ABERTOQUITADO, NVL(T.VLRPAGO, 0) AS VLRPAGO, T.DTAVENCIMENTO
            FROM FI_TITULO T
            INNER JOIN MSU_CCDIVIDA CD ON CD.SEQTITULO = T.SEQTITULO
            WHERE CD.SEQTITULO IS NOT NULL AND T.SITUACAO != 'C'
            UNION
            SELECT A.NROACORDO, A.NROEMPRACORDOPROMOC AS NROEMPRESA, T.SEQTITULO, T.ABERTOQUITADO, NVL(T.VLRPAGO, 0) AS VLRPAGO, T.DTAVENCIMENTO
            FROM FI_TITULO T
            INNER JOIN MSU_ACORDOPROMOC A ON A.SEQFORNECEDOR = T.SEQPESSOA AND (T.NRODOCUMENTO = A.NROACORDO OR T.NROTITULO = A.NROACORDO) AND T.NROEMPRESA = A.NROEMPRACORDOPROMOC
            WHERE T.SITUACAO != 'C' AND T.CODESPECIE IN ('VERBA', 'ACORDO', 'ACRCIM', 'ACRCOM', 'ACRINT', 'ACRLOG', 'ACRMKT', 'ACRPRE', 'ACRTRO', 'DEVREC', 'BONIF', 'VEXTRA')
        )
    ),
    CTE_VALORES_PRE AS (
        SELECT DISTINCT /*+ MATERIALIZE */
            A.NROEMPRESA,
            A.NROACORDO,
            AC.SEQPROCESSO,
            B.SEQPESSOA AS SEQFORNECEDOR,
            B.NOMERAZAO,
            A.DESCACORDO,
            A.DTAEMISSAO,
            C.APELIDO,
            A.STATUS,
            A.TIPOACORDO,
            A.SEQPRODUTO,
            A.QTDUTILIZADAVERBA,
            A.DTAFINALVERBA,
            NVL(
                (SELECT MIN(DTAVENCIMENTO) FROM CTE_TITULOS_ACORDO TA WHERE TA.NROACORDO = A.NROACORDO AND TA.NROEMPRESA = A.NROEMPRESA AND TA.ABERTOQUITADO = 'A'),
                NVL(
                    (SELECT MIN(DTAVENCIMENTO) FROM MSU_ACORDOPROMOCPARCELA P WHERE P.NROACORDO = A.NROACORDO AND P.NROEMPRESA = A.NROEMPRESA),
                    (SELECT MAX(DTAVENCIMENTO) FROM CTE_TITULOS_ACORDO TA WHERE TA.NROACORDO = A.NROACORDO AND TA.NROEMPRESA = A.NROEMPRESA)
                )
            ) AS DTAVENCIMENTO,
            SUBSTR(A.NUMERONF, 1, 250) AS NUMERONF,
            A.NROPEDIDOSUPRIM,
            NVL(A.VLRFINVENCIDO, fValorTitAcordo(A.NROACORDO, A.NROEMPRESA, A.SEQFORNECEDOR, 'V')) AS CALC_VLRFINVENCIDO,
            NVL(A.VLRFINAVENCER, fValorTitAcordo(A.NROACORDO, A.NROEMPRESA, A.SEQFORNECEDOR, 'A')) AS CALC_VLRFINAVENCER,
            A.VLRACORDO,
            A.VLRSALDOACORDO,
            A.VLRUTILPROD,
            GREATEST(
                NVL((SELECT COUNT(*) FROM MSU_ACORDOPROMOCPARCELA P WHERE P.NROACORDO = A.NROACORDO AND P.NROEMPRESA = A.NROEMPRESA), 0),
                NVL((SELECT COUNT(*) FROM CTE_TITULOS_ACORDO TA WHERE TA.NROACORDO = A.NROACORDO AND TA.NROEMPRESA = A.NROEMPRESA), 0)
            ) AS TOTAL_PARCELAS,
            NVL((SELECT COUNT(*) FROM CTE_TITULOS_ACORDO TA WHERE TA.NROACORDO = A.NROACORDO AND TA.NROEMPRESA = A.NROEMPRESA AND (TA.ABERTOQUITADO = 'Q' OR TA.VLRPAGO > 0)), 0) AS PARCELAS_PAGAS,
            NVL((SELECT COUNT(*) FROM CTE_TITULOS_ACORDO TA WHERE TA.NROACORDO = A.NROACORDO AND TA.NROEMPRESA = A.NROEMPRESA AND TA.ABERTOQUITADO = 'A' AND NVL(TA.VLRPAGO, 0) = 0), 0) AS PARCELAS_PENDENTES
        FROM MSUV_ACORDOPROMOC A
        INNER JOIN GE_PESSOA B ON B.SEQPESSOA = A.SEQFORNECEDOR
        INNER JOIN MAX_COMPRADOR C ON C.SEQCOMPRADOR = A.SEQCOMPRADOR
        LEFT JOIN MSU_ACORDOPROMOC AC ON AC.NROACORDO = A.NROACORDO AND AC.NROEMPRESA = A.NROEMPRESA
        WHERE A.NROEMPRESA IN (#LT1)
          AND TRUNC(A.DTAEMISSAO) BETWEEN :DT1 AND :DT2
          AND (NVL(:NR1, 0) = 0 OR A.NROACORDO = :NR1)
          AND (
              NVL(TRIM(:LS1), '0 - TODOS') IN ('0 - TODOS', 'TODOS', '', '0')
              OR (INSTR(:LS1, ' - ') > 0 AND C.SEQCOMPRADOR = TO_NUMBER(SUBSTR(:LS1, 1, INSTR(:LS1, ' - ') - 1)))
          )
          AND (
              NVL(TRIM(:LS2), '0 - TODOS') IN ('0 - TODOS', 'TODOS', '', '0')
              OR (INSTR(:LS2, ' - ') > 0 AND B.SEQPESSOA = TO_NUMBER(SUBSTR(:LS2, 1, INSTR(:LS2, ' - ') - 1)))
          )
          AND (
              NVL(TRIM(:LS3), '0 - TODOS') IN ('0 - TODOS', 'TODOS', '', '0')
              OR (INSTR(:LS3, ' - ') > 0 AND A.STATUS = TO_NUMBER(SUBSTR(:LS3, 1, INSTR(:LS3, ' - ') - 1)))
          )
    ),
    CTE_BASE AS (
        SELECT DISTINCT /*+ MATERIALIZE */
            NROEMPRESA,
            NROACORDO,
            SEQPROCESSO,
            SEQFORNECEDOR,
            NOMERAZAO,
            DESCACORDO,
            DTAEMISSAO,
            APELIDO,
            STATUS,
            TIPOACORDO,
            SEQPRODUTO,
            QTDUTILIZADAVERBA,
            DTAFINALVERBA,
            DTAVENCIMENTO,
            NUMERONF,
            NROPEDIDOSUPRIM,
            CALC_VLRFINVENCIDO AS VLRFINVENCIDO,
            CALC_VLRFINAVENCER AS VLRFINAVENCER,
            VLRACORDO,
            VLRSALDOACORDO,
            VLRUTILPROD,
            TOTAL_PARCELAS,
            PARCELAS_PAGAS,
            PARCELAS_PENDENTES,
            GREATEST(0, VLRACORDO - (CASE 
                WHEN TIPOACORDO = 1 OR NVL(CALC_VLRFINVENCIDO, 0) + NVL(CALC_VLRFINAVENCER, 0) > 0 THEN 
                    NVL(CALC_VLRFINVENCIDO, 0) + NVL(CALC_VLRFINAVENCER, 0)
                ELSE 
                    NVL(VLRSALDOACORDO, 0)
            END)) AS VLR_JA_QUITADO,
            CASE 
                WHEN TIPOACORDO = 1 OR NVL(CALC_VLRFINVENCIDO, 0) + NVL(CALC_VLRFINAVENCER, 0) > 0 THEN 
                    NVL(CALC_VLRFINVENCIDO, 0) + NVL(CALC_VLRFINAVENCER, 0)
                ELSE 
                    NVL(VLRSALDOACORDO, 0)
            END AS VLR_EM_ABERTO
        FROM CTE_VALORES_PRE
    ),
    CTE_TOTAL_ACORDO AS (
        SELECT /*+ MATERIALIZE */
            NVL(SUM(VLRACORDO), 0) AS TOTAL_GERAL_VLR_ACORDO
        FROM (
            SELECT DISTINCT NROACORDO, NROEMPRESA, VLRACORDO
            FROM CTE_BASE
        )
    ),
    CTE_TOTAL_SALDO AS (
        SELECT /*+ MATERIALIZE */
            NVL(SUM(VLRSALDOACORDO), 0) AS TOTAL_GERAL_SALDO_ACORDO
        FROM (
            SELECT MAX(VLRSALDOACORDO) AS VLRSALDOACORDO
            FROM CTE_BASE
            GROUP BY NROEMPRESA, NROACORDO, SEQPRODUTO
        )
    ),
    CTE_TOTAIS AS (
        SELECT /*+ MATERIALIZE */
            (SELECT TOTAL_GERAL_VLR_ACORDO FROM CTE_TOTAL_ACORDO) AS TOTAL_VLRACORDO,
            (SELECT TOTAL_GERAL_SALDO_ACORDO FROM CTE_TOTAL_SALDO) AS TOTAL_VLRSALDO,
            (SELECT NVL(SUM(VLRFINVENCIDO), 0) FROM (SELECT DISTINCT NROACORDO, NROEMPRESA, VLRFINVENCIDO FROM CTE_BASE)) AS TOTAL_VLRFINVENCIDO,
            (SELECT NVL(SUM(VLRFINAVENCER), 0) FROM (SELECT DISTINCT NROACORDO, NROEMPRESA, VLRFINAVENCER FROM CTE_BASE)) AS TOTAL_VLRFINAVENCER,
            (SELECT NVL(SUM(VLRUTILPROD), 0) FROM CTE_BASE) AS TOTAL_VLRUTILPROD,
            (SELECT NVL(SUM(VLR_JA_QUITADO), 0) FROM (SELECT DISTINCT NROACORDO, NROEMPRESA, VLR_JA_QUITADO FROM CTE_BASE)) AS TOTAL_VLR_QUITADO,
            (SELECT NVL(SUM(VLR_EM_ABERTO), 0) FROM (SELECT DISTINCT NROACORDO, NROEMPRESA, VLR_EM_ABERTO FROM CTE_BASE)) AS TOTAL_VLR_ABERTO,
            (SELECT NVL(SUM(TOTAL_PARCELAS), 0) FROM (SELECT DISTINCT NROACORDO, NROEMPRESA, TOTAL_PARCELAS FROM CTE_BASE)) AS TOTAL_PARC_GERADAS,
            (SELECT NVL(SUM(PARCELAS_PAGAS), 0) FROM (SELECT DISTINCT NROACORDO, NROEMPRESA, PARCELAS_PAGAS FROM CTE_BASE)) AS TOTAL_PARC_PAGAS,
            (SELECT NVL(SUM(PARCELAS_PENDENTES), 0) FROM (SELECT DISTINCT NROACORDO, NROEMPRESA, PARCELAS_PENDENTES FROM CTE_BASE)) AS TOTAL_PARC_PENDENTES
        FROM DUAL
    )
    SELECT 
        CODIGO_EMPRESA,
        NUMERO_ACORDO,
        NUMERO_PROCESSO,
        CODIGO_FORNECEDOR,
        FORNECEDOR,
        DESCRICAO_ACORDO,
        DATA_EMISSAO,
        COMPRADOR,
        STATUS_ACORDO,
        TIPO_ACORDO,
        CODIGO_PRODUTO,
        QTD_UTILIZADA_VERBA,
        DATA_FINAL_VERBA,
        DATA_VENCIMENTO,
        NUMERO_NF,
        NUMERO_PEDIDO_SUPRIMENTO,
        VALOR_ACORDO,
        VLR_FIN_A_VENCER,
        VLR_EM_ABERTO,
        VLR_FIN_VENCIDO,
        VLR_JA_QUITADO,
        VALOR_SALDO_ACORDO,
        VALOR_UTILIZADO_PRODUTO,
        TOTAL_PARCELAS,
        PARCELAS_PAGAS,
        PARCELAS_PENDENTES
    FROM (
        SELECT
            1 AS ORDEM_LINHA,
            X.NROACORDO AS ORDEM_ACORDO,
            TO_CHAR(X.NROEMPRESA) AS CODIGO_EMPRESA,
            TO_CHAR(X.NROACORDO) AS NUMERO_ACORDO,
            TO_CHAR(X.SEQPROCESSO) AS NUMERO_PROCESSO,
            TO_CHAR(X.SEQFORNECEDOR) AS CODIGO_FORNECEDOR,
            X.NOMERAZAO AS FORNECEDOR,
            X.DESCACORDO AS DESCRICAO_ACORDO,
            TO_CHAR(X.DTAEMISSAO, 'DD/MM/YYYY') AS DATA_EMISSAO,
            X.APELIDO AS COMPRADOR,
            CASE
                WHEN X.STATUS = 1 THEN 'EM ANDAMENTO'
                WHEN X.STATUS = 2 THEN 'CANCELADO'
                WHEN X.STATUS = 3 THEN 'CONCLUIDO'
                WHEN X.STATUS = 4 THEN 'INTERROMPIDA'
            END AS STATUS_ACORDO,
            CASE
                WHEN X.TIPOACORDO = 1 THEN 'VERBA EXTRA'
                WHEN X.TIPOACORDO = 2 THEN 'SELL-OUT'
                WHEN X.TIPOACORDO = 3 THEN 'SELL-IN'
            END AS TIPO_ACORDO,
            TO_CHAR(X.SEQPRODUTO) AS CODIGO_PRODUTO,
            TO_CHAR(X.QTDUTILIZADAVERBA) AS QTD_UTILIZADA_VERBA,
            TO_CHAR(X.DTAFINALVERBA, 'DD/MM/YYYY') AS DATA_FINAL_VERBA,
            TO_CHAR(X.DTAVENCIMENTO, 'DD/MM/YYYY') AS DATA_VENCIMENTO,
            X.NUMERONF AS NUMERO_NF,
            TO_CHAR(X.NROPEDIDOSUPRIM) AS NUMERO_PEDIDO_SUPRIMENTO,
            'R$ ' || TO_CHAR(NVL(X.VLRACORDO, 0), 'FM999G999G990D00', 'NLS_NUMERIC_CHARACTERS='',.''') AS VALOR_ACORDO,
            'R$ ' || TO_CHAR(NVL(X.VLRFINAVENCER, 0), 'FM999G999G990D00', 'NLS_NUMERIC_CHARACTERS='',.''') AS VLR_FIN_A_VENCER,
            'R$ ' || TO_CHAR(NVL(X.VLR_EM_ABERTO, 0), 'FM999G999G990D00', 'NLS_NUMERIC_CHARACTERS='',.''') AS VLR_EM_ABERTO,
            'R$ ' || TO_CHAR(NVL(X.VLRFINVENCIDO, 0), 'FM999G999G990D00', 'NLS_NUMERIC_CHARACTERS='',.''') AS VLR_FIN_VENCIDO,
            'R$ ' || TO_CHAR(NVL(X.VLR_JA_QUITADO, 0), 'FM999G999G990D00', 'NLS_NUMERIC_CHARACTERS='',.''') AS VLR_JA_QUITADO,
            'R$ ' || TO_CHAR(NVL(X.VLRSALDOACORDO, 0), 'FM999G999G990D00', 'NLS_NUMERIC_CHARACTERS='',.''') AS VALOR_SALDO_ACORDO,
            'R$ ' || TO_CHAR(NVL(X.VLRUTILPROD, 0), 'FM999G999G990D00', 'NLS_NUMERIC_CHARACTERS='',.''') AS VALOR_UTILIZADO_PRODUTO,
            TO_CHAR(X.TOTAL_PARCELAS) AS TOTAL_PARCELAS,
            TO_CHAR(X.PARCELAS_PAGAS) AS PARCELAS_PAGAS,
            TO_CHAR(X.PARCELAS_PENDENTES) AS PARCELAS_PENDENTES
        FROM CTE_BASE X
        UNION ALL
        SELECT
            2 AS ORDEM_LINHA,
            9999999999 AS ORDEM_ACORDO,
            NULL AS CODIGO_EMPRESA,
            NULL AS NUMERO_ACORDO,
            NULL AS NUMERO_PROCESSO,
            NULL AS CODIGO_FORNECEDOR,
            'TOTAL GERAL ->' AS FORNECEDOR,
            NULL AS DESCRICAO_ACORDO,
            NULL AS DATA_EMISSAO,
            NULL AS COMPRADOR,
            NULL AS STATUS_ACORDO,
            NULL AS TIPO_ACORDO,
            NULL AS CODIGO_PRODUTO,
            NULL AS QTD_UTILIZADA_VERBA,
            NULL AS DATA_FINAL_VERBA,
            NULL AS DATA_VENCIMENTO,
            NULL AS NUMERO_NF,
            NULL AS NUMERO_PEDIDO_SUPRIMENTO,
            'R$ ' || TO_CHAR(NVL(T.TOTAL_VLRACORDO, 0), 'FM999G999G990D00', 'NLS_NUMERIC_CHARACTERS='',.''') AS VALOR_ACORDO,
            'R$ ' || TO_CHAR(NVL(T.TOTAL_VLRFINAVENCER, 0), 'FM999G999G990D00', 'NLS_NUMERIC_CHARACTERS='',.''') AS VLR_FIN_A_VENCER,
            'R$ ' || TO_CHAR(NVL(T.TOTAL_VLR_ABERTO, 0), 'FM999G999G990D00', 'NLS_NUMERIC_CHARACTERS='',.''') AS VLR_EM_ABERTO,
            'R$ ' || TO_CHAR(NVL(T.TOTAL_VLRFINVENCIDO, 0), 'FM999G999G990D00', 'NLS_NUMERIC_CHARACTERS='',.''') AS VLR_FIN_VENCIDO,
            'R$ ' || TO_CHAR(NVL(T.TOTAL_VLR_QUITADO, 0), 'FM999G999G990D00', 'NLS_NUMERIC_CHARACTERS='',.''') AS VLR_JA_QUITADO,
            'R$ ' || TO_CHAR(NVL(T.TOTAL_VLRSALDO, 0), 'FM999G999G990D00', 'NLS_NUMERIC_CHARACTERS='',.''') AS VALOR_SALDO_ACORDO,
            'R$ ' || TO_CHAR(NVL(T.TOTAL_VLRUTILPROD, 0), 'FM999G999G990D00', 'NLS_NUMERIC_CHARACTERS='',.''') AS VALOR_UTILIZADO_PRODUTO,
            TO_CHAR(T.TOTAL_PARC_GERADAS) AS TOTAL_PARCELAS,
            TO_CHAR(T.TOTAL_PARC_PAGAS) AS PARCELAS_PAGAS,
            TO_CHAR(T.TOTAL_PARC_PENDENTES) AS PARCELAS_PENDENTES
        FROM CTE_TOTAIS T
    )
    ORDER BY ORDEM_LINHA, ORDEM_ACORDO
)
