SELECT
  X.PROMOCAO,
  X.DTAINICIO,
  X.DTAFIM,
  X.COMPRADOR,
  X.NOME,
  X.COD,
  X.DESCRICAO,
  X.PRECO,
  X.MGNORMAL,
  X.PROMO,
  X.MGPROMOC,
  X.QTD_ATUAL,
  X.QTD_ANTERIOR,
  'R$    ' || TO_CHAR(ROUND(NVL(X.PROMO_NUM, 0) * NVL(X.QTD_ATUAL, 0), 2), 'FM999G990D00') AS VALOR_TOTAL_VENDIDO
FROM (
  SELECT
    M.PROMOCAO,
    TO_CHAR(M.DTAINICIO, 'DD/MM/YYYY') AS DTAINICIO,
    TO_CHAR(M.DTAFIM, 'DD/MM/YYYY') AS DTAFIM,
    NVL(COMP.APELIDO, NVL(COMP.COMPRADOR, 'SEM COMPRADOR')) AS COMPRADOR,
    M.SEQPROMOCAO AS NOME,
    M.SEQPRODUTO AS COD,
    M.DESCCOMPLETA AS DESCRICAO,
    'R$ ' || TO_CHAR(ROUND(MIN(M.PRECONORMAL), 2), 'FM999G990D00') AS PRECO,
    '   ' || TO_CHAR(MIN(M.MGMNORMAL), 'FM999G990D99') AS MGNORMAL,
    'R$ ' || TO_CHAR(ROUND(MIN(M.PRECOPROMOCIONAL), 2), 'FM999G990D00') AS PROMO,
    MIN(M.PRECOPROMOCIONAL) AS PROMO_NUM,
    '   ' || TO_CHAR(MIN(M.MGMPROMOC), 'FM999G990D99') AS MGPROMOC,
    '   ' || NVL(Q1.QTD_ATUAL, 0) AS QTD_ATUAL,
    '   ' || NVL(Q2.QTD_ANTERIOR, 0) AS QTD_ANTERIOR
  FROM MRLV_BASEPRODPROMOC M
  JOIN MAD_SEGMENTO S ON M.NROSEGMENTO = S.NROSEGMENTO
  LEFT JOIN MAP_PRODUTO P ON P.SEQPRODUTO = M.SEQPRODUTO
  LEFT JOIN MAP_FAMDIVISAO FD ON FD.SEQFAMILIA = P.SEQFAMILIA AND FD.NRODIVISAO = 1
  LEFT JOIN MAX_COMPRADOR COMP ON COMP.SEQCOMPRADOR = FD.SEQCOMPRADOR
  LEFT JOIN (
    SELECT V.SEQPRODUTO, SUM(V.QTDVDA) AS QTD_ATUAL
    FROM MRL_CUSTODIA V
    WHERE V.NROEMPRESA IN (SELECT DISTINCT NROEMPRESA FROM MRLV_BASEPRODPROMOC WHERE PROMOCAO = :LS1 AND PRINCIPAL = 'S' AND CENTRALLOJA = 'C')
      AND V.DTAENTRADASAIDA BETWEEN :DT3 AND :DT4
    GROUP BY V.SEQPRODUTO
  ) Q1 ON Q1.SEQPRODUTO = M.SEQPRODUTO
  LEFT JOIN (
    SELECT V.SEQPRODUTO, SUM(V.QTDVDA) AS QTD_ANTERIOR
    FROM MRL_CUSTODIA V
    WHERE V.NROEMPRESA IN (SELECT DISTINCT NROEMPRESA FROM MRLV_BASEPRODPROMOC WHERE PROMOCAO = :LS1 AND PRINCIPAL = 'S' AND CENTRALLOJA = 'C')
      AND V.DTAENTRADASAIDA BETWEEN :DT1 AND :DT2
    GROUP BY V.SEQPRODUTO
  ) Q2 ON Q2.SEQPRODUTO = M.SEQPRODUTO
  WHERE M.CENTRALLOJA = 'C'
    AND M.PRINCIPAL = 'S'
    AND M.PROMOCAO = :LS1
    AND M.DTAINICIO <= :DT4
    AND M.DTAFIM >= :DT3
    AND (
      NVL(TRIM(:LS2), '0 - TODOS') IN ('0 - TODOS', 'TODOS', '')
      OR (
        INSTR(:LS2, ' - ') > 0
        AND FD.SEQCOMPRADOR = TO_NUMBER(SUBSTR(:LS2, 1, INSTR(:LS2, ' - ') - 1))
      )
    )
  GROUP BY
    M.PROMOCAO,
    M.DTAINICIO,
    M.DTAFIM,
    COMP.APELIDO,
    COMP.COMPRADOR,
    M.SEQPROMOCAO,
    M.SEQPRODUTO,
    M.DESCCOMPLETA,
    Q1.QTD_ATUAL,
    Q2.QTD_ANTERIOR
) X
ORDER BY
  X.DTAINICIO DESC, X.DTAFIM DESC, X.COMPRADOR, X.NOME, X.DESCRICAO