SELECT
    NVL(DEP.DEPARTAMENTO, 'SEM DEPARTAMENTO') AS DEPARTAMENTO,
    NVL(COMP.COMPRADOR, 'SEM GESTOR') AS COMPRADOR,
    A.SEQPRODUTO AS CODIGO_PRODUTO,
    A.DESCCOMPLETA AS DESCRICAO_PRODUTO,
    FD.FORMAABASTECIMENTO AS FORMA_ABASTECIMENTO
FROM MAP_PRODUTO A
INNER JOIN MAP_FAMDIVISAO FD ON FD.SEQFAMILIA = A.SEQFAMILIA AND FD.NRODIVISAO = 1
LEFT JOIN (
    SELECT X.SEQFAMILIA, MAX(Y.CATEGORIA) AS DEPARTAMENTO
    FROM MAP_FAMDIVCATEG X
    INNER JOIN MAP_CATEGORIA Y ON Y.SEQCATEGORIA = X.SEQCATEGORIA AND Y.NRODIVISAO = X.NRODIVISAO
    WHERE X.NRODIVISAO = 1 
      AND X.STATUS = 'A'
      AND Y.NIVELHIERARQUIA = 1
      AND Y.TIPCATEGORIA = 'M'
      AND UPPER(Y.CATEGORIA) NOT IN ('A CLASSIFICAR', 'ALMOXARIFADO', 'INATIVAR', 'SERVICOS')
    GROUP BY X.SEQFAMILIA
) DEP ON DEP.SEQFAMILIA = A.SEQFAMILIA
LEFT JOIN MAX_COMPRADOR COMP ON COMP.SEQCOMPRADOR = FD.SEQCOMPRADOR
WHERE EXISTS (
    SELECT 1 
    FROM MRL_PRODUTOEMPRESA PE 
    WHERE PE.SEQPRODUTO = A.SEQPRODUTO 
      AND PE.STATUSCOMPRA = 'A' 
      AND PE.NROEMPRESA IN (1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 14, 15, 17, 18)
)
AND FD.FORMAABASTECIMENTO = SUBSTR(:LS1, 1, 1)
ORDER BY DEP.DEPARTAMENTO, COMP.COMPRADOR, A.DESCCOMPLETA
