SELECT TO_CHAR(NVL(FP.CODIGO_FORNECEDOR, 0)) AS CODIGO_FORNECEDOR,
       NVL(FP.FORNECEDOR_PRINCIPAL, 'SEM FORNECEDOR') AS FORNECEDOR,
       COUNT(DISTINCT I.SEQPRODUTO) AS QTD_SKU,
       ROUND(SUM(NVL(I.VLRITEM, 0)), 2) AS VLR_VENDA_ITEM
  FROM MLFV_BASENFE N
  JOIN MFLV_BASEDFITEM I
    ON I.NROEMPRESA = N.NROEMPRESA
   AND I.SEQNF = N.SEQNF
   AND I.TIPNOTAFISCAL = N.TIPNOTAFISCAL
   AND I.SERIEDF = N.SERIENF
   AND I.NUMERODF = N.NUMERONF
   AND I.SEQPESSOA = N.SEQPESSOA
  JOIN MAP_PRODUTO A
    ON A.SEQPRODUTO = I.SEQPRODUTO
  LEFT JOIN (
        SELECT F.SEQFAMILIA,
               MAX(F.SEQFORNECEDOR) AS CODIGO_FORNECEDOR,
               MAX(P.NOMERAZAO) AS FORNECEDOR_PRINCIPAL
          FROM MAP_FAMFORNEC F
          JOIN GE_PESSOA P
            ON P.SEQPESSOA = F.SEQFORNECEDOR
         WHERE F.PRINCIPAL = 'S'
         GROUP BY F.SEQFAMILIA
  ) FP
    ON FP.SEQFAMILIA = A.SEQFAMILIA
 WHERE N.TIPNOTAFISCAL = 'S'
   AND N.CODGERALOPER IN (800,810,834,848)
   AND NVL(N.MODELO, '0') <> '65'
   AND N.NROEMPRESA IN (1,2,3,4,5,6,7,8,11,12,13,14,17,18)
   AND N.DTAEMISSAO >= TO_DATE('01/05/2026', 'DD/MM/YYYY')
   AND N.DTAEMISSAO < TO_DATE('01/06/2026', 'DD/MM/YYYY')
 GROUP BY FP.CODIGO_FORNECEDOR,
          FP.FORNECEDOR_PRINCIPAL
HAVING SUM(NVL(I.VLRITEM, 0)) > 0
 ORDER BY VLR_VENDA_ITEM DESC,
          FORNECEDOR ASC;