SELECT 
    I.SEQPRODUTO AS CODIGO_PRODUTO,
    P.DESCCOMPLETA AS DESCRICAO_PRODUTO,
    SUM(I.QUANTIDADE) AS QTD_INCINERADA,
    FORN.CODIGO_FORNECEDOR,
    FORN.FORNECEDOR
FROM MLFV_BASENFE N
INNER JOIN MFLV_BASEDFITEM I ON I.NROEMPRESA = N.NROEMPRESA
                            AND I.SEQNF = N.SEQNF
                            AND I.TIPNOTAFISCAL = N.TIPNOTAFISCAL
                            AND I.SERIEDF = N.SERIENF
                            AND I.NUMERODF = N.NUMERONF
                            AND I.SEQPESSOA = N.SEQPESSOA
INNER JOIN MAP_PRODUTO P ON P.SEQPRODUTO = I.SEQPRODUTO
LEFT JOIN (
    SELECT F.SEQFAMILIA, MAX(F.SEQFORNECEDOR) AS CODIGO_FORNECEDOR, MAX(G.NOMERAZAO) AS FORNECEDOR
    FROM MAP_FAMFORNEC F
    INNER JOIN GE_PESSOA G ON G.SEQPESSOA = F.SEQFORNECEDOR
    WHERE F.PRINCIPAL = 'S'
    GROUP BY F.SEQFAMILIA
) FORN ON FORN.SEQFAMILIA = P.SEQFAMILIA
WHERE N.CODGERALOPER = 831
  AND N.TIPNOTAFISCAL = 'S'
  AND NVL(N.MODELO, '0') <> '65'
  AND N.NROEMPRESA IN (1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 14, 15, 17, 18)
GROUP BY I.SEQPRODUTO, P.DESCCOMPLETA, FORN.CODIGO_FORNECEDOR, FORN.FORNECEDOR
ORDER BY QTD_INCINERADA DESC
