SELECT
  X.CODIGO_PRODUTO,
  X.DESCRICAO,
  X.VALOR_CUSTO_NF,
  X.ALIQUOTA_PIS,
  X.ALIQUOTA_COFINS,
  X.PIS_COFINS_GRAVADO,
  X.PIS_COFINS_CALCULADO,
  X.PIS_COFINS_PADRAO,
  X.NUMERO_NF,
  X.SERIE_NF,
  X.DTA_ENTRADA,
  X.NRO_EMPRESA
FROM (
  SELECT
    P.SEQPRODUTO AS CODIGO_PRODUTO,
    P.DESCCOMPLETA AS DESCRICAO,
    ROUND(NVL(N.VLRITEM, 0) / NULLIF(N.QUANTIDADE * N.QTDEMBALAGEM, 0), 4) AS VALOR_CUSTO_NF,
    NVL(N.ALIQPISCALC, 0) AS ALIQUOTA_PIS,
    NVL(N.ALIQCOFINSCALC, 0) AS ALIQUOTA_COFINS,
    ROUND((NVL(N.VLRPIS, 0) + NVL(N.VLRCOFINS, 0)) / NULLIF(N.QUANTIDADE * N.QTDEMBALAGEM, 0), 4) AS PIS_COFINS_GRAVADO,
    ROUND((NVL(N.VLRITEM, 0) / NULLIF(N.QUANTIDADE * N.QTDEMBALAGEM, 0)) * ((NVL(N.ALIQPISCALC, 0) + NVL(N.ALIQCOFINSCALC, 0)) / 100), 4) AS PIS_COFINS_CALCULADO,
    ROUND((NVL(N.VLRITEM, 0) / NULLIF(N.QUANTIDADE * N.QTDEMBALAGEM, 0)) * 0.0925, 4) AS PIS_COFINS_PADRAO,
    N.NUMERONF AS NUMERO_NF,
    N.SERIENF AS SERIE_NF,
    NF.DTAENTRADA AS DTA_ENTRADA,
    N.NROEMPRESA AS NRO_EMPRESA,
    ROW_NUMBER() OVER (PARTITION BY P.SEQPRODUTO ORDER BY NF.DTAENTRADA DESC, NF.SEQNF DESC) AS RN
  FROM MAP_PRODUTO P
  INNER JOIN MLF_NFITEM N ON N.SEQPRODUTO = P.SEQPRODUTO
  INNER JOIN MLF_NOTAFISCAL NF 
     ON NF.NUMERONF = N.NUMERONF 
    AND NF.SERIENF = N.SERIENF
    AND NF.NROEMPRESA = N.NROEMPRESA 
    AND NF.TIPNOTAFISCAL = N.TIPNOTAFISCAL
    AND NVL(NF.SEQNF, 0) = NVL(N.SEQNF, NVL(NF.SEQNF, 0))
  WHERE NF.TIPNOTAFISCAL = 'E'
    AND NF.STATUSNF <> 'C'
    AND NF.CODGERALOPER = 1
    AND N.TIPITEM = 'R'
    AND (NVL(:NR1, 0) = 0 OR P.SEQPRODUTO = :NR1)
) X
WHERE X.RN = 1
ORDER BY X.DESCRICAO
