SELECT 
    C.CATEGORIA AS DEPARTAMENTO,
    NVL(COMP.COMPRADOR, 'SEM GESTOR') AS COMPRADOR,
    Y.NROEMPRESA AS CODIGO_EMPRESA,
    A.SEQPRODUTO AS CODIGO_PRODUTO,
    A.DESCCOMPLETA AS DESCRICAO_PRODUTO,
    CASE WHEN Y.STATUSCOMPRA = 'A' THEN 'Ativo' ELSE 'Inativo' END AS STATUS_COMPRA,
    FD.PADRAOEMBCOMPRA AS EMBL_COMPRA,
    FD.PADRAOEMBTRANSF AS EMBL_TRANSFERENCIA,
    (NVL(Y.ESTQLOJA, 0) + NVL(Y.ESTQDEPOSITO, 0) - NVL(Y.QTDRESERVADAVDA, 0) - NVL(Y.QTDRESERVADARECEB, 0)) AS QUANTIDADE_DISPONIVEL,
    NVL(Y.QTDPENDPEDCOMPRA, 0) AS QTD_PEND_PEDCOMPRA,
    (
        SELECT ROUND(NVL(SUM(CUST.QTDVDA), 0), 2)
        FROM MRL_CUSTODIA CUST
        WHERE CUST.SEQPRODUTO = A.SEQPRODUTO
          AND CUST.NROEMPRESA = Y.NROEMPRESA
          AND CUST.DTAENTRADASAIDA >= TRUNC(SYSDATE) - 30
    ) AS QTD_VENDIDA_30D,
    NVL(Y.ESTQMINIMOLOJA, 0) AS QUANTIDADE_ESTOQUE_MINIMO,
    NVL(Y.ESTQMAXIMOLOJA, 0) AS QUANTIDADE_ESTOQUE_MAXIMO
FROM MAP_PRODUTO A
INNER JOIN MRL_PRODUTOEMPRESA Y ON A.SEQPRODUTO = Y.SEQPRODUTO
INNER JOIN MAX_EMPRESA E ON Y.NROEMPRESA = E.NROEMPRESA
INNER JOIN MAP_FAMILIA B ON A.SEQFAMILIA = B.SEQFAMILIA
LEFT JOIN MAP_FAMDIVISAO FD ON A.SEQFAMILIA = FD.SEQFAMILIA AND FD.NRODIVISAO = 1
LEFT JOIN MAX_COMPRADOR COMP ON COMP.SEQCOMPRADOR = FD.SEQCOMPRADOR
INNER JOIN MAP_FAMDIVCATEG FDC ON FDC.SEQFAMILIA = A.SEQFAMILIA AND FDC.NRODIVISAO = 1 AND FDC.STATUS = 'A'
INNER JOIN MAP_CATEGORIA C ON C.SEQCATEGORIA = FDC.SEQCATEGORIA AND C.NRODIVISAO = 1 AND C.NIVELHIERARQUIA = 1 AND C.STATUSCATEGOR = 'A'
WHERE Y.STATUSCOMPRA = 'A'
  AND Y.NROEMPRESA IN (1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 14, 15, 17, 18)
  AND FD.FINALIDADEFAMILIA = 'R'
  AND (
      UPPER(C.CATEGORIA) IN ('BEBIDAS', 'MERCEARIA', 'PERFUMARIA E LIMPEZA', 'PRODUTOS PET')
      OR EXISTS (
          SELECT 1 
          FROM MAP_FAMDIVCATEG FDC2
          INNER JOIN MAP_CATEGORIA C2 ON FDC2.SEQCATEGORIA = C2.SEQCATEGORIA
          WHERE FDC2.SEQFAMILIA = A.SEQFAMILIA 
            AND FDC2.NRODIVISAO = 1 
            AND FDC2.STATUS = 'A' 
            AND C2.NRODIVISAO = 1 
            AND C2.STATUSCATEGOR = 'A'
            AND (UPPER(C2.CATEGORIA) LIKE '%LEITE%' OR UPPER(C2.CATEGORIA) LIKE '%CARV%O%')
      )
  )
ORDER BY C.CATEGORIA, Y.NROEMPRESA, A.DESCCOMPLETA
