SELECT
    PEPE.SEQPONTOEXTRA,
    PE.DESCRICAO,
    PEPE.SEQPRODUTO,
    PROD.DESCCOMPLETA,
    PEPE.NROEMPRESA,
    PEPE.ESTQMINIMO,
    PEPE.ESTQMAXIMO,
    PEPE.DTAVIGENCIAINICIO,
    PEPE.DTAVIGENCIAFIM
FROM MRL_PONTOEXTRA PE
INNER JOIN MRL_PONTOEXTRAPRODUTO PEP
    ON PEP.SEQPONTOEXTRA = PE.SEQPONTOEXTRA
INNER JOIN MRL_PONTOEXTRAPRODUTOEMPRESA PEPE
    ON PEPE.SEQPONTOEXTRA = PEP.SEQPONTOEXTRA
   AND PEPE.SEQPRODUTO    = PEP.SEQPRODUTO
INNER JOIN MAP_PRODUTO PROD
    ON PROD.SEQPRODUTO    = PEPE.SEQPRODUTO
WHERE PE.STATUS = 'A'
ORDER BY PEPE.SEQPONTOEXTRA, PEPE.NROEMPRESA, PEPE.SEQPRODUTO
