SELECT
    PEPE.SEQPONTOEXTRA,
    PE.DESCRICAO,
    PEPE.SEQPRODUTO,
    PROD.DESCCOMPLETA,
    PEPE.NROEMPRESA,
    EMP.FANTASIA,
    PEPE.ESTQMINIMO,
    PEPE.ESTQMAXIMO,
    NVL(ESTQ.ESTQLOJA, 0) AS ESTQLOJA,
    PEPE.DTAVIGENCIAINICIO,
    PEPE.DTAVIGENCIAFIM,
    PEPE.QTDDIASSUGESTAO,
    PEPE.STATUS,
    PEPE.SEQVIGENCIA,
    COMP.APELIDO
FROM MRL_PONTOEXTRA PE
INNER JOIN MRL_PONTOEXTRAPRODUTO PEP
    ON PEP.SEQPONTOEXTRA = PE.SEQPONTOEXTRA
INNER JOIN MRL_PONTOEXTRAPRODUTOEMPRESA PEPE
    ON PEPE.SEQPONTOEXTRA = PEP.SEQPONTOEXTRA
   AND PEPE.SEQPRODUTO    = PEP.SEQPRODUTO
INNER JOIN MAP_PRODUTO PROD
    ON PROD.SEQPRODUTO    = PEPE.SEQPRODUTO
INNER JOIN MAX_EMPRESA EMP
    ON EMP.NROEMPRESA     = PEPE.NROEMPRESA
LEFT JOIN MRL_PRODUTOEMPRESA ESTQ
    ON ESTQ.SEQPRODUTO    = PEPE.SEQPRODUTO
   AND ESTQ.NROEMPRESA    = PEPE.NROEMPRESA
LEFT JOIN MAP_FAMDIVISAO FD
    ON FD.SEQFAMILIA      = PROD.SEQFAMILIA
   AND FD.NRODIVISAO      = 1
LEFT JOIN MAX_COMPRADOR COMP
    ON COMP.SEQCOMPRADOR  = FD.SEQCOMPRADOR
WHERE PE.STATUS = 'A'
ORDER BY PEPE.SEQPONTOEXTRA, PROD.DESCCOMPLETA, PEPE.NROEMPRESA
