SELECT
    P.SEQPRODUTO                  AS COD_PRODUTO,
    P.DESCCOMPLETA                AS DESC_PRODUTO,
    ROUND(SUM(NVL(I.QUANTIDADE, 0)), 2) AS QTD_VENDIDA,
    ROUND(SUM(NVL(I.VLRITEM, 0)), 2) AS VLR_FAT_LIQUIDO
FROM MLFV_BASENFE N
INNER JOIN MFLV_BASEDFITEM I
    ON I.NROEMPRESA = N.NROEMPRESA
   AND I.SEQNF = N.SEQNF
   AND I.TIPNOTAFISCAL = N.TIPNOTAFISCAL
   AND I.SERIEDF = N.SERIENF
   AND I.NUMERODF = N.NUMERONF
   AND I.SEQPESSOA = N.SEQPESSOA
INNER JOIN MAP_PRODUTO P
    ON P.SEQPRODUTO = I.SEQPRODUTO
WHERE N.TIPNOTAFISCAL = 'S'
  AND N.CODGERALOPER = 800
  AND N.NROEMPRESA IN (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 20, 21, 22, 23, 50, 900, 901, 902)
  AND N.DTAEMISSAO >= TRUNC(:DT1)
  AND N.DTAEMISSAO < TRUNC(:DT2) + 1
  AND (:NR1 = 0 OR P.SEQPRODUTO = :NR1)
GROUP BY
    P.SEQPRODUTO,
    P.DESCCOMPLETA
HAVING SUM(NVL(I.VLRITEM, 0)) > 0
ORDER BY
    VLR_FAT_LIQUIDO DESC
