SELECT * FROM (
    WITH ITENS_PEDIDO_PERIODO AS (
        SELECT /*+ MATERIALIZE */
            R.SEQFORNECEDOR,
            R.SEQPRODUTO,
            R.NROEMPRESA,
            R.NROPEDIDOSUPRIM,
            SUM(R.QTDSOLICITADA) AS QTDSOLICITADA,
            MAX(RI.VLRUNITARIO) AS VLRUNITARIO,
            MAX(RI.VLREMBITEM) AS VLREMBITEM,
            MAX(NVL(RI.VLREMBITEM,0) + NVL(RI.VLREMBICMSST,0) + NVL(RI.VLREMBIPI, 0) + NVL(RI.VLREMBFCPST, 0)) AS CUSTO_BRUTO,
            MAX(RI.VLREMBIPI) AS VLREMBIPI,
            MAX(RI.VLREMBICMSST) AS VLREMBICMSST,
            MAX(RI.VLREMBFCPST) AS VLREMBFCPST,
            MAX(RI.VLREMBDESPESA) AS VLREMBDESPESA,
            SUM((R.QTDSOLICITADA / NVL(RI.QTDEMBALAGEM, 1)) * (NVL(RI.VLREMBITEM,0) + NVL(RI.VLREMBICMSST,0) + NVL(RI.VLREMBIPI, 0) + NVL(RI.VLREMBFCPST, 0))) AS VLRTOTALITEM_BRUTO
        FROM MACV_PSITEMRECEBER R
        LEFT JOIN MSU_PSITEMRECEBER RI
            ON RI.NROPEDIDOSUPRIM = R.NROPEDIDOSUPRIM
           AND RI.NROEMPRESA = R.NROEMPRESA
           AND RI.CENTRALLOJA = R.CENTRALLOJA
           AND RI.SEQPRODUTO = R.SEQPRODUTO
        LEFT JOIN MSU_PEDIDOSUPRIM PS
            ON PS.NROPEDIDOSUPRIM = R.NROPEDIDOSUPRIM
           AND PS.NROEMPRESA = R.NROEMPRESA
           AND PS.CENTRALLOJA = R.CENTRALLOJA
        WHERE TRUNC(R.DTAEMISSAO) BETWEEN TRUNC(:DT1) AND TRUNC(:DT2)
          AND R.TIPPEDIDOSUPRIM = 'C'
          AND NVL(R.STATUSITEM, 'A') != 'C'
          AND NVL(R.SITUACAOPED, 'A') != 'C'
          AND R.NROEMPRESA IN (1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 14, 15, 16, 17, 18)
          AND (
              TO_CHAR(R.SEQFORNECEDOR) = TRIM(:LS1)
              OR INSTR(TRIM(:LS1), TO_CHAR(R.SEQFORNECEDOR) || ' - ') = 1
              OR INSTR(TRIM(:LS1), TO_CHAR(R.SEQFORNECEDOR) || '-') = 1
          )
          AND (
              NVL(TRIM(:LS2), 'TODOS') IN ('TODOS', '0 - TODOS', '0', '')
              OR INSTR(TRIM(:LS2), 'TODOS') > 0
              OR TO_CHAR(NVL(R.SEQCOMPRADOR, PS.SEQCOMPRADOR)) = TRIM(:LS2)
              OR INSTR(TRIM(:LS2), TO_CHAR(NVL(R.SEQCOMPRADOR, PS.SEQCOMPRADOR)) || ' - ') = 1
              OR INSTR(TRIM(:LS2), TO_CHAR(NVL(R.SEQCOMPRADOR, PS.SEQCOMPRADOR)) || '-') = 1
          )
          AND (
              NVL(TRIM(:LT1), 'TODOS') IN ('TODOS', '0', '')
              OR INSTR(',' || REPLACE(TRIM(:LT1), ' ', '') || ',', ',' || TO_CHAR(R.NROEMPRESA) || ',') > 0
          )
          AND (
              NVL(TRIM(:LT2), 'TODOS') IN ('TODOS', '0', '')
              OR PS.CODGERALOPER IS NULL
              OR PS.CODGERALOPER = 0
              OR INSTR(',' || REPLACE(TRIM(:LT2), ' ', '') || ',', ',' || TO_CHAR(PS.CODGERALOPER) || ',') > 0
          )
        GROUP BY R.SEQFORNECEDOR, R.SEQPRODUTO, R.NROEMPRESA, R.NROPEDIDOSUPRIM
    ),
    PEDIDOS_LOJA AS (
        SELECT /*+ MATERIALIZE */
            NROEMPRESA,
            MAX(NROPEDIDOSUPRIM) AS NROPEDIDOSUPRIM,
            SUM(VLRTOTALITEM_BRUTO) AS VLRTOTALPEDIDO
        FROM ITENS_PEDIDO_PERIODO
        GROUP BY NROEMPRESA
    ),
    LINHA_CABECALHO AS (
        SELECT /*+ MATERIALIZE */
            0 AS ORDEM,
            TO_NUMBER(NULL) AS CODIGO_FORNECEDOR,
            0 AS CODIGO_PRODUTO,
            TO_CHAR(MAX((SELECT MAX(SEQFORNECEDOR) FROM ITENS_PEDIDO_PERIODO))) AS CODIGO_FORN,
            '               ' AS CODIGO_EAN,
            '>>> NÚMERO DO PEDIDO DA LOJA >>>' AS DESCRICAO,
            0 AS EMBALAGEM,
            TO_NUMBER(NULL) AS VALOR_UNIT,
            TO_NUMBER(NULL) AS VALOR_ITEM,
            TO_NUMBER(NULL) AS CUSTO_BRUTO,
            TO_NUMBER(NULL) AS VALOR_IPI,
            TO_NUMBER(NULL) AS VALOR_ICMS_ST,
            TO_NUMBER(NULL) AS VALOR_FCP_ST,
            TO_NUMBER(NULL) AS VALOR_DESP,
            NVL(MAX(CASE WHEN NROEMPRESA = 1 THEN NROPEDIDOSUPRIM END), 0) AS L1,
            NVL(MAX(CASE WHEN NROEMPRESA = 2 THEN NROPEDIDOSUPRIM END), 0) AS L2,
            NVL(MAX(CASE WHEN NROEMPRESA = 3 THEN NROPEDIDOSUPRIM END), 0) AS L3,
            NVL(MAX(CASE WHEN NROEMPRESA = 4 THEN NROPEDIDOSUPRIM END), 0) AS L4,
            NVL(MAX(CASE WHEN NROEMPRESA = 5 THEN NROPEDIDOSUPRIM END), 0) AS L5,
            NVL(MAX(CASE WHEN NROEMPRESA = 6 THEN NROPEDIDOSUPRIM END), 0) AS L6,
            NVL(MAX(CASE WHEN NROEMPRESA = 7 THEN NROPEDIDOSUPRIM END), 0) AS L7,
            NVL(MAX(CASE WHEN NROEMPRESA = 8 THEN NROPEDIDOSUPRIM END), 0) AS L8,
            NVL(MAX(CASE WHEN NROEMPRESA = 11 THEN NROPEDIDOSUPRIM END), 0) AS L11,
            NVL(MAX(CASE WHEN NROEMPRESA = 12 THEN NROPEDIDOSUPRIM END), 0) AS L12,
            NVL(MAX(CASE WHEN NROEMPRESA = 13 THEN NROPEDIDOSUPRIM END), 0) AS L13,
            NVL(MAX(CASE WHEN NROEMPRESA = 14 THEN NROPEDIDOSUPRIM END), 0) AS L14,
            NVL(MAX(CASE WHEN NROEMPRESA = 17 THEN NROPEDIDOSUPRIM END), 0) AS L17,
            NVL(MAX(CASE WHEN NROEMPRESA = 18 THEN NROPEDIDOSUPRIM END), 0) AS L18,
            NVL(MAX(CASE WHEN NROEMPRESA = 15 THEN NROPEDIDOSUPRIM END), 0) AS C15,
            NVL(MAX(CASE WHEN NROEMPRESA = 16 THEN NROPEDIDOSUPRIM END), 0) AS C16,
            0 AS TOTAL_QTD
        FROM PEDIDOS_LOJA
    ),
    LINHA_RODAPE AS (
        SELECT /*+ MATERIALIZE */
            2 AS ORDEM,
            TO_NUMBER(NULL) AS CODIGO_FORNECEDOR,
            999999999 AS CODIGO_PRODUTO,
            '               ' AS CODIGO_FORN,
            '               ' AS CODIGO_EAN,
            '>>> VALOR TOTAL DO PEDIDO >>>' AS DESCRICAO,
            0 AS EMBALAGEM,
            TO_NUMBER(NULL) AS VALOR_UNIT,
            TO_NUMBER(NULL) AS VALOR_ITEM,
            TO_NUMBER(NULL) AS CUSTO_BRUTO,
            TO_NUMBER(NULL) AS VALOR_IPI,
            TO_NUMBER(NULL) AS VALOR_ICMS_ST,
            TO_NUMBER(NULL) AS VALOR_FCP_ST,
            TO_NUMBER(NULL) AS VALOR_DESP,
            SUM(CASE WHEN NROEMPRESA = 1 THEN VLRTOTALPEDIDO END) AS L1,
            SUM(CASE WHEN NROEMPRESA = 2 THEN VLRTOTALPEDIDO END) AS L2,
            SUM(CASE WHEN NROEMPRESA = 3 THEN VLRTOTALPEDIDO END) AS L3,
            SUM(CASE WHEN NROEMPRESA = 4 THEN VLRTOTALPEDIDO END) AS L4,
            SUM(CASE WHEN NROEMPRESA = 5 THEN VLRTOTALPEDIDO END) AS L5,
            SUM(CASE WHEN NROEMPRESA = 6 THEN VLRTOTALPEDIDO END) AS L6,
            SUM(CASE WHEN NROEMPRESA = 7 THEN VLRTOTALPEDIDO END) AS L7,
            SUM(CASE WHEN NROEMPRESA = 8 THEN VLRTOTALPEDIDO END) AS L8,
            SUM(CASE WHEN NROEMPRESA = 11 THEN VLRTOTALPEDIDO END) AS L11,
            SUM(CASE WHEN NROEMPRESA = 12 THEN VLRTOTALPEDIDO END) AS L12,
            SUM(CASE WHEN NROEMPRESA = 13 THEN VLRTOTALPEDIDO END) AS L13,
            SUM(CASE WHEN NROEMPRESA = 14 THEN VLRTOTALPEDIDO END) AS L14,
            SUM(CASE WHEN NROEMPRESA = 17 THEN VLRTOTALPEDIDO END) AS L17,
            SUM(CASE WHEN NROEMPRESA = 18 THEN VLRTOTALPEDIDO END) AS L18,
            SUM(CASE WHEN NROEMPRESA = 15 THEN VLRTOTALPEDIDO END) AS C15,
            SUM(CASE WHEN NROEMPRESA = 16 THEN VLRTOTALPEDIDO END) AS C16,
            SUM(VLRTOTALPEDIDO) AS TOTAL_QTD
        FROM PEDIDOS_LOJA
    ),
    GRADE_LOJAS AS (
        SELECT /*+ MATERIALIZE */
            I.SEQFORNECEDOR AS CODIGO_FORNECEDOR,
            I.SEQPRODUTO,
            MAX(I.VLRUNITARIO) AS VALOR_UNIT,
            MAX(I.VLREMBITEM) AS VALOR_ITEM,
            MAX(I.CUSTO_BRUTO) AS CUSTO_BRUTO,
            MAX(I.VLREMBIPI) AS VALOR_IPI,
            MAX(I.VLREMBICMSST) AS VALOR_ICMS_ST,
            MAX(I.VLREMBFCPST) AS VALOR_FCP_ST,
            MAX(I.VLREMBDESPESA) AS VALOR_DESP,
            SUM(CASE WHEN I.NROEMPRESA = 1 THEN I.QTDSOLICITADA END) AS L1,
            SUM(CASE WHEN I.NROEMPRESA = 2 THEN I.QTDSOLICITADA END) AS L2,
            SUM(CASE WHEN I.NROEMPRESA = 3 THEN I.QTDSOLICITADA END) AS L3,
            SUM(CASE WHEN I.NROEMPRESA = 4 THEN I.QTDSOLICITADA END) AS L4,
            SUM(CASE WHEN I.NROEMPRESA = 5 THEN I.QTDSOLICITADA END) AS L5,
            SUM(CASE WHEN I.NROEMPRESA = 6 THEN I.QTDSOLICITADA END) AS L6,
            SUM(CASE WHEN I.NROEMPRESA = 7 THEN I.QTDSOLICITADA END) AS L7,
            SUM(CASE WHEN I.NROEMPRESA = 8 THEN I.QTDSOLICITADA END) AS L8,
            SUM(CASE WHEN I.NROEMPRESA = 11 THEN I.QTDSOLICITADA END) AS L11,
            SUM(CASE WHEN I.NROEMPRESA = 12 THEN I.QTDSOLICITADA END) AS L12,
            SUM(CASE WHEN I.NROEMPRESA = 13 THEN I.QTDSOLICITADA END) AS L13,
            SUM(CASE WHEN I.NROEMPRESA = 14 THEN I.QTDSOLICITADA END) AS L14,
            SUM(CASE WHEN I.NROEMPRESA = 17 THEN I.QTDSOLICITADA END) AS L17,
            SUM(CASE WHEN I.NROEMPRESA = 18 THEN I.QTDSOLICITADA END) AS L18,
            SUM(CASE WHEN I.NROEMPRESA = 15 THEN I.QTDSOLICITADA END) AS C15,
            SUM(CASE WHEN I.NROEMPRESA = 16 THEN I.QTDSOLICITADA END) AS C16,
            SUM(I.QTDSOLICITADA) AS TOTAL_QTD
        FROM ITENS_PEDIDO_PERIODO I
        GROUP BY I.SEQFORNECEDOR, I.SEQPRODUTO
    ),
    COD_FORN_PRODUTO AS (
        SELECT /*+ MATERIALIZE */
            SEQPRODUTO,
            CODACESSO AS CODIGO_FORN
        FROM (
            SELECT
                C.SEQPRODUTO,
                C.CODACESSO,
                ROW_NUMBER() OVER (PARTITION BY C.SEQPRODUTO ORDER BY C.CODACESSO ASC) AS RN
            FROM MAP_PRODCODIGO C
            WHERE C.TIPCODIGO = 'F'
        )
        WHERE RN = 1
    ),
    EAN_PRODUTO AS (
        SELECT /*+ MATERIALIZE */
            SEQPRODUTO,
            CODACESSO AS CODIGO_EAN
        FROM (
            SELECT
                C.SEQPRODUTO,
                C.CODACESSO,
                ROW_NUMBER() OVER (PARTITION BY C.SEQPRODUTO ORDER BY DECODE(C.TIPCODIGO, 'E', 1, 'D', 2, 3) ASC, C.CODACESSO ASC) AS RN
            FROM MAP_PRODCODIGO C
            WHERE C.TIPCODIGO IN ('E', 'D')
        )
        WHERE RN = 1
    ),
    LINHAS_ITENS AS (
        SELECT /*+ MATERIALIZE */
            1 AS ORDEM,
            TO_NUMBER(NULL) AS CODIGO_FORNECEDOR,
            P.SEQPRODUTO AS CODIGO_PRODUTO,
            NVL(CF.CODIGO_FORN, ' ') AS CODIGO_FORN,
            NVL(E.CODIGO_EAN, ' ') AS CODIGO_EAN,
            P.DESCCOMPLETA AS DESCRICAO,
            NVL(FD.PADRAOEMBCOMPRA, 1) AS EMBALAGEM,
            G.VALOR_UNIT,
            G.VALOR_ITEM,
            G.CUSTO_BRUTO,
            G.VALOR_IPI,
            G.VALOR_ICMS_ST,
            G.VALOR_FCP_ST,
            G.VALOR_DESP,
            G.L1,
            G.L2,
            G.L3,
            G.L4,
            G.L5,
            G.L6,
            G.L7,
            G.L8,
            G.L11,
            G.L12,
            G.L13,
            G.L14,
            G.L17,
            G.L18,
            G.C15,
            G.C16,
            G.TOTAL_QTD
        FROM GRADE_LOJAS G
        INNER JOIN MAP_PRODUTO P ON P.SEQPRODUTO = G.SEQPRODUTO
        INNER JOIN MAP_FAMDIVISAO FD ON FD.SEQFAMILIA = P.SEQFAMILIA AND FD.NRODIVISAO = 1
        LEFT JOIN COD_FORN_PRODUTO CF ON CF.SEQPRODUTO = G.SEQPRODUTO
        LEFT JOIN EAN_PRODUTO E ON E.SEQPRODUTO = G.SEQPRODUTO
    )
    SELECT
        CODIGO_PRODUTO AS SEQPRODUTO,
        CODIGO_FORN AS COD_FORN,
        CODIGO_EAN,
        DESCRICAO,
        EMBALAGEM AS EMB,
        TO_CHAR(VALOR_UNIT, 'FM999G999G990D00') AS VLR_UNIT,
        TO_CHAR(VALOR_ITEM, 'FM999G999G990D00') AS VLR_ITEM,
        TO_CHAR(CUSTO_BRUTO, 'FM999G999G990D00') AS CUST_BRT,
        TO_CHAR(VALOR_IPI, 'FM999G999G990D00') AS VLR_IPI,
        TO_CHAR(VALOR_ICMS_ST, 'FM999G999G990D00') AS VLR_ST,
        TO_CHAR(VALOR_FCP_ST, 'FM999G999G990D00') AS VLR_FCP,
        TO_CHAR(VALOR_DESP, 'FM999G999G990D00') AS VLR_DESP,
        CASE WHEN ORDEM = 2 THEN TO_CHAR(L1, 'FM999G999G990D00') ELSE TRIM(TO_CHAR(L1)) END AS L1,
        CASE WHEN ORDEM = 2 THEN TO_CHAR(L2, 'FM999G999G990D00') ELSE TRIM(TO_CHAR(L2)) END AS L2,
        CASE WHEN ORDEM = 2 THEN TO_CHAR(L3, 'FM999G999G990D00') ELSE TRIM(TO_CHAR(L3)) END AS L3,
        CASE WHEN ORDEM = 2 THEN TO_CHAR(L4, 'FM999G999G990D00') ELSE TRIM(TO_CHAR(L4)) END AS L4,
        CASE WHEN ORDEM = 2 THEN TO_CHAR(L5, 'FM999G999G990D00') ELSE TRIM(TO_CHAR(L5)) END AS L5,
        CASE WHEN ORDEM = 2 THEN TO_CHAR(L6, 'FM999G999G990D00') ELSE TRIM(TO_CHAR(L6)) END AS L6,
        CASE WHEN ORDEM = 2 THEN TO_CHAR(L7, 'FM999G999G990D00') ELSE TRIM(TO_CHAR(L7)) END AS L7,
        CASE WHEN ORDEM = 2 THEN TO_CHAR(L8, 'FM999G999G990D00') ELSE TRIM(TO_CHAR(L8)) END AS L8,
        CASE WHEN ORDEM = 2 THEN TO_CHAR(L11, 'FM999G999G990D00') ELSE TRIM(TO_CHAR(L11)) END AS L11,
        CASE WHEN ORDEM = 2 THEN TO_CHAR(L12, 'FM999G999G990D00') ELSE TRIM(TO_CHAR(L12)) END AS L12,
        CASE WHEN ORDEM = 2 THEN TO_CHAR(L13, 'FM999G999G990D00') ELSE TRIM(TO_CHAR(L13)) END AS L13,
        CASE WHEN ORDEM = 2 THEN TO_CHAR(L14, 'FM999G999G990D00') ELSE TRIM(TO_CHAR(L14)) END AS L14,
        CASE WHEN ORDEM = 2 THEN TO_CHAR(L17, 'FM999G999G990D00') ELSE TRIM(TO_CHAR(L17)) END AS L17,
        CASE WHEN ORDEM = 2 THEN TO_CHAR(L18, 'FM999G999G990D00') ELSE TRIM(TO_CHAR(L18)) END AS L18,
        CASE WHEN ORDEM = 2 THEN TO_CHAR(C15, 'FM999G999G990D00') ELSE TRIM(TO_CHAR(C15)) END AS C15,
        CASE WHEN ORDEM = 2 THEN TO_CHAR(C16, 'FM999G999G990D00') ELSE TRIM(TO_CHAR(C16)) END AS C16,
        CASE WHEN ORDEM = 2 THEN TO_CHAR(TOTAL_QTD, 'FM999G999G990D00') ELSE TRIM(TO_CHAR(TOTAL_QTD)) END AS TOTAL_QTD
    FROM (
        SELECT * FROM LINHA_CABECALHO
        UNION ALL
        SELECT * FROM LINHAS_ITENS
        UNION ALL
        SELECT * FROM LINHA_RODAPE
    )
    ORDER BY ORDEM ASC, DESCRICAO ASC, CODIGO_PRODUTO ASC
)
