SELECT * FROM (
    WITH ITENS_PEDIDO_PERIODO AS (
        SELECT /*+ MATERIALIZE */
            R.SEQFORNECEDOR,
            R.SEQPRODUTO,
            R.NROEMPRESA,
            R.NROPEDIDOSUPRIM,
            SUM(R.QTDSOLICITADA) AS QTDSOLICITADA
        FROM MACV_PSITEMRECEBER R
        LEFT JOIN MSU_PEDIDOSUPRIM PS
            ON PS.NROPEDIDOSUPRIM = R.NROPEDIDOSUPRIM
           AND PS.NROEMPRESA = R.NROEMPRESA
           AND PS.CENTRALLOJA = R.CENTRALLOJA
        WHERE TRUNC(R.DTAEMISSAO) BETWEEN TRUNC(:DT1) AND TRUNC(:DT2)
          AND R.TIPPEDIDOSUPRIM = 'C'
          AND NVL(R.STATUSITEM, 'A') != 'C'
          AND NVL(R.SITUACAOPED, 'A') != 'C'
          AND R.NROEMPRESA IN (1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 14, 17, 18)
          AND (
              NVL(TRIM(:LS1), 'TODOS') IN ('TODOS', '0 - TODOS', '0', '')
              OR INSTR(TRIM(:LS1), 'TODOS') > 0
              OR TO_CHAR(R.SEQFORNECEDOR) = TRIM(:LS1)
              OR INSTR(TRIM(:LS1), TO_CHAR(R.SEQFORNECEDOR) || ' - ') = 1
              OR INSTR(TRIM(:LS1), TO_CHAR(R.SEQFORNECEDOR) || '-') = 1
          )
          AND (
              NVL(TRIM(:LS2), 'TODOS') IN ('TODOS', '0 - TODOS', '0', '')
              OR INSTR(TRIM(:LS2), 'TODOS') > 0
              OR TO_CHAR(NVL(R.SEQCOMPRADOR, PS.SEQCOMPRADOR)) = TRIM(:LS2)
              OR INSTR(TRIM(:LS2), TO_CHAR(NVL(R.SEQCOMPRADOR, PS.SEQCOMPRADOR)) || ' - ') = 1
              OR INSTR(TRIM(:LS2), TO_CHAR(NVL(R.SEQCOMPRADOR, PS.SEQCOMPRADOR)) || '-') = 1
          )
          AND (
              NVL(TRIM(:LT1), 'TODOS') IN ('TODOS', '0', '')
              OR INSTR(',' || REPLACE(TRIM(:LT1), ' ', '') || ',', ',' || TO_CHAR(R.NROEMPRESA) || ',') > 0
          )
          AND (
              NVL(TRIM(:LT2), 'TODOS') IN ('TODOS', '0', '')
              OR PS.CODGERALOPER IS NULL
              OR PS.CODGERALOPER = 0
              OR INSTR(',' || REPLACE(TRIM(:LT2), ' ', '') || ',', ',' || TO_CHAR(PS.CODGERALOPER) || ',') > 0
          )
        GROUP BY R.SEQFORNECEDOR, R.SEQPRODUTO, R.NROEMPRESA, R.NROPEDIDOSUPRIM
    ),
    PEDIDOS_LOJA AS (
        SELECT /*+ MATERIALIZE */
            NROEMPRESA,
            MAX(NROPEDIDOSUPRIM) AS NROPEDIDOSUPRIM
        FROM ITENS_PEDIDO_PERIODO
        GROUP BY NROEMPRESA
    ),
    LINHA_CABECALHO AS (
        SELECT /*+ MATERIALIZE */
            0 AS ORDEM,
            0 AS CODIGO_FORNECEDOR,
            0 AS CODIGO_PRODUTO,
            '               ' AS CODIGO_EAN,
            '>>> NÚMERO DO PEDIDO DA LOJA >>>' AS DESCRICAO,
            0 AS EMBALAGEM,
            NVL(MAX(CASE WHEN NROEMPRESA = 1 THEN NROPEDIDOSUPRIM END), 0) AS L1,
            NVL(MAX(CASE WHEN NROEMPRESA = 2 THEN NROPEDIDOSUPRIM END), 0) AS L2,
            NVL(MAX(CASE WHEN NROEMPRESA = 3 THEN NROPEDIDOSUPRIM END), 0) AS L3,
            NVL(MAX(CASE WHEN NROEMPRESA = 4 THEN NROPEDIDOSUPRIM END), 0) AS L4,
            NVL(MAX(CASE WHEN NROEMPRESA = 5 THEN NROPEDIDOSUPRIM END), 0) AS L5,
            NVL(MAX(CASE WHEN NROEMPRESA = 6 THEN NROPEDIDOSUPRIM END), 0) AS L6,
            NVL(MAX(CASE WHEN NROEMPRESA = 7 THEN NROPEDIDOSUPRIM END), 0) AS L7,
            NVL(MAX(CASE WHEN NROEMPRESA = 8 THEN NROPEDIDOSUPRIM END), 0) AS L8,
            NVL(MAX(CASE WHEN NROEMPRESA = 11 THEN NROPEDIDOSUPRIM END), 0) AS L11,
            NVL(MAX(CASE WHEN NROEMPRESA = 12 THEN NROPEDIDOSUPRIM END), 0) AS L12,
            NVL(MAX(CASE WHEN NROEMPRESA = 13 THEN NROPEDIDOSUPRIM END), 0) AS L13,
            NVL(MAX(CASE WHEN NROEMPRESA = 14 THEN NROPEDIDOSUPRIM END), 0) AS L14,
            NVL(MAX(CASE WHEN NROEMPRESA = 17 THEN NROPEDIDOSUPRIM END), 0) AS L17,
            NVL(MAX(CASE WHEN NROEMPRESA = 18 THEN NROPEDIDOSUPRIM END), 0) AS L18,
            0 AS TOTAL_QTD
        FROM PEDIDOS_LOJA
    ),
    GRADE_LOJAS AS (
        SELECT /*+ MATERIALIZE */
            I.SEQFORNECEDOR AS CODIGO_FORNECEDOR,
            I.SEQPRODUTO,
            SUM(CASE WHEN I.NROEMPRESA = 1 THEN I.QTDSOLICITADA END) AS L1,
            SUM(CASE WHEN I.NROEMPRESA = 2 THEN I.QTDSOLICITADA END) AS L2,
            SUM(CASE WHEN I.NROEMPRESA = 3 THEN I.QTDSOLICITADA END) AS L3,
            SUM(CASE WHEN I.NROEMPRESA = 4 THEN I.QTDSOLICITADA END) AS L4,
            SUM(CASE WHEN I.NROEMPRESA = 5 THEN I.QTDSOLICITADA END) AS L5,
            SUM(CASE WHEN I.NROEMPRESA = 6 THEN I.QTDSOLICITADA END) AS L6,
            SUM(CASE WHEN I.NROEMPRESA = 7 THEN I.QTDSOLICITADA END) AS L7,
            SUM(CASE WHEN I.NROEMPRESA = 8 THEN I.QTDSOLICITADA END) AS L8,
            SUM(CASE WHEN I.NROEMPRESA = 11 THEN I.QTDSOLICITADA END) AS L11,
            SUM(CASE WHEN I.NROEMPRESA = 12 THEN I.QTDSOLICITADA END) AS L12,
            SUM(CASE WHEN I.NROEMPRESA = 13 THEN I.QTDSOLICITADA END) AS L13,
            SUM(CASE WHEN I.NROEMPRESA = 14 THEN I.QTDSOLICITADA END) AS L14,
            SUM(CASE WHEN I.NROEMPRESA = 17 THEN I.QTDSOLICITADA END) AS L17,
            SUM(CASE WHEN I.NROEMPRESA = 18 THEN I.QTDSOLICITADA END) AS L18,
            SUM(I.QTDSOLICITADA) AS TOTAL_QTD
        FROM ITENS_PEDIDO_PERIODO I
        GROUP BY I.SEQFORNECEDOR, I.SEQPRODUTO
    ),
    EAN_PRODUTO AS (
        SELECT /*+ MATERIALIZE */
            SEQPRODUTO,
            CODACESSO AS CODIGO_EAN
        FROM (
            SELECT
                C.SEQPRODUTO,
                C.CODACESSO,
                ROW_NUMBER() OVER (PARTITION BY C.SEQPRODUTO ORDER BY DECODE(C.TIPCODIGO, 'E', 1, 'D', 2, 3) ASC, C.CODACESSO ASC) AS RN
            FROM MAP_PRODCODIGO C
            WHERE C.TIPCODIGO IN ('E', 'D')
        )
        WHERE RN = 1
    ),
    LINHAS_ITENS AS (
        SELECT /*+ MATERIALIZE */
            1 AS ORDEM,
            G.CODIGO_FORNECEDOR,
            P.SEQPRODUTO AS CODIGO_PRODUTO,
            NVL(E.CODIGO_EAN, ' ') AS CODIGO_EAN,
            P.DESCCOMPLETA AS DESCRICAO,
            NVL(FD.PADRAOEMBCOMPRA, 1) AS EMBALAGEM,
            G.L1,
            G.L2,
            G.L3,
            G.L4,
            G.L5,
            G.L6,
            G.L7,
            G.L8,
            G.L11,
            G.L12,
            G.L13,
            G.L14,
            G.L17,
            G.L18,
            G.TOTAL_QTD
        FROM GRADE_LOJAS G
        INNER JOIN MAP_PRODUTO P ON P.SEQPRODUTO = G.SEQPRODUTO
        INNER JOIN MAP_FAMDIVISAO FD ON FD.SEQFAMILIA = P.SEQFAMILIA AND FD.NRODIVISAO = 1
        LEFT JOIN EAN_PRODUTO E ON E.SEQPRODUTO = G.SEQPRODUTO
    )
    SELECT
        CODIGO_FORNECEDOR AS FORN,
        CODIGO_PRODUTO AS SEQPRODUTO,
        CODIGO_EAN,
        DESCRICAO,
        EMBALAGEM,
        L1,
        L2,
        L3,
        L4,
        L5,
        L6,
        L7,
        L8,
        L11,
        L12,
        L13,
        L14,
        L17,
        L18,
        TOTAL_QTD
    FROM (
        SELECT * FROM LINHA_CABECALHO
        UNION ALL
        SELECT * FROM LINHAS_ITENS
    )
    ORDER BY ORDEM ASC, DESCRICAO ASC, CODIGO_PRODUTO ASC
)
