SELECT
    A.NROEMPRESA AS CODIGO_EMPRESA,
    A.NROACORDO AS NUMERO_ACORDO,
    AC.SEQPROCESSO AS NUMERO_PROCESSO,
    B.SEQPESSOA AS CODIGO_FORNECEDOR,
    B.NOMERAZAO AS FORNECEDOR,
    A.DESCACORDO AS DESCRICAO_ACORDO,
    TO_CHAR(A.DTAEMISSAO, 'DD/MM/YYYY') AS DATA_EMISSAO,
    CASE
        WHEN A.TIPOACORDO = 1 THEN 'VERBA EXTRA'
        WHEN A.TIPOACORDO = 2 THEN 'SELL-OUT'
        WHEN A.TIPOACORDO = 3 THEN 'SELL-IN'
    END AS TIPO_ACORDO,
    A.SEQPRODUTO AS CODIGO_PRODUTO,
    VC.NROEMPRESAVERBA AS LOJA_CONSUMO,
    VC.SEQLOTE AS SEQ_LOTE_CONSUMO,
    TO_CHAR(VC.DTAUTILIZACAOVERBA, 'DD/MM/YYYY') AS DATA_UTILIZACAO,
    VC.STATUSVERBA AS STATUS_MOVIMENTO,
    VC.QTDLIMITEVERBA AS QTD_LIMITE_VERBA_PRODUTO,
    VC.QTDUTILIZADAVERBA AS QTD_UTILIZADA_NA_ETAPA,
    'R$ ' || TO_CHAR(NVL(VC.VLRUNITVERBA, 0), 'FM999G999G990D00', 'NLS_NUMERIC_CHARACTERS='',.''') AS VLR_UNITARIO_DESCONTO,
    'R$ ' || TO_CHAR(NVL(VC.VLRUTILIZADOVERBA, 0), 'FM999G999G990D00', 'NLS_NUMERIC_CHARACTERS='',.''') AS VALOR_UTILIZADO_NA_ETAPA,
    'R$ ' || TO_CHAR(NVL(A.VLRSALDOACORDO, 0), 'FM999G999G990D00', 'NLS_NUMERIC_CHARACTERS='',.''') AS SALDO_RESULTANTE_VIEW,
    'R$ ' || TO_CHAR(NVL(A.VLRACORDO, 0), 'FM999G999G990D00', 'NLS_NUMERIC_CHARACTERS='',.''') AS VALOR_TOTAL_ACORDO
FROM MSUV_ACORDOPROMOC A
INNER JOIN GE_PESSOA B ON B.SEQPESSOA = A.SEQFORNECEDOR
LEFT JOIN MSU_ACORDOPROMOC AC ON AC.NROACORDO = A.NROACORDO AND AC.NROEMPRESA = A.NROEMPRESA
LEFT JOIN MRLV_VERBACONSUMIDA VC ON VC.NROACORDO = A.NROACORDO AND VC.NROEMPRESAACORDO = A.NROEMPRESA AND VC.SEQPRODUTO = A.SEQPRODUTO AND VC.APPORIGEM = 2 AND VC.STATUSVERBA != 'R'
WHERE A.NROACORDO = 684
ORDER BY A.SEQPRODUTO, VC.NROEMPRESAVERBA, VC.DTAUTILIZACAOVERBA
