SELECT
    DEP.CATEGORIA AS DEPARTAMENTO,
    SUB.SEQCATEGORIA || '-' || SUB.CATEGORIA AS SUBGRUPO,
    Y.NROEMPRESA AS CODIGO_EMPRESA,
    A.SEQPRODUTO AS CODIGO_PRODUTO,
    A.DESCCOMPLETA AS DESCRICAO_PRODUTO,
    G.PADRAOEMBVENDA AS EMBALAGEM,
    ROUND(
        (NVL(Y.CMULTVLRNF, 0) + NVL(Y.CMULTIPI, 0) - NVL(Y.CMULTCREDICMS, 0) + NVL(Y.CMULTICMSST, 0)
        + NVL(Y.CMULTDESPNF, 0) + NVL(Y.CMULTDESPFORANF, 0) - NVL(Y.CMULTDCTOFORANF, 0)
        - NVL(Y.CMULTCREDPIS, 0) - NVL(Y.CMULTCREDCOFINS, 0) - NVL(Y.CMULTVLRVERBA, 0))
    , 2) AS PRECO_CUSTO,
    ROUND(NVL(NULLIF(F.PRECOVALIDPROMOC, 0), F.PRECOVALIDNORMAL), 2) AS PRECO_VENDA,
    NVL(VND.QTD_PERIODO, 0) AS QTD_VENDIDA,
    NVL(Y.ESTQMINIMOLOJA, 0) AS PONTO_PEDIDO,
    NVL(Y.ESTQMAXIMOLOJA, 0) AS ESTOQUE_IDEAL,
    (NVL(Y.ESTQLOJA, 0) + NVL(Y.ESTQDEPOSITO, 0) - NVL(Y.QTDRESERVADAVDA, 0)
     - NVL(Y.QTDRESERVADARECEB, 0) - NVL(Y.QTDRESERVADAFIXA, 0)) AS ESTOQUE_DISPONIVEL,
    NVL(Y.ESTQDEPOSITO, 0) AS ESTOQUE_DEPOSITO,
    NVL(Y.QTDPENDPEDCOMPRA, 0) AS QTD_NF_DEPOSITO,
    TO_CHAR(Y.DTAULTENTRADA, 'DD/MM/YYYY') AS DT_NF_DEPOSITO
FROM MAP_PRODUTO A
INNER JOIN MRL_PRODUTOEMPRESA Y ON A.SEQPRODUTO = Y.SEQPRODUTO
INNER JOIN MAX_EMPRESA C ON Y.NROEMPRESA = C.NROEMPRESA
INNER JOIN MAP_FAMILIA B ON A.SEQFAMILIA = B.SEQFAMILIA
LEFT JOIN MAP_FAMDIVISAO FD ON A.SEQFAMILIA = FD.SEQFAMILIA AND FD.NRODIVISAO = C.NRODIVISAO
LEFT JOIN MAD_FAMSEGMENTO G ON A.SEQFAMILIA = G.SEQFAMILIA AND C.NROSEGMENTOPRINC = G.NROSEGMENTO
LEFT JOIN MRL_PRODEMPSEG F ON A.SEQPRODUTO = F.SEQPRODUTO
    AND Y.NROEMPRESA = F.NROEMPRESA
    AND C.NROSEGMENTOPRINC = F.NROSEGMENTO
    AND G.PADRAOEMBVENDA = F.QTDEMBALAGEM
    AND F.STATUSVENDA = 'A'
LEFT JOIN (
    SELECT X.SEQFAMILIA, Y2.CATEGORIA
    FROM MAP_FAMDIVCATEG X
    INNER JOIN MAP_CATEGORIA Y2 ON X.SEQCATEGORIA = Y2.SEQCATEGORIA
    WHERE Y2.NIVELHIERARQUIA = 1 AND X.NRODIVISAO = 1 AND Y2.NRODIVISAO = 1 AND X.STATUS = 'A' AND Y2.STATUSCATEGOR = 'A'
) DEP ON DEP.SEQFAMILIA = A.SEQFAMILIA
LEFT JOIN (
    SELECT X.SEQFAMILIA, Y2.SEQCATEGORIA, Y2.CATEGORIA
    FROM MAP_FAMDIVCATEG X
    INNER JOIN MAP_CATEGORIA Y2 ON X.SEQCATEGORIA = Y2.SEQCATEGORIA
    WHERE Y2.NIVELHIERARQUIA = 3 AND X.NRODIVISAO = 1 AND Y2.NRODIVISAO = 1 AND X.STATUS = 'A' AND Y2.STATUSCATEGOR = 'A'
) SUB ON SUB.SEQFAMILIA = A.SEQFAMILIA
LEFT JOIN (
    SELECT SEQPRODUTO, NROEMPRESA, ROUND(SUM(QTDVDA), 2) AS QTD_PERIODO
    FROM MRL_PRODVENDADIA
    WHERE DTAVDA BETWEEN TO_DATE('05/04/2026', 'DD/MM/YYYY')
                     AND TO_DATE('06/04/2026', 'DD/MM/YYYY')
    GROUP BY SEQPRODUTO, NROEMPRESA
) VND ON VND.SEQPRODUTO = A.SEQPRODUTO AND VND.NROEMPRESA = Y.NROEMPRESA
WHERE Y.STATUSCOMPRA = 'A'
  AND Y.NROEMPRESA = 1
  AND FD.FINALIDADEFAMILIA = 'R'
ORDER BY SUB.CATEGORIA, A.DESCCOMPLETA
