SELECT
    'MAXV_MSUPEDIDOSUPRIMEXP' AS FONTE,
    X.NROEMPRESA,
    X.NROEMPDESTINO,
    X.SEQPRODUTO,
    X.NROPEDIDOSUPRIM AS NRO_PEDIDO_REFERENCIA,
    TO_CHAR(TRUNC(X.DTAEMISSAO), 'DD/MM/YYYY') AS DATA_REFERENCIA,
    NULL AS NRO_CARGA
FROM MAXV_MSUPEDIDOSUPRIMEXP X
WHERE X.SEQPRODUTO = 1679
  AND X.DTAEMISSAO >= TO_DATE('01/03/2026', 'DD/MM/YYYY')
  AND X.NROPEDIDOSUPRIM IN (31339, 31342)

UNION ALL

SELECT
    'MSU_PSITEMEXPEDIDO' AS FONTE,
    P.NROEMPRESA,
    P.NROEMPRESAPEDVENDA AS NROEMPDESTINO,
    P.SEQPRODUTO,
    P.NROPEDVENDA AS NRO_PEDIDO_REFERENCIA,
    NULL AS DATA_REFERENCIA,
    NULL AS NRO_CARGA
FROM MSU_PSITEMEXPEDIDO P
WHERE P.SEQPRODUTO = 1679
  AND (
      P.NROPEDIDOSUPRIM IN (31339, 31342)
      OR P.NROPEDVENDA IN (31339, 31342)
  )

UNION ALL

SELECT
    'MAD_PEDVENDA' AS FONTE,
    V.NROEMPRESA,
    NULL AS NROEMPDESTINO,
    NULL AS SEQPRODUTO,
    V.NROPEDVENDA AS NRO_PEDIDO_REFERENCIA,
    NULL AS DATA_REFERENCIA,
    V.NROCARGA AS NRO_CARGA
FROM MAD_PEDVENDA V
WHERE V.NROPEDVENDA IN (31339, 31342, 56123)

UNION ALL

SELECT
    'MLO_CARGAECLIPROD' AS FONTE,
    C.NROEMPRESA,
    NULL AS NROEMPDESTINO,
    C.SEQPRODUTO,
    C.NROPEDVENDA AS NRO_PEDIDO_REFERENCIA,
    NULL AS DATA_REFERENCIA,
    C.NROCARGA AS NRO_CARGA
FROM MLO_CARGAECLIPROD C
WHERE C.SEQPRODUTO = 1679
  AND C.NROPEDVENDA IN (31339, 31342, 56123)

UNION ALL

SELECT
    'MLO_CARGAECOLETOR' AS FONTE,
    C.NROEMPRESA,
    NULL AS NROEMPDESTINO,
    C.SEQPRODUTO,
    C.NROPEDVENDA AS NRO_PEDIDO_REFERENCIA,
    NULL AS DATA_REFERENCIA,
    C.NROCARGA AS NRO_CARGA
FROM MLO_CARGAECOLETOR C
WHERE C.SEQPRODUTO = 1679
  AND C.NROPEDVENDA IN (31339, 31342, 56123)

ORDER BY
    FONTE,
    NROEMPRESA,
    NRO_PEDIDO_REFERENCIA
