SELECT
    A.NROEMPRESA AS EMPRESA_ORIGEM_PEDIDO,
    A.NROEMPDESTINO AS CODIGO_EMPRESA,
    A.SEQPRODUTO AS CODIGO_PRODUTO,
    B.DESCCOMPLETA AS DESCRICAO_PRODUTO,
    NVL(DEP.DEPARTAMENTO, 'SEM DEPARTAMENTO') AS DEPARTAMENTO,
    A.NROPEDIDOSUPRIM AS NRO_PEDIDO_SUPRIMENTO,
    TO_CHAR(TRUNC(A.DTAEMISSAO), 'DD/MM/YYYY') AS DATA_PEDIDO_SUPRIMENTO,
    P.NROEMPRESAPEDVENDA AS EMPRESA_PEDIDO_EXPEDICAO,
    P.NROPEDVENDA AS NRO_PEDIDO_EXPEDICAO,
    CP.NROPEDVENDA AS NRO_PEDIDO_VINCULADO_CARGA,
    CC.NROPEDVENDA AS NRO_PEDIDO_VINCULADO_COLETOR,
    MV.NROCARGA AS NROCARGA,
    A.QTDEMBALAGEM AS EMBALAGEM,
    A.QUANTIDADE_A_EXPEDIR AS QUANTIDADE_A_EXPEDIR,
    NVL(SUM(CP.QTDEMBSEPARADA), 0) AS QTD_SEPARADA,
    NVL(SUM(CC.QTDCONTADA / CP.QTDEMBALAGEM), 0) AS QTD_CONFERIDA,
    TO_CHAR(TRUNC(ATV.DTAHORFIMTAREFA), 'DD/MM/YYYY') AS DATA_CONFERENCIA,
    ATV.USUARIO_CONFERENCIA AS USUARIO_CONFERENCIA,
    CASE
        WHEN CP.NROPEDVENDA IS NULL THEN 'Sem pedido vinculado na carga'
        WHEN CP.NROPEDVENDA = P.NROPEDVENDA THEN 'Mesmo pedido'
        ELSE 'Pedido vinculado diferente do pedido de expedicao'
    END AS STATUS_PEDIDO_VINCULADO,
    CASE
        WHEN A.QUANTIDADE_A_EXPEDIR = 0 THEN 'Cancelado'
        WHEN P.NROPEDVENDA IS NULL THEN 'Aguardando Pedido Venda'
        WHEN MV.NROCARGA IS NULL THEN 'Pedido Venda Criado'
        WHEN NVL(SUM(CP.QTDEMBSEPARADA), 0) = 0 THEN 'Aguardando Separacao'
        WHEN NVL(SUM(CC.QTDCONTADA / CP.QTDEMBALAGEM), 0) = 0 AND NVL(SUM(CP.QTDEMBSEPARADA), 0) > 0 THEN 'Separado - Sem Conferencia'
        WHEN NVL(SUM(CC.QTDCONTADA / CP.QTDEMBALAGEM), 0) < NVL(SUM(CP.QTDEMBSEPARADA), 0) THEN 'Conferencia Parcial'
        WHEN NVL(SUM(CC.QTDCONTADA / CP.QTDEMBALAGEM), 0) = NVL(SUM(CP.QTDEMBSEPARADA), 0) AND NVL(SUM(CP.QTDEMBSEPARADA), 0) > 0 THEN 'Conferido'
        ELSE 'Em Andamento'
    END AS ETAPA_ATUAL
FROM (
    SELECT
        X.NROEMPDESTINO,
        X.SEQPRODUTO,
        X.NROPEDIDOSUPRIM,
        TRUNC(X.DTAEMISSAO) AS DTAEMISSAO,
        X.QTDEMBALAGEM,
        X.NROEMPRESA,
        SUM(X.QTDSOLICITADA) - SUM(X.QTDEXPCANC) AS QUANTIDADE_A_EXPEDIR
    FROM MAXV_MSUPEDIDOSUPRIMEXP X
        WHERE X.DTAEMISSAO >= TO_DATE('01/03/2026', 'DD/MM/YYYY')
            AND X.SEQPRODUTO = 1679
            AND X.NROPEDIDOSUPRIM IN (31339, 31342)
    GROUP BY
        X.NROEMPDESTINO,
        X.SEQPRODUTO,
        X.NROPEDIDOSUPRIM,
        TRUNC(X.DTAEMISSAO),
        X.QTDEMBALAGEM,
        X.NROEMPRESA
) A
INNER JOIN MAP_PRODUTO B
    ON A.SEQPRODUTO = B.SEQPRODUTO
LEFT JOIN (
    SELECT
        X.SEQFAMILIA,
        MAX(Y.CATEGORIA) AS DEPARTAMENTO
    FROM MAP_FAMDIVCATEG X
    INNER JOIN MAP_CATEGORIA Y
        ON Y.SEQCATEGORIA = X.SEQCATEGORIA
    WHERE X.NRODIVISAO = 1
      AND Y.NRODIVISAO = 1
      AND Y.NIVELHIERARQUIA = 1
      AND UPPER(Y.CATEGORIA) NOT IN ('A CLASSIFICAR', 'ALMOXARIFADO', 'INATIVAR')
      AND UPPER(Y.CATEGORIA) NOT LIKE 'SERVIC%'
    GROUP BY X.SEQFAMILIA
) DEP
    ON B.SEQFAMILIA = DEP.SEQFAMILIA
LEFT JOIN MSU_PSITEMEXPEDIDO P
    ON A.NROPEDIDOSUPRIM = P.NROPEDIDOSUPRIM
    AND A.SEQPRODUTO = P.SEQPRODUTO
    AND A.NROEMPRESA = P.NROEMPRESA
LEFT JOIN MAD_PEDVENDA MV
    ON P.NROPEDVENDA = MV.NROPEDVENDA
    AND P.NROEMPRESAPEDVENDA = MV.NROEMPRESA
LEFT JOIN MLO_CARGAECLIPROD CP
    ON MV.NROCARGA = CP.NROCARGA
    AND A.SEQPRODUTO = CP.SEQPRODUTO
    AND MV.SEQPESSOA = CP.SEQPESSOA
    AND CP.NROEMPRESA = 15
LEFT JOIN MLO_CARGAECOLETOR CC
    ON CP.NROCARGA = CC.NROCARGA
    AND CP.CODDEPOSSEPAR = CC.CODDEPOSSEPAR
    AND CP.SEQLOTE = CC.SEQLOTE
    AND CP.NROQUEBRA = CC.NROQUEBRA
    AND CP.NROPEDVENDA = CC.NROPEDVENDA
    AND CP.SEQPRODUTO = CC.SEQPRODUTO
    AND CP.CODDEPOSITANTE = CC.CODDEPOSITANTE
    AND CP.QTDEMBALAGEM = CC.QTDEMBALAGEM
    AND CP.NROEMPRESA = CC.NROEMPRESA
LEFT JOIN (
    SELECT
        A.NROCARGA,
        A.CODDEPOSSEPAR,
        A.SEQLOTE,
        A.NROQUEBRA,
        A.NROEMPRESA,
        MAX(T.DTAHORFIMTAREFA) AS DTAHORFIMTAREFA,
        MAX(P.NOMEREDUZ) KEEP (DENSE_RANK LAST ORDER BY T.DTAHORFIMTAREFA) AS USUARIO_CONFERENCIA
    FROM MLO_ATIVIDADE A
    INNER JOIN MLO_TAREFA T
        ON A.MESANO = T.MESANO
       AND A.SEQTAREFA = T.SEQTAREFA
       AND A.NROEMPRESA = T.NROEMPRESA
    LEFT JOIN MLO_TAREFAPRODUT TP
        ON T.MESANO = TP.MESANO
       AND T.SEQTAREFA = TP.SEQTAREFA
       AND T.NROEMPRESA = TP.NROEMPRESA
    LEFT JOIN MLO_PRODUTIVO P
        ON TP.CODPRODUTIVO = P.CODPRODUTIVO
       AND TP.NROEMPRESA = P.NROEMPRESA
    WHERE A.CODTIPATIVIDADE = 'CS'
      AND A.INDEXCLUSAO = 'N'
    GROUP BY
        A.NROCARGA,
        A.CODDEPOSSEPAR,
        A.SEQLOTE,
        A.NROQUEBRA,
        A.NROEMPRESA
) ATV
    ON CC.NROCARGA = ATV.NROCARGA
    AND CC.CODDEPOSSEPAR = ATV.CODDEPOSSEPAR
    AND CC.SEQLOTE = ATV.SEQLOTE
    AND CC.NROQUEBRA = ATV.NROQUEBRA
    AND CC.NROEMPRESA = ATV.NROEMPRESA
GROUP BY
    A.NROEMPRESA,
    A.NROEMPDESTINO,
    A.SEQPRODUTO,
    B.DESCCOMPLETA,
    NVL(DEP.DEPARTAMENTO, 'SEM DEPARTAMENTO'),
    A.NROPEDIDOSUPRIM,
    TRUNC(A.DTAEMISSAO),
    P.NROEMPRESAPEDVENDA,
    P.NROPEDVENDA,
    CP.NROPEDVENDA,
    CC.NROPEDVENDA,
    MV.NROCARGA,
    A.QTDEMBALAGEM,
    A.QUANTIDADE_A_EXPEDIR,
    TRUNC(ATV.DTAHORFIMTAREFA),
    ATV.USUARIO_CONFERENCIA
ORDER BY
    TRUNC(A.DTAEMISSAO),
    A.NROEMPDESTINO,
    A.NROPEDIDOSUPRIM