SELECT * FROM (
    SELECT 
        A.NROEMPRESA,
        A.NUMERONF,
        A.SEQPESSOA,
        (SELECT P.FANTASIA FROM GE_PESSOA P WHERE P.SEQPESSOA = A.SEQPESSOA) AS FORNECEDOR,
        A.CODGERALOPER AS CGO_CABECALHO,
        I.CFOP,
        I.CFOPORIGEM,
        I.CFOPESCRIT,
        I.SEQPRODUTO,
        A.DTAEMISSAO
    FROM MLFV_NFENTRADA A
    JOIN MLF_NFITEM I ON I.NROEMPRESA = A.NROEMPRESA 
                      AND I.NUMERONF = A.NUMERONF 
                      AND I.SERIENF = A.SERIENF
    WHERE I.CFOP IN (5910, 6910)
       OR I.CFOPORIGEM IN (5910, 6910)
       OR I.CFOPESCRIT IN (5910, 6910)
    ORDER BY A.DTAEMISSAO DESC
) WHERE ROWNUM <= 100;
