SELECT
    P.SEQPESSOA AS CODIGO_FORNECEDOR,
    P.NOMERAZAO AS RAZAO_SOCIAL,
    NVL(P.FANTASIA, P.NOMERAZAO) AS DESCRICAO_FORNECEDOR,
    REGEXP_REPLACE(NVL(P.NROCGCCPF, ''), '[^0-9]', '') AS CNPJ
FROM GE_PESSOA P
WHERE P.SEQPESSOA IS NOT NULL
  AND P.NOMERAZAO IS NOT NULL
  AND P.NROCGCCPF IS NOT NULL
  AND LENGTH(REGEXP_REPLACE(NVL(P.NROCGCCPF, ''), '[^0-9]', '')) = 14
ORDER BY
    P.SEQPESSOA,
    P.NOMERAZAO,
    CNPJ