SELECT
    C.OWNER,
    C.TABLE_NAME,
    C.COLUMN_NAME,
    C.DATA_TYPE,
    C.DATA_LENGTH
FROM ALL_TAB_COLUMNS C
WHERE C.OWNER = USER
  AND (
      C.COLUMN_NAME LIKE 'NROPED%'
      OR C.COLUMN_NAME LIKE '%PEDIDO%'
      OR C.COLUMN_NAME LIKE '%SUPRIM%'
      OR C.COLUMN_NAME LIKE '%RECEB%'
  )
  AND (
      C.TABLE_NAME LIKE 'MAC%'
      OR C.TABLE_NAME LIKE 'MAD%'
      OR C.TABLE_NAME LIKE 'MSU%'
      OR C.TABLE_NAME LIKE 'MLO%'
      OR C.TABLE_NAME LIKE 'MAXV%'
      OR C.TABLE_NAME LIKE 'MLF%'
      OR C.TABLE_NAME LIKE 'MFL%'
  )
ORDER BY
    C.TABLE_NAME,
    C.COLUMN_NAME
