SELECT
    'MAD_JUNCAOPEDCLIENTEPALETE' AS FONTE,
    J.NROPEDORIGEM AS PEDIDO_ORIGEM,
    J.NROPEDGERADO AS PEDIDO_GERADO,
    J.NROPEDSUPRIM AS PEDIDO_SUPRIMENTO,
    NULL AS DATA_REFERENCIA,
    J.QTDPEDIDO AS QTDE_REFERENCIA,
    NULL AS PEDIDO_FORNECEDOR
FROM MAD_JUNCAOPEDCLIENTEPALETE J
WHERE J.NROPEDORIGEM IN (31339, 31342)
   OR J.NROPEDGERADO IN (31339, 31342)
   OR J.NROPEDSUPRIM IN (31339, 31342)

UNION ALL

SELECT
    'MACX_IMPABASTECIMENTO' AS FONTE,
    TO_NUMBER(I.NROPEDORIGEM) AS PEDIDO_ORIGEM,
    I.NROPEDGERADO AS PEDIDO_GERADO,
    NULL AS PEDIDO_SUPRIMENTO,
    TO_CHAR(TRUNC(I.DTAPROCPEDIDO), 'DD/MM/YYYY') AS DATA_REFERENCIA,
    NULL AS QTDE_REFERENCIA,
    NULL AS PEDIDO_FORNECEDOR
FROM MACX_IMPABASTECIMENTO I
WHERE REGEXP_LIKE(I.NROPEDORIGEM, '^[0-9]+$')
  AND (TO_NUMBER(I.NROPEDORIGEM) IN (31339, 31342) OR I.NROPEDGERADO IN (31339, 31342))

UNION ALL

SELECT
    'MAC_GERCOMPRAPED' AS FONTE,
    NULL AS PEDIDO_ORIGEM,
    G.NROPEDIDO AS PEDIDO_GERADO,
    NULL AS PEDIDO_SUPRIMENTO,
    TO_CHAR(TRUNC(G.DTARECEBIMENTO), 'DD/MM/YYYY') AS DATA_REFERENCIA,
    NULL AS QTDE_REFERENCIA,
    NULL AS PEDIDO_FORNECEDOR
FROM MAC_GERCOMPRAPED G
WHERE G.NROPEDIDO IN (31339, 31342)

UNION ALL

SELECT
    'MAC_GERCOMPRAITEMPED' AS FONTE,
    NULL AS PEDIDO_ORIGEM,
    G.NROPEDIDO AS PEDIDO_GERADO,
    NULL AS PEDIDO_SUPRIMENTO,
    TO_CHAR(TRUNC(G.DTALIMRECEBTO), 'DD/MM/YYYY') AS DATA_REFERENCIA,
    NULL AS QTDE_REFERENCIA,
    NULL AS PEDIDO_FORNECEDOR
FROM MAC_GERCOMPRAITEMPED G
WHERE G.NROPEDIDO IN (31339, 31342)

UNION ALL

SELECT
    'MACV_PSITEMRECEBER' AS FONTE,
    NULL AS PEDIDO_ORIGEM,
    R.NROPEDFORNECEDORNUM AS PEDIDO_GERADO,
    R.NROPEDIDOSUPRIM AS PEDIDO_SUPRIMENTO,
    TO_CHAR(TRUNC(R.DTARECEBTOPED), 'DD/MM/YYYY') AS DATA_REFERENCIA,
    R.QTDRECEBIDA AS QTDE_REFERENCIA,
    R.NROPEDFORNECEDOR AS PEDIDO_FORNECEDOR
FROM MACV_PSITEMRECEBER R
WHERE R.NROPEDIDOSUPRIM IN (31339, 31342)
   OR R.NROPEDFORNECEDORNUM IN (31339, 31342)

UNION ALL

SELECT
    'MACV_PSITEMEXPEDIR' AS FONTE,
    NULL AS PEDIDO_ORIGEM,
    E.NROPEDFORNECEDORNUM AS PEDIDO_GERADO,
    E.NROPEDIDOSUPRIM AS PEDIDO_SUPRIMENTO,
    TO_CHAR(TRUNC(E.DTARECEBTO), 'DD/MM/YYYY') AS DATA_REFERENCIA,
    NULL AS QTDE_REFERENCIA,
    E.NROPEDFORNECEDOR AS PEDIDO_FORNECEDOR
FROM MACV_PSITEMEXPEDIR E
WHERE E.NROPEDIDOSUPRIM IN (31339, 31342)
   OR E.NROPEDFORNECEDORNUM IN (31339, 31342)

UNION ALL

SELECT
    'MAD_PEDVENDACONTROL' AS FONTE,
    C.NROPEDVENDAORIG AS PEDIDO_ORIGEM,
    C.NROPEDVENDANOVO AS PEDIDO_GERADO,
    C.NROPEDEXPEDIR AS PEDIDO_SUPRIMENTO,
    NULL AS DATA_REFERENCIA,
    NULL AS QTDE_REFERENCIA,
    NULL AS PEDIDO_FORNECEDOR
FROM MAD_PEDVENDACONTROL C
WHERE C.NROPEDEXPEDIR IN (31339, 31342)
   OR C.NROPEDVENDAANT IN (31339, 31342)
   OR C.NROPEDVENDANOVO IN (31339, 31342)
   OR C.NROPEDVENDAORIG IN (31339, 31342)

ORDER BY
    FONTE,
    PEDIDO_SUPRIMENTO,
    PEDIDO_ORIGEM,
    PEDIDO_GERADO
