SELECT
    'MAXV_MSUPEDIDOSUPRIMEXP' AS FONTE,
    X.NROEMPRESA,
    X.NROEMPDESTINO,
    X.SEQPRODUTO,
    X.NROPEDIDOSUPRIM,
    TO_CHAR(TRUNC(X.DTAEMISSAO), 'DD/MM/YYYY') AS DATA_EMISSAO,
    X.QTDEMBALAGEM,
    X.QTDSOLICITADA,
    X.QTDEXPCANC
FROM MAXV_MSUPEDIDOSUPRIMEXP X
WHERE X.DTAEMISSAO >= TO_DATE('01/03/2026', 'DD/MM/YYYY')
  AND X.SEQPRODUTO = 1679
  AND X.NROPEDIDOSUPRIM IN (31339, 31342)

UNION ALL

SELECT
    'MSU_PSITEMEXPEDIDO' AS FONTE,
    P.NROEMPRESA,
    P.NROEMPRESAPEDVENDA AS NROEMPDESTINO,
    P.SEQPRODUTO,
    P.NROPEDIDOSUPRIM,
    NULL AS DATA_EMISSAO,
    NULL AS QTDEMBALAGEM,
    NULL AS QTDSOLICITADA,
    NULL AS QTDEXPCANC
FROM MSU_PSITEMEXPEDIDO P
WHERE P.SEQPRODUTO = 1679
  AND (
      P.NROPEDIDOSUPRIM IN (31339, 31342)
      OR P.NROPEDVENDA IN (31339, 31342)
  )
ORDER BY
    FONTE,
    NROEMPRESA,
    NROEMPDESTINO,
    NROPEDIDOSUPRIM
