SELECT DISTINCT
    G.SEQPESSOA AS CODIGO_FORNECEDOR,
    G.NOMERAZAO AS DESCRICAO_FORNECEDOR,
    C.COMPRADOR,
    MFD.PZOPAGAMENTO AS PRAZO_PAGAMENTO_CADASTRO,
    MFD.PZOMEDENTREGA AS PRAZO_MEDIO_ENTREGA_DIAS,
    DECODE(MFD.INDPZOPAGAMENTO, 
        'F', 'Faturamento', 
        'V', 'A Vista', 
        'A', 'Antecipado', 
        'C', 'Contra Apresentacao', 
        MFD.INDPZOPAGAMENTO) AS FORMA_PAGAMENTO,
    FPDEV.FORMAPAGTO AS FORMA_DEVOLUCAO,
    CPDEV.DESCCONDICAOPAGTO AS CONDICAO_DEVOLUCAO
FROM GE_PESSOA G
INNER JOIN MAP_FAMFORNEC FF 
    ON FF.SEQFORNECEDOR = G.SEQPESSOA
INNER JOIN MAP_FAMDIVISAO FD 
    ON FD.SEQFAMILIA = FF.SEQFAMILIA
INNER JOIN MAX_COMPRADOR C 
    ON C.SEQCOMPRADOR = FD.SEQCOMPRADOR
LEFT JOIN MAF_FORNECDIVISAO MFD 
    ON MFD.SEQFORNECEDOR = FF.SEQFORNECEDOR 
   AND MFD.NRODIVISAO = FD.NRODIVISAO
LEFT JOIN MRL_FORMAPAGTO FPDEV 
    ON FPDEV.NROFORMAPAGTO = MFD.NROFORMAPAGTODEV
LEFT JOIN MAD_CONDICAOPAGTO CPDEV 
    ON CPDEV.NROCONDICAOPAGTO = MFD.NROCONDPAGDEV
WHERE (
    EXISTS (
        SELECT 1
        FROM MRL_PRODUTOEMPRESA PE
        INNER JOIN MAP_PRODUTO P ON P.SEQPRODUTO = PE.SEQPRODUTO
        WHERE P.SEQFAMILIA = FF.SEQFAMILIA
          AND PE.DTAULTCOMPRA >= TRUNC(SYSDATE, 'YYYY')
    )
    OR EXISTS (
        SELECT 1
        FROM MLF_NOTAFISCAL NF
        WHERE NF.SEQPESSOA = G.SEQPESSOA
          AND NF.DTAENTRADA >= TRUNC(SYSDATE, 'YYYY')
          AND NF.TIPNOTAFISCAL = 'E'
          AND NF.STATUSNF != 'C'
    )
)
AND (:NR1 = 0 OR G.SEQPESSOA = TO_NUMBER(:NR1))
ORDER BY G.NOMERAZAO;
