SELECT
    X.FONTE,
    X.SEQCONSULTA,
    X.SEQPRODUTO,
    X.DESCRICAO_PRODUTO,
    X.MARGEMCADASTRO,
    X.RN_FONTE,
    X.IND_MARGEM_VALIDA
FROM (
    SELECT
        'MBI_TABCDISTRIB' AS FONTE,
        D.SEQCONSULTA,
        D.SEQDETALHE2 AS SEQPRODUTO,
        P.DESCCOMPLETA AS DESCRICAO_PRODUTO,
        NVL(D.MARGEMCADASTRO, 0) AS MARGEMCADASTRO,
        ROW_NUMBER() OVER (
            PARTITION BY D.SEQDETALHE2
            ORDER BY D.SEQCONSULTA DESC
        ) AS RN_FONTE,
        CASE WHEN NVL(D.MARGEMCADASTRO, 0) > 0 THEN 'S' ELSE 'N' END AS IND_MARGEM_VALIDA
    FROM MBI_TABCDISTRIB D
    INNER JOIN MAP_PRODUTO P ON P.SEQPRODUTO = D.SEQDETALHE2
    WHERE D.SEQDETALHE2 = 12278

    UNION ALL

    SELECT
        'MBI_TABCESTOQUE' AS FONTE,
        E.SEQCONSULTA,
        E.SEQDETALHE2 AS SEQPRODUTO,
        P.DESCCOMPLETA AS DESCRICAO_PRODUTO,
        NVL(E.MARGEMCADASTRO, 0) AS MARGEMCADASTRO,
        ROW_NUMBER() OVER (
            PARTITION BY E.SEQDETALHE2
            ORDER BY E.SEQCONSULTA DESC
        ) AS RN_FONTE,
        CASE WHEN NVL(E.MARGEMCADASTRO, 0) > 0 THEN 'S' ELSE 'N' END AS IND_MARGEM_VALIDA
    FROM MBI_TABCESTOQUE E
    INNER JOIN MAP_PRODUTO P ON P.SEQPRODUTO = E.SEQDETALHE2
    WHERE E.SEQDETALHE2 = 12278
) X
ORDER BY X.FONTE, X.SEQCONSULTA DESC