SELECT
    T.OWNER,
    T.TABLE_NAME,
    T.NUM_ROWS,
    T.LAST_ANALYZED,
    'TABLE' AS TIPO_OBJETO
FROM ALL_TABLES T
WHERE (
        T.OWNER = USER
        OR T.OWNER LIKE 'CONSINCO%'
      )
  AND (
        T.TABLE_NAME LIKE 'MLO%'
        OR T.TABLE_NAME LIKE 'WMS%'
        OR T.TABLE_NAME LIKE 'WMSV%'
      )
ORDER BY
    T.OWNER,
    T.TABLE_NAME;

SELECT
    V.OWNER,
    V.VIEW_NAME AS TABLE_NAME,
    NULL AS NUM_ROWS,
    NULL AS LAST_ANALYZED,
    'VIEW' AS TIPO_OBJETO
FROM ALL_VIEWS V
WHERE (
        V.OWNER = USER
        OR V.OWNER LIKE 'CONSINCO%'
      )
  AND (
        V.VIEW_NAME LIKE 'MLO%'
        OR V.VIEW_NAME LIKE 'WMS%'
        OR V.VIEW_NAME LIKE 'WMSV%'
      )
ORDER BY
    V.OWNER,
    V.VIEW_NAME;

SELECT
    C.OWNER,
    C.TABLE_NAME,
    C.COLUMN_NAME,
    C.DATA_TYPE,
    C.DATA_LENGTH
FROM ALL_TAB_COLUMNS C
WHERE (
        C.OWNER = USER
        OR C.OWNER LIKE 'CONSINCO%'
      )
  AND (
        C.TABLE_NAME LIKE 'MLO%'
        OR C.TABLE_NAME LIKE 'WMS%'
        OR C.TABLE_NAME LIKE 'WMSV%'
      )
  AND (
        C.COLUMN_NAME LIKE '%NROCARGA%'
        OR C.COLUMN_NAME LIKE '%NROPED%'
        OR C.COLUMN_NAME LIKE '%SEQPRODUTO%'
        OR C.COLUMN_NAME LIKE '%NROEMPRESA%'
        OR C.COLUMN_NAME LIKE '%CODDEPOSSEPAR%'
        OR C.COLUMN_NAME LIKE '%SEQLOTE%'
        OR C.COLUMN_NAME LIKE '%NROQUEBRA%'
        OR C.COLUMN_NAME LIKE '%SEQPESSOA%'
        OR C.COLUMN_NAME LIKE '%NROFORN%'
        OR C.COLUMN_NAME LIKE '%RECEB%'
      )
ORDER BY
    C.OWNER,
    C.TABLE_NAME,
    C.COLUMN_NAME;

SELECT
    C.OWNER,
    C.TABLE_NAME,
    SUM(CASE WHEN C.COLUMN_NAME LIKE '%NROCARGA%' THEN 1 ELSE 0 END) AS TEM_NROCARGA,
    SUM(CASE WHEN C.COLUMN_NAME LIKE '%NROPED%' THEN 1 ELSE 0 END) AS TEM_NROPED,
    SUM(CASE WHEN C.COLUMN_NAME LIKE '%SEQPRODUTO%' THEN 1 ELSE 0 END) AS TEM_SEQPRODUTO,
    SUM(CASE WHEN C.COLUMN_NAME LIKE '%NROEMPRESA%' THEN 1 ELSE 0 END) AS TEM_NROEMPRESA,
    SUM(CASE WHEN C.COLUMN_NAME LIKE '%CODDEPOSSEPAR%' THEN 1 ELSE 0 END) AS TEM_CODDEPOSSEPAR,
    SUM(CASE WHEN C.COLUMN_NAME LIKE '%SEQLOTE%' THEN 1 ELSE 0 END) AS TEM_SEQLOTE,
    SUM(CASE WHEN C.COLUMN_NAME LIKE '%NROQUEBRA%' THEN 1 ELSE 0 END) AS TEM_NROQUEBRA,
    SUM(CASE WHEN C.COLUMN_NAME LIKE '%SEQPESSOA%' THEN 1 ELSE 0 END) AS TEM_SEQPESSOA,
    SUM(CASE WHEN C.COLUMN_NAME LIKE '%RECEB%' THEN 1 ELSE 0 END) AS TEM_RECEB,
    SUM(CASE WHEN C.COLUMN_NAME LIKE '%NROFORN%' THEN 1 ELSE 0 END) AS TEM_FORNECEDOR,
    COUNT(*) AS QTDE_COLUNAS_TOTAL,
    (
        SUM(CASE WHEN C.COLUMN_NAME LIKE '%NROCARGA%' THEN 1 ELSE 0 END)
      + SUM(CASE WHEN C.COLUMN_NAME LIKE '%NROPED%' THEN 1 ELSE 0 END)
      + SUM(CASE WHEN C.COLUMN_NAME LIKE '%SEQPRODUTO%' THEN 1 ELSE 0 END)
      + SUM(CASE WHEN C.COLUMN_NAME LIKE '%NROEMPRESA%' THEN 1 ELSE 0 END)
      + SUM(CASE WHEN C.COLUMN_NAME LIKE '%CODDEPOSSEPAR%' THEN 1 ELSE 0 END)
      + SUM(CASE WHEN C.COLUMN_NAME LIKE '%SEQLOTE%' THEN 1 ELSE 0 END)
      + SUM(CASE WHEN C.COLUMN_NAME LIKE '%NROQUEBRA%' THEN 1 ELSE 0 END)
      + SUM(CASE WHEN C.COLUMN_NAME LIKE '%SEQPESSOA%' THEN 1 ELSE 0 END)
      + SUM(CASE WHEN C.COLUMN_NAME LIKE '%RECEB%' THEN 1 ELSE 0 END)
      + SUM(CASE WHEN C.COLUMN_NAME LIKE '%NROFORN%' THEN 1 ELSE 0 END)
    ) AS SCORE_RELACIONAMENTO
FROM ALL_TAB_COLUMNS C
WHERE (
        C.OWNER = USER
        OR C.OWNER LIKE 'CONSINCO%'
      )
  AND (
        C.TABLE_NAME LIKE 'MLO%'
        OR C.TABLE_NAME LIKE 'WMS%'
        OR C.TABLE_NAME LIKE 'WMSV%'
      )
GROUP BY
    C.OWNER,
    C.TABLE_NAME
HAVING (
        SUM(CASE WHEN C.COLUMN_NAME LIKE '%NROCARGA%' THEN 1 ELSE 0 END)
      + SUM(CASE WHEN C.COLUMN_NAME LIKE '%NROPED%' THEN 1 ELSE 0 END)
      + SUM(CASE WHEN C.COLUMN_NAME LIKE '%SEQPRODUTO%' THEN 1 ELSE 0 END)
      + SUM(CASE WHEN C.COLUMN_NAME LIKE '%NROEMPRESA%' THEN 1 ELSE 0 END)
      + SUM(CASE WHEN C.COLUMN_NAME LIKE '%CODDEPOSSEPAR%' THEN 1 ELSE 0 END)
      + SUM(CASE WHEN C.COLUMN_NAME LIKE '%SEQLOTE%' THEN 1 ELSE 0 END)
      + SUM(CASE WHEN C.COLUMN_NAME LIKE '%NROQUEBRA%' THEN 1 ELSE 0 END)
      + SUM(CASE WHEN C.COLUMN_NAME LIKE '%SEQPESSOA%' THEN 1 ELSE 0 END)
      + SUM(CASE WHEN C.COLUMN_NAME LIKE '%RECEB%' THEN 1 ELSE 0 END)
      + SUM(CASE WHEN C.COLUMN_NAME LIKE '%NROFORN%' THEN 1 ELSE 0 END)
      ) >= 2
ORDER BY
    SCORE_RELACIONAMENTO DESC,
    C.OWNER,
    C.TABLE_NAME;