SELECT
    'MLO_PEDVENDA' AS FONTE,
    P.NROEMPRESA,
    P.NROPEDVENDA,
    NULL AS NROCARGA,
    NULL AS SEQPRODUTO,
    NULL AS NRONF,
    NULL AS SERIENF,
    NULL AS NRODOCUMENTO,
    NULL AS OBS_RELACAO
FROM MLO_PEDVENDA P
WHERE P.NROPEDVENDA = 56123

UNION ALL

SELECT
    'MLO_PEDVENDAITEM' AS FONTE,
    I.NROEMPRESA,
    I.NROPEDVENDA,
    NULL AS NROCARGA,
    I.SEQPRODUTO,
    NULL AS NRONF,
    NULL AS SERIENF,
    NULL AS NRODOCUMENTO,
    NULL AS OBS_RELACAO
FROM MLO_PEDVENDAITEM I
WHERE I.NROPEDVENDA = 56123

UNION ALL

SELECT
    'MLO_CARGAECLIPROD' AS FONTE,
    C.NROEMPRESA,
    C.NROPEDVENDA,
    C.NROCARGA,
    C.SEQPRODUTO,
    NULL AS NRONF,
    NULL AS SERIENF,
    NULL AS NRODOCUMENTO,
    'Item da carga por pedido de venda' AS OBS_RELACAO
FROM MLO_CARGAECLIPROD C
WHERE C.NROPEDVENDA = 56123

UNION ALL

SELECT
    'MLO_CARGAECOLETOR' AS FONTE,
    C.NROEMPRESA,
    C.NROPEDVENDA,
    C.NROCARGA,
    C.SEQPRODUTO,
    NULL AS NRONF,
    NULL AS SERIENF,
    NULL AS NRODOCUMENTO,
    'Coletor da carga por pedido de venda' AS OBS_RELACAO
FROM MLO_CARGAECOLETOR C
WHERE C.NROPEDVENDA = 56123

UNION ALL

SELECT
    'MLO_CARGAEXPED' AS FONTE,
    E.NROEMPRESA,
    NULL AS NROPEDVENDA,
    E.NROCARGA,
    NULL AS SEQPRODUTO,
    NULL AS NRONF,
    NULL AS SERIENF,
    NULL AS NRODOCUMENTO,
    'Cabecalho da carga de expedicao' AS OBS_RELACAO
FROM MLO_CARGAEXPED E
WHERE E.NROCARGA IN (
    SELECT DISTINCT C.NROCARGA
    FROM MLO_CARGAECLIPROD C
    WHERE C.NROPEDVENDA = 56123
)

UNION ALL

SELECT
    'MLO_CARREGAMENTO' AS FONTE,
    R.NROEMPRESA,
    NULL AS NROPEDVENDA,
    R.NROCARGA,
    NULL AS SEQPRODUTO,
    NULL AS NRONF,
    NULL AS SERIENF,
    NULL AS NRODOCUMENTO,
    'Evento/registro de carregamento' AS OBS_RELACAO
FROM MLO_CARREGAMENTO R
WHERE R.NROCARGA IN (
    SELECT DISTINCT C.NROCARGA
    FROM MLO_CARGAECLIPROD C
    WHERE C.NROPEDVENDA = 56123
)

UNION ALL

SELECT
    'MLO_NOTAFISCAL' AS FONTE,
    N.NROEMPRESA,
    NULL AS NROPEDVENDA,
    N.NROCARGA,
    NULL AS SEQPRODUTO,
    NULL AS NRONF,
    NULL AS SERIENF,
    TO_CHAR(N.ROWID) AS NRODOCUMENTO,
    'NF vinculada a carga' AS OBS_RELACAO
FROM MLO_NOTAFISCAL N
WHERE N.NROCARGA IN (
    SELECT DISTINCT C.NROCARGA
    FROM MLO_CARGAECLIPROD C
    WHERE C.NROPEDVENDA = 56123
)

UNION ALL

SELECT
    'MLO_NFITEM' AS FONTE,
    I.NROEMPRESA,
    NULL AS NROPEDVENDA,
    NULL AS NROCARGA,
    I.SEQPRODUTO,
    NULL AS NRONF,
    NULL AS SERIENF,
    TO_CHAR(I.ROWID) AS NRODOCUMENTO,
    'Itens da NF para produtos do pedido' AS OBS_RELACAO
FROM MLO_NFITEM I
WHERE I.SEQPRODUTO IN (
    SELECT DISTINCT X.SEQPRODUTO
    FROM MSU_PSITEMEXPEDIDO X
    WHERE X.NROPEDVENDA = 56123
)

UNION ALL

SELECT
    'MLO_CARGARECEB' AS FONTE,
    R.NROEMPRESA,
    NULL AS NROPEDVENDA,
    R.NROCARGA,
    NULL AS SEQPRODUTO,
    NULL AS NRONF,
    NULL AS SERIENF,
    NULL AS NRODOCUMENTO,
    'Carga de recebimento (possivel elo loja)' AS OBS_RELACAO
FROM MLO_CARGARECEB R
WHERE R.NROCARGA IN (
    SELECT DISTINCT C.NROCARGA
    FROM MLO_CARGAECLIPROD C
    WHERE C.NROPEDVENDA = 56123
)

UNION ALL

SELECT
    'MLO_CARGARECPROD' AS FONTE,
    R.NROEMPRESA,
    NULL AS NROPEDVENDA,
    R.NROCARGA,
    R.SEQPRODUTO,
    NULL AS NRONF,
    NULL AS SERIENF,
    NULL AS NRODOCUMENTO,
    'Produto da carga de recebimento' AS OBS_RELACAO
FROM MLO_CARGARECPROD R
WHERE R.NROCARGA IN (
    SELECT DISTINCT C.NROCARGA
    FROM MLO_CARGAECLIPROD C
    WHERE C.NROPEDVENDA = 56123
)

UNION ALL

SELECT
    'WMSV_RECEBIMENTOSINTETICO' AS FONTE,
    R.NROEMPRESA,
    NULL AS NROPEDVENDA,
    R.NROCARGA,
    NULL AS SEQPRODUTO,
    NULL AS NRONF,
    NULL AS SERIENF,
    NULL AS NRODOCUMENTO,
    'Resumo de recebimento WMS' AS OBS_RELACAO
FROM WMSV_RECEBIMENTOSINTETICO R
WHERE R.NROCARGA IN (
    SELECT DISTINCT C.NROCARGA
    FROM MLO_CARGAECLIPROD C
    WHERE C.NROPEDVENDA = 56123
)

UNION ALL

SELECT
    'WMSV_RECEBIMENTOSINTETICOITENS' AS FONTE,
    R.NROEMPRESA,
    NULL AS NROPEDVENDA,
    R.NROCARGA,
    R.SEQPRODUTO,
    NULL AS NRONF,
    NULL AS SERIENF,
    NULL AS NRODOCUMENTO,
    'Itens de recebimento WMS' AS OBS_RELACAO
FROM WMSV_RECEBIMENTOSINTETICOITENS R
WHERE R.NROCARGA IN (
    SELECT DISTINCT C.NROCARGA
    FROM MLO_CARGAECLIPROD C
    WHERE C.NROPEDVENDA = 56123
)

ORDER BY
    FONTE,
    NROEMPRESA,
    NROPEDVENDA,
    NROCARGA,
    SEQPRODUTO;