SELECT 
    I.NUMERONF,
    I.SEQPRODUTO,
    P.DESCCOMPLETA AS PRODUTO,
    -- Fornecedor que emitiu a nota (O que está no cabeçalho da NF)
    A.SEQPESSOA AS FORN_NOTA_COD,
    (SELECT F1.FANTASIA FROM GE_PESSOA F1 WHERE F1.SEQPESSOA = A.SEQPESSOA) AS FORN_NOTA_NOME,
    -- Fornecedor Principal do Produto (O que o relatório ABC usa)
    FF.SEQFORNECEDOR AS FORN_PRINCIPAL_COD,
    (SELECT F2.FANTASIA FROM GE_PESSOA F2 WHERE F2.SEQPESSOA = FF.SEQFORNECEDOR) AS FORN_PRINCIPAL_NOME
FROM MLF_NOTAFISCAL A
JOIN MLF_NFITEM I ON I.NUMERONF = A.NUMERONF 
                 AND I.SERIENF = A.SERIENF 
                 AND I.NROEMPRESA = A.NROEMPRESA 
                 AND I.TIPNOTAFISCAL = A.TIPNOTAFISCAL
                 AND NVL(A.SEQNF,0) = NVL(I.SEQNF,NVL(A.SEQNF,0))
JOIN MAP_PRODUTO P ON P.SEQPRODUTO = I.SEQPRODUTO
-- Busca o fornecedor principal da família do produto
LEFT JOIN MAP_FAMFORNEC FF ON FF.SEQFAMILIA = P.SEQFAMILIA AND FF.PRINCIPAL = 'S'
WHERE A.NUMERONF IN (916725, 174296)
  AND A.TIPNOTAFISCAL = 'E'
ORDER BY A.NUMERONF, I.SEQPRODUTO;
