SELECT 'MAC_GERCOMPRAPED' AS FONTE, NROPEDIDO AS NUMERO, TO_CHAR(TRUNC(DTARECEBIMENTO), 'DD/MM/YYYY') AS DATA_REF
FROM MAC_GERCOMPRAPED
WHERE NROPEDIDO = 31342

UNION ALL

SELECT 'MAC_GERCOMPRAITEMPED' AS FONTE, NROPEDIDO AS NUMERO, TO_CHAR(TRUNC(DTALIMRECEBTO), 'DD/MM/YYYY') AS DATA_REF
FROM MAC_GERCOMPRAITEMPED
WHERE NROPEDIDO = 31342

UNION ALL

SELECT 'MACV_PSITEMRECEBER_NROFORN' AS FONTE, NROPEDFORNECEDORNUM AS NUMERO, TO_CHAR(TRUNC(DTARECEBTOPED), 'DD/MM/YYYY') AS DATA_REF
FROM MACV_PSITEMRECEBER
WHERE NROPEDFORNECEDORNUM = 31342

UNION ALL

SELECT 'MACX_IMPABASTECIMENTO_GERADO' AS FONTE, NROPEDGERADO AS NUMERO, TO_CHAR(TRUNC(DTAPROCPEDIDO), 'DD/MM/YYYY') AS DATA_REF
FROM MACX_IMPABASTECIMENTO
WHERE NROPEDGERADO = 31342

UNION ALL

SELECT 'MAD_JUNCAOPEDCLIENTEPALETE_GERADO' AS FONTE, NROPEDGERADO AS NUMERO, NULL AS DATA_REF
FROM MAD_JUNCAOPEDCLIENTEPALETE
WHERE NROPEDGERADO = 31342
