SELECT
    C.OWNER,
    C.TABLE_NAME,
    C.COLUMN_NAME,
    C.DATA_TYPE,
    C.DATA_LENGTH
FROM ALL_TAB_COLUMNS C
WHERE (
        C.OWNER = USER
        OR C.OWNER LIKE 'CONSINCO%'
      )
  AND (
        C.TABLE_NAME LIKE 'MAC%'
        OR C.TABLE_NAME LIKE 'MAD%'
        OR C.TABLE_NAME LIKE 'MSU%'
        OR C.TABLE_NAME LIKE 'MLO%'
      )
  AND (
        C.COLUMN_NAME LIKE '%RECEB%'
        OR C.COLUMN_NAME LIKE '%PED%'
        OR C.COLUMN_NAME LIKE 'NROPED%'
      )
ORDER BY
    C.OWNER,
    C.TABLE_NAME,
    C.COLUMN_NAME;
SELECT
    'MSU_PSITEMEXPEDIDO' AS FONTE,
    P.NROEMPRESA,
    NULL AS NROEMPDESTINO,
    P.SEQPRODUTO,
    P.NROPEDIDOSUPRIM,
    P.NROEMPRESAPEDVENDA,
    P.NROPEDVENDA,
    NULL AS NROPEDFORNECEDORNUM,
    NULL AS NROPEDFORNECEDOR
FROM MSU_PSITEMEXPEDIDO P
WHERE P.NROPEDVENDA = 56123

UNION ALL

SELECT
    'MAD_PEDVENDA' AS FONTE,
    M.NROEMPRESA,
    NULL AS NROEMPDESTINO,
    NULL AS SEQPRODUTO,
    NULL AS NROPEDIDOSUPRIM,
    M.NROEMPRESA AS NROEMPRESAPEDVENDA,
    M.NROPEDVENDA,
    NULL AS NROPEDFORNECEDORNUM,
    NULL AS NROPEDFORNECEDOR
FROM MAD_PEDVENDA M
WHERE M.NROPEDVENDA = 56123

UNION ALL

SELECT
    'MLO_CARGAECLIPROD' AS FONTE,
    C.NROEMPRESA,
    NULL AS NROEMPDESTINO,
    C.SEQPRODUTO,
    NULL AS NROPEDIDOSUPRIM,
    NULL AS NROEMPRESAPEDVENDA,
    C.NROPEDVENDA,
    NULL AS NROPEDFORNECEDORNUM,
    TO_CHAR(C.NROCARGA) AS NROPEDFORNECEDOR
FROM MLO_CARGAECLIPROD C
WHERE C.NROPEDVENDA = 56123

UNION ALL

SELECT
    'MLO_CARGAECOLETOR' AS FONTE,
    C.NROEMPRESA,
    NULL AS NROEMPDESTINO,
    C.SEQPRODUTO,
    NULL AS NROPEDIDOSUPRIM,
    NULL AS NROEMPRESAPEDVENDA,
    C.NROPEDVENDA,
    NULL AS NROPEDFORNECEDORNUM,
    TO_CHAR(C.NROCARGA) AS NROPEDFORNECEDOR
FROM MLO_CARGAECOLETOR C
WHERE C.NROPEDVENDA = 56123

UNION ALL

SELECT
    'MACV_PSITEMRECEBER' AS FONTE,
    R.NROEMPRESA,
    NULL AS NROEMPDESTINO,
    R.SEQPRODUTO,
    R.NROPEDIDOSUPRIM,
    NULL AS NROEMPRESAPEDVENDA,
    NULL AS NROPEDVENDA,
    R.NROPEDFORNECEDORNUM,
    R.NROPEDFORNECEDOR
FROM MACV_PSITEMRECEBER R
WHERE TO_CHAR(R.NROPEDFORNECEDORNUM) = '56123'
   OR TO_CHAR(R.NROPEDFORNECEDOR) = '56123'
   OR R.NROPEDIDOSUPRIM = 31339

UNION ALL

SELECT
    'MACX_IMPABASTECIMENTO' AS FONTE,
    NULL AS NROEMPRESA,
    NULL AS NROEMPDESTINO,
    NULL AS SEQPRODUTO,
    TO_NUMBER(I.NROPEDORIGEM) AS NROPEDIDOSUPRIM,
    NULL AS NROEMPRESAPEDVENDA,
    I.NROPEDGERADO AS NROPEDVENDA,
    NULL AS NROPEDFORNECEDORNUM,
    NULL AS NROPEDFORNECEDOR
FROM MACX_IMPABASTECIMENTO I
WHERE REGEXP_LIKE(I.NROPEDORIGEM, '^[0-9]+$')
  AND (I.NROPEDGERADO = 56123 OR TO_NUMBER(I.NROPEDORIGEM) = 31339)

ORDER BY
    FONTE,
    NROEMPRESA,
    NROEMPDESTINO,
    SEQPRODUTO;
