SELECT '   ' || FI_TITULO.NROEMPRESA AS EMPRESA,
       '   ' || FI_TITULO.SEQTITULO AS SEQ_TITULO,
       FI_TITULO.NROTITULO || '/' || FI_TITULO.SERIETITULO || '-' || FI_TITULO.NROPARCELA AS TITULO,
       FI_TITULO.CODESPECIE AS ESPECIE,
       '   ' || FI_TITULO.SEQPESSOA AS COD_FORNECEDOR,
       GE_PESSOA.NOMERAZAO AS FORNECEDOR,
       NVL(COMP.APELIDO, NVL(COMP.COMPRADOR, 'SEM COMPRADOR')) AS COMPRADOR,
       TO_CHAR(FI_TITULO.DTAEMISSAO, 'DD/MM/YYYY') AS DATA_EMISSAO,
       TO_CHAR(FI_TITULO.DTAVENCIMENTO, 'DD/MM/YYYY') AS DATA_VENCIMENTO,
       TO_CHAR(FI_TITOPERACAO.DTAOPERACAO, 'DD/MM/YYYY') AS DATA_OPERACAO,
       '   ' || FI_TITOPERACAO.VLROPERACAO AS VALOR_OPERACAO,
       '   ' || FI_TITULO.VLRNOMINAL AS VALOR_NOMINAL,
       '   ' || FI_TITULO.VLRPAGO AS VALOR_PAGO,
       '   ' || (FI_TITULO.VLRNOMINAL - FI_TITULO.VLRPAGO) AS SALDO_DEVEDOR,
       FI_TITULO.SITJURIDICA AS SITUACAO_JURIDICA,
       FI_TITULO.OBSERVACAO AS OBSERVACAO
  FROM FI_TITULO
  INNER JOIN FI_TITOPERACAO ON FI_TITULO.SEQTITULO = FI_TITOPERACAO.SEQTITULO
  INNER JOIN GE_PESSOA ON FI_TITULO.SEQPESSOA = GE_PESSOA.SEQPESSOA
  LEFT JOIN FI_TITCOMPRADOR TC ON TC.SEQTITULO = FI_TITULO.SEQTITULO
  LEFT JOIN MAX_COMPRADOR COMP ON COMP.SEQCOMPRADOR = TC.SEQCOMPRADOR
 WHERE FI_TITULO.SITUACAO != 'C'
   AND FI_TITOPERACAO.OPCANCELADA IS NULL
   AND FI_TITULO.OBRIGDIREITO = 'D'
   AND FI_TITOPERACAO.DTAOPERACAO BETWEEN :DT1 AND :DT2
   AND FI_TITULO.CODESPECIE IN ( 'ACRCIM', 'ACRCOM', 'ACRINT', 'ACRLOG', 'ACRMKT', 'ACRPRE', 'ACRTRO', 'DEVREC' )
   AND FI_TITULO.NROEMPRESA IN ( 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 20, 21, 22, 23, 50, 900 )
   AND (NVL(:NR1, 0) = 0 OR FI_TITULO.SEQPESSOA = :NR1)
 ORDER BY GE_PESSOA.NOMERAZAO, FI_TITULO.SEQTITULO, FI_TITOPERACAO.SEQTITOPERACAO
