SELECT DISTINCT
    CAT.DEPARTAMENTO AS DEPARTAMENTO,
    CAT.SECAO       AS SECAO,
    CAT.GRUPO       AS GRUPO,
    CAT.SUBGRUPO    AS SUBGRUPO,
    CAT.NIVEL5      AS NIVEL5,
    CAT.NIVEL6      AS NIVEL6,
    COMP.APELIDO    AS COMPRADOR,
    A.SEQPRODUTO    AS CODIGO_PRODUTO,
    A.DESCCOMPLETA  AS DESCRICAO_PRODUTO,
    PE.STATUSCOMPRA AS STATUS,
    ROUND(
        NVL(
            FC5MARGEMPRECOCADDESPOPER(
                A.SEQPRODUTO,
                ME.NROEMPRESA,
                ME.NROSEGMENTOPRINC,
                NVL(FS.PADRAOEMBVENDA, 1),
                'M'
            ),
            0
        ),
        2
    ) AS MARGEM_OBJETIVA
FROM MAP_PRODUTO A
JOIN MRL_PRODUTOEMPRESA PE
  ON PE.SEQPRODUTO = A.SEQPRODUTO
JOIN MAX_EMPRESA ME
  ON ME.NROEMPRESA = PE.NROEMPRESA
LEFT JOIN MAP_FAMDIVISAO FD
  ON FD.SEQFAMILIA = A.SEQFAMILIA
 AND FD.NRODIVISAO = ME.NRODIVISAO
LEFT JOIN MAX_COMPRADOR COMP
  ON COMP.SEQCOMPRADOR = FD.SEQCOMPRADOR
LEFT JOIN MAD_FAMSEGMENTO FS
  ON FS.SEQFAMILIA = A.SEQFAMILIA
 AND FS.NROSEGMENTO = ME.NROSEGMENTOPRINC
LEFT JOIN (
    SELECT
        X.SEQFAMILIA,
        X.NRODIVISAO,
        MAX(CASE WHEN Y.NIVELHIERARQUIA = 1 THEN Y.CATEGORIA END) AS DEPARTAMENTO,
        MAX(CASE WHEN Y.NIVELHIERARQUIA = 2 THEN Y.CATEGORIA END) AS SECAO,
        MAX(CASE WHEN Y.NIVELHIERARQUIA = 3 THEN Y.CATEGORIA END) AS GRUPO,
        MAX(CASE WHEN Y.NIVELHIERARQUIA = 4 THEN Y.CATEGORIA END) AS SUBGRUPO,
        MAX(CASE WHEN Y.NIVELHIERARQUIA = 5 THEN Y.CATEGORIA END) AS NIVEL5,
        MAX(CASE WHEN Y.NIVELHIERARQUIA = 6 THEN Y.CATEGORIA END) AS NIVEL6
    FROM MAP_FAMDIVCATEG X
    JOIN MAP_CATEGORIA Y
      ON Y.SEQCATEGORIA = X.SEQCATEGORIA
     AND Y.NRODIVISAO = X.NRODIVISAO
    WHERE Y.TIPCATEGORIA = 'M'
      AND Y.NIVELHIERARQUIA IN (1, 2, 3, 4, 5, 6)
      AND X.STATUS = 'A'
    GROUP BY
        X.SEQFAMILIA,
        X.NRODIVISAO
) CAT
  ON CAT.SEQFAMILIA = A.SEQFAMILIA
 AND CAT.NRODIVISAO = ME.NRODIVISAO
WHERE PE.NROEMPRESA IN (1,2,3,4,5,6,7,8,11,12,13,14,15,17,18)
  AND (NVL(:NR1, 0) = 0 OR PE.NROEMPRESA = :NR1)
  AND (NVL(:NR2, 0) = 0 OR A.SEQPRODUTO = :NR2)
  AND (TO_NUMBER(SUBSTR(#LS1, 1, INSTR(#LS1, ' - ') - 1)) = 0 OR FD.SEQCOMPRADOR = TO_NUMBER(SUBSTR(#LS1, 1, INSTR(#LS1, ' - ') - 1)))
  AND CAT.DEPARTAMENTO IS NOT NULL
  AND UPPER(CAT.DEPARTAMENTO) NOT IN ('A CLASSIFICAR', 'ALMOXARIFADO', 'INATIVAR', 'SERVICOS')
ORDER BY
    DEPARTAMENTO,
    SECAO,
    GRUPO,
    SUBGRUPO,
    NIVEL5,
    NIVEL6,
    A.DESCCOMPLETA,
    MARGEM_OBJETIVA;