SELECT * FROM (
    WITH CTE_PRODUTOS AS (
        SELECT /*+ MATERIALIZE */ DISTINCT
            PE.SEQPRODUTO,
            PE.NROEMPRESA,
            PE.STATUSCOMPRA,
            ME.NRODIVISAO,
            ME.NROSEGMENTOPRINC,
            A.SEQFAMILIA,
            A.DESCCOMPLETA AS DESCRICAO_PRODUTO,
            NVL(FS.PADRAOEMBVENDA, 1) AS PADRAOEMBVENDA,
            FD.SEQCOMPRADOR
        FROM MAP_PRODUTO A
        INNER JOIN MRL_PRODUTOEMPRESA PE
            ON PE.SEQPRODUTO = A.SEQPRODUTO
        INNER JOIN MAX_EMPRESA ME
            ON ME.NROEMPRESA = PE.NROEMPRESA
        INNER JOIN MAP_FAMDIVISAO FD
            ON FD.SEQFAMILIA = A.SEQFAMILIA
           AND FD.NRODIVISAO = ME.NRODIVISAO
        LEFT JOIN MAD_FAMSEGMENTO FS
            ON FS.SEQFAMILIA = A.SEQFAMILIA
           AND FS.NROSEGMENTO = ME.NROSEGMENTOPRINC
        WHERE PE.NROEMPRESA IN (1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 14, 15, 17, 18)
          AND PE.STATUSCOMPRA = 'A'
          AND FD.FINALIDADEFAMILIA = 'R'
    ),
    CTE_CATEG AS (
        SELECT /*+ MATERIALIZE */
            X.SEQFAMILIA,
            X.NRODIVISAO,
            MAX(CASE WHEN Y.NIVELHIERARQUIA = 1 THEN Y.CATEGORIA END) AS DEPARTAMENTO,
            MAX(CASE WHEN Y.NIVELHIERARQUIA = 2 THEN Y.CATEGORIA END) AS SECAO,
            MAX(CASE WHEN Y.NIVELHIERARQUIA = 3 THEN Y.CATEGORIA END) AS GRUPO,
            MAX(CASE WHEN Y.NIVELHIERARQUIA = 4 THEN Y.CATEGORIA END) AS SUBGRUPO,
            MAX(CASE WHEN Y.NIVELHIERARQUIA = 5 THEN Y.CATEGORIA END) AS NIVEL5,
            MAX(CASE WHEN Y.NIVELHIERARQUIA = 6 THEN Y.CATEGORIA END) AS NIVEL6
        FROM MAP_FAMDIVCATEG X
        INNER JOIN MAP_CATEGORIA Y
            ON Y.SEQCATEGORIA = X.SEQCATEGORIA
           AND Y.NRODIVISAO = X.NRODIVISAO
        WHERE Y.TIPCATEGORIA = 'M'
          AND Y.NIVELHIERARQUIA IN (1, 2, 3, 4, 5, 6)
          AND X.STATUS = 'A'
        GROUP BY
            X.SEQFAMILIA,
            X.NRODIVISAO
    ),
    CTE_PROMOC AS (
        SELECT /*+ MATERIALIZE */ DISTINCT
            P.SEQPRODUTO,
            P.NROEMPRESA,
            P.DTAINICIO,
            P.DTAFIM
        FROM MRLV_BASEPRODPROMOC P
        INNER JOIN CTE_PRODUTOS PR
            ON PR.SEQPRODUTO = P.SEQPRODUTO
           AND PR.NROEMPRESA = P.NROEMPRESA
        WHERE P.DTAFIM >= TRUNC(SYSDATE) - 60
          AND P.DTAINICIO < TRUNC(SYSDATE)
    ),
    CTE_VENDAS_DIA AS (
        SELECT /*+ MATERIALIZE */
            I.SEQPRODUTO,
            I.NROEMPRESA,
            N.DTAEMISSAO,
            SUM(NVL(I.VLRITEM, 0)) AS VLR_VENDA_DIA
        FROM MLFV_BASENFE N
        INNER JOIN MFLV_BASEDFITEM I
            ON I.NROEMPRESA = N.NROEMPRESA
           AND I.SEQNF = N.SEQNF
           AND I.TIPNOTAFISCAL = N.TIPNOTAFISCAL
        INNER JOIN CTE_PRODUTOS PR
            ON PR.SEQPRODUTO = I.SEQPRODUTO
           AND PR.NROEMPRESA = I.NROEMPRESA
        WHERE N.TIPNOTAFISCAL = 'S'
          AND N.CODGERALOPER = 800
          AND NVL(N.STATUSNF, 'A') != 'C'
          AND N.NROEMPRESA IN (1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 14, 15, 17, 18)
          AND N.DTAEMISSAO >= TRUNC(SYSDATE) - 60
          AND N.DTAEMISSAO < TRUNC(SYSDATE)
        GROUP BY
            I.SEQPRODUTO,
            I.NROEMPRESA,
            N.DTAEMISSAO
    ),
    CTE_VENDAS AS (
        SELECT /*+ MATERIALIZE */
            VD.SEQPRODUTO,
            VD.NROEMPRESA,
            ROUND(SUM(VD.VLR_VENDA_DIA), 2) AS VENDA_VALOR,
            ROUND(SUM(CASE WHEN M.SEQPRODUTO IS NOT NULL THEN VD.VLR_VENDA_DIA ELSE 0 END), 2) AS VENDA_PROMOCAO
        FROM CTE_VENDAS_DIA VD
        LEFT JOIN CTE_PROMOC M
            ON M.SEQPRODUTO = VD.SEQPRODUTO
           AND M.NROEMPRESA = VD.NROEMPRESA
           AND VD.DTAEMISSAO BETWEEN M.DTAINICIO AND M.DTAFIM
        GROUP BY
            VD.SEQPRODUTO,
            VD.NROEMPRESA
    )
    SELECT DISTINCT
        CAT.DEPARTAMENTO AS DEPARTAMENTO,
        CAT.SECAO       AS SECAO,
        CAT.GRUPO       AS GRUPO,
        CAT.SUBGRUPO    AS SUBGRUPO,
        CAT.NIVEL5      AS NIVEL5,
        CAT.NIVEL6      AS NIVEL6,
        COMP.APELIDO    AS COMPRADOR,
        PR.SEQPRODUTO    AS CODIGO_PRODUTO,
        PR.DESCRICAO_PRODUTO AS DESCRICAO_PRODUTO,
        PR.STATUSCOMPRA  AS STATUS,
        ROUND(
            NVL(
                FC5MARGEMPRECOCADDESPOPER(
                    PR.SEQPRODUTO,
                    PR.NROEMPRESA,
                    PR.NROSEGMENTOPRINC,
                    PR.PADRAOEMBVENDA,
                    'M'
                ),
                0
            ),
            2
        ) AS MARGEM_OBJETIVA,
        ROUND(NVL(V.VENDA_VALOR, 0), 2) AS VENDA_VALOR,
        ROUND(NVL(V.VENDA_PROMOCAO, 0), 2) AS VENDA_PROMOCAO
    FROM CTE_PRODUTOS PR
    INNER JOIN CTE_CATEG CAT
        ON CAT.SEQFAMILIA = PR.SEQFAMILIA
       AND CAT.NRODIVISAO = PR.NRODIVISAO
    LEFT JOIN CTE_VENDAS V
        ON V.SEQPRODUTO = PR.SEQPRODUTO
       AND V.NROEMPRESA = PR.NROEMPRESA
    LEFT JOIN MAX_COMPRADOR COMP
        ON COMP.SEQCOMPRADOR = PR.SEQCOMPRADOR
    WHERE CAT.DEPARTAMENTO IS NOT NULL
      AND UPPER(CAT.DEPARTAMENTO) NOT IN ('A CLASSIFICAR', 'ALMOXARIFADO', 'INATIVAR', 'SERVICOS')
    ORDER BY
        CAT.DEPARTAMENTO,
        CAT.SECAO,
        CAT.GRUPO,
        CAT.SUBGRUPO,
        CAT.NIVEL5,
        CAT.NIVEL6,
        PR.DESCRICAO_PRODUTO,
        MARGEM_OBJETIVA
)
