SELECT '   ' || FI_TITULO.NROEMPRESA AS EMPRESA,
       '   ' || FI_TITULO.SEQTITULO AS SEQ_TITULO,
       FI_TITULO.NROTITULO || '/' || FI_TITULO.SERIETITULO || '-' || FI_TITULO.NROPARCELA AS TITULO,
       FI_TITULO.CODESPECIE AS ESPECIE,
       '   ' || FI_TITULO.SEQPESSOA AS COD_FORNECEDOR,
       GE_PESSOA.NOMERAZAO AS FORNECEDOR,
       NVL(COMP.APELIDO, NVL(COMP.COMPRADOR, 'SEM COMPRADOR')) AS COMPRADOR,
       TO_CHAR(FI_TITULO.DTAEMISSAO, 'DD/MM/YYYY') AS DATA_EMISSAO,
       TO_CHAR(FI_TITULO.DTAVENCIMENTO, 'DD/MM/YYYY') AS DATA_VENCIMENTO,
       '   ' || FI_TITULO.VLRNOMINAL AS VALOR_NOMINAL,
       '   ' || SUM(CASE WHEN FI_TITOPERACAO.CODOPERACAO = 19 THEN FI_TITOPERACAO.VLROPERACAO ELSE 0 END) AS VLR_COMPENSADO,
       '   ' || SUM(CASE WHEN FI_TITOPERACAO.CODOPERACAO = 29 THEN FI_TITOPERACAO.VLROPERACAO ELSE 0 END) AS VLR_DESCONTO,
       '   ' || SUM(CASE WHEN FI_TITOPERACAO.CODOPERACAO = 6 THEN FI_TITOPERACAO.VLROPERACAO ELSE 0 END) AS VLR_PAGO_BANCO,
       '   ' || (FI_TITULO.VLRNOMINAL - FI_TITULO.VLRPAGO) AS SALDO_DEVEDOR
  FROM FI_TITULO
  INNER JOIN FI_TITOPERACAO ON FI_TITULO.SEQTITULO = FI_TITOPERACAO.SEQTITULO
  INNER JOIN GE_PESSOA ON FI_TITULO.SEQPESSOA = GE_PESSOA.SEQPESSOA
  LEFT JOIN FI_TITCOMPRADOR TC ON TC.SEQTITULO = FI_TITULO.SEQTITULO
  LEFT JOIN MAX_COMPRADOR COMP ON COMP.SEQCOMPRADOR = TC.SEQCOMPRADOR
 WHERE FI_TITULO.SITUACAO != 'C'
   AND FI_TITOPERACAO.OPCANCELADA IS NULL
   AND FI_TITULO.OBRIGDIREITO = 'O'
   AND FI_TITULO.DTAVENCIMENTO BETWEEN :DT1 AND :DT2
   AND FI_TITULO.CODESPECIE = 'DUPP'
   AND FI_TITULO.NROEMPRESA IN ( 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 20, 21, 22, 23, 50, 900 )
   AND (NVL(:NR1, 0) = 0 OR FI_TITULO.SEQPESSOA = :NR1)
 GROUP BY FI_TITULO.NROEMPRESA,
          FI_TITULO.SEQTITULO,
          FI_TITULO.NROTITULO,
          FI_TITULO.SERIETITULO,
          FI_TITULO.NROPARCELA,
          FI_TITULO.CODESPECIE,
          FI_TITULO.SEQPESSOA,
          GE_PESSOA.NOMERAZAO,
          COMP.APELIDO,
          COMP.COMPRADOR,
          FI_TITULO.DTAEMISSAO,
          FI_TITULO.DTAVENCIMENTO,
          FI_TITULO.VLRNOMINAL,
          FI_TITULO.VLRPAGO
 ORDER BY GE_PESSOA.NOMERAZAO, FI_TITULO.SEQTITULO
