SELECT
    T.TABLE_NAME AS NOME_TABELA,
    TC.COMMENTS AS DESCRICAO_TABELA,
    T.NUM_ROWS AS QTD_LINHAS_ESTIMADA,
    T.TABLESPACE_NAME,
    T.LAST_ANALYZED AS DATA_ULTIMA_ANALISE
FROM ALL_TABLES T
LEFT JOIN ALL_TAB_COMMENTS TC 
       ON T.OWNER = TC.OWNER 
      AND T.TABLE_NAME = TC.TABLE_NAME
WHERE T.OWNER IN ('CONSINCO', USER)
  AND T.TABLE_NAME NOT LIKE 'BIN$%'
  AND T.TABLE_NAME NOT LIKE 'TMP_%'
  AND T.TABLE_NAME NOT LIKE 'SYS_%'
ORDER BY T.TABLE_NAME
