SELECT
    C.TABLE_NAME AS NOME_TABELA,
    TC.COMMENTS AS DESCRICAO_TABELA,
    C.COLUMN_ID AS ORDEM,
    C.COLUMN_NAME AS NOME_COLUNA,
    C.DATA_TYPE || 
      CASE 
        WHEN C.DATA_TYPE LIKE '%CHAR%' THEN '(' || C.DATA_LENGTH || ')'
        WHEN C.DATA_TYPE = 'NUMBER' AND C.DATA_PRECISION IS NOT NULL THEN '(' || C.DATA_PRECISION || ',' || NVL(C.DATA_SCALE, 0) || ')'
        ELSE ''
      END AS TIPO_DADOS,
    C.NULLABLE AS PERMITE_NULO,
    CC.COMMENTS AS DESCRICAO_COLUNA
FROM ALL_TAB_COLUMNS C
JOIN ALL_TABLES T 
  ON C.OWNER = T.OWNER 
 AND C.TABLE_NAME = T.TABLE_NAME
LEFT JOIN ALL_TAB_COMMENTS TC 
  ON T.OWNER = TC.OWNER 
 AND T.TABLE_NAME = TC.TABLE_NAME
LEFT JOIN ALL_COL_COMMENTS CC 
  ON C.OWNER = CC.OWNER 
 AND C.TABLE_NAME = CC.TABLE_NAME 
 AND C.COLUMN_NAME = CC.COLUMN_NAME
WHERE C.OWNER IN ('CONSINCO', USER)
  AND C.TABLE_NAME NOT LIKE 'BIN$%'
  AND C.TABLE_NAME NOT LIKE 'TMP_%'
ORDER BY C.TABLE_NAME, C.COLUMN_ID
