SELECT * FROM (
    WITH CTE_FILTRO_USUARIOS AS (
        SELECT /*+ MATERIALIZE */
            U.SEQUSUARIO,
            U.CODUSUARIO,
            U.NOME AS NOME_USUARIO,
            U.LOGINID AS LOGIN_AD,
            U.INDLOGINAD AS AUTENTICA_AD,
            U.NIVEL,
            U.NROEMPRESA,
            U.SEQPESSOA,
            U.EMAIL AS EMAIL_USUARIO,
            U.DTLIMITEUSO,
            U.EXPIRACAOSENHA,
            U.DTAULTACESSO
        FROM GE_USUARIO U
        WHERE (NVL(TRIM(:LT1), 'TODOS') IN ('TODOS', '0', '') OR UPPER(TRIM(U.CODUSUARIO)) LIKE '%' || UPPER(TRIM(:LT1)) || '%' OR UPPER(TRIM(U.LOGINID)) LIKE '%' || UPPER(TRIM(:LT1)) || '%')
    ),
    CTE_USUARIO_RF AS (
        SELECT /*+ MATERIALIZE */
            DISTINCT CODUSUARIO
        FROM MRF_USUARIORF
    )
    SELECT
        U.CODUSUARIO AS LOGIN_USUARIO,
        NVL(P.NOMERAZAO, U.NOME_USUARIO) AS NOME_COMPLETO_PESSOA,
        U.LOGIN_AD,
        NVL(U.AUTENTICA_AD, 'N') AS AUTENTICA_AD,
        U.NROEMPRESA AS COD_EMPRESA,
        E.CIDADE AS CIDADE_EMPRESA,
        CASE
            WHEN NVL(U.NIVEL, 1) = 0 THEN '0 - BLOQUEADO'
            WHEN U.DTLIMITEUSO IS NOT NULL AND TRUNC(U.DTLIMITEUSO) < TRUNC(SYSDATE) THEN 'EXPIRADO (DATA LIMITE)'
            WHEN U.EXPIRACAOSENHA IS NOT NULL AND TRUNC(U.EXPIRACAOSENHA) < TRUNC(SYSDATE) THEN 'SENHA EXPIRADA'
            ELSE 'ATIVO'
        END AS STATUS_CONTA,
        CASE NVL(U.NIVEL, 1)
            WHEN 0 THEN '0 - BLOQUEADO'
            WHEN 1 THEN '1 - USUARIO PADRAO'
            WHEN 9 THEN '9 - ADMINISTRADOR TOTAL'
            ELSE TO_CHAR(U.NIVEL) || ' - NIVEL ' || TO_CHAR(U.NIVEL)
        END AS NIVEL_ACESSO,
        NVL(U.EMAIL_USUARIO, P.EMAIL) AS EMAIL,
        TO_CHAR(U.DTAULTACESSO, 'DD-MM-YY') AS DATA_ULTIMO_ACESSO,
        CASE
            WHEN RF.CODUSUARIO IS NOT NULL THEN 'SIM'
            ELSE 'NAO'
        END AS ACESSO_COLETOR_RF,
        U.SEQUSUARIO
    FROM CTE_FILTRO_USUARIOS U
    LEFT JOIN GE_PESSOA P ON P.SEQPESSOA = U.SEQPESSOA
    LEFT JOIN MAX_EMPRESA E ON E.NROEMPRESA = U.NROEMPRESA
    LEFT JOIN CTE_USUARIO_RF RF ON RF.CODUSUARIO = U.CODUSUARIO
    ORDER BY
        STATUS_CONTA,
        LOGIN_USUARIO
)
