SELECT
    A.SEQPRODUTO AS CODIGO_PRODUTO,
    A.DESCCOMPLETA AS DESCRICAO_PRODUTO,
    MAX(NVL(COMP.COMPRADOR, 'SEM GESTOR')) AS COMPRADOR,
    MAX(NVL(FP.CODIGO_FORNECEDOR, 0)) AS CODIGO_FORNECEDOR,
    MAX(NVL(FP.FORNECEDOR_PRINCIPAL, 'SEM FORNECEDOR')) AS FORNECEDOR_PRINCIPAL,
    MAX(NVL(VF.QTD_VENDIDA_TOTAL, 0)) AS QTD_VENDIDA_TOTAL,
    SUM(NVL(Y.ESTQLOJA, 0)) AS ESTOQUE_LOJA,
    SUM(NVL(Y.ESTQDEPOSITO, 0)) AS ESTOQUE_DEPOSITO
FROM MAP_PRODUTO A
INNER JOIN MRL_PRODUTOEMPRESA Y ON Y.SEQPRODUTO = A.SEQPRODUTO
LEFT JOIN MAP_FAMDIVISAO FD ON FD.SEQFAMILIA = A.SEQFAMILIA AND FD.NRODIVISAO = 1
LEFT JOIN MAX_COMPRADOR COMP ON COMP.SEQCOMPRADOR = FD.SEQCOMPRADOR
LEFT JOIN (
    SELECT F.SEQFAMILIA,
           MAX(F.SEQFORNECEDOR) AS CODIGO_FORNECEDOR,
           MAX(P.NOMERAZAO) AS FORNECEDOR_PRINCIPAL
    FROM MAP_FAMFORNEC F
    INNER JOIN GE_PESSOA P ON P.SEQPESSOA = F.SEQFORNECEDOR
    WHERE F.PRINCIPAL = 'S'
    GROUP BY F.SEQFAMILIA
) FP ON FP.SEQFAMILIA = A.SEQFAMILIA
INNER JOIN (
    SELECT SEQPRODUTO,
           SUM(QTDVDA) AS QTD_VENDIDA_TOTAL
    FROM MRL_PRODVENDADIA
    WHERE DTAVDA BETWEEN :DT1 AND :DT2
      AND NROEMPRESA IN (#LT1)
    GROUP BY SEQPRODUTO
    HAVING SUM(QTDVDA) > :NR1
) VF ON VF.SEQPRODUTO = A.SEQPRODUTO
WHERE Y.NROEMPRESA IN (#LT1)
  AND (NVL(TRIM(:LT2), '0') = '0' OR TO_CHAR(NVL(FP.CODIGO_FORNECEDOR, 0)) = TRIM(:LT2))
  AND (NVL(TRIM(:LT3), 'TODOS') = 'TODOS' OR UPPER(NVL(COMP.COMPRADOR, 'SEM GESTOR')) = UPPER(TRIM(:LT3)))
GROUP BY
    A.SEQPRODUTO,
    A.DESCCOMPLETA
ORDER BY QTD_VENDIDA_TOTAL DESC, DESCRICAO_PRODUTO