SELECT
    T.NROEMPRESA AS EMPRESA,
    T.SEQPESSOA AS FORNECEDOR,
    P.NOMERAZAO AS NOME_FORNECEDOR,
    T.NROTITULO AS NRO_TITULO,
    T.NROPARCELA AS PARCELA,
    T.CODESPECIE AS ESPECIE,
    TO_CHAR(T.DTAVENCIMENTO, 'DD/MM/YYYY') AS DTA_VENCIMENTO,
    TO_CHAR(T.DTAINCLUSAO, 'DD/MM/YYYY') AS DTA_INCLUSAO,
    TO_CHAR(T.DTAQUITACAO, 'DD/MM/YYYY') AS DTA_QUITACAO,
    TO_CHAR(T.VLRNOMINAL, 'FM999G999G990D00', 'NLS_NUMERIC_CHARACTERS='',.''') AS VLR_NOMINAL,
    TO_CHAR(T.VLRPAGO, 'FM999G999G990D00', 'NLS_NUMERIC_CHARACTERS='',.''') AS VLR_PAGO,
    T.ABERTOQUITADO AS STATUS_PAGTO,
    T.SITUACAO AS SITUACAO,
    T.OBSERVACAO AS OBSERVACAO,
    (SELECT MAX(O.USUALTERACAO) KEEP (DENSE_RANK LAST ORDER BY NVL(O.DTAHORAALTERACAO, O.DTAALTERACAO), O.SEQTITOPERACAO) 
       FROM FI_TITOPERACAO O WHERE O.SEQTITULO = T.SEQTITULO) AS USU_ULT_OPERACAO,
    (SELECT TO_CHAR(MAX(NVL(O.DTAHORAALTERACAO, O.DTAALTERACAO)), 'DD/MM/YYYY HH24:MI:SS') 
       FROM FI_TITOPERACAO O WHERE O.SEQTITULO = T.SEQTITULO) AS DTA_ULT_OPERACAO
FROM FI_TITULO T
LEFT JOIN GE_PESSOA P ON T.SEQPESSOA = P.SEQPESSOA
WHERE T.DTAVENCIMENTO BETWEEN :DT1 AND :DT2
  AND (:LT1 = '0' OR T.CODESPECIE IN (
      SELECT UPPER(TRIM(REGEXP_SUBSTR(:LT1, '[^,]+', 1, LEVEL)))
      FROM DUAL
      CONNECT BY REGEXP_SUBSTR(:LT1, '[^,]+', 1, LEVEL) IS NOT NULL
  ))
  AND (:NR1 = 0 OR T.NROTITULO = :NR1)
  AND (:LT2 = '0' OR T.SEQPESSOA IN (
      SELECT TO_NUMBER(REGEXP_SUBSTR(:LT2, '[^,]+', 1, LEVEL))
      FROM DUAL
      CONNECT BY REGEXP_SUBSTR(:LT2, '[^,]+', 1, LEVEL) IS NOT NULL
  ))
  AND (:LS1 = ' TODAS AS REDES' OR EXISTS (
      SELECT 1 FROM GE_REDEPESSOA RP
      JOIN GE_REDE R ON RP.SEQREDE = R.SEQREDE
      WHERE RP.SEQPESSOA = T.SEQPESSOA
        AND R.DESCRICAO = :LS1
  ))
  AND (:LT3 = '0' OR T.ABERTOQUITADO IN (
      SELECT UPPER(TRIM(REGEXP_SUBSTR(:LT3, '[^,]+', 1, LEVEL)))
      FROM DUAL
      CONNECT BY REGEXP_SUBSTR(:LT3, '[^,]+', 1, LEVEL) IS NOT NULL
  ))
ORDER BY T.DTAVENCIMENTO DESC, T.SEQPESSOA
