SELECT * FROM (
    WITH CTE_FORN_PRINCIPAL AS (
        SELECT /*+ MATERIALIZE */
            F.SEQFAMILIA,
            MAX(F.SEQFORNECEDOR) AS CODIGO_FORN_PRINCIPAL,
            MAX(P.NOMERAZAO) AS NOME_FORN_PRINCIPAL
        FROM MAP_FAMFORNEC F
        INNER JOIN GE_PESSOA P ON P.SEQPESSOA = F.SEQFORNECEDOR
        WHERE F.PRINCIPAL = 'S'
        GROUP BY F.SEQFAMILIA
    ),
    CTE_VENDAS AS (
        SELECT /*+ MATERIALIZE */
            V.SEQPRODUTO,
            SUM(V.QTDVDA) AS QTD_VENDIDA_PERIODO
        FROM MRL_PRODVENDADIA V
        WHERE V.DTAVDA BETWEEN :DT1 AND :DT2
          AND V.QTDVDA > 0
        GROUP BY V.SEQPRODUTO
    ),
    CTE_ENTRADAS AS (
        SELECT /*+ MATERIALIZE */
            I.SEQPRODUTO,
            N.SEQPESSOA AS COD_FORN_ENTRADA,
            N.NROEMPRESA,
            N.NUMERONF,
            N.SERIENF,
            N.DTAENTRADA,
            SUM(I.QUANTIDADE) AS QTD_ENTRADA,
            SUM(NVL(I.VLRITEM, 0)) AS VLR_ENTRADA
        FROM MLF_NOTAFISCAL N
        INNER JOIN MLF_NFITEM I
            ON I.NUMERONF = N.NUMERONF
           AND I.SERIENF = N.SERIENF
           AND I.NROEMPRESA = N.NROEMPRESA
           AND I.TIPNOTAFISCAL = N.TIPNOTAFISCAL
           AND NVL(N.SEQNF, 0) = NVL(I.SEQNF, NVL(N.SEQNF, 0))
        WHERE N.TIPNOTAFISCAL = 'E'
          AND N.DTAENTRADA BETWEEN :DT1 AND :DT2
          AND NVL(N.STATUSNF, 'A') != 'C'
        GROUP BY
            I.SEQPRODUTO,
            N.SEQPESSOA,
            N.NROEMPRESA,
            N.NUMERONF,
            N.SERIENF,
            N.DTAENTRADA
    )
    SELECT
        E.NROEMPRESA AS EMPRESA,
        E.NUMERONF AS NRO_NF_ENTRADA,
        E.SERIENF AS SERIE_NF,
        TO_CHAR(E.DTAENTRADA, 'DD/MM/YYYY') AS DATA_ENTRADA,
        P.SEQPRODUTO AS CODIGO_PRODUTO,
        P.DESCCOMPLETA AS DESCRICAO_PRODUTO,
        E.COD_FORN_ENTRADA AS COD_FORN_ENTRADA,
        PE_ENT.NOMERAZAO AS RAZAO_FORN_ENTRADA,
        NVL(FP.CODIGO_FORN_PRINCIPAL, 0) AS COD_FORN_PRINCIPAL,
        NVL(FP.NOME_FORN_PRINCIPAL, 'SEM FORNECEDOR PRINCIPAL') AS RAZAO_FORN_PRINCIPAL,
        ROUND(E.QTD_ENTRADA, 2) AS QTD_ENTRADA_NF,
        ROUND(E.VLR_ENTRADA, 2) AS VLR_ENTRADA_NF,
        ROUND(V.QTD_VENDIDA_PERIODO, 2) AS QTD_VENDIDA_PERIODO
    FROM CTE_ENTRADAS E
    INNER JOIN MAP_PRODUTO P
        ON P.SEQPRODUTO = E.SEQPRODUTO
    INNER JOIN CTE_VENDAS V
        ON V.SEQPRODUTO = E.SEQPRODUTO
    INNER JOIN GE_PESSOA PE_ENT
        ON PE_ENT.SEQPESSOA = E.COD_FORN_ENTRADA
    LEFT JOIN CTE_FORN_PRINCIPAL FP
        ON FP.SEQFAMILIA = P.SEQFAMILIA
    WHERE NVL(FP.CODIGO_FORN_PRINCIPAL, -1) != E.COD_FORN_ENTRADA
      AND (NVL(:NR1, 0) = 0 OR E.COD_FORN_ENTRADA = :NR1 OR FP.CODIGO_FORN_PRINCIPAL = :NR1 OR P.SEQPRODUTO = :NR1)
    ORDER BY
        E.DTAENTRADA DESC,
        E.NUMERONF,
        P.DESCCOMPLETA
)
