-- Pesquisa nomes de subcategorias (nível 3) de OPLS para uso em filtro
SELECT DISTINCT
  C1.CATEGORIA AS DEPARTAMENTO,
  C2.CATEGORIA AS CATEGORIA_NIVEL2,
  C3.CATEGORIA AS SUBCATEGORIA_NIVEL3
FROM MAP_PRODUTO A
INNER JOIN MAP_FAMILIA B ON A.SEQFAMILIA = B.SEQFAMILIA
INNER JOIN MAP_FAMDIVCATEG FDC3 ON FDC3.SEQFAMILIA = A.SEQFAMILIA AND FDC3.NRODIVISAO = 1 AND FDC3.STATUS = 'A'
INNER JOIN MAP_CATEGORIA C3 ON C3.SEQCATEGORIA = FDC3.SEQCATEGORIA AND C3.NRODIVISAO = 1 AND C3.NIVELHIERARQUIA = 3 AND C3.STATUSCATEGOR = 'A'
INNER JOIN MAP_CATEGORIA C2 ON C2.SEQCATEGORIAPAI = C3.SEQCATEGORIAPAI AND C2.NRODIVISAO = 1 AND C2.NIVELHIERARQUIA = 2 AND C2.STATUSCATEGOR = 'A'
INNER JOIN MAP_CATEGORIA C1 ON C1.SEQCATEGORIAPAI = C2.SEQCATEGORIAPAI AND C1.NRODIVISAO = 1 AND C1.NIVELHIERARQUIA = 1 AND C1.STATUSCATEGOR = 'A'
WHERE REPLACE(UPPER(C1.CATEGORIA), '_', ' ') = 'PERECIVEIS'
  AND NVL(UPPER(C2.CATEGORIA), 'X') = 'OPLS'
ORDER BY C1.CATEGORIA, C2.CATEGORIA, C3.CATEGORIA