SELECT * FROM (
    WITH CTE_FORN_PRINCIPAL AS (
        SELECT /*+ MATERIALIZE */
            F.SEQFAMILIA,
            MAX(F.SEQFORNECEDOR) AS CODIGO_FORN_PRINCIPAL,
            MAX(P.NOMERAZAO) AS NOME_FORN_PRINCIPAL
        FROM MAP_FAMFORNEC F
        INNER JOIN GE_PESSOA P ON P.SEQPESSOA = F.SEQFORNECEDOR
        WHERE F.PRINCIPAL = 'S'
        GROUP BY F.SEQFAMILIA
    ),
    CTE_ENTRADAS AS (
        SELECT /*+ MATERIALIZE */
            I.SEQPRODUTO,
            N.SEQPESSOA AS COD_FORN_ENTRADA,
            N.NROEMPRESA,
            N.NUMERONF,
            N.SERIENF,
            N.DTAENTRADA,
            SUM(I.QUANTIDADE) AS QTD_ENTRADA,
            SUM(NVL(I.VLRITEM, 0)) AS VLR_ENTRADA
        FROM MLF_NOTAFISCAL N
        INNER JOIN MLF_NFITEM I
            ON I.NUMERONF = N.NUMERONF
           AND I.SERIENF = N.SERIENF
           AND I.NROEMPRESA = N.NROEMPRESA
           AND I.TIPNOTAFISCAL = N.TIPNOTAFISCAL
           AND NVL(N.SEQNF, 0) = NVL(I.SEQNF, NVL(N.SEQNF, 0))
        INNER JOIN MAX_CODGERALOPER CGO
            ON CGO.CODGERALOPER = N.CODGERALOPER
        WHERE N.TIPNOTAFISCAL = 'E'
          AND CGO.TIPUSO = 'C'
          AND N.DTAENTRADA BETWEEN :DT1 AND :DT2
          AND NVL(N.STATUSNF, 'A') != 'C'
          AND (NVL(:NR1, 0) = 0 OR I.SEQPRODUTO = :NR1)
        GROUP BY
            I.SEQPRODUTO,
            N.SEQPESSOA,
            N.NROEMPRESA,
            N.NUMERONF,
            N.SERIENF,
            N.DTAENTRADA
    )
    SELECT
        NVL(E.NROEMPRESA, 0) AS EMPRESA,
        E.NUMERONF AS NRO_NF_ENTRADA,
        E.SERIENF AS SERIE_NF,
        TO_CHAR(E.DTAENTRADA, 'DD/MM/YYYY') AS DATA_ENTRADA,
        P.SEQPRODUTO AS CODIGO_PRODUTO,
        P.DESCCOMPLETA AS DESCRICAO_PRODUTO,
        CAT.CATEGORIA AS DEPARTAMENTO,
        COMP.COMPRADOR AS COMPRADOR,
        NVL(FP.CODIGO_FORN_PRINCIPAL, 0) AS COD_FORN_PRINCIPAL,
        NVL(FP.NOME_FORN_PRINCIPAL, 'SEM FORNECEDOR PRINCIPAL') AS RAZAO_FORN_PRINCIPAL,
        E.COD_FORN_ENTRADA AS COD_FORN_ENTRADA,
        PE_ENT.NOMERAZAO AS RAZAO_FORN_ENTRADA,
        CASE 
            WHEN E.NUMERONF IS NULL THEN 'SEM COMPRA NO PERIODO'
            WHEN NVL(FP.CODIGO_FORN_PRINCIPAL, -1) = E.COD_FORN_ENTRADA THEN 'MATCH - FORNECEDOR PRINCIPAL'
            ELSE 'DIVERGENCIA - OUTRO FORNECEDOR'
        END AS STATUS_AUDITORIA,
        ROUND(NVL(E.QTD_ENTRADA, 0), 2) AS QTD_ENTRADA_NF,
        ROUND(NVL(E.VLR_ENTRADA, 0), 2) AS VLR_ENTRADA_NF
    FROM MAP_PRODUTO P
    LEFT JOIN MAP_FAMDIVCATEG FDC
        ON FDC.SEQFAMILIA = P.SEQFAMILIA
       AND FDC.NRODIVISAO = 1
       AND FDC.STATUS = 'A'
    LEFT JOIN MAP_CATEGORIA CAT
        ON CAT.SEQCATEGORIA = FDC.SEQCATEGORIA
       AND CAT.NIVELHIERARQUIA = 1
       AND CAT.TIPCATEGORIA = 'M'
    LEFT JOIN MAP_FAMDIVISAO FD
        ON FD.SEQFAMILIA = P.SEQFAMILIA
       AND FD.NRODIVISAO = 1
    LEFT JOIN MAX_COMPRADOR COMP
        ON COMP.SEQCOMPRADOR = FD.SEQCOMPRADOR
    LEFT JOIN CTE_FORN_PRINCIPAL FP
        ON FP.SEQFAMILIA = P.SEQFAMILIA
    LEFT JOIN CTE_ENTRADAS E
        ON E.SEQPRODUTO = P.SEQPRODUTO
    LEFT JOIN GE_PESSOA PE_ENT
        ON PE_ENT.SEQPESSOA = E.COD_FORN_ENTRADA
    WHERE (
        (NVL(:NR1, 0) > 0 AND P.SEQPRODUTO = :NR1)
        OR
        (NVL(:NR1, 0) = 0 AND E.NUMERONF IS NOT NULL)
    )
      AND (SUBSTR(:LS1, 1, INSTR(:LS1 || ' - ', ' - ') - 1) = '0' OR TO_CHAR(CAT.SEQCATEGORIA) = SUBSTR(:LS1, 1, INSTR(:LS1 || ' - ', ' - ') - 1))
      AND (SUBSTR(:LS2, 1, INSTR(:LS2 || ' - ', ' - ') - 1) = '0' OR TO_CHAR(FD.SEQCOMPRADOR) = SUBSTR(:LS2, 1, INSTR(:LS2 || ' - ', ' - ') - 1))
      AND (
          SUBSTR(:LS3, 1, 1) = '0'
          OR (SUBSTR(:LS3, 1, 1) = '1' AND E.NUMERONF IS NOT NULL AND NVL(FP.CODIGO_FORN_PRINCIPAL, -1) = E.COD_FORN_ENTRADA)
          OR (SUBSTR(:LS3, 1, 1) = '2' AND E.NUMERONF IS NOT NULL AND NVL(FP.CODIGO_FORN_PRINCIPAL, -1) != E.COD_FORN_ENTRADA)
      )
    ORDER BY
        P.DESCCOMPLETA,
        E.DTAENTRADA DESC,
        E.NUMERONF
)
