SELECT * FROM (

    WITH COMPRADOR_SUGERIDO AS (
        SELECT /*+ MATERIALIZE */
            SEQFORNECEDOR,
            SEQCOMPRADOR AS SEQCOMPRADOR_SUGERIDO
        FROM (
            SELECT
                B.SEQFORNECEDOR,
                B.SEQCOMPRADOR,
                ROW_NUMBER() OVER (PARTITION BY B.SEQFORNECEDOR ORDER BY COUNT(1) DESC) AS RN
            FROM MACV_PSITEMRECEBER B
            WHERE B.TIPPEDIDOSUPRIM = 'C'
              AND NVL(B.STATUSITEM, 'A') != 'C'
              AND NVL(B.SEQCOMPRADOR, 0) <> 1
              AND B.NROEMPRESA IN (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 20, 21, 22, 23, 50, 900)
            GROUP BY B.SEQFORNECEDOR, B.SEQCOMPRADOR
        )
        WHERE RN = 1
    ),
    TIT_COMPRADOR AS (
        SELECT /*+ MATERIALIZE */
            TC.SEQTITULO,
            MIN(TC.SEQCOMPRADOR) AS SEQCOMPRADOR_MIN,
            MAX(TC.SEQCOMPRADOR) AS SEQCOMPRADOR_MAX
        FROM FI_TITCOMPRADOR TC
        GROUP BY TC.SEQTITULO
    )
    SELECT
        BASE.ORIGEM,
        BASE.EMPRESA,
        BASE.TITULO,
        BASE.PEDIDO,
        BASE.COD_FORNECEDOR,
        BASE.FORNECEDOR,
        NVL(COMP.APELIDO, NVL(COMP.COMPRADOR, 'MODELO')) AS COMPRADOR,
        BASE.DATA_EMISSAO,
        BASE.DATA_PREV_ENTREGA,
        BASE.PRAZO_PAGAMENTO_DIAS,
        BASE.PARCELA,
        BASE.DATA_VENCIMENTO,
        BASE.STATUS_PEDIDO,
        BASE.VALOR_NOMINAL,
        BASE.VALOR_PAGO,
        BASE.VALOR_PROJETADO
    FROM (
        SELECT
            '1-TITULO_REAL' AS ORIGEM,
            '   ' || FT.NROEMPRESA AS EMPRESA,
            FT.NROTITULO || '/' || FT.SERIETITULO || '-' || FT.NROPARCELA AS TITULO,
            NULL AS PEDIDO,
            '   ' || FT.SEQPESSOA AS COD_FORNECEDOR,
            GP.NOMERAZAO AS FORNECEDOR,
            TO_CHAR(FT.DTAEMISSAO, 'DD/MM/YYYY') AS DATA_EMISSAO,
            NULL AS DATA_PREV_ENTREGA,
            TO_CHAR(FT.DTAVENCIMENTO - FT.DTAEMISSAO) AS PRAZO_PAGAMENTO_DIAS,
            TO_CHAR(FT.NROPARCELA) AS PARCELA,
            TO_CHAR(FT.DTAVENCIMENTO, 'DD/MM/YYYY') AS DATA_VENCIMENTO,
            'FATURADO' AS STATUS_PEDIDO,
            '   ' || FT.VLRNOMINAL AS VALOR_NOMINAL,
            '   ' || FT.VLRPAGO AS VALOR_PAGO,
            '   ' || (FT.VLRNOMINAL - FT.VLRPAGO) AS VALOR_PROJETADO,
            FT.SEQPESSOA AS SEQFORNECEDOR_CHAVE,
            NVL(TCA.SEQCOMPRADOR_MIN, 1) AS SEQCOMPRADOR_ORIGEM,
            CASE
                WHEN NVL(TCA.SEQCOMPRADOR_MIN, -1) <> NVL(TCA.SEQCOMPRADOR_MAX, -1) THEN 'S'
                ELSE 'N'
            END AS FLG_COMPRADOR_MULTIPLO
        FROM FI_TITULO FT
        INNER JOIN GE_PESSOA GP ON GP.SEQPESSOA = FT.SEQPESSOA
        LEFT JOIN TIT_COMPRADOR TCA ON TCA.SEQTITULO = FT.SEQTITULO
        WHERE FT.SITUACAO != 'C'
          AND FT.OBRIGDIREITO = 'O'
          AND FT.DTAVENCIMENTO >= TRUNC(SYSDATE) - 60
          AND FT.DTAVENCIMENTO < TRUNC(SYSDATE) + 60
          AND FT.CODESPECIE = 'DUPP'
          AND FT.NROEMPRESA IN (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 20, 21, 22, 23, 50, 900)
          AND EXISTS (
              SELECT 1
              FROM FI_TITOPERACAO OP
              WHERE OP.SEQTITULO = FT.SEQTITULO
                AND OP.OPCANCELADA IS NULL
          )

        UNION ALL

        SELECT
            '2-PROJECAO_PEDIDO' AS ORIGEM,
            '   ' || A.NROEMPRESA AS EMPRESA,
            NULL AS TITULO,
            TO_CHAR(A.NROPEDIDOSUPRIM) AS PEDIDO,
            '   ' || A.SEQFORNECEDOR AS COD_FORNECEDOR,
            GP.NOMERAZAO AS FORNECEDOR,
            TO_CHAR(A.DTAEMISSAO, 'DD/MM/YYYY') AS DATA_EMISSAO,
            TO_CHAR(A.DTARECEBTO, 'DD/MM/YYYY') AS DATA_PREV_ENTREGA,
            TO_CHAR(A.PZOPAGAMENTO) AS PRAZO_PAGAMENTO_DIAS,
            '1' AS PARCELA,
            TO_CHAR(NVL(A.DTARECEBTO, A.DTAEMISSAO) + NVL(TO_NUMBER(REGEXP_SUBSTR(A.PZOPAGAMENTO, '[0-9]+')), 0), 'DD/MM/YYYY') AS DATA_VENCIMENTO,
            CASE
                WHEN SUM(NVL(A.QTDSOLICITADA, 0)) > SUM(NVL(A.QTDSALDOTOTAL, 0)) THEN 'SALDO RESIDUAL'
                ELSE 'PENDENTE INTEGRAL'
            END AS STATUS_PEDIDO,
            '   ' || SUM(ROUND((A.VLRUNITARIO) * (NVL(A.QTDSOLICITADA, 0) / NVL(A.QTDEMBALAGEM, 1)) * NVL(A.QTDEMBALAGEM, 1), 2)) AS VALOR_NOMINAL,
            '   0' AS VALOR_PAGO,
            '   ' || SUM(ROUND((A.VLRUNITARIO) * ((NVL(A.QTDSALDOTOTAL, 0) - NVL(A.QTDTRANSITO, 0)) / NVL(A.QTDEMBALAGEM, 1)) * NVL(A.QTDEMBALAGEM, 1), 2)) AS VALOR_PROJETADO,
            A.SEQFORNECEDOR AS SEQFORNECEDOR_CHAVE,
            NVL(A.SEQCOMPRADOR, 1) AS SEQCOMPRADOR_ORIGEM,
            'N' AS FLG_COMPRADOR_MULTIPLO
        FROM MACV_PSITEMRECEBER A
        INNER JOIN MSU_PEDIDOSUPRIM P ON P.NROPEDIDOSUPRIM = A.NROPEDIDOSUPRIM AND P.NROEMPRESA = A.NROEMPRESA
        INNER JOIN GE_PESSOA GP ON GP.SEQPESSOA = A.SEQFORNECEDOR
        WHERE A.TIPPEDIDOSUPRIM = 'C'
          AND (NVL(A.QTDSALDOTOTAL, 0) - NVL(A.QTDTRANSITO, 0)) > 0
          AND A.SITUACAOPED NOT IN ('C', 'F')
          AND NVL(A.STATUSITEM, 'A') != 'C'
          AND NVL(P.DTALIMITERECEBTO, TRUNC(SYSDATE)) >= TRUNC(SYSDATE)
          AND (NVL(A.DTARECEBTO, A.DTAEMISSAO) + NVL(TO_NUMBER(REGEXP_SUBSTR(A.PZOPAGAMENTO, '[0-9]+')), 0)) >= TRUNC(SYSDATE) - 60
          AND (NVL(A.DTARECEBTO, A.DTAEMISSAO) + NVL(TO_NUMBER(REGEXP_SUBSTR(A.PZOPAGAMENTO, '[0-9]+')), 0)) < TRUNC(SYSDATE) + 60
          AND A.NROEMPRESA IN (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 20, 21, 22, 23, 50, 900)
        GROUP BY
            A.NROEMPRESA,
            A.NROPEDIDOSUPRIM,
            A.SEQFORNECEDOR,
            GP.NOMERAZAO,
            A.SEQCOMPRADOR,
            A.DTAEMISSAO,
            A.DTARECEBTO,
            A.PZOPAGAMENTO
    ) BASE
    LEFT JOIN COMPRADOR_SUGERIDO SUG ON SUG.SEQFORNECEDOR = BASE.SEQFORNECEDOR_CHAVE
    LEFT JOIN MAX_COMPRADOR COMP ON COMP.SEQCOMPRADOR = (
        CASE
            WHEN BASE.SEQCOMPRADOR_ORIGEM = 1
             AND SUG.SEQCOMPRADOR_SUGERIDO IS NOT NULL THEN SUG.SEQCOMPRADOR_SUGERIDO
            WHEN BASE.FLG_COMPRADOR_MULTIPLO = 'S'
             AND SUG.SEQCOMPRADOR_SUGERIDO IS NOT NULL THEN SUG.SEQCOMPRADOR_SUGERIDO
            ELSE BASE.SEQCOMPRADOR_ORIGEM
        END
    )
    ORDER BY TO_DATE(BASE.DATA_VENCIMENTO, 'DD/MM/YYYY'), BASE.ORIGEM, BASE.FORNECEDOR

)
