SELECT * FROM (

SELECT 
    '1-TITULO_REAL' AS ORIGEM,
    '   ' || FI_TITULO.NROEMPRESA AS EMPRESA,
    FI_TITULO.NROTITULO || '/' || FI_TITULO.SERIETITULO || '-' || FI_TITULO.NROPARCELA AS TITULO,
    NULL AS PEDIDO,
    '   ' || FI_TITULO.SEQPESSOA AS COD_FORNECEDOR,
    GE_PESSOA.NOMERAZAO AS FORNECEDOR,
    NVL(COMP.APELIDO, NVL(COMP.COMPRADOR, 'SEM COMPRADOR')) AS COMPRADOR,
    TO_CHAR(FI_TITULO.DTAEMISSAO, 'DD/MM/YYYY') AS DATA_EMISSAO,
    NULL AS DATA_PREV_ENTREGA,
    TO_CHAR(FI_TITULO.DTAVENCIMENTO - FI_TITULO.DTAEMISSAO) AS PRAZO_PAGAMENTO_DIAS,
    TO_CHAR(FI_TITULO.NROPARCELA) AS PARCELA,
    TO_CHAR(FI_TITULO.DTAVENCIMENTO, 'DD/MM/YYYY') AS DATA_VENCIMENTO,
    'FATURADO' AS STATUS_PEDIDO,
    '   ' || (FI_TITULO.VLRNOMINAL - FI_TITULO.VLRPAGO) AS VALOR_PROJETADO
FROM FI_TITULO
INNER JOIN FI_TITOPERACAO ON FI_TITULO.SEQTITULO = FI_TITOPERACAO.SEQTITULO
INNER JOIN GE_PESSOA ON FI_TITULO.SEQPESSOA = GE_PESSOA.SEQPESSOA
LEFT JOIN FI_TITCOMPRADOR TC ON TC.SEQTITULO = FI_TITULO.SEQTITULO
LEFT JOIN MAX_COMPRADOR COMP ON COMP.SEQCOMPRADOR = TC.SEQCOMPRADOR
WHERE FI_TITULO.SITUACAO != 'C'
  AND FI_TITOPERACAO.OPCANCELADA IS NULL
  AND FI_TITULO.OBRIGDIREITO = 'O'
  AND FI_TITULO.DTAVENCIMENTO BETWEEN :DT1 AND :DT2
  AND FI_TITULO.CODESPECIE = 'DUPP'
  AND FI_TITULO.NROEMPRESA IN ( 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 20, 21, 22, 23, 50, 900 )
  AND (NVL(TRIM(:NR1), '0') = '0' OR TO_CHAR(FI_TITULO.SEQPESSOA) = TRIM(:NR1))
GROUP BY 
    FI_TITULO.NROEMPRESA,
    FI_TITULO.SEQTITULO,
    FI_TITULO.NROTITULO,
    FI_TITULO.SERIETITULO,
    FI_TITULO.NROPARCELA,
    FI_TITULO.SEQPESSOA,
    GE_PESSOA.NOMERAZAO,
    COMP.APELIDO,
    COMP.COMPRADOR,
    FI_TITULO.DTAEMISSAO,
    FI_TITULO.DTAVENCIMENTO,
    FI_TITULO.VLRNOMINAL,
    FI_TITULO.VLRPAGO

UNION ALL

SELECT 
    '2-PROJECAO_PEDIDO' AS ORIGEM,
    '   ' || A.NROEMPRESA AS EMPRESA,
    NULL AS TITULO,
    TO_CHAR(A.NROPEDIDOSUPRIM) AS PEDIDO,
    '   ' || A.SEQFORNECEDOR AS COD_FORNECEDOR,
    GE_PESSOA.NOMERAZAO AS FORNECEDOR,
    NVL(COMP.APELIDO, NVL(COMP.COMPRADOR, 'SEM COMPRADOR')) AS COMPRADOR,
    TO_CHAR(A.DTAEMISSAO, 'DD/MM/YYYY') AS DATA_EMISSAO,
    TO_CHAR(A.DTARECEBTO, 'DD/MM/YYYY') AS DATA_PREV_ENTREGA,
    TO_CHAR(A.PZOPAGAMENTO) AS PRAZO_PAGAMENTO_DIAS,
    '1' AS PARCELA,
    TO_CHAR(NVL(A.DTARECEBTO, A.DTAEMISSAO) + NVL(TO_NUMBER(REGEXP_SUBSTR(A.PZOPAGAMENTO, '[0-9]+')), 0), 'DD/MM/YYYY') AS DATA_VENCIMENTO,
    CASE 
        WHEN SUM(NVL(A.QTDSOLICITADA, 0)) > SUM(NVL(A.QTDSALDOTOTAL, 0)) THEN 'SALDO RESIDUAL'
        ELSE 'PENDENTE INTEGRAL'
    END AS STATUS_PEDIDO,
    '   ' || SUM(ROUND((A.VLRUNITARIO) * ((NVL(A.QTDSALDOTOTAL, 0) - NVL(A.QTDTRANSITO, 0)) / NVL(A.QTDEMBALAGEM, 1)) * NVL(A.QTDEMBALAGEM, 1), 2)) AS VALOR_PROJETADO
FROM MACV_PSITEMRECEBER A
INNER JOIN MSU_PEDIDOSUPRIM P ON P.NROPEDIDOSUPRIM = A.NROPEDIDOSUPRIM AND P.NROEMPRESA = A.NROEMPRESA
INNER JOIN GE_PESSOA ON A.SEQFORNECEDOR = GE_PESSOA.SEQPESSOA
LEFT JOIN MAX_COMPRADOR COMP ON COMP.SEQCOMPRADOR = A.SEQCOMPRADOR
WHERE A.TIPPEDIDOSUPRIM = 'C'
  AND (NVL(A.QTDSALDOTOTAL, 0) - NVL(A.QTDTRANSITO, 0)) > 0
  AND A.SITUACAOPED NOT IN ('C', 'F') 
  AND NVL(A.STATUSITEM, 'A') != 'C'
  AND NVL(P.DTALIMITERECEBTO, TRUNC(SYSDATE)) >= TRUNC(SYSDATE)
  AND (NVL(A.DTARECEBTO, A.DTAEMISSAO) + NVL(TO_NUMBER(REGEXP_SUBSTR(A.PZOPAGAMENTO, '[0-9]+')), 0)) BETWEEN :DT1 AND :DT2
  AND A.NROEMPRESA IN ( 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 20, 21, 22, 23, 50, 900 )
  AND (NVL(TRIM(:NR1), '0') = '0' OR TO_CHAR(A.SEQFORNECEDOR) = TRIM(:NR1))
GROUP BY
    A.NROEMPRESA,
    A.NROPEDIDOSUPRIM,
    A.SEQFORNECEDOR,
    GE_PESSOA.NOMERAZAO,
    COMP.APELIDO,
    COMP.COMPRADOR,
    A.DTAEMISSAO,
    A.DTARECEBTO,
    A.PZOPAGAMENTO

)
ORDER BY TO_DATE(DATA_VENCIMENTO, 'DD/MM/YYYY'), ORIGEM, FORNECEDOR;
