SELECT * FROM (
    WITH ENTRADAS_LOJA AS (
        SELECT /*+ MATERIALIZE */
            B.SEQPRODUTO,
            MAX(A.NROEMPRESA) KEEP (DENSE_RANK LAST ORDER BY A.DTAENTRADA, A.SEQAUXNOTAFISCAL) AS ULTIMA_LOJA_RECEBEU,
            MAX(A.DTAENTRADA) KEEP (DENSE_RANK LAST ORDER BY A.DTAENTRADA, A.SEQAUXNOTAFISCAL) AS DTA_ULTIMO_RECEBIMENTO
        FROM MLF_NOTAFISCAL A
        INNER JOIN MLF_NFITEM B ON A.SEQAUXNOTAFISCAL = B.SEQAUXNOTAFISCAL
        WHERE A.DTAENTRADA >= TRUNC(SYSDATE) - NVL(:NR1, 180)
          AND A.CODGERALOPER = 1
          AND A.STATUSNF != 'C'
          AND A.NROEMPRESA IN (1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 14, 17, 18)
        GROUP BY B.SEQPRODUTO
    ),
    ENTRADAS_CD AS (
        SELECT /*+ MATERIALIZE */ DISTINCT B.SEQPRODUTO
        FROM MLF_NOTAFISCAL A
        INNER JOIN MLF_NFITEM B ON A.SEQAUXNOTAFISCAL = B.SEQAUXNOTAFISCAL
        WHERE A.DTAENTRADA >= TRUNC(SYSDATE) - NVL(:NR1, 180)
          AND A.CODGERALOPER = 1
          AND A.STATUSNF != 'C'
          AND A.NROEMPRESA NOT IN (1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 14, 17, 18)
    ),
    PEND_COMPRA_CD AS (
        SELECT /*+ MATERIALIZE */
            X.SEQPRODUTO,
            SUM(NVL(X.QTDSOLICITADA, 0) - NVL(X.QTDRECCANC, 0)) AS QTD_PEND_PEDIDO_CD
        FROM MAXV_MSUPEDIDOSUPRIMREC X
        WHERE X.TIPPEDIDOSUPRIM = 'C'
          AND NVL(X.QTDSOLICITADA, 0) > NVL(X.QTDRECCANC, 0)
          AND X.NROEMPRESA NOT IN (1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 14, 17, 18)
        GROUP BY X.SEQPRODUTO
    )
    SELECT DISTINCT
        P.SEQPRODUTO AS COD_PRODUTO,
        P.DESCCOMPLETA AS DESC_PRODUTO,
        TO_CHAR(TRUNC(P.DTAHORINCLUSAO), 'DD/MM/YYYY') AS DATA_CADASTRO_PRODUTO,
        C.CATEGORIA AS DEPARTAMENTO,
        COMP.COMPRADOR AS COMPRADOR,
        FD.FORMAABASTECIMENTO AS FORMA_ABASTECIMENTO,
        EL.ULTIMA_LOJA_RECEBEU AS ULTIMA_LOJA_RECEBEU,
        TO_CHAR(EL.DTA_ULTIMO_RECEBIMENTO, 'DD/MM/YYYY') AS DATA_ULTIMO_RECEBIMENTO,
        NVL(EST_CD.ESTOQUE_CD, 0) AS ESTOQUE_CD,
        NVL(PCD.QTD_PEND_PEDIDO_CD, 0) AS QTD_PEND_PEDIDO_CD,
        CASE WHEN NVL(PCD.QTD_PEND_PEDIDO_CD, 0) > 0 THEN 'SIM' ELSE 'NAO' END AS TEM_PEDIDO_PEND_CD
    FROM MAP_PRODUTO P
    INNER JOIN MAP_FAMILIA F ON P.SEQFAMILIA = F.SEQFAMILIA
    INNER JOIN ENTRADAS_LOJA EL ON P.SEQPRODUTO = EL.SEQPRODUTO
    LEFT JOIN ENTRADAS_CD ECD ON P.SEQPRODUTO = ECD.SEQPRODUTO
    LEFT JOIN PEND_COMPRA_CD PCD ON P.SEQPRODUTO = PCD.SEQPRODUTO
    LEFT JOIN (
        SELECT FDC.SEQFAMILIA, C.CATEGORIA
        FROM MAP_FAMDIVCATEG FDC
        INNER JOIN MAP_CATEGORIA C ON FDC.SEQCATEGORIA = C.SEQCATEGORIA AND C.NRODIVISAO = 1
        WHERE FDC.NRODIVISAO = 1 AND FDC.STATUS = 'A' AND C.TIPCATEGORIA = 'M' AND C.NIVELHIERARQUIA = 1
        GROUP BY FDC.SEQFAMILIA, C.CATEGORIA
    ) C ON C.SEQFAMILIA = F.SEQFAMILIA
    LEFT JOIN MAP_FAMDIVISAO FD ON F.SEQFAMILIA = FD.SEQFAMILIA AND FD.NRODIVISAO = 1
    LEFT JOIN MAX_COMPRADOR COMP ON FD.SEQCOMPRADOR = COMP.SEQCOMPRADOR
    LEFT JOIN (
        SELECT 
            SEQPRODUTO,
            SUM(NVL(ESTQLOJA, 0) + NVL(ESTQDEPOSITO, 0) - NVL(QTDRESERVADAVDA, 0) - NVL(QTDRESERVADARECEB, 0) - NVL(QTDRESERVADAFIXA, 0)) AS ESTOQUE_CD
        FROM MRL_PRODUTOEMPRESA
        WHERE NROEMPRESA NOT IN (1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 14, 17, 18)
        GROUP BY SEQPRODUTO
    ) EST_CD ON P.SEQPRODUTO = EST_CD.SEQPRODUTO
    WHERE ECD.SEQPRODUTO IS NULL
      AND (:LS2 = '0 - TODOS' OR NVL(FD.SEQCOMPRADOR, 0) = TO_NUMBER(SUBSTR(:LS2, 1, INSTR(:LS2, ' - ') - 1)))
      AND EXISTS (
          SELECT 1 
          FROM MRL_PRODUTOEMPRESA PE
          WHERE PE.SEQPRODUTO = P.SEQPRODUTO
            AND PE.STATUSCOMPRA = 'A'
            AND PE.NROEMPRESA IN (1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 14, 17, 18)
      )
      AND INSTR(UPPER(NVL(:LT1, 'L,M,C,I')), UPPER(FD.FORMAABASTECIMENTO)) > 0
      AND (
          NVL(TRIM(:LT2), '0') IN ('0', 'NENHUM', '')
          OR NOT REGEXP_LIKE(
              REPLACE(TRANSLATE(UPPER(NVL(C.CATEGORIA, ' ')), 'ÁÉÍÓÚÀÈÌÒÙÃÕÂÊÎÔÛÇ', 'AEIOUAEIOUAOAEIOUC'), ' ', ''),
              REPLACE(REPLACE(TRANSLATE(UPPER(TRIM(:LT2)), 'ÁÉÍÓÚÀÈÌÒÙÃÕÂÊÎÔÛÇ', 'AEIOUAEIOUAOAEIOUC'), ' ', ''), ',', '|'),
              'i'
          )
      )
)
ORDER BY DESC_PRODUTO ASC
