SELECT
    NVL(CAT.DEPARTAMENTO, 'SEM DEPARTAMENTO') AS DEPARTAMENTO,
    NVL(CAT.NIVEL5, 'SEM CATEGORIA NIVEL 5') AS CATEGORIA_NIVEL_5,
    ROUND(SUM(NVL(I.VLRITEM, 0)), 2) AS VENDA_TOTAL,
    ROUND(SUM(CASE WHEN M.SEQPRODUTO IS NOT NULL THEN NVL(I.VLRITEM, 0) ELSE 0 END), 2) AS VENDA_OFERTA,
    ROUND(
        SUM(CASE WHEN M.SEQPRODUTO IS NOT NULL THEN NVL(I.VLRITEM, 0) ELSE 0 END) 
        / NULLIF(SUM(NVL(I.VLRITEM, 0)), 0) * 100, 
        2
    ) AS PERC_VENDA_EM_OFERTA
FROM MLFV_BASENFE N
INNER JOIN MFLV_BASEDFITEM I
  ON I.NROEMPRESA = N.NROEMPRESA
  AND I.SEQNF = N.SEQNF
  AND I.TIPNOTAFISCAL = N.TIPNOTAFISCAL
  AND I.SERIEDF = N.SERIENF
  AND I.NUMERODF = N.NUMERONF
  AND I.SEQPESSOA = N.SEQPESSOA
INNER JOIN MAP_PRODUTO P ON P.SEQPRODUTO = I.SEQPRODUTO
INNER JOIN MAP_FAMDIVISAO FD
  ON FD.SEQFAMILIA = P.SEQFAMILIA
  AND FD.NRODIVISAO = 1
  AND FD.FINALIDADEFAMILIA = 'R'
LEFT JOIN (
    SELECT
        X.SEQFAMILIA,
        MAX(CASE WHEN Y.NIVELHIERARQUIA = 1 THEN Y.CATEGORIA END) AS DEPARTAMENTO,
        MAX(CASE WHEN Y.NIVELHIERARQUIA = 5 THEN Y.CATEGORIA END) AS NIVEL5
    FROM MAP_FAMDIVCATEG X
    JOIN MAP_CATEGORIA Y
      ON Y.SEQCATEGORIA = X.SEQCATEGORIA
     AND Y.NRODIVISAO = X.NRODIVISAO
    WHERE Y.TIPCATEGORIA = 'M'
      AND Y.NIVELHIERARQUIA IN (1, 5)
      AND X.STATUS = 'A'
      AND X.NRODIVISAO = 1
    GROUP BY
        X.SEQFAMILIA
) CAT ON CAT.SEQFAMILIA = P.SEQFAMILIA
LEFT JOIN (
    SELECT DISTINCT SEQPRODUTO, NROEMPRESA, DTAINICIO, DTAFIM
    FROM MRLV_BASEPRODPROMOC
) M ON M.SEQPRODUTO = I.SEQPRODUTO 
   AND M.NROEMPRESA = I.NROEMPRESA 
   AND N.DTAEMISSAO BETWEEN M.DTAINICIO AND M.DTAFIM
WHERE N.TIPNOTAFISCAL = 'S'
  AND N.CODGERALOPER IN (800, 810, 834, 848)
  AND N.NROEMPRESA IN (1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 14, 17, 18)
  AND N.DTAEMISSAO >= TRUNC(:DT1)
  AND N.DTAEMISSAO < TRUNC(:DT2) + 1
  AND CAT.DEPARTAMENTO IS NOT NULL
  AND UPPER(CAT.DEPARTAMENTO) <> 'ALMOXARIFADO'
GROUP BY
    NVL(CAT.DEPARTAMENTO, 'SEM DEPARTAMENTO'),
    NVL(CAT.NIVEL5, 'SEM CATEGORIA NIVEL 5')
ORDER BY
    DEPARTAMENTO,
    CATEGORIA_NIVEL_5
