SELECT * FROM (
    WITH CTE_VENDAS AS (
        SELECT /*+ MATERIALIZE */
            I.SEQPRODUTO,
            SUM(NVL(I.VLRITEM, 0) + NVL(I.VLRIPI, 0) + NVL(I.VLRICMSST, 0)) AS VALOR_VENDIDO
        FROM MLFV_BASENFE N
        INNER JOIN MFLV_BASEDFITEM I
            ON I.NROEMPRESA = N.NROEMPRESA
           AND I.SEQNF = N.SEQNF
           AND I.TIPNOTAFISCAL = N.TIPNOTAFISCAL
           AND I.SERIEDF = N.SERIENF
           AND I.NUMERODF = N.NUMERONF
           AND I.SEQPESSOA = N.SEQPESSOA
        WHERE N.TIPNOTAFISCAL = 'S'
          AND N.CODGERALOPER IN (800, 810, 848)
          AND NVL(N.STATUSNF, 'A') != 'C'
          AND N.DTAEMISSAO >= TRUNC(SYSDATE) - TO_NUMBER(NVL(REGEXP_SUBSTR(:LS2, '^[0-9]+'), '30'))
          AND N.NROEMPRESA IN (1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 14, 15, 17, 18)
        GROUP BY I.SEQPRODUTO
        HAVING SUM(NVL(I.VLRITEM, 0) + NVL(I.VLRIPI, 0) + NVL(I.VLRICMSST, 0)) > 0
    ),
    CTE_CATEGORIAS AS (
        SELECT /*+ MATERIALIZE */
            X.SEQFAMILIA,
            MAX(CASE WHEN Y.NIVELHIERARQUIA = 1 THEN Y.SEQCATEGORIA END) AS SEQDEPARTAMENTO,
            MAX(CASE WHEN Y.NIVELHIERARQUIA = 1 THEN Y.CATEGORIA END) AS DEPARTAMENTO,
            COALESCE(
                MAX(CASE WHEN Y.NIVELHIERARQUIA = 4 THEN Y.CATEGORIA END),
                MAX(CASE WHEN Y.NIVELHIERARQUIA = 3 THEN Y.CATEGORIA END),
                MAX(CASE WHEN Y.NIVELHIERARQUIA = 5 THEN Y.CATEGORIA END),
                'SEM SUBGRUPO'
            ) AS SUBGRUPO
        FROM MAP_FAMDIVCATEG X
        INNER JOIN MAP_CATEGORIA Y
            ON Y.SEQCATEGORIA = X.SEQCATEGORIA
           AND Y.NRODIVISAO = X.NRODIVISAO
        WHERE Y.TIPCATEGORIA = 'M'
          AND Y.NIVELHIERARQUIA IN (1, 3, 4, 5)
          AND X.STATUS = 'A'
          AND X.NRODIVISAO = 1
        GROUP BY X.SEQFAMILIA
    ),
    CTE_PRODUTOS AS (
        SELECT /*+ MATERIALIZE */
            V.SEQPRODUTO,
            V.VALOR_VENDIDO,
            NVL(COMP.COMPRADOR, 'SEM COMPRADOR') AS COMPRADOR,
            CAT.DEPARTAMENTO,
            CAT.SUBGRUPO,
            A.SEQPRODUTO AS SEQCODIGO,
            A.DESCCOMPLETA AS DESCRICAO,
            CASE
                WHEN EXISTS (
                    SELECT 1
                    FROM MRL_PRODUTOEMPRESA PE
                    WHERE PE.SEQPRODUTO = A.SEQPRODUTO
                      AND PE.STATUSCOMPRA = 'A'
                      AND PE.NROEMPRESA IN (1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 14, 15, 17, 18)
                ) THEN 'A'
                ELSE 'I'
            END AS STATUS_COMPRA
        FROM CTE_VENDAS V
        INNER JOIN MAP_PRODUTO A
            ON A.SEQPRODUTO = V.SEQPRODUTO
        INNER JOIN CTE_CATEGORIAS CAT
            ON CAT.SEQFAMILIA = A.SEQFAMILIA
        LEFT JOIN MAP_FAMDIVISAO FD
            ON FD.SEQFAMILIA = A.SEQFAMILIA
           AND FD.NRODIVISAO = 1
        LEFT JOIN MAX_COMPRADOR COMP
            ON COMP.SEQCOMPRADOR = FD.SEQCOMPRADOR
        WHERE CAT.DEPARTAMENTO IS NOT NULL
          AND UPPER(CAT.DEPARTAMENTO) <> 'ALMOXARIFADO'
          AND (
              NVL(TRIM(:LS1), '0 - TODOS') IN ('0 - TODOS', '0', 'TODOS', '')
              OR (
                  INSTR(:LS1, ' - ') > 0
                  AND CAT.SEQDEPARTAMENTO = TO_NUMBER(SUBSTR(:LS1, 1, INSTR(:LS1, ' - ') - 1))
              )
              OR CAT.SEQDEPARTAMENTO = TO_NUMBER(REGEXP_SUBSTR(:LS1, '^[0-9]+'))
          )
          AND (
              NVL(TRIM(:NR1), '0') IN ('0', '')
              OR TO_NUMBER(NVL(:NR1, '0')) = 0
              OR EXISTS (
                  SELECT 1
                  FROM MAP_FAMFORNEC F
                  WHERE F.SEQFAMILIA = A.SEQFAMILIA
                    AND F.SEQFORNECEDOR = TO_NUMBER(:NR1)
              )
          )
    ),
    CTE_RANKING AS (
        SELECT /*+ MATERIALIZE */
            P.COMPRADOR,
            P.DEPARTAMENTO,
            P.SUBGRUPO,
            P.SEQCODIGO,
            P.DESCRICAO,
            P.STATUS_COMPRA,
            P.VALOR_VENDIDO,
            SUM(P.VALOR_VENDIDO) OVER (
                ORDER BY P.VALOR_VENDIDO DESC, P.SEQCODIGO ASC
                ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
            ) AS SOMA_ACUMULADA,
            SUM(P.VALOR_VENDIDO) OVER () AS SOMA_TOTAL
        FROM CTE_PRODUTOS P
    )
    SELECT
        R.COMPRADOR AS COMPRADOR,
        R.DEPARTAMENTO AS DEPARTAMENTO,
        R.SUBGRUPO AS SUBGRUPO,
        R.SEQCODIGO AS SEQCODIGO,
        R.DESCRICAO AS DESCRICAO,
        R.STATUS_COMPRA AS STATUS_COMPRA,
        ROUND(R.VALOR_VENDIDO, 2) AS VALOR_VENDIDO,
        ROUND((R.VALOR_VENDIDO / NULLIF(R.SOMA_TOTAL, 0)) * 100, 2) AS PERC_PARTICIPACAO,
        ROUND((R.SOMA_ACUMULADA / NULLIF(R.SOMA_TOTAL, 0)) * 100, 2) AS PERC_ACUMULADO,
        CASE
            WHEN (R.SOMA_ACUMULADA / NULLIF(R.SOMA_TOTAL, 0)) <= 0.500001 THEN 'A'
            WHEN (R.SOMA_ACUMULADA / NULLIF(R.SOMA_TOTAL, 0)) <= 0.900001 THEN 'B'
            ELSE 'C'
        END AS RANK
    FROM CTE_RANKING R
)
ORDER BY VALOR_VENDIDO DESC, SEQCODIGO ASC
