SELECT * FROM (
    WITH CTE_OPERACAO AS (
        SELECT /*+ MATERIALIZE */
            CODOPERACAO,
            DESCRICAO
        FROM FI_OPERACAO
    ),
    CTE_TITULOS AS (
        SELECT /*+ MATERIALIZE */
            FI_TITULO.SEQTITULO,
            FI_TITULO.NROEMPRESA,
            FI_TITULO.NROBANCO,
            FI_TITULO.SEQAGENCIA,
            FI_TITULO.NROTITULO,
            FI_TITULO.SERIETITULO,
            FI_TITULO.NROPARCELA,
            FI_TITULO.CODESPECIE,
            FI_TITULO.SEQPESSOA,
            FI_TITULO.VLRNOMINAL,
            FI_TITULO.VLRPAGO,
            FI_TITULO.VLRORIGINAL,
            FI_TITULO.SITJURIDICA,
            FI_TITULO.DTAPROGRAMADA,
            FI_TITULO.DTAEMISSAO,
            FI_TITULO.DTAVENCIMENTO,
            FI_TITULO.DTAMOVIMENTO,
            FI_TITULO.DTAQUITACAO,
            FI_TITULO.SEQVENDEDOR,
            FI_TITULO.OBSERVACAO AS OBSERVACAO_TITULO,
            GE_PESSOA.NOMERAZAO,
            GE_PESSOA.NROCGCCPF,
            GE_PESSOA.DIGCGCCPF,
            GE_PESSOA.FISICAJURIDICA
        FROM FI_TITULO
        INNER JOIN GE_PESSOA ON FI_TITULO.SEQPESSOA = GE_PESSOA.SEQPESSOA
        WHERE FI_TITULO.SITUACAO != 'C'
          AND FI_TITULO.OBRIGDIREITO = 'O'
          AND FI_TITULO.DTAVENCIMENTO BETWEEN :DT1 AND :DT2
          AND FI_TITULO.NROEMPRESA IN ( 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 20, 21, 22, 23, 50, 900 )
          AND (NVL(:NR1, 0) = 0 OR FI_TITULO.SEQPESSOA = :NR1 OR FI_TITULO.NROEMPRESA = :NR1)
          AND (
              NVL(TRIM(:LS1), '0') IN ('0', '0 - TODOS', '0 - TODAS', 'TODOS', 'TODAS', '')
              OR INSTR(TRIM(:LS1), 'TODOS') > 0
              OR TRIM(FI_TITULO.CODESPECIE) = TRIM(:LS1)
              OR INSTR(TRIM(:LS1), TRIM(FI_TITULO.CODESPECIE)) = 1
              OR TRIM(FI_TITULO.CODESPECIE) = TRIM(SUBSTR(TRIM(:LS1), 1, INSTR(TRIM(:LS1) || ' ', ' ') - 1))
          )
    )
    SELECT
        T.NROEMPRESA AS EMPRESA,
        T.SEQTITULO AS SEQ_TITULO,
        T.NROTITULO || '/' || T.SERIETITULO || '-' || T.NROPARCELA AS TITULO,
        T.CODESPECIE AS ESPECIE,
        T.SEQPESSOA AS COD_FORNECEDOR,
        T.NOMERAZAO || ' - ' || T.SEQPESSOA AS FORNECEDOR,
        SUBSTR(FC5MASKCNPJCPF(T.NROCGCCPF, T.DIGCGCCPF, T.FISICAJURIDICA), 1, 20) AS CNPJ_CPF,
        O.CODOPERACAO AS COD_OPERACAO,
        NVL(OP.DESCRICAO, 'SEM DESCRICAO') AS DESCRICAO_OPERACAO,
        TO_CHAR(O.DTAOPERACAO, 'DD/MM/YYYY') AS DATA_OPERACAO,
        TO_CHAR(O.DTACONTABILIZA, 'DD/MM/YYYY') AS DATA_CONTABILIZA,
        TO_CHAR(T.DTAEMISSAO, 'DD/MM/YYYY') AS DATA_EMISSAO,
        TO_CHAR(T.DTAVENCIMENTO, 'DD/MM/YYYY') AS DATA_VENCIMENTO,
        TO_CHAR(T.DTAPROGRAMADA, 'DD/MM/YYYY') AS DATA_PROGRAMADA,
        TO_CHAR(T.DTAQUITACAO, 'DD/MM/YYYY') AS DATA_QUITACAO,
        ROUND(O.VLROPERACAO, 2) AS VALOR_OPERACAO,
        ROUND(T.VLRNOMINAL, 2) AS VALOR_NOMINAL_TITULO,
        ROUND(T.VLRPAGO, 2) AS VALOR_PAGO_TITULO,
        ROUND(T.VLRNOMINAL - T.VLRPAGO, 2) AS SALDO_DEVEDOR_TITULO,
        T.NROBANCO AS BANCO,
        T.SEQAGENCIA AS AGENCIA,
        FIF_DESCCTACORRENTE_TITULO(T.SEQTITULO, 'S') AS CONTA_CORRENTE,
        O.USUALTERACAO AS USUARIO_ALTERACAO,
        O.OBSERVACAO AS OBSERVACAO_OPERACAO,
        T.OBSERVACAO_TITULO
    FROM CTE_TITULOS T
    INNER JOIN FI_TITOPERACAO O ON O.SEQTITULO = T.SEQTITULO
    LEFT JOIN CTE_OPERACAO OP ON OP.CODOPERACAO = O.CODOPERACAO
    WHERE O.OPCANCELADA IS NULL
    ORDER BY
        T.NROEMPRESA,
        O.DTAOPERACAO DESC,
        T.SEQTITULO,
        O.CODOPERACAO
)
