SELECT * FROM (
    WITH CTE_VENDAS AS (
        SELECT /*+ MATERIALIZE */
            I.SEQPRODUTO,
            I.NROEMPRESA,
            SUM(NVL(I.VLRITEM, 0)) AS VLR_VENDIDO,
            SUM(NVL(I.QUANTIDADE, 0)) AS QTD_VENDIDA
        FROM MLFV_BASENFE N
        INNER JOIN MFLV_BASEDFITEM I
            ON I.NROEMPRESA = N.NROEMPRESA
           AND I.SEQNF = N.SEQNF
           AND I.TIPNOTAFISCAL = N.TIPNOTAFISCAL
           AND I.SERIEDF = N.SERIENF
           AND I.NUMERODF = N.NUMERONF
           AND I.SEQPESSOA = N.SEQPESSOA
        WHERE N.TIPNOTAFISCAL = 'S'
          AND N.CODGERALOPER = 800
          AND NVL(N.STATUSNF, 'A') != 'C'
          AND N.NROEMPRESA IN (1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 14, 15, 17, 18)
          AND N.DTAEMISSAO >= TRUNC(:DT1)
          AND N.DTAEMISSAO < TRUNC(:DT2) + 1
          AND NOT (
                (N.NROEMPRESA = 3 AND N.NUMERONF = 10068 AND N.SERIENF = 703)
                OR (N.NROEMPRESA = 4 AND N.NUMERONF = 18130 AND N.SERIENF = 710)
          )
        GROUP BY
            I.SEQPRODUTO,
            I.NROEMPRESA
    ),
    CTE_VENDAS_LOJA AS (
        SELECT /*+ MATERIALIZE */
            TO_CHAR(E.NROEMPRESA, 'FM00') || ' - ' || NVL(E.NOMEREDUZIDO, 'LOJA ' || TO_CHAR(E.NROEMPRESA)) AS EMPRESA_VENDA,
            ROUND(SUM(V.VLR_VENDIDO), 2) AS VALOR_TOTAL_VENDIDO,
            ROUND(SUM(V.QTD_VENDIDA * (NVL(PE.CMULTVLRNF, 0) + NVL(PE.CMULTIPI, 0) + NVL(PE.CMULTICMSST, 0) + NVL(PE.CMULTDESPNF, 0) + NVL(PE.CMULTDESPFORANF, 0))), 2) AS VALOR_TOTAL_CUSTO,
            ROUND(
                (SUM(V.VLR_VENDIDO) - SUM(V.QTD_VENDIDA * (NVL(PE.CMULTVLRNF, 0) + NVL(PE.CMULTIPI, 0) + NVL(PE.CMULTICMSST, 0) + NVL(PE.CMULTDESPNF, 0) + NVL(PE.CMULTDESPFORANF, 0))))
                / NULLIF(SUM(V.VLR_VENDIDO), 0) * 100
            , 2) AS MARGEM_LUCRO
        FROM CTE_VENDAS V
        INNER JOIN MAP_PRODUTO P
            ON P.SEQPRODUTO = V.SEQPRODUTO
        INNER JOIN MAP_FAMDIVISAO FD
            ON FD.SEQFAMILIA = P.SEQFAMILIA
           AND FD.NRODIVISAO = 1
           AND FD.FINALIDADEFAMILIA = 'R'
        LEFT JOIN MRL_PRODUTOEMPRESA PE
            ON PE.SEQPRODUTO = V.SEQPRODUTO
           AND PE.NROEMPRESA = V.NROEMPRESA
        INNER JOIN MAX_EMPRESA E
            ON E.NROEMPRESA = V.NROEMPRESA
        GROUP BY
            TO_CHAR(E.NROEMPRESA, 'FM00') || ' - ' || NVL(E.NOMEREDUZIDO, 'LOJA ' || TO_CHAR(E.NROEMPRESA))
    )
    SELECT
        X.EMPRESA_VENDA,
        'R$ ' || TO_CHAR(
            X.VALOR_TOTAL_VENDIDO,
            'FM999G999G999G990D00',
            'NLS_NUMERIC_CHARACTERS = '',.'''
        ) AS VALOR_TOTAL_VENDIDO,
        TO_CHAR(
            X.MARGEM_LUCRO,
            'FM999G990D00',
            'NLS_NUMERIC_CHARACTERS = '',.'''
        ) || '%' AS MARGEM_LUCRO
    FROM (
        SELECT
            EMPRESA_VENDA,
            VALOR_TOTAL_VENDIDO,
            MARGEM_LUCRO,
            1 AS ORDEM
        FROM CTE_VENDAS_LOJA

        UNION ALL

        SELECT
            'TOTAL_PERIODO' AS EMPRESA_VENDA,
            ROUND(SUM(VALOR_TOTAL_VENDIDO), 2) AS VALOR_TOTAL_VENDIDO,
            ROUND(
                (SUM(VALOR_TOTAL_VENDIDO) - SUM(VALOR_TOTAL_CUSTO))
                / NULLIF(SUM(VALOR_TOTAL_VENDIDO), 0) * 100
            , 2) AS MARGEM_LUCRO,
            2 AS ORDEM
        FROM CTE_VENDAS_LOJA
    ) X
    ORDER BY
        X.ORDEM,
        X.EMPRESA_VENDA
)
