SELECT * FROM (
    WITH CTE_VENDAS AS (
        SELECT /*+ MATERIALIZE */
            I.SEQPRODUTO,
            I.NROEMPRESA,
            SUM(NVL(I.QUANTIDADE, 0)) AS QTD_VENDIDA,
            SUM(NVL(I.VLRITEM, 0)) AS VLR_BRUTO,
            SUM(NVL(I.VLRDESCITEM, 0)) AS VLR_DESCONTO,
            SUM(NVL(I.VLRICMS, 0) + NVL(I.VLRPIS, 0) + NVL(I.VLRCOFINS, 0)) AS VLR_IMPOSTOS
        FROM MLFV_BASENFE N
        INNER JOIN MFLV_BASEDFITEM I
            ON I.NROEMPRESA = N.NROEMPRESA
           AND I.SEQNF = N.SEQNF
           AND I.TIPNOTAFISCAL = N.TIPNOTAFISCAL
           AND I.SERIEDF = N.SERIENF
           AND I.NUMERODF = N.NUMERONF
           AND I.SEQPESSOA = N.SEQPESSOA
        WHERE N.TIPNOTAFISCAL = 'S'
          AND N.CODGERALOPER = 800
          AND NVL(N.STATUSNF, 'A') != 'C'
          AND N.NROEMPRESA IN (1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 14, 15, 17, 18)
          AND N.DTAEMISSAO >= TRUNC(:DT1)
          AND N.DTAEMISSAO < TRUNC(:DT2) + 1
          AND NOT (
                (N.NROEMPRESA = 3 AND N.NUMERONF = 10068 AND N.SERIENF = 703)
                OR (N.NROEMPRESA = 4 AND N.NUMERONF = 18130 AND N.SERIENF = 710)
          )
        GROUP BY
            I.SEQPRODUTO,
            I.NROEMPRESA
    ),
    CTE_DEPARTAMENTO AS (
        SELECT /*+ MATERIALIZE */
            X.SEQFAMILIA,
            MAX(Y.CATEGORIA) AS DEPARTAMENTO
        FROM MAP_FAMDIVCATEG X
        INNER JOIN MAP_CATEGORIA Y
            ON Y.SEQCATEGORIA = X.SEQCATEGORIA
           AND Y.NRODIVISAO = X.NRODIVISAO
        WHERE X.NRODIVISAO = 1
          AND X.STATUS = 'A'
          AND Y.NIVELHIERARQUIA = 1
          AND Y.TIPCATEGORIA = 'M'
          AND UPPER(Y.CATEGORIA) NOT IN ('A CLASSIFICAR', 'ALMOXARIFADO', 'INATIVAR', 'SERVICOS')
        GROUP BY
            X.SEQFAMILIA
    ),
    CTE_VENDAS_DEPTO AS (
        SELECT /*+ MATERIALIZE */
            D.DEPARTAMENTO,
            ROUND(SUM(V.VLR_BRUTO), 2) AS VALOR_BRUTO,
            ROUND(SUM(V.VLR_DESCONTO), 2) AS VALOR_DESCONTO,
            ROUND(SUM(V.VLR_BRUTO - V.VLR_DESCONTO), 2) AS VENDA_REAL,
            ROUND(SUM(V.QTD_VENDIDA * NVL(PE.CMULTCUSLIQUIDOEMP, 0)), 2) AS CUSTO_LIQUIDO,
            ROUND(SUM(V.VLR_IMPOSTOS), 2) AS IMPOSTOS,
            ROUND(
                SUM(V.VLR_BRUTO - V.VLR_DESCONTO)
                - SUM(V.QTD_VENDIDA * NVL(PE.CMULTCUSLIQUIDOEMP, 0))
                - SUM(V.VLR_IMPOSTOS)
            , 2) AS LUCRATIVIDADE_TOTAL,
            ROUND(
                (
                    SUM(V.VLR_BRUTO - V.VLR_DESCONTO)
                    - SUM(V.QTD_VENDIDA * NVL(PE.CMULTCUSLIQUIDOEMP, 0))
                    - SUM(V.VLR_IMPOSTOS)
                )
                / NULLIF(SUM(V.VLR_BRUTO - V.VLR_DESCONTO), 0) * 100
            , 2) AS MARGEM_LUCRO
        FROM CTE_VENDAS V
        INNER JOIN MAP_PRODUTO P
            ON P.SEQPRODUTO = V.SEQPRODUTO
        INNER JOIN MAP_FAMDIVISAO FD
            ON FD.SEQFAMILIA = P.SEQFAMILIA
           AND FD.NRODIVISAO = 1
           AND FD.FINALIDADEFAMILIA = 'R'
        INNER JOIN CTE_DEPARTAMENTO D
            ON D.SEQFAMILIA = P.SEQFAMILIA
        LEFT JOIN MRL_PRODUTOEMPRESA PE
            ON PE.SEQPRODUTO = V.SEQPRODUTO
           AND PE.NROEMPRESA = V.NROEMPRESA
        GROUP BY
            D.DEPARTAMENTO
    )
    SELECT
        X.DEPARTAMENTO,
        'R$ ' || TO_CHAR(X.VALOR_BRUTO, 'FM999G999G999G990D00', 'NLS_NUMERIC_CHARACTERS = '',.''' ) AS VALOR_BRUTO,
        'R$ ' || TO_CHAR(X.VALOR_DESCONTO, 'FM999G999G999G990D00', 'NLS_NUMERIC_CHARACTERS = '',.''' ) AS VALOR_DESCONTO,
        'R$ ' || TO_CHAR(X.VENDA_REAL, 'FM999G999G999G990D00', 'NLS_NUMERIC_CHARACTERS = '',.''' ) AS VENDA_REAL,
        'R$ ' || TO_CHAR(X.CUSTO_LIQUIDO, 'FM999G999G999G990D00', 'NLS_NUMERIC_CHARACTERS = '',.''' ) AS CUSTO_LIQUIDO,
        'R$ ' || TO_CHAR(X.IMPOSTOS, 'FM999G999G999G990D00', 'NLS_NUMERIC_CHARACTERS = '',.''' ) AS IMPOSTOS,
        'R$ ' || TO_CHAR(X.LUCRATIVIDADE_TOTAL, 'FM999G999G999G990D00', 'NLS_NUMERIC_CHARACTERS = '',.''' ) AS LUCRATIVIDADE_TOTAL,
        TO_CHAR(X.MARGEM_LUCRO, 'FM999G990D00', 'NLS_NUMERIC_CHARACTERS = '',.''' ) || '%' AS MARGEM_LUCRO
    FROM (
        SELECT
            DEPARTAMENTO,
            VALOR_BRUTO,
            VALOR_DESCONTO,
            VENDA_REAL,
            CUSTO_LIQUIDO,
            IMPOSTOS,
            LUCRATIVIDADE_TOTAL,
            MARGEM_LUCRO,
            1 AS ORDEM
        FROM CTE_VENDAS_DEPTO

        UNION ALL

        SELECT
            'TOTAL_PERIODO' AS DEPARTAMENTO,
            ROUND(SUM(VALOR_BRUTO), 2) AS VALOR_BRUTO,
            ROUND(SUM(VALOR_DESCONTO), 2) AS VALOR_DESCONTO,
            ROUND(SUM(VENDA_REAL), 2) AS VENDA_REAL,
            ROUND(SUM(CUSTO_LIQUIDO), 2) AS CUSTO_LIQUIDO,
            ROUND(SUM(IMPOSTOS), 2) AS IMPOSTOS,
            ROUND(SUM(LUCRATIVIDADE_TOTAL), 2) AS LUCRATIVIDADE_TOTAL,
            ROUND(
                SUM(LUCRATIVIDADE_TOTAL)
                / NULLIF(SUM(VENDA_REAL), 0) * 100
            , 2) AS MARGEM_LUCRO,
            2 AS ORDEM
        FROM CTE_VENDAS_DEPTO
    ) X
    ORDER BY
        X.ORDEM,
        X.DEPARTAMENTO
)