SELECT
  TO_CHAR(TRUNC(N.DTAEMISSAO), 'DD/MM/YYYY') AS DIA_VENDA,
  CASE
    WHEN N.CODGERALOPER = 800 THEN 'CUPONS 800'
    ELSE 'OUTROS ' || TO_CHAR(N.CODGERALOPER)
  END AS TIPO_REGISTRO,
  NVL(DEP.CATEGORIA, 'SEM DEPARTAMENTO') AS DEPARTAMENTO,
  NVL(COMP.APELIDO, 'SEM COMPRADOR') AS COMPRADOR,
  P.SEQPRODUTO AS CODIGO_PRODUTO,
  P.DESCCOMPLETA AS DESCRICAO_PRODUTO,
  N.NUMERONF AS NUMERO_CUPOM,
  N.NROEMPRESA AS LOJA,
  TO_CHAR(
    ROUND(NVL(I.VLRITEM, 0), 2),
    'FM999G999G999G990D00',
    'NLS_NUMERIC_CHARACTERS = '',.'''
  ) AS VLR_ITEM
FROM MLFV_BASENFE N
INNER JOIN MFLV_BASEDFITEM I
  ON I.NROEMPRESA = N.NROEMPRESA
  AND I.SEQNF = N.SEQNF
  AND I.TIPNOTAFISCAL = N.TIPNOTAFISCAL
  AND I.SERIEDF = N.SERIENF
  AND I.NUMERODF = N.NUMERONF
  AND I.SEQPESSOA = N.SEQPESSOA
INNER JOIN MAP_PRODUTO P ON P.SEQPRODUTO = I.SEQPRODUTO
INNER JOIN MAP_FAMDIVISAO FD
  ON FD.SEQFAMILIA = P.SEQFAMILIA
  AND FD.NRODIVISAO = 1
  AND FD.FINALIDADEFAMILIA = 'R'
LEFT JOIN (
  SELECT
    FDC.SEQFAMILIA,
    NVL(
      MAX(CASE
        WHEN UPPER(CAT.CATEGORIA) NOT IN (
          'A CLASSIFICAR', 'ALMOXARIFADO', 'INATIVAR',
          'INATIVOS', 'INATIVO', 'SERVICOS'
        ) THEN CAT.CATEGORIA
      END),
      MAX(CAT.CATEGORIA)
    ) AS CATEGORIA
  FROM MAP_FAMDIVCATEG FDC
  INNER JOIN MAP_CATEGORIA CAT ON CAT.SEQCATEGORIA = FDC.SEQCATEGORIA
    AND CAT.NRODIVISAO = FDC.NRODIVISAO
  WHERE FDC.NRODIVISAO = 1
    AND CAT.NIVELHIERARQUIA = 1
    AND CAT.TIPCATEGORIA = 'M'
  GROUP BY FDC.SEQFAMILIA
) DEP ON DEP.SEQFAMILIA = P.SEQFAMILIA
LEFT JOIN MAX_COMPRADOR COMP ON COMP.SEQCOMPRADOR = FD.SEQCOMPRADOR
WHERE N.TIPNOTAFISCAL = 'S'
  AND N.CODGERALOPER = :NR1
  AND N.NROEMPRESA IN (1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 14, 15, 17, 18)
  AND (:NR2 = 0 OR N.NROEMPRESA = :NR2)
  AND N.DTAEMISSAO >= TRUNC(:DT1)
  AND N.DTAEMISSAO < TRUNC(:DT2) + 1
  AND (
    UPPER(:LT1) = 'TODOS'
    OR UPPER(NVL(DEP.CATEGORIA, 'SEM DEPARTAMENTO')) = UPPER(:LT1)
  )
  AND (
    UPPER(:LT2) = 'TODOS'
    OR (
      UPPER(:LT2) = 'FANTASMA'
      AND UPPER(NVL(DEP.CATEGORIA, 'SEM DEPARTAMENTO')) IN (
        'A CLASSIFICAR',
        'ALMOXARIFADO',
        'INATIVAR',
        'INATIVOS',
        'INATIVO'
      )
    )
    OR (
      UPPER(:LT2) = 'VENDA'
      AND UPPER(NVL(DEP.CATEGORIA, 'SEM DEPARTAMENTO')) NOT IN (
        'A CLASSIFICAR',
        'ALMOXARIFADO',
        'INATIVAR',
        'INATIVOS',
        'INATIVO'
      )
    )
  )
ORDER BY
  TRUNC(N.DTAEMISSAO) ASC,
  CASE
    WHEN N.CODGERALOPER = 800 THEN 'CUPONS 800'
    ELSE 'OUTROS ' || TO_CHAR(N.CODGERALOPER)
  END ASC,
  NVL(DEP.CATEGORIA, 'SEM DEPARTAMENTO') ASC,
  NVL(COMP.APELIDO, 'SEM COMPRADOR') ASC,
  N.NUMERONF ASC,
  P.SEQPRODUTO ASC,
  P.DESCCOMPLETA ASC,
  N.NROEMPRESA ASC


