SELECT
  TO_CHAR(TRUNC(N.DTAEMISSAO), 'DD/MM/YYYY') AS DIA_VENDA,
  NVL(DEP.CATEGORIA, 'SEM DEPARTAMENTO') AS DEPARTAMENTO,
  NVL(COMP.APELIDO, 'SEM COMPRADOR') AS COMPRADOR,
  N.NROEMPRESA AS LOJA,
  ROUND(SUM(NVL(I.VLRITEM, 0)), 2) AS VLR_VENDAS
FROM MLFV_BASENFE N
INNER JOIN MFLV_BASEDFITEM I
  ON I.NROEMPRESA = N.NROEMPRESA
  AND I.SEQNF = N.SEQNF
  AND I.TIPNOTAFISCAL = N.TIPNOTAFISCAL
  AND I.SERIEDF = N.SERIENF
  AND I.NUMERODF = N.NUMERONF
  AND I.SEQPESSOA = N.SEQPESSOA
INNER JOIN MAP_PRODUTO P ON P.SEQPRODUTO = I.SEQPRODUTO
INNER JOIN MAP_FAMDIVISAO FD
  ON FD.SEQFAMILIA = P.SEQFAMILIA
  AND FD.NRODIVISAO = 1
  AND FD.FINALIDADEFAMILIA = 'R'
LEFT JOIN (
  SELECT
    FDC.SEQFAMILIA,
    MAX(CAT.CATEGORIA) AS CATEGORIA
  FROM MAP_FAMDIVCATEG FDC
  INNER JOIN MAP_CATEGORIA CAT ON CAT.SEQCATEGORIA = FDC.SEQCATEGORIA
  WHERE FDC.NRODIVISAO = 1
    AND CAT.NIVELHIERARQUIA = 1
    AND CAT.TIPCATEGORIA = 'M'
    AND UPPER(CAT.CATEGORIA) NOT IN ('A CLASSIFICAR', 'ALMOXARIFADO', 'INATIVAR', 'SERVICOS')
  GROUP BY FDC.SEQFAMILIA
) DEP ON DEP.SEQFAMILIA = P.SEQFAMILIA
LEFT JOIN MAX_COMPRADOR COMP ON COMP.SEQCOMPRADOR = FD.SEQCOMPRADOR
WHERE N.TIPNOTAFISCAL = 'S'
  AND N.CODGERALOPER = 800
  AND N.NROEMPRESA IN (1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 14, 15, 17, 18)
  AND N.DTAEMISSAO >= TRUNC(:DT1)
  AND N.DTAEMISSAO < TRUNC(:DT2) + 1
GROUP BY
  TRUNC(N.DTAEMISSAO),
  NVL(DEP.CATEGORIA, 'SEM DEPARTAMENTO'),
  NVL(COMP.APELIDO, 'SEM COMPRADOR'),
  N.NROEMPRESA
ORDER BY
  TRUNC(N.DTAEMISSAO) ASC,
  NVL(DEP.CATEGORIA, 'SEM DEPARTAMENTO') ASC,
  NVL(COMP.APELIDO, 'SEM COMPRADOR') ASC,
  N.NROEMPRESA ASC
