SELECT * FROM (
    WITH CTE_MOVIMENTACAO AS (
        SELECT /*+ MATERIALIZE */ DISTINCT SEQPESSOA
        FROM FI_TITULO
        WHERE DTAEMISSAO >= TRUNC(SYSDATE, 'YYYY')
    )
    SELECT 
        P.SEQPESSOA AS CODIGO_FORNECEDOR,
        P.NOMERAZAO AS DESCRICAO_FORNECEDOR,
        P.NROCGCCPF AS CNPJ,
        R.DESCRICAO AS REDE
    FROM GE_PESSOA P
    INNER JOIN CTE_MOVIMENTACAO M ON M.SEQPESSOA = P.SEQPESSOA
    LEFT JOIN GE_REDEPESSOA RP ON RP.SEQPESSOA = P.SEQPESSOA
    LEFT JOIN GE_REDE R ON R.SEQREDE = RP.SEQREDE
)
ORDER BY DESCRICAO_FORNECEDOR
