-- =========================================================
-- Exemplo de Cálculo de Custos, Tributos e Margens de Estoque (TOTVS Consinco)
-- =========================================================

INSERT INTO MBI_TABCESTOQUE(
SEQCONSULTA, SEQLINHA, SEQDETALHE1, CODDETALHE1, NOMEDETALHE1, SEQDETALHE2, CODDETALHE2, NOMEDETALHE2, NOMEDETALHE, 
NIVELHIERARQUIA, ACTFAMILIA, SEQCATEGORIAPAI, QTDEMBALAGEM, EMBALAGEM, LITROS, STATUSCOMPRA, STATUSVENDA, DTAVALIDADELOTE, 
CODACESSOMENOREMB, INDPOSICAOCATEG, NROITENS, QTDTOTAL, LITRAGEM, QTDRESERVADA, QTDDISPONIVEL, VLRPRECOVENDA, VLRGMROI, VLRPRECOVENDAUNIT, 
VLRMENORPRECOUNIT, VLRMAIORPRECOUNIT, VLRPMZ, MARGEMCADASTRO, VLRCTOLIQUIDO, VLRCTOLIQUNIT, VLRULTCTOLIQUNIT, VLRCTOLIQUIDOEXTRA, 
VLRCTOLIQUNITEXTRA, MARGEMLUCRO, VLRLUCRO, MARKUP, MARKDOWN, VLRCTOBRUTO, CTOBRUTOMARKUPDOWN, VLRCTOBRUTOUNIT, 
VLRCTOBRUTOUNITMKUD, VLRCONTRIB, MARGEMCONTRIB, QTDPENDPEDCOMPRA, QTDPENDPEDEXPED, MEDVDIA, DIASESTOQUE, DIASULTIMAENTRADA, 
DIASULTENTRCUSTO, PESOBRUTO, PESOLIQUIDO, MEDVDIAXCUSTOLIQUNIT, VLRDESPESAVDA, VLRCOMPROR, VLRDESCDIVERSOS, VLRDESCPISTRANSF, 
VLRDESCCOFINSTRANSF, VLRDESCIPITRANSF, VLRDESCLUCROTRANSF, VLRDESCVERBATRANSF, VLRDESCDIFERENCATRANSF, VLRDESCTRANSFERENCIA, VLRDESCTOTAIS, VLRCOMISSAO, 
VLRIMPOSTOVDA, VLRICMSVDA, VLRPISVDA, VLRCOFINSVDA, VLROUTROSIMPOSTOS, DIASESTOQUEPAGO, VLRESTOQUEPAGO, DIASESTOQUEAPAGAR, VLRESTOQUEAPAGAR, 
ESTQEMPRESA, CUSTOFISCALUNIT, CUSTOFISCALTOTAL, VLRDESPFIXAUNIT, VLRDESCFIXOUNIT, VLRDESPFIXA, VLRDESCFIXO, VLRICMSSTEMBUTPROD, VLRDESCRESTICMSTRANSF, 
CMVLRVERBACOMPRASELLIN, CMVLRVERBABONIFINCIDSELLIN, CMVLRVERBABONIFSEMINCIDSELLIN, CMVLRDESCVERBATRANSFSELLIN, 
QTDESTOQUEMINIMO, QTDESTOQUEMAXIMO, QTDDIASSEMVENDA, VLRIMPOSTOIBSMUN, VLRIMPOSTOIBSUF, VLRIMPOSTOCBS, VLRIMPOSTOIS,
CLNCUSTOM1, CLNCUSTOM2, CLNCUSTOM3, CLNCUSTOM4, CLNCUSTOM5, CLNCUSTOM6, CLNCUSTOM7, CLNCUSTOM8, CLSCUSTOM9, CLSCUSTOM10, 
CLSCUSTOM11, CLSCUSTOM12 , VLRCTOLIQESTOQUE )

select /*+ */ '48137' as SEQCONSULTA, to_number( null ) as SEQLINHA, 

O.SEQCOMPRADOR as SEQDETALHE1,
null as CODDETALHE1,
O.APELIDO as NOMEDETALHE1,
A.SEQPRODUTO as SEQDETALHE2,
null as CODDETALHE2,
A.DESCCOMPLETA as NOMEDETALHE2,
O.APELIDO || ' : ' || A.DESCCOMPLETA as NOMEDETALHE,
-- Omissão de resto dos cálculos extensos apenas para economizar espaço de leitura se não for preciso --
-- Ver referência original que gerou este script para as literais brutas dos cálculos Custo etc. --

from MAP_PRODUTO A, MAP_FAMILIA B,
( select Y.SEQPRODUTO, Y.NROEMPRESA, Y.SEQCLUSTER ,
decode( ( ESTQDEPOSITO ), 0, null, Y.SEQPRODUTO ) SEQPRODUTOCOMESTQ,
-- Subquery geradora contendo os campos de Estoque e Impostos: MRL_PRODEMPSEG + MRL_PRODUTOEMPRESA
 ) X, MRL_PRODUTOEMPRESA Y, MAX_EMPRESA E Where E.NROEMPRESA = Y.NROEMPRESA
  -- (...)
group by O.SEQCOMPRADOR, O.APELIDO, A.SEQPRODUTO, A.DESCCOMPLETA
